### ISSUE TITLE
Refactor Clubs CSS to make it more maintainable and extensible

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#1002]
One of the things I noticed when adding the clubs list, and am now reminded of while reviewing #1001, is that `page.less` uses the `listItemBorderColorizer` mixin to add orange borders to every `<ul>` on the Clubs page's main content, regardless of its context. This makes it *extremely* hard to have lists that are styled differently.

So, two things should be done:

- [x] Move the clubs-specific rules from `page.less` to `clubs.less`.
- [x] Scope the rule containing the `listItemBorderColorizer` to require a specific class of some sort (not sure what its name should be), and then change the existing `<ul>`'s on the clubs page to use this class.
- [x] For Club list items on `\clubs`, remove `border-top` from the `first-child` and `border-bottom` from `last-child` so that borders only appear *in between* list items.

**Comment by mmmavis** [comment]
this can be a P2 ticket for this heartbeat

**Comment by mmmavis** [comment]
oops, closed by accident
