### ISSUE TITLE
Choose a new color for Teach Like Mozilla

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1005]
We're going to add Tools as a top-level nav item, and it will be green (to match the new Thimble design). We'll need a new color for Teach Like Mozilla and its subpage, the Web Lit Map.

**Comment by toolness** [comment]
I say we use the same color red as the background of the mozilla.org page, since it's about teaching like MOZILLA!

![screen shot 2015-06-09 at 11 59 34 am](https://cloud.githubusercontent.com/assets/124687/8062658/dac110ec-0e9e-11e5-839d-77d86b65230c.png)

eh just a thought.

**Comment by mmmavis** [comment]
Note that once the colour has been chosen we will also need to update illustrations on these 2 pages with the new colour.

**Comment by cassiemc** [comment]
For context, we are talking about teach.mozilla.org, and will need to change the color in the section https://teach.mozilla.org/teach-like-mozilla/.

@sabrinang do you have any guidance on colors here (if say, a contributor were to take this on)?

**Comment by sabrinang** [comment]
This ticket will tie into colors that are being audited and determined - https://github.com/mozilla/teach.mozilla.org/issues/1260
