### ISSUE TITLE
Losslessly optimize images

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#1030]
As mentioned in #946, it might be useful to use a tool like `gulp-imagemin` to optimize our images. Specifically, we ought to optimize:

- [ ] SVG files (see #1052)
- [ ] PNG files
- [ ] JPEG files

We don't seem to have any GIFs, so no need to optimize those.

**Comment by mmmavis** [comment]
let's check what the current status is for this master ticket

**Comment by Pomax** [comment]
this will be revisited when we do https://github.com/mozilla/teach.mozilla.org/issues/1509
