### ISSUE TITLE
Inconsistenct button styling

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1045]
@hannahkane @sabrinang @toolness 
I'm not sure if this is intended or something we need to fix.  Just wanna create a ticket so we each have a chance to check.

There's flat, full width styled buttons (for example, seen on "Add Your Clubs" modals)
![screen shot 2015-06-17 at 3 39 14 pm](https://cloud.githubusercontent.com/assets/2896608/8220390/1f1e304e-1507-11e5-90bf-52cf6b8815eb.png)
![screen shot 2015-06-17 at 3 39 36 pm](https://cloud.githubusercontent.com/assets/2896608/8220389/1f0bb6da-1507-11e5-9d0b-6b34887f855a.png)

There's also the non full-width, CTA-like button (seen in the Pledge Modal)
![Pledge Modal](https://cloud.githubusercontent.com/assets/2492510/8044040/cd3ce344-0dde-11e5-98c5-09f6cc4f6af3.png)

**Comment by mmmavis** [comment]
@sabrinang I'm assigning this to you since you are the decision maker.

**Comment by mmmavis** [comment]
Just wanna flag that we just carried over some Makerstrap-style buttons for https://github.com/mozilla/teach.webmaker.org/issues/1119 and https://github.com/mozilla/teach.webmaker.org/issues/1125

![screen shot 2015-07-23 at 12 50 01 pm](https://cloud.githubusercontent.com/assets/2896608/8860538/64e67fca-3139-11e5-9fd7-6a71d551f87f.png)

We should take these buttons into consideration when we tackle this inconsistent button styling issue. :wink:

**Comment by hannahkane** [comment]
This is part of #1260
