### ISSUE TITLE
Factor out a <EmailSignupForm> component

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1050]
As discussed in https://github.com/mozilla/teach.webmaker.org/pull/1039#discussion_r32724789, we should prevent ourselves from copying the same code for email signup form over and over again.

When https://github.com/mozilla/teach.webmaker.org/pull/1039 and PR for #900 are landed we will have in total 3 almost identical email signup forms on the Teach site. To keep us [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) we should probably

- [ ] Factor out a `<EmailSignupForm>` component that includes 2 form fields `email` and the `privacy checkbox`.
- [ ] Add unit tests for it
- [ ] Revisit [the fake checkbox privacy policy design discussion](https://github.com/mozilla/teach.webmaker.org/pull/1039#discussion_r32792452)

**Comment by hannahkane** [comment]
@mmmavis - is this ticket still needed?

**Comment by mmmavis** [comment]
i think we can close this.
