### ISSUE TITLE
Visual conventions across Teaching Activities and Maker Party case studies is inconsistent

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#1083]
When I saw the cool new Maker Party case studies, I tried clicking on the title/image to see where it took me, and was confused for a bit because they weren't hyperlinked:

![2015-07-08_19-01-29](https://cloud.githubusercontent.com/assets/124687/8584400/1f201104-25a4-11e5-9d4b-6ac7732c3646.jpg)

Upon further reflection I realized that I had *assumed* they were hyperlinked because we use very similar visual conventions on the Teaching Activities page:

![2015-07-08_19-01-58](https://cloud.githubusercontent.com/assets/124687/8584404/35b36ac4-25a4-11e5-9b24-2c8c992224e0.jpg)

*Those* titles/images are hyperlinked. It seems like we might want to be more consistent with our visual conventions, maybe? I'm not sure about this one--I've actually done similar kinds of things on my own projects, and have similarly avoided underlining hyperlinked headings because it just looks way too gaudy... But on the other hand, when the only indication you have of whether something is hyperlinked is by hovering over it or tabbing to it--gestures that don't even exist on touch devices--that could be bad. Maybe we could put some sort of icon next to each link instead of underlining it? I dunno.

**Comment by mmmavis** [comment]
I agree with you @toolness. I have a tendency to interpret text in body colour(black, grey) as non-hyperlinks as well - I never tried to hover over them. :eyes:  Maybe adding icon or changing the font colour would help?

I was thinking if we could add some flavours to the hyperlinked image... maybe some sort of tiny animation?  This is not touch devices friendly but I guess users can always check out the hyperlinked headers.

Btw, I just noticed there's inconsistency in letter casing in headers.

**Comment by mmmavis** [comment]
@sabrinang this is not urgent, just pinging you in case this gets buried in your inbox :wink: 
Would love your thoughts on ^^
