### ISSUE TITLE
CSS Animation Inspiration / Resources

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1088]
Below is a list of resources I found. Not all of them are open source(I think). But we can still use them as source of inspiration

- 12 Fun Sharing Button Effects http://demo.tutorialzine.com/2014/11/12-fun-sharing-button-effects/
- Hover.css http://ianlunn.github.io/Hover/
- Creative Link Effects  http://tympanus.net/codrops/2013/08/06/creative-link-effects/
- Simple Icon Hover Effects  http://tympanus.net/codrops/2013/05/30/simple-icon-hover-effects/
- Some More Subtle Hover Effect Ideas http://tympanus.net/Development/HoverEffectIdeas/
- Caption Hover Effects  http://tympanus.net/codrops/2013/06/18/caption-hover-effects/
- Shape Hover Effect with SVG http://tympanus.net/codrops/2014/01/07/shape-hover-effect-with-svg/
- Inspiration for Inline Anchor Styles  http://tympanus.net/codrops/2014/06/04/inspiration-for-inline-anchor-styles/

(will update this ticket if I find more :dancers: )

**Comment by hannahkane** [comment]
@mmmavis - is it important to keep this ticket open? Since it doesn't seem actionable, I'm tempted to close, but I could move these to another space for documentation if you'd like.

**Comment by mmmavis** [comment]
that's fine. let's just close it :+1:
