### ISSUE TITLE
Add ES6 support

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#1107]
Development of the specification for ECMAScript 6, the next version of JavaScript, is now complete, so it's not going to change anytime soon. Furthermore, it seems to have the support of the JS community and a lot of projects, including Webmaker, are starting to support it via tools like [Babel](https://babeljs.io/).

Possible reasons to support ES6:
* Lots of new language features that make it way less painful to write JS. Some of my personal favorites are [`let`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let), [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), [generators](http://davidwalsh.name/es6-generators), [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), and new built-in methods like [`String.prototype.startsWith()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith).
* It's where the entire JS/browser world is going, and if we don't migrate eventually then we may start alienating potential contributors.

Possible reasons to *not* support ES6:
* It's possible (but unlikely) that using Babel or another converter could mess with our source map support. Maintaining at least our current level of source map support **must** be a requirement for adding ES6 support.
* Contributors might be confused by the new syntax that we use. However, because it's what the entire JS/browser world is migrating towards--and not some kind of niche language like CoffeeScript--it's probably safe to assume that contributors will *want* to learn it if they don't know it already, rather than being alienated by it.

@mmmavis, if you're unfamiliar w/ ES6 and have some free time for continuing education, want to take a look at [ES6: The Future Is Now](https://www.youtube.com/watch?v=Hjkc9m9vYCU) and provide your opinion?

**Comment by Pomax** [comment]
closing, we'll be going the webpack/babel (with esnext/react presets) way in 2016
