### ISSUE TITLE
Update semver string for phantomjs once mocha-phantomjs update theirs

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1115]
This ticket serves as a reminder.  For context see https://github.com/mozilla/teach.webmaker.org/issues/1113

**Comment by simonwex** [comment]
Probably worth tracking this: https://github.com/nathanboktae/mocha-phantomjs/issues/175

**Comment by nathanboktae** [comment]
mocha-phantomjs v4 has [been released](https://github.com/nathanboktae/mocha-phantomjs/releases/tag/v4.0.0) and has a direct dependency on `phantomjs`, so you can remove yours. Excuse all the peer dependency pain the last couple of months.

**Comment by mmmavis** [comment]
Wow lovely! thanks for the reminder @nathanboktae  :+1: :dancer:

**Comment by hannahkane** [comment]
Hey @Pomax - this ticket is hanging out in an old milestone. Should we move it?

**Comment by Pomax** [comment]
this landed in october, but apparently never auto-closed the issue... very odd, but closing now =)
