### ISSUE TITLE
Document findings from co-design session with Helen and Dethe

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1116]

**Comment by hannahkane** [comment]
Moving to current heartbeat

**Comment by hannahkane** [comment]
@sabrinang - I'm tempted to close this. Feels like it's been hanging out for too long. What do you think?

**Comment by sabrinang** [comment]
@hannahkane - Yes, the findings from the session definitely informed lots of the initial research and ideas to progress on MLN work already and I don't think it will be a priority to document it now - I'll close this.
