### ISSUE TITLE
Design a way for users to submit curriculum for consideration

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1118]
This is a bit of a stop-gap measure, but we should indicate on /activities that we'd welcome curriculum submissions from the community. Could be as simple as a short "Submit Your Curriculum" form that lets the user link to content hosted elsewhere. A designated member of our staff should be notified each time the form is submitted (eventually this will be the Curriculum Writer, though I'm not sure who it is in the meantime), so they can evaluate it and potentially add it to the /activities page.

**Comment by jgmac1106** [comment]
I think we could have a template in thimble for curriculum. The template
could have a prepopulated tag. The curriculum writer (who hopefully is more
of a curator) could monitor the tag.

**Comment by hannahkane** [comment]
That's a good idea. Would also like to accommodate people who don't want to use Thimble, though.

**Comment by jgmac1106** [comment]
Can there be a category on Discourse called curriculum? There people can
submit curriculum ideas or link to a lesson plan. Users with more adept
skills could still fork the curriculum pages.

**Comment by hannahkane** [comment]
Yes. I like that idea. So this ticket would just be linking to that Discourse category and inviting ppl to submit there.
