### ISSUE TITLE
Collect input from community members on MLN Directory wireframes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1145]
In addition to collecting staff input on the Directory, we also need to consult with community members to validate that the Directory will meet their needs.

**Comment by hannahkane** [comment]
Goal for August 28th heartbeat: talk to Emma Irwin!

**Comment by LauraReynal** [comment]
CC :santa:

**Comment by hannahkane** [comment]
This is a dupe of #1284
