### ISSUE TITLE
Principle number 5 in the Mozilla Manifesto leads to webmaker.org/teach

### ISSUE THREAD

**Issue by ryanw-se** [mozilla/teach.mozilla.org#1171]
A user came into the #webmaker IRC channel today reporting that the Mozilla Manifesto principle number 5, redirects to a URL that doesn't exist. I apologize if this isn't the correct place, I am not familiar with all of these repositories, hopefully this was the correct place.

You can see the exact message sent by alanmoo via #webmaker on IRC here, ```<alanmoo>: Hey all, I realize throwing this into the ether on a Saturday night probably isn't the most useful, but I'm not sure where to put it and I don't want to pester anyone specific at the moment: https://www.mozilla.org/en-US/about/manifesto/ item 5 links to https://webmaker.org/teach which is a 404 right now.```

**Comment by ldecoursy** [comment]
Thanks @ryanw-se!  @HPaulJohnson @KevZawacki Do either of you know the best place to ask to have this link updated to https://teach.mozilla.org/tools? 

See below - it's the first link that says "Use these free tools to teach the Web"
![screen shot 2015-08-17 at 9 35 10 am](https://cloud.githubusercontent.com/assets/4885898/9305958/4c275eee-44c3-11e5-936a-50c62f698a3d.png)

**Comment by HPaulJohnson** [comment]
I can reach out to moz.org team. I'll suggest that we point to teach.mozilla.org/tools if no one objects?

**Comment by ldecoursy** [comment]
Thanks @HPaulJohnson!

**Comment by HPaulJohnson** [comment]
Should be fixed shortly: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1195376

**Comment by mmmavis** [comment]
RESOLVED FIXED :information_desk_person:
