### ISSUE TITLE
Wireframes for Member profiles

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1180]
Should include:
 * entry form (inline editing)
 * viewers (including a view for the owner)
 * changes to nav bar (visual prompt to user to edit their profile)
 * photo upload UX
 * for both mobile and desktop

Fields:
* username (from Webmaker account) 
* email (from Webmaker account)
* name
* Designated Mozilla Leadership Role (e.g. "Club Captain of Blah Blah Club", "Regional Coordinator of 10 CCs", "Member of Hive Chicago") - system field 
* location
* photo 
* skills (tags)
* interests (tags)

**Comment by sabrinang** [comment]
mobile wireframe ideas of member profile views
![mln_directory-member-profile-views](https://cloud.githubusercontent.com/assets/2492510/9822927/21d4cf8c-5878-11e5-9d59-c132b43981cf.png)

**Comment by sabrinang** [comment]
mobile wireframe ideas of member profile editor
![mln_directory-member-profile-views2](https://cloud.githubusercontent.com/assets/2492510/9822970/50d2bdee-5878-11e5-94b2-4033e06b4996.png)

**Comment by hannahkane** [comment]
@sabrinang - welcome back! These look great. Can you put them on redpen so we can comment?

**Comment by sabrinang** [comment]
redpen: https://redpen.io/p/ve944daa8712303367

**Comment by jgmac1106** [comment]
Should there be a link to someone's Mozillian.org account on the MLN
profile as well?

I just ask as I was someone who was very active in old webmaker community
but knew nothing of mozillian.org.

We are creating another system where we will have two profiles (three if
you count Discourse).

Is this desired? Are the audiences different? Do we just make a place to
link to your mozillian.org account OR make getting a mozillian account a
pre req to a MLN profile?

**Comment by sabrinang** [comment]
Thanks for surfacing these questions of how the profiles are related to other mozilla systems. On some older desktop iterations - I did consider a space for other mozilla profiles so they can be found in one place: 
![old-desktop-example](https://cloud.githubusercontent.com/assets/2492510/10030902/fccaeda6-612e-11e5-8a00-1a85f27446ea.png)

For my updated mobile iteration, I integrated back the idea of this dedicated space for "mozilla channels" to link from: 
![mln_directory-wireframes-member-profile_v2](https://cloud.githubusercontent.com/assets/2492510/10031082/03720c6a-6130-11e5-98cb-c363932eaea3.png)
Also, I included groups section (shows what you groups organize or join), badges (achievements) and placeholder for projects to consider the integration of projects from our learning tools.

I think making prerequisites for a MLN may exclude some audiences but will surface these type of ideas of what profile relationships could be.

**Comment by hannahkane** [comment]
Looking really good. Would love to invite feedback from @ldecoursy, @chrislarry33, and @omnignorant and others. https://redpen.io/p/ve944daa8712303367

Robert - especially curious to know your thoughts on the "Vouching" feature suggested here. It's meant to be a solution for local groups, like Hive Chicago, who might have specific roles they want to display on Member Profiles.

**Comment by hannahkane** [comment]
@sabrinang - I think we might want to close this ticket, and re-open a new one that's about collecting feedback from @LauraReynal. What do you think?

**Comment by sabrinang** [comment]
@hannahkane - Yeah for Laura's research I should get these into her slidedeck for collecting feedback for this trip https://github.com/mozilla/teach.mozilla.org/issues/1284 but also collecting feedback from Laura ticket would be great too

**Comment by hannahkane** [comment]
Closing because we've advanced a lot of this work. Let's open new tickets as we see the findings from the research project.
