### ISSUE TITLE
Wireframes for Club pages

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1181]
Should include:
 * entry form (inline editing)
 * viewers (including a view for the Club Captain)
 * how does user access their page
 * for both mobile and desktop

Fields:
* name of club
* location
* Image
* Club Captain (system field)
* Regional Coordinator (system field)
* Links (as many as they'd like)
* Published Report ("Add a new one" for Club Captains)
* focus areas (tags)

**Comment by jgmac1106** [comment]
There is also the mozilla web club make that we created for clubs to design
a logo. That could be included. Though I have no idea how this would work
technically.

Is the goal to create a front-end directory so you also have a backend
directory of all the club members? I wonder if this shouldn't be done in
mozillians.org while we make a template for a club website it Thimble.

It could have all of your pages and a template page for reports. I have no
JS skills but maybe there could be a way for input fields for the report.

**Comment by hannahkane** [comment]
@jgmac1106 - thanks for the logo suggestion. Users will be able to add an image, so they can choose to add a logo, if they'd like. I don't think we'll do anything to facilitate that beyond having an "upload image" tool for our MVP.

This is meant to be a directory of Clubs, though not necessarily a directory of Club *members* just yet. We'll see if that need emerges. (Do you feel you'd need a directory to track the members of your Club?) We are spec'ing out a template for reports in #1182.

**Comment by sabrinang** [comment]
mobile wireframe ideas of group page views
![mln_directory-group-pages-views](https://cloud.githubusercontent.com/assets/2492510/9826634/b6b7f8f0-5890-11e5-887f-0397f1a2e81b.png)

**Comment by sabrinang** [comment]
mobile wireframe ideas of group page editor
![mln_directory-group-pages-views2](https://cloud.githubusercontent.com/assets/2492510/9826657/d5fdfff2-5890-11e5-9d3c-7c1568236b29.png)

**Comment by jgmac1106** [comment]
No. I misunderstood the directory. In terms of a club's directory I am now
thinking a club website template in Thimble would be better.

**Comment by hannahkane** [comment]
@jgmac1106 - we can definitely provide a template for Thimble, though I don't think we'll mandate how Club Captains manage their Clubs, beyond requiring a presence in the Directory.

**Comment by sabrinang** [comment]
included members and affiliated group list, refined social channels and links section and some of the editing UI
![mln_directory-wireframes-group club -profile_v2](https://cloud.githubusercontent.com/assets/2492510/10034575/752726b8-6146-11e5-93f8-7875bb69f9f3.png)

Note: 
- in the editor, managing members and affiliated groups UI to be ideated on and included
- include Update group and Cancel buttons on the bottom of editor

**Comment by hannahkane** [comment]
This looks really great, @sabrinang. Would love to start getting feedback from @amirad, @chrislarry33, @soapdog, and RCs and CCs soon.

**Comment by hannahkane** [comment]
Closing because we've advanced a lot of this work. Let's open new tickets as we see the findings from the research project.

**Comment by soapdog** [comment]
I know this is closed but I just got here and would like to say that this is awesome and I am loving this work. Sorry for the delay in the feedback. Please tag me in future tickets, I promise I will act quicker.

**Comment by hannahkane** [comment]
No worries, @soapdog. Feel free to leave feedback on the redpen if you want. We'll be picking this back up after we see the results of the research project. Feedback in the meantime would be welcomed.
