### ISSUE TITLE
teach-api rewrite plan

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1185]
@Pomax, there are lots of design related deliverables scheduled in the [Sept 11 Milestone](https://github.com/mozilla/teach.webmaker.org/milestones/September%2011,%202015).  I'm trying to find things for us devs to work on without getting much design help within that heartbeat and I think teach-api rewrite can be one of them.

No details yet and I'm hoping to work with you on the plan once you get a chance. :bowtie: 

/cc @hannahkane

**Comment by Pomax** [comment]
let's make this dependent on the work done in https://github.com/mozilla/teach.webmaker.org/issues/1180, https://github.com/mozilla/teach.webmaker.org/issues/1181, https://github.com/mozilla/teach.webmaker.org/issues/1182, and https://github.com/mozilla/teach.webmaker.org/issues/1183

**Comment by mmmavis** [comment]
no longer applicable
