### ISSUE TITLE
As an authenticated user, I should be able to apply for a badge instance

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1192]
Entry point: the badge landing page (#1191)

Acceptance criteria:
 * I can see the criteria 
 * I can submit my evidence
 * I am aware of the timeline for my application to be reviewed
 * I am notified when my application is approved or denied
 * My authentication experience should be seamless
 * I should be able to choose from a list of partner organizations that I might belong to

Phases of work:
 - [ ] Design workflow and page design
 - [ ] Implement workflow, including authentication step

**Comment by AbuAlKarmi** [comment]
@hannahkane @simonwex @kristinashu 
I'm working on the Badges MVP, and I need to know the status of the design thinks and the flows. 
any updates please?

**Comment by hannahkane** [comment]
I believe the designs for the application workflow are here: https://redpen.io/p/tq1fbf0a41edd3909f. @kristinashu, can you verify?

**Comment by kristinashu** [comment]
Yes, starting at "MLN Badge: Detail Apply" and then once the user applies they would get an email verification. Once the application has been reviewed, a user will receive an approved/rejected email. If approved and a user goes back to the badge detail page, they would see "MLN Badge: Detail Approved".

**Comment by Pomax** [comment]
This is blocked until souktel has access to a working heroku setup

**Comment by Pomax** [comment]
- [ ] I can see the criteria
- [ ] I can submit my evidence
- [ ] I am aware of the timeline for my application to be reviewed
- [ ] I am notified when my application is approved or denied
- [ ] My authentication experience should be seamless
- [ ] I should be able to choose from a list of partner organizations that I might belong to

**Comment by hannahkane** [comment]
Just a note that I don't think the last item is needed at this time. And the third one might be vague...e.g. a success message that says "Thanks for applying for the [name of badge] badge. We'll let you know when your badge has been reviewed."

**Comment by Pomax** [comment]
perfect. I've updated the checklist to reflect that.
