### ISSUE TITLE
As a user, I can access my earned and pending badge instances from my Member Profile

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1194]
Acceptance criteria:
 * My earned badges as well as the evidence I submitted are displayed on my Member Profile
 * My pending badges are displayed only to me
 * I can easily share my badges on social media profiles

Blocked on creation of member profile (in progress)

**Comment by AbuAlKarmi** [comment]
@hannahkane @simonwex @kristinashu any updates regarding the work that done on Member profile? 
Or should I work on that? if So, I need to send me the needed designs. and How the badges should appear on that profile?

**Comment by hannahkane** [comment]
We won't have a full member profile any time soon, but perhaps @kristinashu can provide a design for a My Badges page (similar to the projects page at /me).

Ideally, this page would be accessible by others. That is, if a user wants to share their "My Badges" page, they should be able to copy/paste the url and share with friends.

**Comment by kristinashu** [comment]
I've added a couple profile screens to https://redpen.io/p/tq1fbf0a41edd3909f

Users would primarily see their badges on the logged in view of "Badge: Landing" but I guess they could also see it on the new profile page "MLN My Profile". If a user shares their profile page with someone else, that person would see "MLN External profile"

@hannahkane does that sound right?

**Comment by hannahkane** [comment]
@kristinashu. Yes, I think this an ideal interim step, before we have a fully fleshed out profile.

**Comment by AbuAlKarmi** [comment]
Working on this issue

**Comment by samerasbahh** [comment]
@simonwex @Pomax @issasouktel @AbuAlKarmi 
Blocked by Heroku installation

**Comment by Pomax** [comment]
Would it make sense to, for MVP at least, let users do this through Credly's website, rather than our own?

**Comment by hannahkane** [comment]
Yes. :) Closing.
