### ISSUE TITLE
As an admin, I should be able to search issued badge instances

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1195]
Acceptance criteria
* I should be able to search previously issued badges by date range, badge type, location of applicant, partner organization, or reviewer.  
* The search results should include all of the above fields, as well as the recipient's name, email address, and link to their user profile
* The results should be exportable in a useful format, such as .csv

Phases of work:
 - [ ] Design search UX
 - [ ] Implement functionality

**Comment by Ihab-Asafrah** [comment]
I noticed that the badges function in Credly API matches the query string/keyword with the badge title only. So there is no direct way to match a query with the badge description or creation date or any other criteria. Can we perform the search process and the matching on the Teach API itself and return the matched badges to any application that request them?

**Comment by hannahkane** [comment]
cc @Pomax

**Comment by AbuAlKarmi** [comment]
@hannahkane @simonwex @kristinashu I need to provide me with the required designs to be implemented.

**Comment by hannahkane** [comment]
@simonwex @AbuAlKarmi - is there existing UI/UX for this on the cred.ly side, or do we need to provide UI for our side?

**Comment by simonwex** [comment]
@hannahkane this functionality exists in the credly UI available to admins.

**Comment by hannahkane** [comment]
Then let's just go with that UI.

**Comment by Pomax** [comment]
resolving this due to decision to use credly's own UI for this.
