### ISSUE TITLE
Add Google Analytics event tracking to outbound links on /tools

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1196]
...so we know how many people are finding those tools via our site

/cc @hannahkane @Pomax

**Comment by Pomax** [comment]
we could use our own link component that can do tracking if a `ga={...}` is passed in. That way we can track any link we want to track, only when we want to.

**Comment by mmmavis** [comment]
I added a [`<OutboundLink>` component](https://github.com/mozilla/react-ga/blob/fa681ffafdb094b0e05a1cf1e80d695f84942a6b/src/components/OutboundLink.js) on Adam's react-ga that we can probably make use of. 

e.g., https://github.com/mozilla/teach.webmaker.org/blob/5b5d5be732b03ef75f13feb5cd8d0c21b3c14472/pages/activities.jsx#L93

**Comment by mmmavis** [comment]
assigning this to myself
