### ISSUE TITLE
rename repository to teach.webmaker.org to teach.mozilla.org

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1197]
things to consider:
- CI linking
- issue links from other github locations
- issue links externally

**Comment by mmmavis** [comment]
moving this to this milestone as the repo has already been rename to teach.mozilla.org as part of the Webmaker deprecation plan.

**Comment by mmmavis** [comment]
I plan to push out a new release tomorrow.  We'll see if Travis CI linking works.

**Comment by mmmavis** [comment]
we have successfully pushed out a new release just now!  YEAH :clap:
