### ISSUE TITLE
rewrite the goggles login system to use id.wmo

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1220]
based on https://github.com/mozilla/teach.webmaker.org/issues/1184

**Comment by hannahkane** [comment]
@Pomax - is this ticket going to close this heartbeat, or should we move to the next?

**Comment by Pomax** [comment]
this works, PR https://github.com/mozilla/goggles.webmaker.org/pull/202 is open for this, but is currently blocked to land pending publish.wmo schema changes, and some cleanup to take hardcoded URLs out of the code.
