### ISSUE TITLE
club listing usernames still link to webmaker.org

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1228]
https://teach.mozilla.org/clubs/list uses the old webmaker.org/en-US/search/.... to link to people's profiles. If those are no longer going to be maintained, we may have to turn those into "not links"

**Comment by mmmavis** [comment]
Agree if the profile search service on Webmaker has been deprecated.

cc @hannahkane

**Comment by hannahkane** [comment]
Hmm...yeah, I guess we can just un-link for now, and then re-link when we have Teach profiles.
