### ISSUE TITLE
remove Toolkit from Clubs sub-nav

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1234]
We're replacing the Toolkit with new content: "Your First Month as a Club Captain" and "Your First Month as a Regional Coordinator" guides. These are in the process of being built now and will be github pages for the time being.

For now, please remove the Toolkit from the Clubs sub-nav.

**Comment by mmmavis** [comment]
do we also want to kill https://teach.mozilla.org/clubs/toolkit/ ? or simply remove the Toolkit from side nav is enough?

**Comment by hannahkane** [comment]
Let's kill it since the content is now out of date.

**Comment by mmmavis** [comment]
On https://teach.mozilla.org/clubs/ and https://teach.mozilla.org/clubs/list/ we have a link that goes to the `/clubs-toolkit` page. Do we want to remove it or replace it with something else?

![screen shot 2015-09-14 at 5 04 41 pm](https://cloud.githubusercontent.com/assets/2896608/9864810/b820ab96-5b02-11e5-852d-42e8d9a78968.png)

**Comment by hannahkane** [comment]
Oooh...thanks for noticing it. Let's link that to http://mozilla.github.io/learning-networks/clubs/. Can keep copy and illustration the same.
