### ISSUE TITLE
Oct 1: Create "Our submission approval process" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1236]
- [x] https://github.com/mozilla/2015.mozillafestival.org/issues/177

This page should **not** be live *before* October 1.

**Comment by hannahkane** [comment]
blocked on not having content

**Comment by hannahkane** [comment]
Closing here, too. Go @mmmavis!

**Comment by mmmavis** [comment]
thanks, totally forgot this ticket :grimacing:
