### ISSUE TITLE
Update auto-responder email for new club signups

### ISSUE THREAD

**Issue by amirad** [mozilla/teach.mozilla.org#1241]
New text here
https://teach.etherpad.mozilla.org/clubsignupemail

@ldecoursy can you give the text a quick peek to make sure it's fine?
@hannahkane updating the text with questions we send clubs after they sign up.

**Comment by hannahkane** [comment]
Comments added to the pad. Will put into a milestone as soon as we have final copy!

**Comment by hannahkane** [comment]
@amirad - can you ping when you have final copy for this?

**Comment by hannahkane** [comment]
We did this. Closing.
