### ISSUE TITLE
Meet with Ryan to transfer ownership of the MozFest app

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1243]
Seems like a meeting is the best place to start! Early in the heartbeat if possible.

**Comment by mmmavis** [comment]
Hey @ryanpitts ,

I just forked and quickly checked out your amazing [mozfest-test-schedule](https://github.com/ryanpitts/mozfest-test-schedule). :clap: Everything seems pretty straightforward and customizable! Awesome work! This will definitely save us many many hours :+1: 

2 questions:

- This ticket title mentioned about "ownership transfer". Is there anything you have built that needs be transferred to the MozFestLand?
- Did the SRCCON app use any cache server? Just curious what's the best way to serve data. I don't know much about it but I guess I can check with DevOps people on this as well.

I'm going to meet with Adil(our MozFest designer) tomorrow to see his design proposal on the schedule app.  Will ping you if I have further questions :bowtie:

**Comment by ryanpitts** [comment]
Hmm, the only thing I can think of would be just transferring that GitHub repo to the MoFo org? Happy to do that, or it also might be just as easy to download that code and start a fresh repo to work from? Just let me know.

We didn't have to use any cache server, because the whole thing is flat files :) The `sessions.json` file contains all the data, so once someone loads the schedule the first time, they've got everything locally.

**Comment by mmmavis** [comment]
@ryanpitts 
> [...] it also might be just as easy to download that code and start a fresh repo to work from? Just let me know.

Yea would you mind doing this? I could do this myelf too but I don't wanna steal the credits from you :grin:  I *think* "mozfest-schedule-app" can be the repo name but I'm up for anything you suggest. :+1:

**Comment by mmmavis** [comment]
@ryanpitts 

Ah, I have another question (not sure if you know the answer). Is this app going to live on https://2015.mozillafestival.org/, on its own domain, or a subdomain on a mozfest url?

**Comment by mmmavis** [comment]
@ryanpitts got some time to help on this today? :smile:

**Comment by ryanpitts** [comment]
Yep, definitely. Which org should I create the "mozfest-schedule-app" repo inside? Mozilla? Mozilla Foundation?

**Comment by ryanpitts** [comment]
As for where it should live, when we've used this app with SRCCON, we've always gone with a schedule.srccon.org sudomain pointed at the gh-pages site. No deployment required, updating sessions.json in the repo means that the app automatically gets new data. If that approach works for MozFest, it sure gets rid of some headaches.

**Comment by mmmavis** [comment]
> Yep, definitely. Which org should I create the "mozfest-schedule-app" repo inside? Mozilla? Mozilla Foundation

mozilla is good, thanks! :+1: 

> As for where it should live, when we've used this app with SRCCON, we've always gone with a schedule.srccon.org sudomain pointed at the gh-pages site. No deployment required, updating sessions.json in the repo means that the app automatically gets new data. If that approach works for MozFest, it sure gets rid of some headaches.

wow, never thought of this!  good suggestion :D

**Comment by ryanpitts** [comment]
OK, repo is ready! https://github.com/mozilla/mozfest-schedule-app

**Comment by mmmavis** [comment]
Raaaad! :tada: 

Thanks for much @ryanpitts :dancers: :dancers: :dancers:
