### ISSUE TITLE
design 404 page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1247]
See #406

**Comment by emmairwin** [comment]
@hannahkane is there a wire frame for this ?  or..

**Comment by hannahkane** [comment]
Nope, @emmairwin. This ticket is for creating one!

**Comment by kristinashu** [comment]
@natalieworth is going to help out with this one (thank you!). She's going to illustrate and possibly make an animated gif. We're thinking of playing off 'page not found' and show an open book with pages flying out of from it - using a book will also play off the teaching aspect. Kinda like these:
![b02e1cafc38b3062214c8cd78dc82d31](https://cloud.githubusercontent.com/assets/1068783/11942143/6f8092f0-a7e9-11e5-8a28-6b657a1ef1a3.jpg)
![stock-illustration-1829536-open-book-flying-pages-illustration-350x350](https://cloud.githubusercontent.com/assets/1068783/11942142/6f7f677c-a7e9-11e5-8819-59c6ca62e41a.jpg)

Here's a layout of the page with the copy:
![teach-404-01-01](https://cloud.githubusercontent.com/assets/1068783/11942129/4faa2e8c-a7e9-11e5-8140-61b9f6dbca34.jpg)

**Comment by natalieworth** [comment]
@kristinashu Have a draft of the book illustration up on red pen: https://redpen.io/p/ugc7c37b6146ed5b34 I haven't added animation yet, so it may slightly affect the layout of the design depending on how the pages move but I'm not anticipating it'll change too much.

**Comment by kristinashu** [comment]
@natalieworth sweet, looks great! The layout is super flexible so don't let that restrict you. Looking forward to seeing it animated!

**Comment by mmmavis** [comment]
@kristinashu @natalieworth Rad! :tada: 

I volunteer to implement this page! Don't wanna lose the opportunity to practice my CSS animation skills. Heh!

**Comment by natalieworth** [comment]
@mmmavis Would CSS animation be easier for you to implement? I was also thinking we could create a gif for it, but would this be more difficult on your end? Or I could mock it up in After Effects for how the motion should look, then we could try animating it in CSS?

**Comment by mmmavis** [comment]
@natalieworth I do agree this might be too complicated for me a CSS animation n00b to implement ha! Let's go with gif first in case it takes me forever to animate it in code :bowtie:

**Comment by natalieworth** [comment]
@kristinashu Super rough, but I was able to get the page flip plug-in to work in ae! I'll have to adjust a lot of things still, e.g. timing, position, add more pages flipping, etc.—so this is just to get an idea of the flip :)  (page is pink too since it was hard to see/ animate with white on white, but I will change the colours back if the gif works out) 
![book_layers_04](https://cloud.githubusercontent.com/assets/14876567/12210437/cf42cfa4-b60e-11e5-9346-03089b7edc83.gif)

**Comment by kristinashu** [comment]
OMG it's working! Very cool.

**Comment by mmmavis** [comment]
Looking rad! :wink: 
@kristinashu @natalieworth is this ready for implementation? Do I reference https://redpen.io/yw5a4c7ed0dce5e275 and substitute the static image with the awesome gif @natalieworth made?

**Comment by kristinashu** [comment]
@mmmavis not quite ready yet. @natalieworth is doing the finishing touches on the gif 

You could build an interim static page tho, if you're keen.

**Comment by mmmavis** [comment]
Cool, that's fine. I'll wait till this design ticket is finished and close then :+1:

**Comment by natalieworth** [comment]
@flukeout

**Comment by hannahkane** [comment]
moving to next heartbeat to reflect actual priorities

**Comment by hannahkane** [comment]
@natalieworth - has there been any progress on this? It's not urgent, so I can remove from the milestone if it doesn't fit in, given other priorities.

**Comment by cassiemc** [comment]
This seems launchable with a static graphic, if the animation isn't done.

**Comment by natalieworth** [comment]
@hannahkane I've got the .ai files and an svg file here if you are wanting to implement static for now:

**Comment by hannahkane** [comment]
Thanks, @natalieworth! I think the page flip looks good, but will let @cassiemc make the final call. If we decide we do want to work more on this, I'm going to suggest we take it out of the milestone, because there are lots of other things going on.

**Comment by cassiemc** [comment]
Yes, R+ on the gif. Thanks @natalieworth! If you want to file a follow up issue for further finesse please feel free, we can loop it into a future heartbeat, but this looks great to me.

**Comment by hannahkane** [comment]
Cool. Closing this ticket, and unblocking the implementation ticket. Thanks, all!
