### ISSUE TITLE
Polish goggles login experience

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1248]
@Pomax to provide details

**Comment by Pomax** [comment]
While id.wmo login works now, the look is not very good.

Initial attempt to publish, without a login already having been established:

![screenshot 30](https://cloud.githubusercontent.com/assets/177243/9857226/330c1578-5ace-11e5-834d-d8c59a1f6fb3.png)

This pops up a new window, currently unrestricted in size:

![screenshot 31](https://cloud.githubusercontent.com/assets/177243/9857227/3683dfb0-5ace-11e5-8da4-737d54917cb0.png)

The user fills this in and gets redirected to a goggles-hosted "hurray you logged in" page:

![screenshot 32](https://cloud.githubusercontent.com/assets/177243/9857229/37ce3d3e-5ace-11e5-851e-440411e06887.png)

That page basically just says "hurray you logged in you can close this window now", after which the page the user was editing on and was trying to publish regains focus and checks for the authentication information. If it finds it, it shows "who you are" and will enable the publish options:

![screenshot 33](https://cloud.githubusercontent.com/assets/177243/9857231/390d7d0e-5ace-11e5-9b3d-c38d299facf9.png)

**Comment by kristinashu** [comment]
@Pomax can you please clarify what can/can't be styled here? I know the login is fixed but can the other pages change? Layout, button styles, font size, colors... Can light box be smaller?

**Comment by kristinashu** [comment]
I've mocked up these screens. You can see them below or here https://redpen.io/p/wjdd96d46ae8c63dc3
I've copied the steps above and left a few question. Let me know if something isn't doable. 

Initial attempt to publish, without a login already having been established:
![signin-02](https://cloud.githubusercontent.com/assets/1068783/10379494/6c0090a4-6dc3-11e5-92cd-050b2172d1f3.jpg)

This pops up a new window, currently unrestricted in size: Can we change anything here? Can we restrict the window size?
![signin-03](https://cloud.githubusercontent.com/assets/1068783/10379495/6c1118e8-6dc3-11e5-90f4-5b81c30d0f9a.jpg)

The user fills this in and gets redirected to a goggles-hosted "hurray you logged in" page: Do we have to have this step or can the window close automatically? Can we have this back button?
![signin-04](https://cloud.githubusercontent.com/assets/1068783/10379497/6c2f57b8-6dc3-11e5-9cc6-9b50236a85e4.jpg)

Enable the publish options: Do we have to have this step? Can it just publish and go to publish confirmation?
![signin-05](https://cloud.githubusercontent.com/assets/1068783/10379496/6c21eb96-6dc3-11e5-9930-f346932d1aa9.jpg)

Publish confirmation:
![signin-06](https://cloud.githubusercontent.com/assets/1068783/10379498/6c3fc0e4-6dc3-11e5-80a5-26dae840eb5e.jpg)

**Comment by Pomax** [comment]
my todo for this: file implementation issue based on these designs

**Comment by Pomax** [comment]
new login landed via https://github.com/mozilla/teach.mozilla.org/issues/1322, let's file new issues we find due to the switch as follow up issues.
