### ISSUE TITLE
MozFest favicon

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1249]
- [ ] https://github.com/mozilla/2015.mozillafestival.org/issues/200

**Comment by sabrinang** [comment]
@mmmavis 
Using the Mozilla Festival Logo as the favicon and exported various sizes of the logo here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_edGJhUDhvdHBsX2c&usp=sharing

 ![mozilla-festival_favicon-114x114](https://cloud.githubusercontent.com/assets/2492510/9862144/d1025126-5aeb-11e5-8f1e-b4538d8c64ba.png)

Tried to make an tiny 16x16 .ico version :mag::mag: haha if you find it useful it is in the folder too
<img width="1440" alt="screen shot 2015-09-14 at 2 28 54 pm" src="https://cloud.githubusercontent.com/assets/2492510/9862354/27086348-5aed-11e5-85a9-95784cb3a657.png">

**Comment by mmmavis** [comment]
live on http://2015.mozillafestival.org/
if we want to use a crisper version of favicon let's just create a new ticket instead
