### ISSUE TITLE
Add OpenGraph tags to MozFest site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1250]
- [ ] https://github.com/mozilla/2015.mozillafestival.org/issues/201

**Comment by sabrinang** [comment]
@mmmavis 
The recommended resolution for an OG image is 1200 pixels x 630 pixels (1.91/1 ratio) - some social media channels crop it so it is 1:1 so the first graphic will work for both and I exported it 630 x 630 in case you need it.

![mozfest-opengraph-imagetag-1200x630](https://cloud.githubusercontent.com/assets/2492510/9861257/03bce460-5ae6-11e5-86ec-40cbed620dc2.png)
![mozfest-opengraph-imagetag-630x630](https://cloud.githubusercontent.com/assets/2492510/9861256/03b9ee5e-5ae6-11e5-96fb-a7c7e445129d.png)

Assets located here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eUWk2ZFA4QldXVzg&usp=sharing

**Comment by mmmavis** [comment]
:tada: done!

**Comment by hannahkane** [comment]
woohoo!
