### ISSUE TITLE
Add messaging for deprecated Appmaker/Popcorn Makes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1252]
We're going to allow people access to their old Makes, but we need a friendly message to let them know that we're no longer supporting these tools, and therefore they aren't remixable.

I'm thinking it's just a banner at the top of the Make, and at the top of the landing page.

Suggested copy: "Unfortunately, we no longer support [name of tool], so your awesome project is no longer remixable. Guess it's one-of-a-kind!"

cc @xmatthewx to fact-check 
cc @KevZawacki to provide better copy

(This will close https://github.com/MozillaFoundation/plan/issues/527)

**Comment by KevZawacki** [comment]
I like the "one-of-a-kind" phrase, but worry some affected users might find it too playful. So perhaps:

"Unfortunately, we no longer support [name of tool], so your awesome project is no longer remixable. Have you tried the new [Mozilla Thimble](http://thimble.mozilla.org)."

**Comment by jbuck** [comment]
Sure

**Comment by hannahkane** [comment]
@Pomax - don't want to forget about this one. Are there any blockers to finishing this one this heartbeat?

**Comment by hannahkane** [comment]
Possible to get done today, or should we move to next heartbeat?

**Comment by Pomax** [comment]
@jbuck @cadecairos we took out the remix button in make-valet, can we make the valet service generate that banner on top? It feels like that's the quickest way to land this.

**Comment by cadecairos** [comment]
It shouldn't be too difficult to add a banner to the make-valet wrapper page, I think

**Comment by jbuck** [comment]
Yeah, that should be an easy change
