### ISSUE TITLE
Disable current badge application flow

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1253]
Users are somehow finding the badge application flow (I'm not sure how) and applying for badges that we are no longer supporting. Can we disable this flow? What's the easiest way to do that? Perhaps just removing the "Apply" button and replacing it with a message??

Solution being discussed here: https://github.com/MozillaFoundation/plan/issues/558

**Comment by hannahkane** [comment]
@davidascher - can you provide some insight into the best way to prevent users from applying for badges using the old flow? No one seems sure of the most efficient way to do that.

**Comment by hannahkane** [comment]
@Pomax - see conversation on https://github.com/MozillaFoundation/plan/issues/558.

**Comment by Pomax** [comment]
Changes suggested in https://github.com/MozillaFoundation/plan/issues/558 look to require a change to the views/badge-details.html file, which should kick in for all badge routes we are still hosting.

**Comment by Pomax** [comment]
@hannahkane is there copy anywhere that can be dropped in to explain why you can no longer apply for a badge (perhaps with a link to a moz post about that?)

**Comment by Pomax** [comment]
![screenshot 52](https://cloud.githubusercontent.com/assets/177243/10460580/cd51225a-7189-11e5-982d-8856fa24d2b3.png)

**Comment by hannahkane** [comment]
Hmm...good question, @pomax. 

@chrislarry33 - any suggestions on how to frame the changing badges? It's entirely possible we'll start supporting these badges again in the future. How about, "Please note: We are temporarily unable to support approving new badge requests, as we migrate to a different badging platform. Please follow the [Mozilla Learning Blog](https://blog.webmaker.org) for the latest updates on badges."

**Comment by Pomax** [comment]
What about "Please Note: we will not be issueing badges for a while as we migrate to a new badging platform. Please follow the [Mozilla Learning Blog](https://blog.webmaker.org) for the latest updates on badges"?

**Comment by anmechung** [comment]
+1 @hannahkane language. "Temporarily unable" sounds more positive than "for a while"

**Comment by Pomax** [comment]
The one problem I have with "unable" is that it suggests that the availability is not our own decision. Would something like "Approving new badge requests has been disabled while we migrate to a new badges platform. Please follow the [Mozilla Learning Blog](https://blog.webmaker.org) for the latest updates on badges." work?

**Comment by hannahkane** [comment]
+1 for the passive voice

**Comment by Pomax** [comment]
PR updated to use the text from https://github.com/mozilla/teach.mozilla.org/issues/1253#issuecomment-148464818

**Comment by Pomax** [comment]
There is some oddness going on with webmaker staging on heroku, it does not seem connected to a badgekit with actual badge information, making testing rather difficult. @cadecairos @jbuck can we tell webmaker staging to use the same badgekit creds as the production instance?

**Comment by jbuck** [comment]
@Pomax Just :shipit: to prod

**Comment by Pomax** [comment]
are we still using Jenkins for oid wmo?

**Comment by jbuck** [comment]
@Pomax yes, we are

**Comment by Pomax** [comment]
webmaker.org v1.1.158 deployed with the updates merged. Example: https://webmaker.org/badges/webmaker-mentor

**Comment by hannahkane** [comment]
Thank you!

/cc @amirad
