### ISSUE TITLE
Mockups for user badge pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1257]
Based on wireframes https://redpen.io/p/cf7e3f8ea85544c703 created in #1218 

Pages include: 
- badges overview landing page
- badge detail page
- confirmation email
- approval/denied email
- badge section of the user profile page

Design of badges #1242

**Comment by kristinashu** [comment]
Here are the comps: https://redpen.io/p/tq1fbf0a41edd3909f

Badge designs are just placeholder for now - dependent on #1242

I've based the 21 Century Skills badges on this content https://etherpad.mozilla.org/21CSkillsbadgesdesign
Instead of having macro and micro badges I'm suggesting we keep them all equal and we use colors as a way to differentiate the different badge types (to keep it simple as possible). 

At this stage, I think it would be helpful to get more content in order to better plan out the layout.

**Comment by anmechung** [comment]
@kristinashu  This is what I was trying to send you earlier - https://docs.google.com/spreadsheets/d/1FlW5VfBXus-WY0PIqs7MG7RDiuNYS0OZadYOiWcNxHI/edit#gid=1436259449
Is this what you mean by having more content?

**Comment by kristinashu** [comment]
@anmechung thanks for sharing the doc - this is helpful. 

For content I also mean it would be great to know what all the badges will be (beyond 21st century) and what all the copy will be (section title, badge descriptions and requirements, email copy...).

**Comment by anmechung** [comment]
Agreed, but this info not available now.  We're starting with just 21C Skills badges as a test, and then will move on from there with the web literacy and other badges based on what we learn.

**Comment by kristinashu** [comment]
@hannahkane @cassiemc @sabrinang let me know if you have any feedback on the comps https://redpen.io/p/tq1fbf0a41edd3909f

**Comment by cassiemc** [comment]
Looking good, I like that purple. Left a few comments on the redpen about layout and hierarchy of info.

@hannahkane we are going to need to socialize the badge changes with the moco team who originally designed the system. Please let me know when we're at a good point to do that and I can help set it up.

@davidascher was also interested (as am I!) in doing some thought experiments around how badges might roll out in other products, ie webmaker or thimble. This could certainly impact the style of badges themselves so I'd recommend we do this soon.

**Comment by kristinashu** [comment]
Thanks for the feedback! I've updated the comps https://redpen.io/p/tq1fbf0a41edd3909f

**Comment by hannahkane** [comment]
Looks great, @kristinashu. Wondering if @KevZawacki or @ldecoursy has time to do a pass through for copy?

**Comment by KevZawacki** [comment]
Happy to do a copy edit. Is the text also living in a pad somewhere? A bit easier to tweak it that way.

**Comment by anmechung** [comment]
@KevZawacki - we have some real draft copy for the actual badges that I'll forward to you

**Comment by hannahkane** [comment]
@anmechung - what's the best way to solicit feedback from our partners on this?

**Comment by kristinashu** [comment]
Made some design updates to the comps https://redpen.io/p/tq1fbf0a41edd3909f

**Comment by anmechung** [comment]
@hannahkane - have a call scheduled with partners Oct 5 and will solicit feedback.  In the meantime, I've shared the redpen comps and asked that they show to youth and get feedback.

**Comment by hannahkane** [comment]
@anmechung - hmm...might want to wait until we have better copy before sharing with that audience.

**Comment by hannahkane** [comment]
@kristinashu - we said we could close this, right? just want to double check. :)

**Comment by kristinashu** [comment]
@hannahkane yup
