### ISSUE TITLE
Redesign footer bar

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1258]
- assess better location for items (i.e. surface about into main navigation? removed webmaker?)
- highlight social 
- be strategic about how content aligns with MLN (i.e. if we document program offerings like hive it should not be highlighted in footer but on that program page)
- align with navigation/side bar design

**Comment by mmmavis** [comment]
relates to #505

**Comment by kristinashu** [comment]
covered by #1368
