### ISSUE TITLE
Visual Design Audit for MLN

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1260]
We can audit and collect examples in MLN site that are an immediate visual/brand issues that we can propose ideas to solve.

cc/ @kristinashu @cassiemc @lovegushwa 

**Attributes to review:**
- [x] headers
- [x] footers
- [x] grid / responsive layouts
- [x] illustration (needs updating with badges work)
- [x] photography
- [x] iconography
- [x] typography
- [x] colors (needs updating with badges work)
- [x] buttons
- [x] labels
- [x] treatment/placement of logo

**Comment by sabrinang** [comment]
![mln_visual-brand-issues3](https://cloud.githubusercontent.com/assets/2492510/9864570/ba3b2684-5aff-11e5-85bc-bb30649dd9ed.png)

- current usage of mozilla wordmark on MLN has been the interim solution

**Comment by sabrinang** [comment]
![mln_visual-brand-issues2](https://cloud.githubusercontent.com/assets/2492510/9864598/0c36620a-5b00-11e5-8964-f7f50264f927.png)
- font awesome is the font icon set we use on the site
- line art from various creators has different styles and haven't yet established unified method to create them

**Comment by sabrinang** [comment]
![mln_visual-brand-issues1](https://cloud.githubusercontent.com/assets/2492510/9864647/8bed8a6e-5b00-11e5-88e9-68c05319cb62.png)
- have been using light blue as MLN site main colour
- unsure if these colours align with existing properties and how do we establish new colours in the palette?

**Comment by sabrinang** [comment]
![mln_visual-brand-issues4](https://cloud.githubusercontent.com/assets/2492510/9865028/573e8994-5b05-11e5-87f9-b2bb6072cc75.png)
- variations due to different uses and implemented at different times (can be easily streamlined when we decide on which styles)
- related to issue #1045

**Comment by sabrinang** [comment]
related to issue #1083

**Comment by lovegushwa** [comment]
yes @sabrinang this is so good!

**Comment by cassiemc** [comment]
Wow, this is amazing @sabrinang. This list is surfacing a whole bunch of meaningful bugs. I would start turning your questions into individual issues and assign them to a big milestone, "designaudit" or something. @hannahkane have you seen this?

**Comment by hannahkane** [comment]
I have seen this, but thanks for the reminder to comment, @cassiemc. This is fantastic.

+1 to the idea of adding individual tickets (I know at least one is already ticketed - the button one). It will be difficult to prioritize these issues, given the abundance of high-priority projects we have, so I'm wondering if we can label them with "designaudit" but add them individually to the dated milestones (e.g. "September 25, 2015") rather than put them all in a shared milestone. This way we can resolve the various inconsistencies over time, within the context of our regular project prioritization.

**Comment by cassiemc** [comment]
yes that makes a lot of sense @hannahkane, that is why you are PM and not me hahah :)

**Comment by cassiemc** [comment]
Copying a checklist from the [Mofo Design Audit ticket](https://github.com/MozillaFoundation/Design/issues/94) to the top comment. Once we complete that checklist we can close this issue.

**Comment by sabrinang** [comment]
We will complete this audit and transfer it into a gslide deck and format similarly to the MoFo wide audit for comparison purposes. (Benchmarking will also be in these slides)

Next steps after would be to examine problems that are surfaced and prioritize them with analytics to help with decision making on what to focus on.

**Comment by hannahkane** [comment]
Thanks for the update. Exciting!

Just to confirm my understanding - the deliverables for the Oct 23 milestone will be the deck and a list of prioritized issues, is that right? If so, can we either add those to the first comment in this ticket, or perhaps open a new ticket?

**Comment by sabrinang** [comment]
Let's tackle this with 8 hrs and after that we can reassess how far we are on this ticket.

**Comment by sabrinang** [comment]
Almost complete the audit and working on it on google slides here: https://docs.google.com/a/mozilla.com/presentation/d/1ICoje0Bxq_OwLsMR9yl1gNECwZUCQQoV1wpvm7T5hps/edit?usp=sharing

**Comment by sabrinang** [comment]
The deck is complete with all the sections noted on the ticket (with interface and visual elements included too): https://docs.google.com/presentation/d/1ICoje0Bxq_OwLsMR9yl1gNECwZUCQQoV1wpvm7T5hps/edit#slide=id.gcfe2d278c_0_36

@cassiemc @kristinashu  Please review the deck and if you have more notes feel free to add in the slide deck. Let's meet sometime this week to discuss and make the prioritized list so we are ready for next heartbeat with priorities in mind.

**Comment by kristinashu** [comment]
@sabrinang this is great!

**Comment by cassiemc** [comment]
Fantastic work @sabrinang and @kristinashu. Can't wait to see this manifest in more issues!

**Comment by sabrinang** [comment]
Around 30 issues are filed from this audit with the *design audit* label and referenced here. We can file more as we encounter them. Closing this ticket!
