### ISSUE TITLE
Wireframe for Directory homepage

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1263]
a landing page for users when they want to search in the directory
- search bar
- by location
- by type

a search results page after user enters keyword or query
- filters
- results

(various states to consider)
- not logged-in
- logged-in
- logged-in with admin capabilities

**Comment by sabrinang** [comment]
mobile (and desktop) wireframe ideas of home page view
![mln_directory-home-pages-views](https://cloud.githubusercontent.com/assets/2492510/9893161/b97eaaec-5bca-11e5-8972-22e7d2d8ec30.png)

**Comment by sabrinang** [comment]
mobile wireframe of home page view category ideas
![mln_directory-home-pages-views2](https://cloud.githubusercontent.com/assets/2492510/9893196/fa797af4-5bca-11e5-9423-5f0e5622bc2f.png)

**Comment by sabrinang** [comment]
mobile wireframe of home page view site navigation ideas to help orient the user of where the directory is in relation to the MLN website
![mln_directory-home-pages-views3](https://cloud.githubusercontent.com/assets/2492510/9893219/2edb13ac-5bcb-11e5-9004-d7004b8d6c96.png)

**Comment by sabrinang** [comment]
mobile wireframe of results page view ideas
![mln_directory-home-pages-views4](https://cloud.githubusercontent.com/assets/2492510/9893854/f77ccd40-5bd1-11e5-8da2-a983af00f44e.png)

**Comment by sabrinang** [comment]
mobile wireframe of more search and filtering view ideas
![mln_directory-home-pages-views5](https://cloud.githubusercontent.com/assets/2492510/9921826/c893b9c4-5c96-11e5-85db-8c44cf047f14.png)

**Comment by sabrinang** [comment]
simplified search homepage by removing category option and include location UI
![mln_directory-wireframes-home_v2](https://cloud.githubusercontent.com/assets/2492510/10027769/98721624-611d-11e5-9e5a-4807bd56484d.png)

excluded filtering for a sort by option previously seen on homepage and included location UI
![mln_directory-wireframes-search-results_v2](https://cloud.githubusercontent.com/assets/2492510/10027777/9bdce2ee-611d-11e5-98f9-1d5c587cff04.png)

**Comment by hannahkane** [comment]
Just flagging this as "needs testing" for @LauraReynal, because I think it's an area where we really need to better understand users' mental models for searching.

**Comment by LauraReynal** [comment]
Perfect. cc @secretrobotron 

---


@sabrinang I was thinking about using the wireframes for research. Would that work for you?
I am thinking of combining all of them into a single deck (teach / directory /login / curriculum / badges etc) and use them for testing / prompting questions. 
We'll probably do the live testing on the teach.mozilla.org website as welll, with questions such as : can you look for curriculum ? To see the mental models and our IA.

**Comment by sabrinang** [comment]
@LauraReynal Yeah using the wireframes for research would be great! I think wireframes on a refined a slide deck or even a rough prototype will be great for user in testing. If there is a format you have in mind I can definitely assist in formatting or adding additional screens to accompany and research questions.

**Comment by hannahkane** [comment]
Closing because we've advanced a lot of this work. Let's open new tickets as we see the findings from the research project.
