### ISSUE TITLE
Create new page for Webmaker activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1264]
This should use the same template as /activities/web-lit-basics, and should live at /activities/webmaker

 - [ ] Create the page. Content is here: https://docs.google.com/document/d/1FOEOjMlYc8iqtaDdmqAul-s8F37xGQaF8HqRU9RheDw/edit
 - [ ] Add a section to /activities that links to the new page. The content is in the same doc.

**Comment by mmmavis** [comment]
adding **blocked** label - looks like the content is still in its draft state

**Comment by hannahkane** [comment]
I don't think it's actually draft. I removed the word "DRAFT" from the title. Let me know if anything in the doc is incomplete.

**Comment by ldecoursy** [comment]
Just checking if if this is still blocked for any reason?

**Comment by hannahkane** [comment]
@mmmavis - do you know if the Grace Hopper team submitted a PR for this one?

**Comment by mmmavis** [comment]
@hannahkane ummm not that i'm aware of

**Comment by hannahkane** [comment]
@mmmavis - ok, then I'm calling it a p2 for this heartbeat.

**Comment by hannahkane** [comment]
Didn't get done, so moving to next heartbeat.
