### ISSUE TITLE
Interim design to accommodate /me transition

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1265]
We've messaged to users that they'll be able to access their "old' makes via webmaker.org/me, but we can no longer host that on Webmaker, so we need to move it to the teach site.

Step 1 is coming up with a new design that fits in with teach.mozilla.org. This is an example of what the current page looks like:

![screen shot 2015-09-15 at 3 19 30 pm](https://cloud.githubusercontent.com/assets/8389648/9891709/3a897300-5bbd-11e5-8851-59d13aafa7d1.png)

We don't need to add any functionality. We do need a way for authenticated users to access this page from teach.

**Comment by sabrinang** [comment]
Some initial questions:

**Content**
- when users are messaged they can access old "makes" - what does this include?
 - thimble only? or does this include webmaker projects or legacy makes from popcorn etc.?
- how does this work with the current thimble projects list (https://thimble.mozilla.org/projects/ when user is logged in)?
 - may be fragmented UX if new projects showed up in a separately from older projects

**Location on MLN**
- Where will users access this page?
 - from the tools page?
 - from clicking on their log-in name? (could mimic thimble's drop down to "Your Projects")

**Comment by hannahkane** [comment]
@cadecairos to verify, but here are my answers: 
* They can access all old Makes, from all old tools
* Old Thimble makes will have a "Open in New Thimble" option. I *think* both old and new Thimble makes will be accessible from "My Projects" page in Thimble, but that's outside the scope of this ticket
 * I like your second idea for placement - a dropdown from the username

**Comment by sabrinang** [comment]
@kristinashu - I posted some initial questions from the earlier discussion and feel free to add more and we can discuss how to dive into this page design

**Comment by sabrinang** [comment]
Discussed with @kristinashu and decided that to accommodate this interim makes page, we need to revise the log-in section beneath the logo on the MLN site. We can unify this style to look like our learning products that have projects *(like Thimble)*.

**User not logged-in:** has text for login or sign up

**User logged-in:** has profile image, username and drop down arrow

**Selected drop down:** the section is shaded and shows options to your makes or to log out

**On makes page:** the section is shaded to show your currently on it 

**Note on language:** There is an inconsistent language/labels between MLN and Thimble 
- sign up or create an account
- sign out or logout
- are we calling them projects or makes?
![dsc02309](https://cloud.githubusercontent.com/assets/2492510/10006898/0aeff584-6076-11e5-8921-5d78b1b9fed9.png)

**Comment by cadecairos** [comment]
I believe the old content generated from `thimble.webmaker.org`, `popcorn.webmaker.org`, `goggles.webmaker.org` and `apps.webmaker.org` are "makes". This content will continue to live on makes.org, I believe.

Content generated by the new Thimble at `thimble.mozilla.org` and from the Webmaker app is now referred to as "projects"

**Comment by cadecairos** [comment]
@hannahkane @sabrinang 

> They can access all old Makes, from all old tools

:+1: 

> Old Thimble makes will have a "Open in New Thimble" option. I think both old and new Thimble makes will be accessible from "My Projects" page in Thimble, but that's outside the scope of this ticket

:+1: - I'm not sure about old Thimble makes being accessible from within new Thimble, but certainly not a concern in this issue.

> I like your second idea for placement - a dropdown from the username

I'm no design guru, but that sounds good to me!

**Comment by hannahkane** [comment]
Thanks, @sabrinang and @cadecairos 

Re: terminology: I prefer Thimble's "Sign up" to Teach's "Create an account" because it is shorter and more human-sounding, but I prefer Teach's "Log out" to Thimble's "Sign out" because Sign Out is not a very common phrasing. If others agree, I can file a ticket to change "Sign out" to "Log out" in the Thimble repo.

Not sure what the right answer is for Makes vs. Projects. I find "Makes" to be less-than-intuitive, but I know *a lot* of our users are familiar with that term and would be looking for it. I guess I'm leaning towards "Makes," until we fully flesh out the profile, at which point I might advocate for switching to "Projects," and trying to socialize that term amongst our users.

The profile picture is weird to me, since we don't offer a way for users to edit it (I don't think). Can we leave that out until we add that functionality? (I can file on Thimble repo as well.)

**Comment by kristinashu** [comment]
@hannahkane @sabrinang @cadecairos here's a basic version of the profile page https://redpen.io/p/jm7c4b7f90c1269904

**Comment by hannahkane** [comment]
wfm. @cadecairos - do you need anything to start the implementation ticket?

**Comment by cadecairos** [comment]
@hannahkane I can take care of the /me page itself pretty easily, but I'm going need someone with some better HTML/CSS skills for that navigation menu change.

**Comment by hannahkane** [comment]
@mmmavis - are you the right person to help with the nav change?

**Comment by hannahkane** [comment]
Closing this ticket. Moving discussion to implementation ticket: #1276
