### ISSUE TITLE
Mozilla Learning Network - Directory Design

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1267]
### Context
The directory is part of a larger eco-system vision: http://mzl.la/1ILyfD8
Directory hypothesis, content and meeting notes from sharing initial design ideas *(see below)*: http://bit.ly/1ITuHhH
_____________________________________________
### Initial Ideas and Exploration
Initial design ideas, internal comparisons, questions and (desktop) iterations : http://bit.ly/1iuaTrF
From the slides above, here are some Mozilla resources I examined and referenced to be aware of:
> ####  Directories
> * Hive Global Directory: https://directory.hivelearningnetworks.org/
> * Hive Learning Networks (locations): https://hivelearningnetworks.org/locations/
> * Mozilla Reps (people): https://reps.mozilla.org/people/#/
> * Discourse: https://discourse.webmaker.org/users
> * Mozillians: https://mozillians.org
> * Mozilla Communities: https://www.mozilla.org/en-US/contact/communities/

> #### Profiles Examples
> * Hive Global Directory: https://directory.hivelearningnetworks.org/users/omnignorant/
> * Mozilla Reps: https://reps.mozilla.org/u/Tanha/
> * Discourse: https://discourse.webmaker.org/users/ldecoursy/activity
> * Mozillians: https://mozillians.org/en-US/u/mitchell/
> * Mozilla Developer Network: https://developer.mozilla.org/en-US/profiles/Blend4Web

_____________________________________________
### Wireframes
Next phase is to simplify directory ideas to MVP and mobile wireframes:
- wireframes of homepage: #1263
- wireframes of group page: #1181 *(hive page would be very similar #1183)*
- wireframes of member page: #1180
     - wireframes of report from a member to group (i.e. - club captain to mozilla club): #1182

*Wireframes on Redpen: https://redpen.io/p/ve944daa8712303367*

_____________________________________________
### Design
I’ll use this bug to track some bigger picture design deliverables that would be useful to create:
- [ ] A directory map - an overview to show how the pages are linked or grouped to form this directory
- [ ] A rough prototype - for users to interact with that communicates the design better to do some usability testing

**Comment by secretrobotron** [comment]
Super cool. :+1:

**Comment by LauraReynal** [comment]
:+1:

**Comment by sabrinang** [comment]
There are certain aspects of our directory that are informed by other Mozilla systems, it would be a good idea to run ideas or ask technical questions with them that will inform our MLN design. 

Who do we ask and when would be an appropriate time (part of research or after?) to connect with:
- someone from Mozilla Reps about reporter (or get an account with access to reps portal)?
- someone from Mozillians.org about vouching system and directory insight?

@hannahkane @LauraReynal - any suggestions on how to set this up?

**Comment by LauraReynal** [comment]
I was wondering the same thing regarding Mozillians.org 
did you already sketch out how they would complement / differ from each others?

We might ask the volunteers/mozillians about their use of the site www.mozillians.org

**Comment by hannahkane** [comment]
Closing. Will re-open with more clarity in H2 2016.
