### ISSUE TITLE
Design for Web Lit Map v2.0

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1268]
@anmechung to provide details when she has them :)

**Comment by sabrinang** [comment]
connect with an-me about this with design brief

**Comment by sabrinang** [comment]
We had a design kick off today and worked on the design brief here: https://docs.google.com/document/d/1yFjUU_vEppNBA8JlG5weYa-P3Rpp1v78sthXhHq7DNw/edit?ts=5609890b

#### Some next steps to note are:

**Research** 
- investigate previous research, user stories and personas (An-Me’s focus group research, previous quiz work & Laura’s field research)

**Connect** 
- discuss and sync up with Credential work and Curriculum work to understand how this work ties into theirs and into the larger MLN system

**Plan** 
- find out where this belongs in the MLN site navigation and IA

**Ideate** 
- explore ideas around needs before they get to the Web Lit Map like an onboarding phase to supplement the Web Lit Map (user assessment options, quiz, survey, vocabulary list etc.) 
- explore ideas of pathways and relevant modes that the Web Lit Map can be adapt visually to
- explore visual ideas and relationships of the skills on the map (*skills to be finalized*)
- continue exploration of previous concepts: https://www.dropbox.com/s/kzl0xa0rj3yoe1c/webliteracymap_sngconcepts.pdf

**Continue Research and Feedback**
- design an activity (i.e. mapping, sketching, card sorting session etc.) for MozFest that encourages user participation to create a version of the map and collect feedback to inform our design
- share out some initial ideas for feedback

**Comment by hannahkane** [comment]
awesome summary, @sabrinang. Should we file a separate ticket for the MozFest activity?

**Comment by sabrinang** [comment]
MozFest activity has been filed as a separate ticket #1305 
Also, replied an e-mail asking Sarah and An-me if we also need to file it in the mozfest-program repo in the MLN space [milestone]  (https://github.com/mozilla/mozfest-program/milestones/Mozilla%20Learning%20Networks) when we haven't finalized the activity yet. I will update when I hear back.

**Comment by sabrinang** [comment]
@anmechung - do you have the link to the quiz/survey placement research of users determining where their skills that you mentioned about during our design brief? it will help give me some insight on thinking about the assessment part that may accompany this map

**Comment by anmechung** [comment]
@sabrinang - searching for it as links to it are in old  openbadges etherpads that are no more! Will keep looking and keep you posted.

**Comment by hannahkane** [comment]
Would like to take this out of any heartbeat, since the current actionable deliverable is the Mozfest work described in #1305. Make sense to you, @sabrinang ?

**Comment by sabrinang** [comment]
@hannahkane - Yeah, I'm currently doing the research step of this ticket that is related to mozfest session as well. I can split this ticket to all the next step phases mentioned above so this can be out of any heartbeat.

**Comment by sabrinang** [comment]
Next phase is to create wireframes with new web lit map visual ideas

**Comment by hannahkane** [comment]
Closing this ticket because it has a lot of history. Will re-open a more concise ticket.
