### ISSUE TITLE
Mozilla Learning Network - Profile (and Log-in) Design

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1272]
### Context

For the upcoming MLN directory (#1267), we will be designing user profiles and they may be related to existing or not-yet-existing profiles using the WebmakerID log-in system. We also want to align across the Mozilla Learning products, consider their possible needs that will inform the MLN profile design to create a unified user experience.
__________________________
### Things to Consider
Currently, there are some issues to note from our site and also considering the tools to see where profiles could be involved:

**Mozilla Learning Network Site**
- the webmaker logo is show by the log-in 
  - does this confuse users to think they are logging into Webmaker? 
  - if they are unfamiliar with Webmaker, do they think it is our log-in system?
- the log-in UX takes you away from our site to a Webmaker branded page
![p_2](https://cloud.githubusercontent.com/assets/2492510/9948067/b15f3fbc-5d54-11e5-888d-b693001e98df.png)

**Discourse**
- has its own unique profile
- the UX is completely separate from the MLN site where you can log-in with Persona or WebmakerID system
![p_1](https://cloud.githubusercontent.com/assets/2492510/9948070/b8dd5f4e-5d54-11e5-819b-4b363f7331ae.png)

**Webmaker**
- doesn’t have a desktop experience for profile or login?
- has a profile on the app
![p_4](https://cloud.githubusercontent.com/assets/2492510/9948073/be5e2a3e-5d54-11e5-981d-dd5e19498dbf.png)

**Thimble**
- does not have a profile
- the log-in UX also takes you away from our site to a webmaker branded page
![p_3](https://cloud.githubusercontent.com/assets/2492510/9948075/c153096c-5d54-11e5-83a7-cbf5f2a5ecaf.png)

__________________________
### Log-in Things to Discuss:
- does it make sense to use the Webmaker brand for log-in?
- how do users figure out the log-in relationship between MLN and webmaker?

### Profile Things to Discuss:
- will Persona go away? why does discourse have the option of Persona?
- does discourse need its own unique profile?
- what does Webmaker and Thimble plan to incorporate in their profiles?
- if you are logged into one product are you present elsewhere? or if you make changes in one how does it effect the others?
- if the profiles share the same information, how do they appear across products?

**Comment by sabrinang** [comment]
/cc @hannahkane @kristinashu @mmmavis 
overview of some of the UX questions when we talked about profiles today

**Comment by sabrinang** [comment]
/cc @LauraReynal @secretrobotron 
research related questions to log-in

**Comment by hannahkane** [comment]
@sabrinang - this is a great list. /cc @xmatthewx @simonwex @flukeout because I think this is essentially the agenda for the meeting I scheduled for next week.

**Comment by sabrinang** [comment]
note: consider if issue #1265 informs profile design

**Comment by sabrinang** [comment]
questions and considerations from https://github.com/mozilla/teach.mozilla.org/issues/1180#issuecomment-139681803 about how it is connected to other mozilla profile properties a user might have and what the profile relationships could be (e.g. prerequisites, linking etc.)

profiles to note:
- Mozilla Reps (e.g. https://reps.mozilla.org/u/hlee/)
- Mozillians (e.g. https://mozillians.org/en-US/u/mitchell/)
- Mozilla Developer Network (e.g. https://developer.mozilla.org/en-US/profiles/Blend4Web)
- Hive Directory (e.g. https://directory.hivelearningnetworks.org/users/omnignorant/)

**Comment by hannahkane** [comment]
I'm closing this ticket, even though it contains some really great thinking. Will reopen when we have a project that pushes the profile forward. The Badges work requires a kind of profile stub, so we'll be building that out, but, otherwise, add'l profile content has yet to be prioritized.
