### ISSUE TITLE
Run new homepage CTA test - embed pledge form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1273]
Design: https://redpen.io/p/cm2c1c9eb67aa9430e

Instructions from @adamlofting:

So I'd recommended committing that winning variation to the repo, pushing it to production, and stopping the current test. Then treat that as your new control to test as many of these further variants as you like / have capacity to build.

CTA01 and CTA02 are quite similar though, so you could test one of them against the current winner. And if it wins, then test the variation as a smaller tweak-style test.

**Comment by mmmavis** [comment]
Regarding committing the winning variation(auto open Pledge modal) to the repo...

As we have received [some feedback](https://github.com/mozilla/teach.mozilla.org/issues/1245#issuecomment-141461862) about the pledge modal showing up too often. I wonder if we should  reduce the frequency from auto pops up that modal once per session to something like once per week?  I feel our current approach would get many of the first-time visitors to pledge but would annoy frequent visitor a lot. :eyes:

**Comment by mmmavis** [comment]
decision: let's do auto popup once "forever" (or until the users clear their browser cookie)

**Comment by mmmavis** [comment]
Let's run a new A/B testing with the current winning variation(will soon be permanent, default on the site) & variation 3, 4 on https://redpen.io/p/cm2c1c9eb67aa9430e

**Comment by mmmavis** [comment]
@kristinashu can you attach the icon file and provide colour code for the background here? Thanks!

**Comment by kristinashu** [comment]
@mmmavis colour is #00af84 and svg is here https://drive.google.com/open?id=0B2irLVDJivhLd2tibHZCVnU5dkU
Let me know if you need anything else.

**Comment by mmmavis** [comment]
hey @kristinashu can you link me to the pattern file as well? the one in your mockup (cta 3, 4) looks brighter than the one we are currently have on the site :grin:

**Comment by kristinashu** [comment]
@mmmavis the pattern is just white with 8% opacity. Does that help? Or do you need a png or svg of the pattern?

**Comment by kristinashu** [comment]
@mmmavis PNGs are attached. 

![teach-pattern-8 white- 2x](https://cloud.githubusercontent.com/assets/1068783/10108334/2b96a3da-6375-11e5-9b32-dd4f6822e759.png)
![teach-pattern-8 white](https://cloud.githubusercontent.com/assets/1068783/10108335/2b98f00e-6375-11e5-8df5-f0fc3a7cf708.png)

**Comment by mmmavis** [comment]
For these 2 embedded form variations, do we also want to auto present the pledge modal for users who are visiting the site for the first time?

**Comment by hannahkane** [comment]
I would also vote no

**Comment by mmmavis** [comment]
@kristinashu if you have it, can you provide the sketch file or .ai file? I used the existing sizing rules but the end result doesn't look quite like what you have on your mockup :no_mouth: 

<img width="1090" alt="screen shot 2015-09-28 at 3 34 38 pm" src="https://cloud.githubusercontent.com/assets/2896608/10150780/77ec7240-65f6-11e5-8662-8feeea36c5d0.png">

**Comment by kristinashu** [comment]
@mmmavis it looks pretty close! Here's the ai file https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLVDg4U2UxM3oxc1k/view?usp=sharing

**Comment by mmmavis** [comment]
Ok I just started a new A/B testing called "Teach Site Embedded Pledge Forms" on Optimizely.

@adamlofting I'm using redirect tests this time since I built the 2 variations as separate pages. (`/home3` and `/home4`). 

![screen shot 2015-09-30 at 2 05 15 pm](https://cloud.githubusercontent.com/assets/2896608/10206550/52d3648c-677c-11e5-891f-1a5c5bd232aa.png)

hopefully I've done this right :grin:

**Comment by adamlofting** [comment]
> hopefully I've done this right :grin:

That's perfect :+1:
