### ISSUE TITLE
Design homepage variation: less intrusive sliding pledge

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1274]
One more idea, a slightly less intrusive pop-up we could try is when it slides up from the bottom of the browser window and doesn't completely cover the page. We could also time it so it comes up a few seconds after the user has been on the page.

**Comment by hannahkane** [comment]
Calling this a P2, because it's not more important than the badges work. Could definitely wait until the next heartbeat.

cc @kristinashu

**Comment by mmmavis** [comment]
Users can still click on the Pledge CTA button to bring up the modal.  Just wondering if we are changing the fade-in effect to slide-up too.

**Comment by kristinashu** [comment]
I think we could keep the same existing modal if the user clicks on the Pledge CTA.

**Comment by kristinashu** [comment]
@hannahkane I've added the mockup to redpen https://redpen.io/p/cm2c1c9eb67aa9430e

**Comment by hannahkane** [comment]
Nice! Should it disappear automatically after a few seconds, or does it require the user to dismiss it?

**Comment by kristinashu** [comment]
Would be nice if it slid up once the user has been on the page for about 4 seconds and then stays up until they use it, close it or click somewhere else on the page. 

This makes me think of another test option where we use the existing pop up but instead of it popping up as soon as the user lands on the page, maybe it could pop up after a few second.

**Comment by hannahkane** [comment]
@kristinashu - your plan (4 seconds, then load; requires dismissal or clicking elsewhere) sounds good. I'll file an implementation ticket, and I think we can close this one.

At this point we have 5 variations, which is awesome. Let's see how they do and then decide if we need more. Right now, the winning variation has an 8% conversion rate. If we can get to 10%, I think that would be great.

**Comment by kristinashu** [comment]
Sounds good! Thanks @hannahkane
