### ISSUE TITLE
Build "Fringe events" submission and approval process

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1280]
Site visitors will be able to submit events for inclusion on the Fringe Events page. We need a process for easily allowing @marcwalsh to see the submitted events, approve or deny them, and have the approved events appear on the public page.

Design ticket: https://github.com/mozilla/2015.mozillafestival.org/issues/194

**Comment by hannahkane** [comment]
Just discussed with @mmmavis - we can use a column in the google spreadsheet for "Approved - y/n", and use that to dynamically render the approved content on the page.

**Comment by hannahkane** [comment]
No longer blocked

**Comment by hannahkane** [comment]
@mmmavis - can we close this one? Page looks good!

**Comment by mmmavis** [comment]
yup yup! :tada:
