### ISSUE TITLE
Make a wireframe deck for the research 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/teach.mozilla.org#1284]
@sabrinang @kristinashu @mmmavis cc @secretrobotron 

Let's collaborate on this collection of wireframes to test. 
https://drive.google.com/open?id=19haCbs4KAQnmpItgg-VPwa-ehvrgX139Ycw2h88BiIs

**Comment by sabrinang** [comment]
@LauraReynal I'm working on the deck and wondering if you have a refined set of questions for research? it will help inform how I can help structure the deck for you that matches your questions and help you find appropriate benchmarks to fit your questions.

So far some topics on the slides are:
- navigation & content
- community
- leadership development
- curriculum
- web literacy map

I know we should keep the slide short and focused for the interviews so let me know if you have a preferred format.

**Comment by LauraReynal** [comment]
Hey @sabrinang I have started to refine and adapt the deck today. For now it's good. 
I have one question though: Can you help us cutting the directory wireframes into multiple parts so that they would fit the slides? 

I think we dont need to add much in the deck right now, let me do a few first rounds and I will ping you if we need changes :smile_cat:

**Comment by sabrinang** [comment]
@LauraReynal I updated slides 18-21 with desktop versions (with corresponding mobile view beside it). Let me know if you need any changes.
