### ISSUE TITLE
Update "Curriculum Queue" github page with new content 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1285]
- [ ] The content on this page: http://chadsansing.github.io/curriculum-testing/curriculum-queue/ needs to replace the content on this page: http://mozilla.github.io/webmaker-curriculum/index.html
- [ ] Figure out from where we point to this on the teach site
- [ ] Design improvements

And @chadsansing has asked for some design help on the layout.

**Comment by cassiemc** [comment]
@hannahkane @kristinashu What are the 'design improvements' in this list? Is that in addition to helping @chadsansing with layout? Curious about scope and how you're measuring design success in this ticket.

**Comment by chadsansing** [comment]
For my part, I just want more equal column widths at present -

**Comment by hannahkane** [comment]
I think we could also make it match the styles of the Teach site

**Comment by emmairwin** [comment]
I'm sorry this task isn't super clear, how it relates to the teach.mozilla.org site ? Can you help us understand for our codeathon tomorrow? Otherwise will have to pass over.

**Comment by chadsansing** [comment]
The map outlines the plan/pipeline of upcoming curricular content; the Web Literacy modules on the top half of the map will eventually make their way to /activities. I think how and where to connect the map to teach dot are topics for discussion, Thoughts, @ldecoursy?

**Comment by ldecoursy** [comment]
Perhaps on the /activities page, there is a link to see what curricular content is coming soon? Could be good for folks to see what's in the pipeline, and/or then post in Discourse if they're not seeing something in the queue but would like to...

**Comment by hannahkane** [comment]
Closing this ticket and opening new ones, divided along functional areas (e.g. dev / design)
