### ISSUE TITLE
Mobile comps for badge pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1287]
Create mobile versions for the desktop comps in #1257

**Comment by hannahkane** [comment]
Blocked on copy #1291

**Comment by hannahkane** [comment]
No longer blocked. Copy is here: https://etherpad.mozilla.org/21CSkillsbadgesdesign

**Comment by kristinashu** [comment]
Here are the two main screens (landing page and apply page) on mobile: https://invis.io/XD4HYLKPM

To avoid a really long landing page I'm suggesting we put the badges into a slider on mobile.

**Comment by hannahkane** [comment]
Love the slider.

**Comment by anmechung** [comment]
+1

**Comment by kristinashu** [comment]
@cassiemc can you please take a look at these and let me know if you have any feedback?

**Comment by cassiemc** [comment]
Looks great @kristinashu, R+
