### ISSUE TITLE
Create "Back to School" activity kit page and link to from /activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1290]
Content is here: https://docs.google.com/document/d/1Wj6xouojulb7r2PmHOVQAPdBYs84xxeLc0kYdtRNiKE/edit#heading=h.hk7mc464doef

**Comment by mmmavis** [comment]
any pref on the URL? `/activities/back-to-school/` or `/activities/back-to-school-kit/`? Also wondering where should this module go on the list on /activities :grin:

**Comment by hannahkane** [comment]
url:  teach.mozilla.org/activities/back-to-school-write-the-web
@chadsansing - can you please add where you'd like this module to go on the /activities page, along with the Level and Developed by information?

**Comment by mmmavis** [comment]
> url:  teach.mozilla.org/activities/back-to-school-write-the-web
oops, sorry, should've read that google doc first :wink:

**Comment by chadsansing** [comment]
Let's say, "Developed by Mozilla."

Level: 13+<br>Beginner.

Let's put it 3rd, underneath Protect Your Data - sound right, @ldecoursy?

Thanks, @hannahkane!

**Comment by PaulaPaul** [comment]
Hello all!  I'm excited to work with Mozilla as a mentor on Open Source Day at GHC15 and have been familiarizing myself with this repo and issues tagged with Grace Hopper.  I requested access to the Google Doc for this issue and just wanted to introduce myself.  I've forked the repo and have been making some simple changes in my own branch to understand the structure (good stuff!) so that I can help the attendees.

**Comment by chadsansing** [comment]
@PaulaPaul, there's not much there there, so to speak, beyond meta information to help us build out a landing page for the kit. Are there any particular questions I or we can help you with?

**Comment by PaulaPaul** [comment]
Thanks @chadsansing - this will be my first GHC and first Open Source Day so I just wanted to be prepared. I enjoy teaching and content creation as well as coding and would like to help with projects going forward. I've been coding for a long time but just beginning to navigate these waters; if you have any pointers for me or additional tasks I can help with, please let me know-

**Comment by chadsansing** [comment]
Very glad to have you participating here with us, @PaulaPaul! Right now our most active spot for developing and testing new curriculum is over on [Discourse] (https://discourse.webmaker.org/), our community forum. You can find Curriculum threads there, as well as Club and Event threads.

**Comment by hannahkane** [comment]
Hi @PaulaPaul! Great to have you here. We're looking forward to having you and others help us build out these pages. To help orient you - I serve as a project manager for our dev and design work, @chadsansing manages our curriculum development work (which this ticket relates to), and @mmmavis is our front-end developer. You can see what other curriculum pages look like here: https://teach.mozilla.org/activities (click on, for example, the Web Lit Basics kit).

**Comment by emmairwin** [comment]
@chadsansing @hannahkane  -   @PaulaPaul is one of our fantastic mentors coming to help run a session with tasks tagged for Grace Hopper. You can see more introductions [here](https://discourse.mozilla-community.org/t/grace-hopper-open-source-day-introductions/4594/7) - we're excited for tomorrow.  

One question on this re:

Level: 13+
Beginner.

Let's put it 3rd, underneath Protect Your Data - sound right, @ldecoursy?


Can you tell me how to locate this? I don't see Protect your Data, but I think I might have the menu levels confused.    Thanks!

**Comment by hannahkane** [comment]
Thanks, @emmairwin. That's referring to the [activities page](https://teach.mozilla.org/activities) where this activity page will be linked from. The first module is called Web Literacy Basics, the second is called Protect Your Data. We're suggesting that this teaching kit will be the third one on the page.

**Comment by HelenHChen** [comment]
Hi @hannahkane! I was able to address this issue last week at Grace Hopper. I made a pull request but am not sure what else I need to do to get the proposed updates merged into the master? I'm new to this so thank you in advance for your help and patience :)

**Comment by hannahkane** [comment]
Thanks, @HelenHChen! Awesome. @mmmavis or @Pomax - are either of you available to review Helen's PR?

**Comment by Pomax** [comment]
totally landed.
