### ISSUE TITLE
Finalize copy for badges

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1291]
See comps here: https://redpen.io/p/tq1fbf0a41edd3909f

**Comment by hannahkane** [comment]
@KevZawacki - the copy doesn't exist on an etherpad. Let me know if it would be useful to create a pad - I can do that.

**Comment by KevZawacki** [comment]
@hannahkane If that's possible, thanks!

**Comment by anmechung** [comment]
@KevZawacki @hannahkane - I started an etherpad  with copy for content of badges:  https://etherpad.mozilla.org/21CSkillsbadgesdesign

**Comment by hannahkane** [comment]
@KevZawacki  - I added the site copy needed to An-Me's pad, including the placeholder copy that's on the redpen.

**Comment by KevZawacki** [comment]
@hannahkane Thanks for dropping it in an etherpad! I've just added my edits. Looks like there are still some gaps in the website copy. Is that something I can help with at all?

**Comment by hannahkane** [comment]
Thanks, @KevZawacki - what gaps are you talking about? Would love your help with whatever you think is missing. 

There are a couple places in the pad where I wrote "[insert brief paragraph]" - would love your help with those.

**Comment by hannahkane** [comment]
cc @kristinashu so you can follow along! :)

**Comment by KevZawacki** [comment]
Hi @hannahkane, by gaps I meant "[insert brief paragraph]."

I've just dropped suggestions into the pad -- let me know what you think.

**Comment by hannahkane** [comment]
@KevZawacki - fantastic. This looks great! Thanks so much. Closing.

**Comment by anmechung** [comment]
Transferred copy to Etherpad Lite  https://public.etherpad-mozilla.org/p/21CSkillsbadgesdesign

**Comment by hannahkane** [comment]
Thanks, @anmechung! #etherpocalypse
