### ISSUE TITLE
determine the new homepage for x-ray goggles

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1294]
The goggles used to live on the now defunct webmaker.org, so a new homepage needs to be made. This can be on teach, or it can be on the domain that goggles will be moving to.

**Comment by Pomax** [comment]
After discussion we decided to put this on the new domain with the tool itself.

**Comment by hannahkane** [comment]
@Pomax - can we close this ticket? Seems like it was just about deciding something.

**Comment by Pomax** [comment]
yup
