### ISSUE TITLE
redesign the landing page and install page for Goggles

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1298]
current landing page: https://webmaker.org/en-US/goggles
current install page:https://webmaker.org/en-US/goggles/install

Let's figure out how much we want to keep this, or redesign it, or just ditch these and design a new one or two pages from scratch.

**Comment by hannahkane** [comment]
Things to keep in mind:
 * Some sort of thematic connection to Thimble AND Teach
 * Focus on usability, removing barriers to entry
 * Can add some teaching content (like the Thimble homepage) - maybe @chadsansing can recommend three Goggles-specific modules we'd want to highlight

**Comment by chadsansing** [comment]
@hannahkane: [Hack the News] (http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html), [Hacking My Media] (https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles) (needs remix/clean-up; can do next week), and [Hack Great Science for Girls] (http://www.lessonpaths.com/learn/i/diving-in/hack-great-science-for-girls-with-the-xray-goggles), perhaps?

I can also work on more focused activities soon - next week or in the two weeks following that, I think. There isn't a gallery, per se, or kit dedicated just to the Goggles, so activities are not easily discoverable.

Students and I found it easiest to navigate when we could install the Goggles from the landing page. One page to rule them all, and all that.

**Comment by sabrinang** [comment]
We discussed about the homepage and here is an initial sketch to capture some ideas that will be on the x-ray goggles page. cc/ @kristinashu 
![dsc02311](https://cloud.githubusercontent.com/assets/2492510/10208549/ea376fce-6788-11e5-8c12-719c8ec6ae0b.png)
The previous elements from both the [current landing page] (https://webmaker.org/en-US/goggles) and [install page] (https://webmaker.org/en-US/goggles/install) can be integrated on this home page to include:
- install button
- welcome/tutorial video
- instruction steps ("Remix this page")
- teaching content and activities to get started

Things to note:
- do we need a log-in/sign-up here for x-ray?
- we will need to update that video (interface will be outdated)
- we may need to adjust instructions copy
- colours for this page is TBD we will determine how this fits our larger brand and theme

@flukeout - Looping you into the x-ray homepage as it will resemble the Thimble homepage a lot so let us know if there are additional things to consider

**Comment by chadsansing** [comment]
Dig this immensely.

**Comment by hannahkane** [comment]
What @chadsansing said.

Wondering if we need both a video and the 3-step instructions. Don't want to push the activities too far down on the page.

**Comment by jgmac1106** [comment]
Even with the redesigned page the x-ray goggle page always caused confusion
when I introduced it. It was mainly the remix this page and the
installation features being on the same page. In the middle of a tutorial
have the audience gets stuck trying to remix the page and the other half
get stuck on installing.

Most users do not know what "drag to bookmark bar means" but the video is
super helpful.  I'd rather be brief then list a bunch of direction but  I
would  think about including a link to a tutorial page that could be like
the old hackasuarus cheat sheet card.

The ideas for the activities are awesome! Users reported a need for
credibility lessons and these are perfectly packaged to help build a
skeptical stance in a production centered way.

**Comment by jgmac1106** [comment]
Ohh the cheat sheet exists:
https://mozteach.makes.org/thimble/xray-goggles-cheatsheet May want to
remix this to include the installation instructions as well.

**Comment by Pomax** [comment]
Yeah, the bookmarklet aspect is not ideal, but probably the only realistic way for use to offer the Goggles at least in the short term.

**Comment by jgmac1106** [comment]
I think back to all the annotation tools I use. They use three to four options including a bookmarklet (while also saying not ideal). 

Look at hypothes.is or genius.com/beta. They offer:
- Bookmarklet 
- Chrome extension (have trouble getting Firefox extensions approved I think). 
- input field to paste in url
- Genius Beta allows you to type genius.com/ in front of any url to activate. 

I don't mind the bookmarklet. I just never found the perfect install instructions.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. Your input, as always, is super useful. We can file a separate ticket for other installation / use options, like you suggested. I want to keep the scope of this re-launch as narrow as possible, though.

**Comment by jgmac1106** [comment]
Yeah I hate derailing the conversation, but  long story long I was trying
to agree with you that I think a few short bullet points (on installation)
even if the content gets pushed down is important.

**Comment by sabrinang** [comment]
Figuring out the copy will definitely assist the UX for understanding the installation process.

![xray-homepage-wireframe3](https://cloud.githubusercontent.com/assets/2492510/10237971/fdb2746e-686d-11e5-9d24-843ccca0e485.png)

If the user needs to drag to install then the button can be accompanied with the *drag to button* text below the button? If the user can install by just clicking (I don't think x-ray works this way though) then the text below may not be needed?

We can figure out some small icon/illustrations for the steps when we finalize the copy - I'm thinking the steps could be something along the lines of (1) Install (2) Activate (3) Remix instructions (unlike the previous landing page which served like an activate preview/mini tutorial which this wouldn't be the best place for).

@hannahkane Can we get some help with the copy? I'm unsure who to assign for that

**Comment by flukeout** [comment]
@sabrinang Good stuff here! One thing to consider here (and along with the larger branding work) is that the Thimble header is missing Terms of Service & Privacy Policy links.

**Comment by hannahkane** [comment]
Hey @sabrinang - great progress. Can you put this in a redpen? We can put copy there.

**Comment by sabrinang** [comment]
Thanks for noting that @flukeout! Over this week, @lovegushwa @kristinashu and I were looking into updating footers across Mozilla Learning Network as part of our brand alignment in our web properties so X-Ray (eventually Thimble too) will soon have unified content in the footers. We also thinking of the single colour (white + alpha channel) version of the logo and perhaps simplifying it so it would scale better too.

@hannahkane - Placed on redpen here: https://redpen.io/p/yof0cc29fb845f14d1

**Comment by Pomax** [comment]
Loving this so far!

**Comment by cassiemc** [comment]
@hannahkane @sabrinang Would a design brief help clarify the scope here? Might be we just need to update the title of this issue to not include a question mark :)

**Comment by hannahkane** [comment]
just removed the question mark, because it seems we've decided to re-design. I'll let @sabrinang answer whether a design brief would be helpful. At this point, I feel like the design is very close to being complete, and the outstanding issues are largely around usability (i.e. helping ppl understand how to install and use Goggles)

**Comment by cassiemc** [comment]
@hannahkane wfm.

**Comment by kristinashu** [comment]
I don't think we need a design brief.

@Pomax @sabrinang @flukeout @natalieworth and I are meeting tomorrow to go over the user flow and brainstorm the simplest way to provide instructions to users. 

After that, the design should be pretty straight forward.

**Comment by kristinashu** [comment]
Notes from our jam session.

We're suggesting two separate pages:
1) A landing page (similar to https://webmaker.org/en-US/goggles/install) focused on installing goggles
2) Then a FTU page for users who have just installed goggles. This page would have a walk through for first time users and a simple activity - sort of similar to https://webmaker.org/en-US/goggles 
Design for FTU page is in a separate ticket https://github.com/mozilla/teach.mozilla.org/issues/1310

Landing Page Content:
*  intro to goggles
*  installation instructions 
  * make sure your bookmark bar is in view and then drag this button to your bookmark bar
  * show gif of the steps instead of a video
*  link to FTU page
*  Activities

![img_6724](https://cloud.githubusercontent.com/assets/1068783/10325692/807537e6-6c48-11e5-992e-9aab65e9b2f6.JPG)

**Comment by jgmac1106** [comment]
+1000 for two pages

**Comment by kristinashu** [comment]
@jgmac1106 Thanks! Your input is always helpful.

**Comment by kristinashu** [comment]
Here's how the install page is coming along: https://redpen.io/p/wjdd96d46ae8c63dc3

I shared v1 during our design critique and want to note a couple of @xmatthewx comments:
* responsive small screen version of this should probably include a message that this is intended for desktop
* we should get input from community members (he's going to put me in touch with a few)

**Comment by hannahkane** [comment]
Looks great! +1 to @xmatthewx's suggestions.

**Comment by kristinashu** [comment]
Thanks for the copy feedback everyone. I'm updating the comp now.

@hannahkane do you know what legal or privacy pages we need to link to? I'm just adding links to the footer now.

**Comment by hannahkane** [comment]
Don't let @flukeout off the hook for doing this on Thimble. :)

TOS is here: https://beta.webmaker.org/#/legal

Privacy policy here: https://www.mozilla.org/en-US/privacy/websites/

**Comment by kristinashu** [comment]
Haha, thanks for the links. 

Comp has been updated https://redpen.io/p/wjdd96d46ae8c63dc3

**Comment by hannahkane** [comment]
woo!
