### ISSUE TITLE
Build Mozfest "Spaces" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1301]
@mmmavis - this should actually be the top priority for today and tomorrow, per a request from the MozFest team, so I'm changing your other tickets to p2 :)

https://github.com/mozilla/2015.mozillafestival.org/issues/176

**Comment by mmmavis** [comment]
closing this ticket since /sessions page is now live
we'll need to add icons to that page once they have been finalized - new ticket filed [here](https://github.com/mozilla/teach.mozilla.org/issues/1308)
