### ISSUE TITLE
Switch to use the new Tabzilla

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1302]
new Tabzilla can be found on https://github.com/mozilla/tabzilla

Would probably need some design discussion on wordmark colour.

**Comment by hannahkane** [comment]
Is this now duped by #1504?

**Comment by cassiemc** [comment]
@hannahkane I heard wind, via @edrushka I believe, that tabzilla was getting phased out. Not sure how to find out for sure, but you might want to "won't fix" this one.

**Comment by hannahkane** [comment]
I'm going to close this since we just did #1504. If/when Tabzilla goes away, we can file a new ticket to remove.
