### ISSUE TITLE
Reorganize Information Architecture for MLN Site

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1303]
## Context
As our MLN Site is growing and developing, we need to consider how the content is understood together as a whole, how we can support new content as it scales and how we can organize content to be located easily by users. 

#### Redesign Navigation #1259

The current navigation area will be influenced by this IA and will be reflected on the nav menu itself. 

We plan to reduce the number of menu items, reassess content grouping for sub pages and provide navigation labels that are more approachable (less internal-langauge & jargon).

#### Redesign Footer #1258 - DONE

The current footer doesn’t align with any of our other Mozilla properties and since Hive is integrated in our network the relationship can be described in the Initiatives Page (see idea below). 

The plan is for the footer to include your typical footer links (privacy, legal, trademark, donate) and include a contact section to connect with us (social, email, discourse). This footer will resolve discourse being the only navigation link that direct users off the site.

#### Introducing an Initiatives Page (*or Programs? the name TBD*)  #1311 - DESIGN COMPLETE

This page will give context and an overview of all the programs and offerings the Mozilla Learning Network has to offer. This includes: Maker Party, Clubs, Hives, Fellowships and MozFest.

This would reduce the number of top level navigation items, provide information on the relationship to MLN and provides a home for future initiatives to go.  

#### An informative homepage (serves as About page) #1312 

This page would be great to introduce users to the Mozilla Learning mission, our universal web literacy approach with our map and Teach like Mozilla values here. If this content is placed here then we do not need to list *About* as a footer item (where it is currently found) and reduces the “teach like mozilla” as a dedicated nav item too.

#### Things in Development:

Credentials, Web Lit Map, Curriculum, Pro. dev. guides content is still in progress and this area may be the least clear in our IA. We are considering various methods to group and organize this content and will develop along with our discussions. Also, we should clarify if Teach like Mozilla and Pro. Dev. are dedicated sections of content or content themes throughout the site. 

Working with @kristinashu on this work for the site.

**Comment by sabrinang** [comment]
![ia-sketch](https://cloud.githubusercontent.com/assets/2492510/10259706/2fc14a36-6920-11e5-9817-416de60a8283.png)
capturing an initial sketch of our ideas to sort out the IA

**Comment by kristinashu** [comment]
Here's a digitized version of this IA with a few different options: https://redpen.io/p/gn6cdd01372d249148

**Comment by kristinashu** [comment]
@hannahkane any chance we could see analytics for the current site? It might guide us in determining which sections are important to surface.

**Comment by hannahkane** [comment]
@adamlofting - can we get analytics accounts for Kristina and Sabrina?

just sent a calendar invite to discuss the IA. Thanks!

**Comment by hannahkane** [comment]
I think we can close this ticket. The work is either complete, or captured in other tickets.
