### ISSUE TITLE
Pledge to Teach email input placeholder text is hard to read

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1304]
On https://teach.mozilla.org/home3/ in Chrome, the pledge to teach input has very hard to read placeholder text...

![image](https://cloud.githubusercontent.com/assets/25212/10288050/6fd56e90-6b4b-11e5-9fe2-8fd8f36b0ef8.png)

Some options for styling it are listed here...
http://stackoverflow.com/questions/2610497/change-an-inputs-html5-placeholder-color-with-css

**Comment by hannahkane** [comment]
We'll be removing the pledge to teach in 2016, so closing this.
