### ISSUE TITLE
Create a Web Lit Map 2.0 participatory design activity for MozFest

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1305]
We will be working with @anmechung to design an activity *(i.e. mapping, sketching, card sorting session etc.)* for MozFest that encourages user participation to create a version of the map and collect feedback to inform our design.

Also, we can use this time to share out initial Web Lit Map ideas and get user feedback on them.

**Ideas for Goals and Outcomes**
- to understand what can help get people started with the map *(approachable, relatable, understandable etc.)*
- to gain insight on how they imagine the map and how they understand it *(reorganize, revise, reimagine etc.)*
- to understand how users make the map relevant to themselves and relevant to an audience *(pathways, personas, outline)* 
- to inform decisions on the web lit map structure and skills *(i.e relationship between web literacy + 21c skills)*

____________________________

*NOTE:* The content for the Web Lit Map itself is still flexible and subject to change so this activity is part of the user centered design process. 

This is part of the Web Lit Map 2.0 redesign: https://github.com/mozilla/teach.mozilla.org/issues/1268
Design brief here: https://docs.google.com/document/d/1yFjUU_vEppNBA8JlG5weYa-P3Rpp1v78sthXhHq7DNw/edit?ts=5609890b

**Comment by hannahkane** [comment]
@sabrinang - okay to move to next heartbeat?

**Comment by sabrinang** [comment]
From our chat with @anmechung today, we have more ideas for the activity at MozFest:

**Persona and Reflection Tool**
- set up link so people can submit their own persona (TBD - google form perhaps?) and this format will be established in #1344 and users can give feedback on this format and the reflection tool idea too 

**Web Lit Map**
- set up a wall space where people are encouraged to add to the map with the constraints of Web Lit Categories *(Read, Write, Participate)* and 21c Skill Categories *(Problem Solving, Collaboration, Creativity, Communication)*
- set up a method to collect feedback on the web lit map (analog and in-person? online google form?)

We can also think of prompts and questions around the map to help guide how they can contribute and participate with the wall space.

**Comment by sabrinang** [comment]
Ideas for activity wall
![mozilla-learning-network_activity-idea](https://cloud.githubusercontent.com/assets/2492510/10555874/28e31e2c-742b-11e5-9129-32c0a47a6421.png)

The section to the left *(reflection, persona and pathways)* will tie into the format from issue #1344 and this section will be for collecting various personas and what people think of pathways.

The section in the middle *(map)* will be for encouraging people to comment on what they think of the content of the map itself and submit or comment on blue sky ideas (I'll be coming up with some blue sky ideas soon #1268).

The section on the right *(how would you use the map?)* is to collect feedback on the applicability and use cases of the map.

We can think about collecting this feedback in an analog manner (i.e post-its) or include a short link on the wall for people to go to or have a station with a laptop depending on what we want to collect.


@anmechung I would love your feedback on some of these ideas so far on the redpen here: https://redpen.io/mf72283f5af6a44817

**Comment by sabrinang** [comment]
reference this ticket here to align with: https://github.com/mozilla/mozfest-program/issues/551

**Comment by sabrinang** [comment]
From the discussion earlier today, we want the MozFest activity to include these aspects:

**Reflection Tool:** People can answer reflection questions and give feedback on the format. People can try the reflection tool that will lead them to create a profile.
**Profile:** Create a profile and add it to the wall.
**Map:** Get feedback on skills. People can add, combine or remove skills on the collaborative wall.
**Visualization Ideas:** Encourage people to reimagine the visuals or relationships of the skills to create a version of the map to add to the wall.
**Feedback:** Collect feedback on how they would use the map at our station.
   **Map Name:** Test the name of the map and get users to suggest names that resonate with their community *(perhaps at the feedback station as well)*. 
**Goodies:** Have snacks to lure people to our station! :candy: :lollipop: :chocolate_bar: 

Updated redpen: https://redpen.io/mf72283f5af6a44817

**Comment by sabrinang** [comment]
We can include an online survey version of all the feedback questions we have (if they don’t want to be recorded at the station or something they can do on their own laptop). The questions could be:

* What do you think about the format of the reflection questions or tool? 
 * Did it help you to understand how the map can be relevant?
* What do you think of these skills or the read, write and participate framework? 
 * What do you think they represent?
* Do you think these skills will help develop web literacy? 
 * Why or why not?
* Do you think these skills will help develop leadership development? 
 * Why or why not?
* What name would you give the map that would resonate with your community? 
 * Why?
* Could you use the map to teach or learn about web literacy and leadership development? 
 * If yes, how would you do so? If no, why not?

We could try using a google form or open etherpad if it is useful. Also, do we need to collect any basic tech demographic info about the person submitting their feedback (like in the focus groups)?

**Comment by sabrinang** [comment]
I updated the redpen: https://redpen.io/mf72283f5af6a44817
I'm going to continue to add some visualization ideas up until MozFest for the map section.

@anmechung Let me know what you think of the feedback questions and if we need to make an online survey for that for the feedback station to guide people recording themselves or to fill out if people don't want to be recorded (see comment above).

**Comment by anmechung** [comment]
@sabrinang I added reflection tool and profile mad-lib here.  https://docs.google.com/document/d/1JHaJOp-6H6rbujUfWo9rbNyHI2wuQCGsdceTDU6oLe4/edit
Online survey - great idea!  I included in the google doc and made some edits and added a bonus question.  Can we give people the option of being recorded or writing in a google doc, their response to how they might use the map? Will set up a call for Tuesday to continue working on this and add @IBGMozilla to call

**Comment by sabrinang** [comment]
I updated the redpen with what I have printed and assembled: https://redpen.io/p/wnff7c7716726ed841
![img_20151102_213403-2](https://cloud.githubusercontent.com/assets/2492510/10902334/261a8b92-81b1-11e5-92c0-d602a33f088d.png)

I won't be working at the office tomorrow so I won't be able to make many changes but please comment on the redpen if there are any concerns. The only thing I'm missing is the label "What might a “webby experience” be for you?" question which I'll see if I can drop by the office to complete if time allows (I'll need to pack and get other stuff ready before I leave).

**Comment by jgmac1106** [comment]
+1 on the redesign.

**Comment by wiobyrne** [comment]
Agreed. Best of luck at the launch. 

Please be sure to get a camera on the display over the course of the day...or snapshots during a timelapse to see what people are moving, decisions being made. I'd be interested in what commentary is provided and what questions people have.

**Comment by anmechung** [comment]
Ian,

Great idea!  Sorry you won't be there, but we will take be adding notes to
the etherpad continuously.  The space will be open the whole time, and the
focus group is scheduled for 3:30 pm London time on Saturday.  Sabrina has
done an amazing job designing!

Btw - really liked the video you put together - captures the history and
the future of the map!

Let's do a catch up next week?  Let me know good time for you, and Iris and
I can hop on a call.

Best,

An-Me

On Nov 3, 2015, at 3:54 PM, wiobyrne <notifications@github.com> wrote:

Agreed. Best of luck at the launch.

Please be sure to get a camera on the display over the course of the
day...or snapshots during a timelapse to see what people are moving,
decisions being made. I'd be interested in what commentary is provided and
what questions people have.

—
Reply to this email directly or view it on GitHub
<https://github.com/mozilla/teach.mozilla.org/issues/1305#issuecomment-153501315>
.

**Comment by wiobyrne** [comment]
Sounds good. Wish I was there, but know that you'll all do a great job. Let me know if you want me to monitor/do anything from this side of the pond. I'll stay on the EtherPad to see what people say. Looking forward to the feedback. 

Best of luck. :)

**Comment by jgmac1106** [comment]
Looking for the link to the etherpad @anmechung or @sabrinang do you have it?

cc/@wiobryne

**Comment by anmechung** [comment]
@jgmac1106 here is the link:  https://public.etherpad-mozilla.org/p/Mozfest2015WebLit2.0feedback
