### ISSUE TITLE
Build 404 page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1307]
Design will happen in #1247

**Comment by Pomax** [comment]
@mmmavis giving this to you based on https://github.com/mozilla/teach.mozilla.org/issues/1247#issuecomment-169106812, feel free to reassign if that's no longer the case =)

**Comment by hannahkane** [comment]
@natalieworth - can you please attach files for the animated gif to this ticket? thanks!

**Comment by natalieworth** [comment]
@mmmavis Here's the link to the gif file: 
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0ak9zdVYxcXN4RVU&usp=drive_web&ddrp=1&tid=0B20-0lpP23c0SF9MY2hScUsyaUE
If there are any issues just ping me and I can export it again quickly.

**Comment by natalieworth** [comment]
@mmmavis Gif can be 500px x 370 px on the teach site

**Comment by hannahkane** [comment]
@Pomax - is this one you could do?

**Comment by Pomax** [comment]
I can take that one this week - is the linked gif the speed we want? (I'm someone who's particularly sensitive to movement anywhere in my field of vision, so to my brain that animation is actually too fast, physically affecting me)

**Comment by hannahkane** [comment]
I don't have a strong opinion about that. @natalieworth - do you?

**Comment by mmmavis** [comment]
Taking this from @Pomax . Gonna use the 404 page as the CMS guinea pig. (basically to see if we can update the content on the 404 page from CMS)

**Comment by natalieworth** [comment]
Agree that it moves a bit quick @Pomax , hoping in the future we can update with a bit of a more refined version but unfortunately didn't have time at the the moment when I was originally working on it.The animation of the book flipping was a bit tricky too :)

**Comment by mmmavis** [comment]
implementation work is being done as part of https://github.com/mozilla/teach.mozilla.org/pull/1687

**Comment by mmmavis** [comment]
PR  PR https://github.com/mozilla/teach.mozilla.org/pull/1687 has been merged to `develop`. Thanks all!
