### ISSUE TITLE
X-Ray Goggles Design

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1309]
We will be looking into X-Ray Goggles design and we will be having a design jam on this!
Homepage redesign is in progress here: https://github.com/mozilla/teach.mozilla.org/issues/1298
Log-in experience: https://github.com/mozilla/teach.mozilla.org/issues/1248

Besides these two areas, here is an overview to capture the other design opportunities we can look at for the X-Ray Goggles design.

![mozilla-xray-goggles_design-overview](https://cloud.githubusercontent.com/assets/2492510/10321735/2238b95a-6c2f-11e5-95d4-52b2d2c0e9af.png)

We can look at and consider:
- color (interface, hover states, buttons)
- UI elements (buttons, menu keys)
- typography (captions, menu)
- brand (log-in)
- favicon

/cc @kristinashu @flukeout @natalieworth

**Comment by sabrinang** [comment]
@Pomax I have taken the screenshots from http://the-ecks-rey-giggles.herokuapp.com/ and if you have any other states or screens in X-Ray Goggles to consider please note them! :)

**Comment by hannahkane** [comment]
Closing this, as more work on Goggles design has not been prioritized.
