### ISSUE TITLE
FTU page for goggles

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1310]
Users would come to this page from the landing page once they have installed goggles. Landing page design https://github.com/mozilla/teach.mozilla.org/issues/1298 

Site would have a fun layout for users to remix (like thimble's stay calm poster) with overlays to walk a user through the steps. ie."Click the goggles icon in your bookmark bar to active", "Click on the image background and replace it by..."

Sort of similar to https://webmaker.org/en-US/goggles

![img_6724](https://cloud.githubusercontent.com/assets/1068783/10325656/215b50b0-6c48-11e5-9ab4-151d94edf706.JPG)

cc @sabrinang

**Comment by hannahkane** [comment]
Nice work, guys! OK to add to current heartbeat, or should it be the next?

**Comment by kristinashu** [comment]
Probably next heartbeat. Getting the landing page done is our main focus and then I think this could come after.

**Comment by Pomax** [comment]
A nice thing for FTU is that we can actually make a page that listens for Goggles events to open up the exploration of the goggles step by step based on the user editing things using the goggles. (goggles uses window-level postMessage, which anyone else can listen too as well)

**Comment by kristinashu** [comment]
Added two tickets that need to be done before starting on this ticket:
* Activity for goggles FTU page #1324 - decide on a fun and simple activity that a first time users of goggles to remix
* Benchmarking FTU/Walkthrough experiences for Goggles #1325 - research and put some thought around the best way to guide users

**Comment by kristinashu** [comment]
@Pomax @hannahkane @cassiemc @chadsansing

I've added some FTU activity screens to redpen. Would love the get everyone's thoughts: https://redpen.io/p/wjdd96d46ae8c63dc3 (copy and illustrations are just placeholder to get the idea across)

I'm trying to keep it as simple as possible but let me know if you think it'll make sense for first time users.

**Comment by Pomax** [comment]
Penguilephamingo! :+1:

I wonder if we should also try some mockups around revealing "next step" text as part of the page, rather than using instruction bubbles.

**Comment by hannahkane** [comment]
I love this direction! Nice job. @kristinashu - not sure I understand where the different ideas are around how to do the tutorial. But as we said at stand today, perhaps we can discuss tomorrow?

**Comment by hannahkane** [comment]
Oh, hah. Just read @Pomax's comment above, and now I get it. Looking forward to reviewing both options tomorrow.

**Comment by kristinashu** [comment]
Here are comps for the two different directions (see benchmarking deck for some references: https://docs.google.com/a/mozilla.com/presentation/d/1qfuIPJU5YybJPDIl-pHVAFTbC3Zg30zIQs_AB4A-rxQ/edit?usp=sharing):

1) Goggles Tour then Activity: https://invis.io/AZ4LT8YBT
* traditional tour of features 
* followed by static activity similar to thimble
* tour similar to Invision and Slack in benchmarking deck
* cons: less interactive (just clicking next)
* pro: can skip and still do activity
* pro: could give tour anytime a user first activates goggles (even outside of FTU page)

2) Goggles Tour + Activity at same time: https://invis.io/5X4MAWTMT
* integrate features tour with the activity
* pro: much more interactive and engaging
* con: seems riskier - users can't do the activity unless they do the walk through
* tour similar to Snapchat in benchmarking deck

I'll go over these at design crit tomorrow but really we should probably user test both options.

**Comment by hannahkane** [comment]
+1 to user testing these options, if we can, ideally with our target audience (young learners or those new to coding). Not sure how to user test these without building them, though. Perhaps the design team will have ideas during your crit tomorrow.

I think it might be strange to use the tutorial styles from Thimble, given that it might set the expectation of having "Create a tutorial" functionality.

**Comment by cassiemc** [comment]
Consensus in the design crit was that Option 2 was stronger, but I'm happy to review user testing script if we want to throw the invision links up on usertesting.com.

**Comment by kristinashu** [comment]
I've updated the comps https://invis.io/5X4MAWTMT  
Focused on the version with the integrated tour/activity and added an intro page to give some context and overview.

**Comment by Pomax** [comment]
tracking dev work for this in https://github.com/mozilla/goggles.webmaker.org/issues/229

**Comment by Pomax** [comment]
@kristinashu what would the "skip tutorial" option do on the modal that "starts" the entire page? Does it just turn off any interaction until the page is reloaded, so you just get a "create your own adventure" page?

**Comment by kristinashu** [comment]
@Pomax yes, exactly. Thinking this would be useful for instructors using this activity in the classroom or users who just want to play around with the activity.

Closing and moving to https://github.com/mozilla/goggles.webmaker.org/issues/230
