### ISSUE TITLE
Wireframes for Initiatives Page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1311]
From the IA ticket https://github.com/mozilla/teach.mozilla.org/issues/1303, we identified the need to introduce an Initiatives Page. The name itself is TBD and can be tested like Leadership Programs.

This page will: 
- give an overview of all the programs and offerings MLN has to offer (context)
- provide information on the relationship to MLN and which audiences they are for (relatable)
- provide information on the roles and opportunities available (leadership development)
- provides a home for future initiatives to go (scalable)

This page includes:
- Maker Party 
- Mozilla Clubs
- Mozilla Hives
- Fellowships 
- Mozilla Festival
 
Each section can include links to corresponding websites and information on leadership roles (host, club captain, hive member, fellow, space wrangler etc.).

/cc @kristinashu @hannahkane

**Comment by sabrinang** [comment]
removing from heartbeat and timing will be strategized with audit #1260

**Comment by kristinashu** [comment]
Here is a wireframe of what @sabrinang and I sketched out earlier: https://redpen.io/p/uvc0135f6b8d5b5f31

Clubs and Maker Party CTAs would link to internal pages similar to the existing ones (https://teach.mozilla.org/clubs/ and https://teach.mozilla.org/events/). 

For now Hive, Fellowships and MozFest CTAs would link to the external sites but eventually these could link to internal pages.

**Comment by hannahkane** [comment]
@kristinashu - nice work! Added a few comments.

Want to flag @chrislarry33 and @ldecoursy so they're aware of this new architecture we're proposing, which I think is super helpful.

**Comment by ldecoursy** [comment]
I love it! Big step towards having these initiatives better integrated and presented. Thank you!

**Comment by kristinashu** [comment]
Updated the wireframes based on everyone's feedback: https://redpen.io/p/uvc0135f6b8d5b5f31

Also added Gigabit to the list and update the layout align more with the existing teach site layouts.

**Comment by hannahkane** [comment]
I'm really liking this. Want to get @HPaulJohnson and @KevZawacki's eyes on this as well.

**Comment by KevZawacki** [comment]
@hannahkane Looks really good! Seems like we're still in the early stages of copy -- happy to take another, closer look when we're building that part out.

**Comment by hannahkane** [comment]
Starting to think about copy here: https://public.etherpad-mozilla.org/p/mlninitiatives

Would welcome edits from @KevZawacki, @ldecoursy, @HPaulJohnson and others.

**Comment by hannahkane** [comment]
Closing this design ticket. Will open separate ticket for copy.
