### ISSUE TITLE
Wireframes for MLN Homepage

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1312]
From the IA ticket #1303, we identified ideas to revise the homepage to be more informative to first time visitors. 

This page could aim to:
- inform users of the Mozilla Learning mission 
- introduce our focus on teaching, leadership and universal web literacy approach (with Web Lit Map)
- introduce our initiatives
- share our Teach like Mozilla values

We want to keep the page simple but we are also considering how we can showcase timely content as well (e.g. featured curriculum, directory activity and current promotions) to provide value for returning users. Also, we can consider to describe the relationship to Mozilla and the open web depending on scope.

/cc @kristinashu @hannahkane

**Comment by sabrinang** [comment]
removing from this heartbeat and timing will be strategized with audit #1260

**Comment by hannahkane** [comment]
Note from @LauraReynal and @secretrobotron's  research: "importance of the first visuals people see.
why dont we try something like https://www.flickr.com/photos/laura_nk/16249739479/in/album-72157650633495175/
with people doing stuff together ?"

**Comment by hannahkane** [comment]
Few thoughts on this:
 * I think we want to emphasize that this is a network / community; it's something to which you *belong*
 * having said that, it's hard to justify asking people to create an account (unless they want to apply to be a Club Captain). Signing up for a newsletter might be a better conversion goal, and it's still sort of "join-y."
 * We know from analytics that /activities and /tools are the most popular pages. Could help people get there quickly.
 * Not sure things like Teach Like Mozilla and the web lit map need homepage prominence - they are "wonkier" and a bit harder to grok.

**Comment by hannahkane** [comment]
Closing this for now, as major changes to Teach content are out-of-scope right now.
