### ISSUE TITLE
Update Research Deck for Laura's NYC Research Trip

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1313]
We have updated ideas around reorganizing the information architecture on the Mozilla Learning Network website (https://github.com/mozilla/teach.mozilla.org/issues/1303) that we want to get feedback with from users. There may be a few new visuals to include in your research by the end of this week.

We will update this issue with ideas but @LauraReynal but please feel free to inform us what you would like to include in your NYC research trip.

**Comment by LauraReynal** [comment]
Thanks folks. I'll ping on Monday 12th with a calendar for a debrief from
Indonesia and we can assess the next steps together.

**Comment by hannahkane** [comment]
@LauraReynal - do you expect you'll need any changes this week?

**Comment by LauraReynal** [comment]
thank you all for the help on this deck. It's been very helpful ! 
we can close this ticket. 
:cat: :bomb: :tulip:
