### ISSUE TITLE
Add a sign-up form to the site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1316]
We created the "Pledge to Teach" as a way to capture interested users, and contact them when we have new resources, tools, content, or announcements to share.

Now, we'd like to offer a more explicit way for people to sign up to receive teaching-related resources and content. We specifically want to capture people who are actively teaching digital literacy skills, but don't want to sign up as a Club because, for example, they're already affiliated with another organization. These people will find our resources and content add value to their existing work. We will likely contact this segment of users more frequently than the pledgers. (See the chart on [Amira's recent blog entry](http://amiradhalla.com/2015/10/06/state-of-mozilla-clubs-whats-left-for-2015/).)

We'll likely have a KPI related to this group of users, so it's important we capture them. 

Information to capture: email address, location, (optional) affiliated organization

Questions:
 * Should this form live on the Clubs page, or somewhere else, or both? (I think it probably needs to live somewhere other than just the Clubs page - for example, the Activities page. Based on what I understand of the target audience, they might not visit the Clubs page given the fact that they already have a Club-like program.)
 * @adamlofting - any suggestions or best practices regarding how to best segment, and keep these groups organized, now that we'll have four different ways to sign up (site-wide sign-up (i.e. Webmaker), Pledge, Clubs, and this new sign-up)?
 * If we need a term for this group, what would we call them? @Amirad and I discussed "affiliates," which connotes a kind of formal relationship. Is that what we want to convey? If so, that might be reflected in copy and UX.

Would welcome feedback from anyone, but I'll specifically call out @kristinashu @sabrinang @mmmavis @Pomax @amirad @adamlofting @ldecoursy @chrislarry33 @cassiemc and @HPaulJohnson

**Comment by HPaulJohnson** [comment]
Good stuff @hannahkane (and super helpful blog post @amirad). I would love to dig in. I'd also love to include welcome comms (emails) in the scope of this conversation too. 

Would be great to carve out sometime next week to hack on this when many of us will be in NYC together. From the [working agenda] (https://docs.google.com/document/d/1maRy2Mcg_0YHXnZj922O2ylR6DCu7fd1HmjDu9xZZuU/edit#)  it looks like Tuesday afternoon or Thursday afternoon might be our best bet (I'll also be there all day Monday).

**Comment by hannahkane** [comment]
Sounds good, @HPaulJohnson.

**Comment by hannahkane** [comment]
We had a discussion in NYC and came up with a plan. Closing this ticket, and will open another detailing the plan, but won't put it into a milestone until we have the complementary newsletter content plan in place.
