### ISSUE TITLE
Add goggles fav icon and bookmark bar icon

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1317]
Design and implementation of a fav icon on landing page and tutorial page that will also work as an icon in the bookmark bar.

**Comment by hannahkane** [comment]
this is for goggles, right?

**Comment by kristinashu** [comment]
Ah yes! Updated.

**Comment by kristinashu** [comment]
We can't customize the bookmark bar icon and pomax already made the fav icon.
