### ISSUE TITLE
Provide a way for users to access Goggles projects

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1318]
I don't think we currently have a way for users to access a list of their Goggles projects, so we'll need to provide an entry point.

**Comment by jgmac1106** [comment]
Yes and for the longest time you have not been able to edit a Goggles
project. This is a PITA when teachers and students do  not finish. They
have to remix the remix which ends up with a painfully long url and project
name.

Not sure if this will be possible with old projects but should be a must
for updated Goggles.

**Comment by Pomax** [comment]
ping @jbuck: ideally for goggles we can use the same code that ends up being used for thimble projects - do you happen to know what that is scheduled for? (next heartbeat, the one after that, ...?)

**Comment by jbuck** [comment]
I don't know when any of this work is planned

**Comment by simonwex** [comment]
This wasn't on my radar for @jbuck or @cadecairos. @hannahkane, let's chat next week about this and the potential conflicts with our planning work.

**Comment by hannahkane** [comment]
This was me misunderstanding how Goggles worked before. Removing from this milestone - not a blocker to releasing new Goggles. Will need to figure out at a later date whether to make Goggles projects editable and discoverable.

**Comment by hannahkane** [comment]
Also, this dupes #1223, so I'm closing.
