### ISSUE TITLE
Curriculum Template Design Review

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1319]
See ticket here: https://github.com/MozillaFoundation/plan/issues/600

**Comment by hannahkane** [comment]
As discussed, deliverable for this milestone is wireframes.

**Comment by hannahkane** [comment]
Thinking we can close this ticket since @flukeout has moved on to comps already! Speedy McGee! Agree?

**Comment by kristinashu** [comment]
Sweet!
