### ISSUE TITLE
implement the goggles landing page

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1321]
based on https://github.com/mozilla/teach.mozilla.org/issues/1298, the landing page for the goggles is ready for implementing. Screens: https://redpen.io/p/wjdd96d46ae8c63dc3

**Comment by kristinashu** [comment]
Few styling notes:

Icon assets are here: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLTkdGc0o1ZndaRDQ&usp=sharing

Arrows are from font awesome:
fa-long-arrow-right [&#xf178;]
fa-arrows [&#xf047;]

Colours:
purple 6A6DB1
dark purple 4B51AA
pink F073AB
dark pink E04164
blue 1BA9E0
dark blue 005188
light grey background F1F1F1

You might be able to pull some styling from Thimble.

**Comment by Pomax** [comment]
I stole *so* much from Thimble.

First draft up on http://ecks-rey-giggles-are-landing.herokuapp.com, will make sure the right colours are in place tomorrow.

**Comment by jgmac1106** [comment]
That is so perfect. Many people have tried a long time to figure out what
you just explained in two simple images.

**Comment by hannahkane** [comment]
Looks awesome!

Two typos: 
 * In "Try a sample activity" the word begin is spelled "begine"
 * In footer, Goggles is spelled "Goggeles"

Help link will be: https://support.mozilla.org/en-US/products/webmaker/x-ray-goggles

**Comment by Pomax** [comment]
where should we point for the terms of service and privacy policies? (since goggles won't be hosting its own pages there)

**Comment by kristinashu** [comment]
This is what @hannahkane provided in #1298
TOS is here: https://beta.webmaker.org/#/legal
Privacy policy here: https://www.mozilla.org/en-US/privacy/websites/

**Comment by Pomax** [comment]
thanks! (#1298 was so long I got lost in it)

**Comment by kristinashu** [comment]
Here are the links for activities:
http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html
https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles
http://www.lessonpaths.com/learn/i/diving-in/hack-great-science-for-girls-with-the-xray-goggles

**Comment by Pomax** [comment]
http://ecks-rey-giggles-are-landing.herokuapp.com/ has the most recent refinements (after running through the site with @kristinashu), with the footer links hooked up properly and the sign in/up top links made functional. 

I would recommend we do a PR pass on the code so far, and if there's nothing horribly broken in it, land it and then work on setting up the three remix project thumb/desc/links correctly as immediate follow-up, so that we can test the login functionality against the real staging servers (which cannot be done with the "giggles" heroku app, as the callback URL for goggles at id.webmaker,org is for the staging server, so we can't test login until it's merged in)

/cc @mmmavis @hannahkane

**Comment by Pomax** [comment]
Landed, and http://x-ray-goggles-staging.herokuapp.com has been updated accordingly. Followup for the sign in / create a new account UI filed as https://github.com/mozilla/teach.mozilla.org/issues/1345
