### ISSUE TITLE
implement the goggles login UX

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1322]
Based on https://github.com/mozilla/teach.mozilla.org/issues/1248, the login UI/UX is ready for implementation, let's make it happen.

**Comment by Pomax** [comment]
crosslinking to https://github.com/mozilla/teach.mozilla.org/issues/1345 "Refine the sign in/up UI on the new goggles landing page"

**Comment by kristinashu** [comment]
@Pomax I've updated the comps to reflect goggles branding rather than teach site https://redpen.io/p/wjdd96d46ae8c63dc3

Ie Fira instead of open sans and blue buttons instead of yellow.

**Comment by Pomax** [comment]
https://x-ray-goggles-staging.herokuapp.com has been updated with the new login UX, let's file any issues we find as followups. New, beautiful, screens:

![screenshot 64](https://cloud.githubusercontent.com/assets/177243/10591916/b52d9ef4-766d-11e5-8874-8654af5e2aa9.png)

![screenshot 65](https://cloud.githubusercontent.com/assets/177243/10591917/b6996624-766d-11e5-92d1-77af58bbbccf.png)

![screenshot 66](https://cloud.githubusercontent.com/assets/177243/10591921/b7e1012c-766d-11e5-9925-fe69024458c5.png)

**Comment by kristinashu** [comment]
Nice!

**Comment by hannahkane** [comment]
Lovely :)
