### ISSUE TITLE
Add co-brand to badges

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1323]
From @anmechung: All 8 badges would have the possibility of being able to co-brand. Examples of partners might be OregonASK, the oregon statewide afterschool network. I imagine these particular badges would be ones they pull off of our site and house on their own platform.

**Comment by hannahkane** [comment]
Just checking my understanding - does "pull off our site" mean we'd give them art files that they could adapt and host on their own systems? So, we'd need to provide an example of how any of the badges might be adapted to include another organization's branding - could that be, for example, adding another tab for a second logo?

**Comment by anmechung** [comment]
@hannahkane I hadn't thought through it to that level, but that's exactly right.

**Comment by hannahkane** [comment]
@kristinashu - any questions about this ticket? Possible to complete this heartbeat?

**Comment by hannahkane** [comment]
Closing, as the requirements aren't clear.
