### ISSUE TITLE
Benchmarking FTU/Walkthrough experiences for Goggles

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1325]
Before designing FTU page for goggles #1310 I'd like to research and put some thought around the best way to guide users.

**Comment by kristinashu** [comment]
Put together a slide deck with some examples and thoughts https://docs.google.com/a/mozilla.com/presentation/d/1qfuIPJU5YybJPDIl-pHVAFTbC3Zg30zIQs_AB4A-rxQ/edit?usp=sharing

**Comment by hannahkane** [comment]
I know you've moved on, but just checking this out now. Very cool. Thanks. :)
