### ISSUE TITLE
Design Research for Web Literacy Map 2.0

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1327]
Synthesize and investigate previous research, user stories and personas that will inform the redesign of the Web Literacy Map with 21 Century Digital Skills. I'll be read this content for context, understanding throughout the development. 

#####  This reading list includes:

- [ ] Web Literacy & Leadership (blog): http://mzl.la/1IbPkkD
- [x] Digital-age Skills for 21st Century Skills (slides): http://bit.ly/1GkdDLV
- [x] 21st Century Skills Badging Framework (blog): https://blog.webmaker.org/21st-century-skills-badging-framework
- [x] Digital Age Skills for Educators (blog): https://blog.webmaker.org/digital-age-skills-for-educators
- [x] Meta-analysis of 21c Skills and Competencies: https://drive.google.com/a/mozillafoundation.org/file/d/0B9qOTaXg3UmRdXBDOEttSllpNFU/view
- [x] new blog post: https://blog.webmaker.org/21c-skills-badging-rubrics-and-pilots
- [ ] 21century skills rubric: https://drive.google.com/file/d/0B9qOTaXg3UmRaEJieEY0MkdtTFk/view

#####  This research includes:
An-Me's concept paper (draft): 
- [x] https://docs.google.com/document/d/1sP_nrYtkoZEyAOzfIxAFIgxBRq6T2ZGoBB_iuWYNyQI/edit

An-Me’s focus group research (interviews/raw data: https://etherpad.mozilla.org/webliteracy2-0)
- [ ] Summary: https://old.etherpad-mozilla.org/weblitfocusgroupstoplines 
- [x] Open science: https://etherpad.mozilla.org/Weblit2-0-OpenScience
- [ ] Open science 2: https://etherpad.mozilla.org/Weblit2-0-OpenScience2
- [ ] Hive Chattanooga:https://etherpad.mozilla.org/Weblit2-0-Chattanooga
- [ ] Hive NYC: https://etherpad.mozilla.org/Weblit2-0-HiveNYC
- [ ] Hive Chicago: https://etherpad.mozilla.org/Weblit2-0-Chicago
- [ ] Hive Pittsburgh: https://etherpad.mozilla.org/Weblit2-0-Pittsburgh
- [ ] International and emerging markets: https://etherpad.mozilla.org/Weblit2-0-International
- [x] Engineers/Developers/Mozilla internal: https://etherpad.mozilla.org/Weblit2-0-Mozilla
- [ ] Advocacy: https://etherpad.mozilla.org/Weblit2-0-Advocates
- [ ] Afterschool:https://etherpad.mozilla.org/Weblit2-0-Afterschool
- [ ] MOUSE Web Lit Educators: https://etherpad.mozilla.org/weblit-MOUSE
- [ ] School people: https://etherpad.mozilla.org/Weblit2-0-educators 
- [ ] General Feedback https://etherpad.mozilla.org/webliteracy2-General

An-Me’s Quiz assessment work
- [ ] To be found?

Laura’s field research and personas
- [ ] Post-Indonesia MLN findings
- [ ] Previous reports (India/Rio/Kenya/Chicago?)

Design brief reference: https://docs.google.com/document/d/1yFjUU_vEppNBA8JlG5weYa-P3Rpp1v78sthXhHq7DNw/edit?ts=5609890b

This ticket informs: #1268 and #1305

**Comment by sabrinang** [comment]
Documenting some initial sketches from research. I looked through the meta-analysis of 21c skills and competencies .pdf and started to sort and group them into broader sets of 21c mindsets/skills and digital/web skills to examine the overlap and trends:
![dsc02316](https://cloud.githubusercontent.com/assets/2492510/10407650/cd35f8d4-6ea2-11e5-88a3-327164fb49b0.png)
I'm continuing to synthesize them and some groups are shaping up:
![dsc02318](https://cloud.githubusercontent.com/assets/2492510/10407654/d238e4ea-6ea2-11e5-9ceb-e8db7b3da61b.png)
Calling out some themes for web/digtal literacy so far and thinking about technology/tools as the medium or affordance for web/digital literacy:
![dsc02317](https://cloud.githubusercontent.com/assets/2492510/10407655/d4708f06-6ea2-11e5-9947-cada4aa54d78.png)
From the sorting activity there is also context and experiences outside the map to consider as a system:
![dsc02319](https://cloud.githubusercontent.com/assets/2492510/10407656/d5e2a0d6-6ea2-11e5-8d58-5dfbdcc75d40.png)

I'll be continuing this research looking map relationships and digitizing some of these notes.

**Comment by sabrinang** [comment]
Ideas to consider that would improve map experience (in various phases: before users get to the map, during the map and outside/after of the map)
![mozilla-learning-network_web-literacy-map-redesign_experience-notes](https://cloud.githubusercontent.com/assets/2492510/10407849/8c898af0-6ea5-11e5-8f61-b576ae305d39.png)

**Comment by anmechung** [comment]
@sabrinang really looks great thus far!  

Here is a summary of the focus group research - https://old.etherpad-mozilla.org/weblitfocusgroupstoplines and new blog post:  https://blog.webmaker.org/21c-skills-badging-rubrics-and-pilots.  Also will have digestable draft of Web Lit 2.0 concept paper by next week.

**Comment by hannahkane** [comment]
@sabrinang - I <3 this! I especially like how you're thinking holistically about how this connects to credentials, curriculum, and tools, and how you're envisioning the map to be much more actionable. If it were also connected to our initiatives (Clubs, Hives, Maker Party, MozFest, Fellowships), it would essentially be a framework for all of the MLN work.

**Comment by anmechung** [comment]
@hannahkane +1 all the away around - love it.

**Comment by hannahkane** [comment]
cc @chrislarry33 because this is awesome

**Comment by chrislarry33** [comment]
piling on @sabrinang I love it! The "connections to the map" is crucial in nexy phase.

**Comment by anmechung** [comment]
@sabrinang draft of Web 2.0 concept paper - you'll see that it matches up well with what you've been designing.  https://docs.google.com/document/d/1sP_nrYtkoZEyAOzfIxAFIgxBRq6T2ZGoBB_iuWYNyQI/edit

Still getting feedback and fleshing out specific web literacy skills and competencies, but this should give you a pretty good sense of where we're headed.   

Quiz - reaching out others to see if they can unearth it.  So far, what I've seen isn't exactly what I'm looking for!

**Comment by anmechung** [comment]
@sabrinang also wondering if part of what we test/get feedback on at MozFest is also some kind of design/concept brief that we cull from concept paper and your work?

**Comment by sabrinang** [comment]
@anmechung thanks for the additional links! I have added them to my reading list which I will continue to sift through. Yes, all this work is adapted from your research which will include the concept paper to inform a concept to test at MozFest. I want to ensure that I am up to speed with all the research readings so I can help make an activity that is relevant and reflective of all your current work. I will keep this ticket updated of where I am at and ideas that come up.

**Comment by anmechung** [comment]
@sabrinang happy to chat/brainstorm any time as you are sifting through the reading!

**Comment by sabrinang** [comment]
As I'm reading through the web lit map draft and visually noting how it may be with the 21c skills.
![dsc02328](https://cloud.githubusercontent.com/assets/2492510/10491768/2303d35e-725d-11e5-9a8f-5be87ffd5ded.JPG)

@anmechung Let's chat about approaches the map could be reimagined and if anything can't be changed so we know any constraints when we design the workshop activity or if we can have more blue-sky ideas?

**Comment by sabrinang** [comment]
Note: There is no specific deliverable for this ticket it is to keep track of research to inform design work.

**Comment by hannahkane** [comment]
@sabrinang - does this ticket still feel useful? I'm thinking we ought to close it and open one that's specifically about delivering a new iteration of the map design.

**Comment by hannahkane** [comment]
Just saw that the ticket for a new map design already exists - #1457. Still wondering if keeping this ticket open is useful.

**Comment by sabrinang** [comment]
@hannahkane Yes we can close this now and it is referenced in #1457
