### ISSUE TITLE
BY OCT 16: Close MozFest Volunteer sign-up

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1330]
The MozFest team would like to close down the Volunteer sign-up form by Friday at the latest, but any time before that is fine.

 - [ ] https://github.com/mozilla/2015.mozillafestival.org/issues/183

**Comment by hannahkane** [comment]
@mmmavis - just wanted to check to see if you saw this? possible to get this done tomorrow?

**Comment by mmmavis** [comment]
done. live on https://2015.mozillafestival.org/volunteer :tada:
