### ISSUE TITLE
mobile comps for goggles landing/install page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1331]
Based on the desktop design of the landing.install page for Goggles in #1298 and https://redpen.io/p/wjdd96d46ae8c63dc3

Comp needs to clarify that goggles only works on desktop.

**Comment by Pomax** [comment]
Or that it was designed for desktop, and *might* work on someone's mobile device but we kind of doubt it and they're on their own(tm)

**Comment by kristinashu** [comment]
Cool, we can say something about it being 'optimized' or 'works best on' desktop. 
@Pomax how do you determine if someone is on mobile - by device detection or screen width?
I think someone could probably install and sort of use goggles on a narrow desktop screen but I think install wouldn't work on touch devices (even giant ones)?

**Comment by Pomax** [comment]
The best way is to not make the mobile/desktop distinction but simply check whether all the things goggles relies on is available. Screen width is a reasonable first check, but the library also uses some JS stuff that could be tested for. However, the main impediments are going to be touch events rather than mouse, paired with the fact that mobile browsers typically handle bookmarks completely different, so there is no bookmark bar available, even if you wanted to use one.

It's probably the easiest for us to check the user agent for known mobile UA strings, and if we see one, add in the warning/notice that goggles might not work for them.

**Comment by kristinashu** [comment]
Here's what I'm thinking: https://invis.io/XT4KEI1PJ
All touch devices would have a message locked to the bottom of their browser. They can close it to dismiss it. Other idea would be the have the message at the top but I don't think it would stand out as much.

**Comment by Pomax** [comment]
What constitutes a "touch device" though? For example, every Surface Pro device is both a touch device and a full, regular windows 8/10 computer with desktop Firefox, so touch is not in itself enough to determine we're generating a warning for our mobile users.

**Comment by kristinashu** [comment]
Yes, whatever you think is the best way to determine whether or not someone can install goggles works for me. If we say mobile will that pick up on tablet as well? Can/should we show the message for both?

**Comment by Pomax** [comment]
it's a tricky thing to detect. The notice looks good, I'll ask around to get some input on what the best way is to detect that a browser is "desktop enough" for our purpose.

**Comment by kristinashu** [comment]
@cassiemc could you please review the mobile comp? https://invis.io/XT4KEI1PJ

**Comment by cassiemc** [comment]
Hey @kristinashu, a couple small nitpicky issues. Adding some screenshots below.
![xray1](https://cloud.githubusercontent.com/assets/1186326/10608707/3163f32e-770e-11e5-9b44-bec85402b715.png)
![xray2](https://cloud.githubusercontent.com/assets/1186326/10608708/3174f638-770e-11e5-816d-83d9f68627c4.png)
![xray3](https://cloud.githubusercontent.com/assets/1186326/10608709/317b9394-770e-11e5-950c-f86d89b03090.png)

**Comment by kristinashu** [comment]
@cassiemc thanks for reviewing. I made all the updates except for the low res Hack Science image, I'll hold off until we know the exact activities. The dark background was a png mistake - it should have been white. 
Updated comp: https://invis.io/XT4KEI1PJ
