### ISSUE TITLE
Prepping main nav bar for the new Credentials page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1333]
We will be adding a new section to the teach site and I'm concerned about the scalability of the side nav bar. With the new page, the vertical length of the side bar is getting long and all the menu items might not be visible on smaller laptops - particularly when a secondary menu items is displayed.

A few suggestions: 
* we could remove the icons (giving us more room for text)
* or replace icons with smaller simpler ones
* or remove the text descriptions for each section (leave users to click to discovery each section)

Any thoughts or suggestions? @sabrinang @mmmavis @hannahkane @cassiemc

**Comment by cassiemc** [comment]
I like the idea of removing the descriptions. I think the icons still give some context as to what is inside each section, and it's a nice step toward the improved nav structure @kristinashu and @sabrinang have planned.

**Comment by mmmavis** [comment]
+1 on removing the descriptions.  The sidebar currently takes up 3 columns of the [Bootstrap's 12-col grid](http://getbootstrap.com/css/#grid-options). If space allows(ie., text won't wrap to 2nd line), we can probably shrink the sidebar to 2-col.

**Comment by hannahkane** [comment]
+1 to removing descriptions, but largely because we know we have a different IA coming. I don't think "Teach Like Mozilla" will necessarily be intuitive to people without a description attached, but OK for now, since we're not trying to drive traffic to that page yet.

**Comment by kristinashu** [comment]
Here's a mock up for the side bar: https://redpen.io/p/jh0a4bc04ea2daf52b (current sidebar on the left, proposed sidebar in the middle, and proposed sidebar with secondary menu item open on the right)

* removed the description
* updated icons - still line icons but simpler so they work at the smaller size (I got most of them from http://linea.io/)
* removed the arrows (I don't really think they served a purpose)
* added Credentials page
* moved Community to the bottom since it's an external link (also add an external link icon to it)
* made column narrower 
* removed Webmaker from footer links

Wondering if we could lock the sidebar so it doesn't scroll (only the content on the right side would scroll). This way users can always access menu items. @mmmavis would this be difficult to do?

cc @cassiemc @sabrinang @hannahkane

**Comment by cassiemc** [comment]
Sounds like all really wise decisions @kristinashu, as mentioned in the redpen it's a beautiful refinement. Great work! I think the only part that might use a bit more work is the subnav.

The locking sidebar I still like as an idea, too. It was always meant to do that and I think was missed in the original QA. I'd had some inspiration I was looking to at the time but can't seem to find it. Will try to dig it out later.

**Comment by cassiemc** [comment]
Found it: http://tympanus.net/Development/MultiLevelPushMenu/index.html#
And another for inspiration if we ever want to hide the sidebar completely: http://tympanus.net/Development/SidebarTransitions/

**Comment by kristinashu** [comment]
@cassiemc I've updated how we show the secondary menu items based on feedback in Redpen. Removed the line connecting the selected main menu item with the secondary menu item but to make sure there is still a connection between the secondary item and main item I've added an arrow before the secondary menu item to make it look like a sub list. Also made non selected icons more transparent while making the selected icon white to better highlight the selected section.

Updated comp: https://redpen.io/p/jh0a4bc04ea2daf52b

**Comment by hannahkane** [comment]
Nice work, @kristinashu. I put a comment in the redpen about possibly user testing the sub-menu because users have failed to notice it in informal user testing.

**Comment by kristinashu** [comment]
I've updated the comps based on redpen feedback: https://redpen.io/p/jh0a4bc04ea2daf52b
* moved Discourse to the footer
* boxed secondary menu items in with main level menu item (this should make it more obvious that there is a secondary menu)

**Comment by kristinashu** [comment]
Updated again https://redpen.io/p/jh0a4bc04ea2daf52b

Discourse is back as a main level menu item (short term plan is to show external link icon and longer term plan is to build a 'community' landing page which will link out to discourse).

**Comment by cassiemc** [comment]
@hannahkane Generally we'd recommend keeping the Community link in the footer until the community page was built. I think it'd be a LOT less jarring to the user, and the current solution where it links out kinda reminds me of the jankiness of an 'under construction' page. Not quite that bad, but similar feeling. If you really need it in the main nav, of course we defer to your judgement.

**Comment by hannahkane** [comment]
@cassiemc - I understand the design/usability concern, but promoting Discourse is a very high programmatic priority right now. I'd prefer to build the page before implementing the new design, rather than demote Discourse to the footer. We can make building the page a P1 in the next heartbeat if necessary.

**Comment by cassiemc** [comment]
That makes sense to me, @hannahkane! However if you're not *ready* to build the Community page yet,  just keep the link in the main nav with the external link icon.

**Comment by kristinashu** [comment]
Sounds good. 

Closing and moving this to the bigger ticket #1370
