### ISSUE TITLE
Update Goggles FAQ on sumo

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1336]
https://support.mozilla.org/en-US/products/webmaker/x-ray-goggles

**Comment by Pomax** [comment]
See https://github.com/mozilla/goggles.webmaker.org/issues/228 for the help page

**Comment by hannahkane** [comment]
Started a pad with suggestions for edits to existing questions and a few new questions. Would love fact-checking from @Pomax, if you can spare some time.

https://public.etherpad-mozilla.org/p/gogglesfaq

**Comment by hannahkane** [comment]
FAQs are ready to go, once new Goggles launches. Could use fact-checking from @Pomax, though. Moving to next heartbeat so we don't lose track of this.

**Comment by Pomax** [comment]
I've left some edits and comments in the FAQ. I don't think it's wise for us to expose the CSS editing capabilities - they look hellacomplex.

**Comment by hannahkane** [comment]
Thanks, @Pomax. Awesome edits, and agreed, we can remove the CSS editing Q.

Updating the milestone to January. I'll make these changes after the new version goes live.

**Comment by hannahkane** [comment]
Updated all relevant SUMO questions
