### ISSUE TITLE
Badge design files for dev

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1337]
Desktop and mobile illustrator files: https://drive.google.com/file/d/0B2irLVDJivhLOEIzWkZiM3c5ZVE/view?usp=sharing

JPG Comps: desktop https://redpen.io/p/tq1fbf0a41edd3909f and mobile https://invis.io/YE4LT4HZH

Badges as PNGs and icons both PNGs and SVGs: https://drive.google.com/folderview?id=0B2irLVDJivhLZTE5VUhxSzlrc2s&usp=sharing
Note: Badges will be animated GIFs. Badges should static but animate on hover and in Twitter shares. GIFs coming in #1338

Some of the icons are from Font Awesome:
fa-check [&#xf00c;] 
fa-clock-o [&#xf017;] 
fa-pencil [&#xf040;]
fa-long-arrow-left [&#xf177;]
fa-long-arrow-right

Let me know if I've missed anything or if you have any questions.

**Comment by AbuAlKarmi** [comment]
I worked on this design and almost done.
you can find it on the following PR: https://github.com/mozilla/teach.mozilla.org/pull/1427
and I'm waiting the API's to complete work

**Comment by hannahkane** [comment]
Closing this since the work is done and can be referenced if needed.

**Comment by Pomax** [comment]
reopening for cross-reference purposes

**Comment by kristinashu** [comment]
Guessing we can close this

**Comment by Pomax** [comment]
technically, but I'd like to keep it open (without the design label) until the badge PR has landed, since testing the PR requires being able to refer back to the redpens.
