### ISSUE TITLE
Create badge GIFs

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1338]
Make the badges into subtle animated GIFs. GIF would show on rollover on the landing page and in social share messages (probably not possible in LinkedIn but should work in Twitter and Facebook?).

**Comment by hannahkane** [comment]
+1!

**Comment by kristinashu** [comment]
@cassiemc please let me know if you have any thoughts about this

**Comment by cassiemc** [comment]
I think this is amazing, +1 to making them move. Just wondering about ideal size (both file size and resolution for retina, or would svg animations work), and how these will render on different platforms. Gif might still be the best option but worth looking into before getting started. cc @flukeout @vazquez

**Comment by cassiemc** [comment]
Email also a platform worth considering.

**Comment by flukeout** [comment]
@kristinashu Do you have a particular badge and animation in mind? Send it my way and we can experiment with some simple animations and see what it does to file sizes.

CSS animations are a nice option too, but would only work on the website. We'd also lose the ability to 'right click' and save the badge images since they'd be made of multiple, moving components - which could be a drawback.

**Comment by kristinashu** [comment]
It's a work in process but just to get an idea of file size.

![badge](https://cloud.githubusercontent.com/assets/1068783/10776283/3f188808-7ccd-11e5-9c63-10791576a7d5.gif)

Because it has so few colours the file size is only 104 KB.

I think gif is the way to go for browser support and so that it works in Twitter shares and emails.

**Comment by kristinashu** [comment]
Might need to look at it here https://dl.dropboxusercontent.com/u/7431680/Badge.gif

**Comment by cassiemc** [comment]
I know these are a work in progress so feel free to tell me to shut up, but it would be nice if the animations were a bit smoother, with easing, etc. Nice start though, can't wait to see 'em finalized, and agree that if you can export higher-fidelity animations to reasonably sized gifs, then that def. seems the way to go.

**Comment by kristinashu** [comment]
Haha feedback is always welcome! But yeah, this was just a rough test to get an idea of size. More work is needed on the animation and I can probably get the file size down as well with some tinkering.

**Comment by kristinashu** [comment]
Here's where I'm at with the GIFs: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLaEMtejhieUxRaVE&usp=sharing

Just two more to go.

**Comment by hannahkane** [comment]
Nice!

**Comment by anmechung** [comment]
+ 1  very nice!

**Comment by kristinashu** [comment]
GIFs are all done https://drive.google.com/folderview?id=0B2irLVDJivhLaEMtejhieUxRaVE&usp=sharing

Because the icons shifted a little they no longer line up with the badge pngs I exported earlier. The new link has both the gifs and the new pngs. @hannahkane not too sure who to tag for dev but they can let me if they need the files in a different size or format.

**Comment by hannahkane** [comment]
Thanks, @kristinashu. They look great! I just opened an implementation ticket (#1429), so I think we can close this.

**Comment by flukeout** [comment]
These are great! @kristinashu - the leaves in the palm one isn't looping like the rest, just animates once.

**Comment by kristinashu** [comment]
Ah thanks @flukeout it should loop now!
