### ISSUE TITLE
Look into current goggles FTU

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1343]
@Pomax can you disable the current FTU hints so we can add new ones?
<img width="1399" alt="screen shot 2015-10-14 at 1 56 54 pm" src="https://cloud.githubusercontent.com/assets/1068783/10497642/c61c336a-727b-11e5-9cce-69da13351ece.png">

Based on FTU page for goggles #1310

**Comment by Pomax** [comment]
found them, and removed them. Staging should be updated to reflect this momentarily
