### ISSUE TITLE
Reflection Tool, Personas and Pathways for the Web Lit Map

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1344]
From the research #1327 and discussions with @anmechung, in order to make the map more approachable, accessible and applicable we need a tool to assists users to understand their own skill levels, interests and goals. This self-assessment informs how we adapt the map's content to meet their needs.

We may need to establish a structure for the persona so it can be reflected in the questions we ask in the reflection tool. There will be no more than 5 or 6 personas for now and at MozFest #1305 we can get people involved in submitting their own that will inform us what they think and if we need more.

Things to figure out:
- [ ] What do we ask on the reflection tool?
- [ ] How do we format the personas and/or pathways?
- [ ] How do we collect user submitted personas and feedback? (using google forms)

**Comment by sabrinang** [comment]
Here are some ideas around the format and relationships between personas and pathways that can make the competencies on the map more relateable: 
![mozilla-learning-network_web-literacy-map-redesign_planning](https://cloud.githubusercontent.com/assets/2492510/10554587/a77b01f8-7419-11e5-8bbb-b18d8b69fbef.png)

The reflection tool could be an important piece to help determine a users Persona which leads them to relevant Pathways and Resources. The content seen was adapted from the rubric. This example may be too limiting in the example but I like the idea of breaking down the [rubric] (https://drive.google.com/file/d/0B9qOTaXg3UmRaEJieEY0MkdtTFk/view) into parts that are digestible, relevant and actionable for the user.

@anmechung I would love to hear your feeback and what you think a Persona should consist of? *(i.e. - in the image example you can see - level, focus, interest, goal etc.)*

I'm thinking of how to include this in the MozFest activity as well.

**Comment by sabrinang** [comment]
redpen here: https://redpen.io/nw2620866a08175bf5

**Comment by hannahkane** [comment]
We did this! Closing.
