### ISSUE TITLE
BSD -> ExactTarget: Updating existing sign-up forms

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1347]
From a doc @adamlofting recently sent out
> Existing places where we offer users an opt-in to receive updates from Mozilla need to be updated to subscribe users to the appropriate list in ExactTarget rather than BSD.

@adamlofting 
some Qs for you: :grin: :grin: :grin: 
1. can we start updating the forms now?
2. how do I access ExactTarget?
3. how do I ensure the forms really work (aka posting data to ExactTarget) after this updating work?

**Comment by mmmavis** [comment]
> how do I access ExactTarget?

ah sorry just saw the 2nd link on your email @adamlofting ... :+1: we'll wait

**Comment by hannahkane** [comment]
Is this ticket closeable? Seems out-of-date.

**Comment by adamlofting** [comment]
Yes! :+1: 

This has been completed.
