### ISSUE TITLE
"logged in" status styling

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1348]
Using Thimble's colours for "logged in" status paired with our darker purple colouring of the nav bar leads to something that is probably too low constrast for many users. We probably want to restyle this a little bit to be more visible for the goggles landing page.

Current style:

![capture](https://cloud.githubusercontent.com/assets/177243/10552263/8ae16e0e-7407-11e5-85af-1368a28363e5.PNG)

**Comment by kristinashu** [comment]
How about text is white and then the current light purple on hover.

**Comment by Pomax** [comment]
switched over to the `@lightgrey` less variable (#F1F1F1)
