### ISSUE TITLE
add a loading state for checking "signed in" status based on a goggles token

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1349]
If there is a token, the landing page will check to see if it's valid to show the user's "logged in" state, but depending on how fast id.wmo responds to that request it can take a few seconds, during which it'll look like we're not signed in at all, and possibly making people click sign more than once because it looks like it's "not doing anything".

A state indicator for "waiting to hear back from id.wmo whether this token was valid" would prevent this. Could be a spinner, or some other animation that suggests to the user that something is happening.

**Comment by hannahkane** [comment]
@Pomax - ok if I assign to you? Want to make sure everything in this heartbeat is assigned.

**Comment by hannahkane** [comment]
Oh, wait...re-reading. You want a designer on this?

**Comment by Pomax** [comment]
let's close this for now. This should not be an issue in production, but if it is we can address it when it pops up.
