### ISSUE TITLE
Create "Privacy Basics" activity page and add section to /activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1353]
### Addition to /activities page ###

(@chadsansing - can you please verify all of the below?)

 * Position on page: Directly following "Protect Your Data"
 * Title: Privacy Basics: Passwords, Tracking, and Data Retention (Teaching Kit)
 * url: /activities/privacy-basics 
 * Level: Intermediate
 * Developed by: [Stacy Martin](https://mozillians.org/en-US/u/stacy/), Senior Data Privacy Manager at Mozilla and the Mozilla Learning Network team
 * Description: Learn how to safeguard your privacy online and develop an awareness of how companies and governments track and collect your data online.
 * Image: https://upload.wikimedia.org/wikipedia/commons/9/98/SafeWalletLogo.png

### Page Content ###
https://docs.google.com/document/d/1Gr9PhZQhKQTFfShW8-rMWvqJz11W6i8rWCuwPs5_dWQ/edit#heading=h.bbi115q13l5l

**Comment by hannahkane** [comment]
Deadline: Oct 30, but let's aim to have it up earlier

**Comment by hannahkane** [comment]
@mmmavis - the first comment needs an OK from @chadsansing, but wanted to get this on your radar now. Do you think it will be possible to get this page up this week or early next? It's part of the SmartOn campaign we're doing with MoCo.

**Comment by chadsansing** [comment]
@hannahkane, confirmed, though we may want to add something like, "...and the Mozilla Learning Network team" to credits to account for all the names on the Lightbeam activity. Thoughts, @ldecoursy & @chrislarry33?

**Comment by ldecoursy** [comment]
+1

**Comment by hannahkane** [comment]
updated

**Comment by ldecoursy** [comment]
Looking like the title will be Privacy Basics: Passwords, Tracking, and Data Retention

@hannahkane Can we set the URL as teach.mozilla.org/activities/privacy-basics 

cc @HPaulJohnson

**Comment by hannahkane** [comment]
@ldecoursy - sure. updated first comment in ticket.

**Comment by HPaulJohnson** [comment]
@hannahkane when will this link be live? i need to supply it to MoCo for inlcusion in SmartOn soon. Even if the pages aren't ready now maybe we just have it redirect to the main activities pages for the time being?

**Comment by hannahkane** [comment]
@pomax - can you estimate when you can have this live?

@hpauljohnson - We know what the link will be (https://teach.mozilla.org/activities/privacy-basics) - can you share that with them even though it doesn't exist yet?

**Comment by HPaulJohnson** [comment]
@hannahkane - yes, but will wait until i have an ETA for going live because they will want to know as they are likely close to QA now.

**Comment by hannahkane** [comment]
@HPaulJohnson - what's the deadline for this?

**Comment by HPaulJohnson** [comment]
@hannahkane the campaign goes live on 11/3. Needs to be available asap. It can redirect to main activities page if need be, just in case we can't get it up ahead of that.

**Comment by Pomax** [comment]
@chadsansing @hannahkane we can't actually use https://commons.wikimedia.org/wiki/File:SafeWalletLogo.png, as its license *only* permits use on wikimedia sites.

**Comment by Pomax** [comment]
In order to have the page up today, we'll be using https://commons.wikimedia.org/wiki/File:Monitor_padlock.svg instead of the wallet

**Comment by chadsansing** [comment]
Nice catch - leveling up license use now. Thanks, @Pomax.

**Comment by chadsansing** [comment]
@Pomax, how goes the build? Any ETA on a live page yet?

**Comment by hannahkane** [comment]
Page looks good, but need to fix this link before releasing (#1403)
 * Avoiding Password Reuse should link to: chadsansing.github.io/curriculum-testing/expanded-privacy-curriculum/avoiding-password-reuse.html

Not a blocker to release:
 * @chadsansing - Passwords Agenda, Creating Strong Passwords, Avoiding Password Reuse, Privacy Elevator Speech, Data Retention Agenda, and Follow Your Data Trail aren't displaying the CSS correctly. Can we fix those files?

**Comment by chadsansing** [comment]
@hannahkane, let's do. They seem to display correctly on my machine. Can we identify the issue? Happy to work on it some or merge a pull request from a bug-whisperer.

![screen shot 2015-10-27 at 5 41 26 pm](https://cloud.githubusercontent.com/assets/4128600/10773492/fb4cdc50-7cd1-11e5-88b4-350d3894017e.png)

**Comment by hannahkane** [comment]
Huh...wonder why it looks like this for me...any front-end ppl have an idea? @mmmavis @flukeout ?
![screen shot 2015-10-27 at 3 00 09 pm](https://cloud.githubusercontent.com/assets/8389648/10773934/773e7876-7cbb-11e5-8d13-6a55bed790ab.png)

**Comment by hannahkane** [comment]
Added https://github.com/mozilla/teach.mozilla.org/issues/1404

**Comment by Pomax** [comment]
@chadsansing @hannahkane this happens if you go to **http**://chadsansing.github.io, rather than https, and is caused by https://github.com/chadsansing/curriculum-testing/issues/120

**Comment by hannahkane** [comment]
Cool. Thanks, @Pomax. Can we fix the link in #1404 and push this page to prod?

**Comment by Pomax** [comment]
PR pending as https://github.com/mozilla/teach.mozilla.org/pull/1405

**Comment by chadsansing** [comment]
Got it.
