### ISSUE TITLE
Vectorized logos for Hive new emerging communities

### ISSUE THREAD

**Issue by simonaramkisson** [mozilla/teach.mozilla.org#1355]
Hey @mmmavis,

Is there anyway to get the logos for Manchester, Waterloo, Cascadia and Vizag in a vector format? Manchester is asking because they need it in a higher resolution?

Not sure of the process but any insights would be awesome!

Thanks,
Simona

**Comment by mmmavis** [comment]
@sabrinang ^ ? :+1:

**Comment by simonaramkisson** [comment]
@mmmavis @sabrinang thank you :)

**Comment by mmmavis** [comment]
Hi @simonaramkisson you can find the .eps files in https://drive.google.com/drive/folders/0B4Q8pzCpDS_eQi1sOXo3Rk83Vms :smile_cat:

**Comment by hannahkane** [comment]
@simonaramkisson - let us know if we can close this ticket

**Comment by simonaramkisson** [comment]
@sabrinang  Thank you so much! 
@hannahkane can go ahead and close
