### ISSUE TITLE
Update auto-email Club Captain applicants receive

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1359]
After completing the Club Captain application form on the /clubs page, users receive an automatic email (current copy below). We'd like to edit that email to include a link to a questionnaire.

---

### Revised text of email ###

Thanks for your interest in teaching the web! We are thrilled that you have taken the first step in your journey to becoming a Mozilla Club Captain. 

In order to better understand your plans and needs for your club, we'd like to know more about you. Please provide brief answers (2-3 sentences) to the questions in this survey http://bit.ly/1MP9BzB. Your answers will help us in the process of reviewing/approving your submission on the Mozilla Clubs map. Note, it is mandatory to complete and return these questions in order to proceed to the next step. 

We look forward to hearing from you! You can tweet to us @mozteach or using hashtag #teachtheweb if you need any help. 

Mozilla Clubs team

**Comment by amirad** [comment]
This ticket is the same as this one yes? https://github.com/mozilla/learning-networks/issues/267

**Comment by hannahkane** [comment]
I think this ticket is the implementation ticket, since it's in the Teach repo. And maybe the LN ticket is for finalizing copy.

**Comment by amirad** [comment]
Ahh okay cool! Well then I'm not blocking!!! Waiting on feedback from others.

**Comment by ldecoursy** [comment]
@amirad Checking back on this after @HPaulJohnson and I shared feedback. I think instead of the questions in the email we should just link to the Google form that @kgorr put together (I added the link in the etherpad).

**Comment by amirad** [comment]
Sorry for blocking, yes the copy links to the survey instead now @ldecoursy 

Final copy @hannahkane https://public.etherpad-mozilla.org/p/teach.clubsignupemail

**Comment by hannahkane** [comment]
Thanks, @amirad. Updated the first comment with the final copy. No longer blocked.

**Comment by mmmavis** [comment]
changes are now live!
