### ISSUE TITLE
Determine content strategy for "Community" page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1361]
Rather than take people off-site (straight to Discourse) from a main navigation item, we want to take people to a "Community" page that provides an overview of *all* of the ways to connect with the MLN Community, including:
 * Discourse
 * Community Call(s)
 * Hive Cities links
 * Community hashtags (i.e. #teachtheweb)

What else? @ldecoursy? @kgorr?

**Comment by KGorr** [comment]
@Mozteach Twitter link please!

Could also link to our community stories submission form: https://docs.google.com/a/mozillafoundation.org/forms/d/1bOXV1OiF2EKS5KprlnzfFpwaoVNwxLAwN_UEq6hGKqU/viewform

Is that OK @ldecoursy?

**Comment by ldecoursy** [comment]
I'm not sure about sharing that form so broadly just yet - worried about getting a lot of noise... Also not so much a way to "connect." That said, we could try it and see if it becomes unwieldy...

I'd add teachtheweb@mozillafoundation.org

**Comment by hannahkane** [comment]
Thanks! Will add twitter, email, and story submission form (can remove later if we need to).

@kgorr - can you please provide the latest information about community calls?

**Comment by ldecoursy** [comment]
Let's hold on community calls until plans are finalized. Amira is hosting monthly Mozilla Clubs open office hours - we can include that.

**Comment by hannahkane** [comment]
@amirad - can you please share info about the monthly MozClubs open office hours?

**Comment by amirad** [comment]
Sure....it's going to be the last thursday of every month from 10-11am ET (might play around with timings if I find that this doesn't work for people). Working on getting some type of text up on a github page soon so can point people there.

**Comment by hannahkane** [comment]
thanks, @amirad. Please drop the github page here when it's up.

**Comment by hannahkane** [comment]
Thanks, all. Closing this ticket, and moving to implementation: https://github.com/mozilla/teach.mozilla.org/issues/1414

Flagged @amirad on that ticket to provide details about Clubs Office Hours when available.

**Comment by amirad** [comment]
Consider me flagged @hannahkane - been trying to get a github page up to point too but I'll be scrappy and get something done this week. Will add to the ticket you have opened with the redpen.
