### ISSUE TITLE
Update "Curriculum Queue" github page with new content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1362]
The content on this page: http://chadsansing.github.io/curriculum-testing/curriculum-queue/ needs to replace the content on this page: http://mozilla.github.io/webmaker-curriculum/index.html

Who currently maintains that page? @thornet - has it been you in the past?

**Comment by hannahkane** [comment]
I think perhaps @thornet needs to do this - does she maintain this page? Taking out of current milestone.

**Comment by hannahkane** [comment]
@mmmavis - Possible to give me edit access to http://mozilla.github.io/webmaker-curriculum/index.html? Then I can probably take this ticket.

**Comment by mmmavis** [comment]
@hannahkane 

You can edit that page directly on Github via https://github.com/mozilla/webmaker-curriculum/blob/gh-pages/index.html

Click that pencil icon to edit the code.
<img width="359" alt="screen shot 2015-12-23 at 11 14 23 am" src="https://cloud.githubusercontent.com/assets/2896608/11983170/5c0b3a12-a966-11e5-97c4-efa8331b0f15.png">


If you want the change to appear live right away, choose "commit directly to `gh-pages` branch.
If you want someone to look over the changes you made before pushing it live, choose the other option.
<img width="1045" alt="screen shot 2015-12-23 at 11 15 43 am" src="https://cloud.githubusercontent.com/assets/2896608/11983203/a35ceb7c-a966-11e5-8736-395ce81cf2a8.png">

Let me know if I can help. :grin:
