### ISSUE TITLE
Improve Curriculum Queue github page layout and styles

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1364]
The [Curriculum Queue](http://mozilla.github.io/webmaker-curriculum/index.html) can be improved in two ways:
 - [ ] make column widths equal
 - [ ] adjust styles to better match look and feel of Teach site

**Comment by hannahkane** [comment]
@flukeout - are you going to be able to get to this this heartbeat?

**Comment by hannahkane** [comment]
@thornet - do you own this github page?

**Comment by mmmavis** [comment]
@hannahkane if it's [this page](http://mozilla.github.io/webmaker-curriculum/index.html) you are referring to, anyone with push power to https://github.com/mozilla/webmaker-curriculum should be able to update that page.

**Comment by hannahkane** [comment]
thanks, @mmmavis. @flukeout - do you have push privs for that repo? ^

**Comment by mmmavis** [comment]
@hannahkane I do.

**Comment by hannahkane** [comment]
@kristinashu - wondering if I can assign this to you? Should not take long.

**Comment by kristinashu** [comment]
Yup. @mmmavis would you be doing the dev for this? I think it just needs more space between the sections and tables should be left aligned with more space in between. Maybe I could just hover over your shoulder when you're ready to work on it and we can make a few adjustments.

**Comment by mmmavis** [comment]
@kristinashu sure we can do that on Thursday! (I'm working from home tomorrow)

**Comment by kristinashu** [comment]
Sounds good!

**Comment by kristinashu** [comment]
I hovered as @mmmavis made the styling changes. Thanks!

**Comment by mmmavis** [comment]
changes are live http://mozilla.github.io/webmaker-curriculum/ :dancer: :dancer: :dancer:

**Comment by hannahkane** [comment]
Sweet relief! Looks much better. :)
