### ISSUE TITLE
[grid] - responsive design for navigation on tablet view

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1365]
**Problems:** 
Tablet view navigation takes up too much vertical space.

**Solutions:** 
* create a navigation design for tablet view

**Seen on:** 
Navigation seen all pages of [MLN] (teach.mozilla.org) 
<img width="969" alt="screen shot 2015-10-21 at 3 48 17 pm" src="https://cloud.githubusercontent.com/assets/2492510/10652392/2ea12366-780b-11e5-88f6-6c51293db657.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
@cassiemc @sabrinang here's what I'm thinking for the revised nav https://redpen.io/p/vn7e635cfaafc2ca85

I think we should just slightly modify what we have. We could just make the logo, bar, and hamburger icon a little smaller and then animate the hamburger/close icon when it changes - like motio.no

The alternative version is just to show another option but I don't think it's worth the extra dev work.

**Comment by cassiemc** [comment]
This looks mostly good @kristinashu, might consider moving the login info to the top right, though.

**Comment by kristinashu** [comment]
Thanks @cassiemc. I've added another option with the login next to the close button, in the main nav bar.

**Comment by kristinashu** [comment]
@cassiemc @sabrinang do you have any preferences for these https://redpen.io/p/vn7e635cfaafc2ca85? I like the first option since it's close to what we have now.

**Comment by sabrinang** [comment]
I like the blue bar option so we don't have to worry what image lies behind the icon + wordmark even if the image changes/resizes for legibility purposes

**Comment by cassiemc** [comment]
@sabrinang I'm not sure what you mean? Both options have a blue bar that expands behind the navigation as the hamburger icon is tapped. 

I do prefer the second option – https://redpen.io/ab290788c0553415fc It keeps the nav bar a little bit shorter, separates the login from the main nav items, and is a more expected placement. I remember seeing feedback about that from the main site at one point (but changing it there would be a bigger shift than here on tablet). But @kristinashu I'll leave it up to you and dev to make a final call.

**Comment by sabrinang** [comment]
@cassiemc - sorry for the confusion my previous comment was referring to this design: https://redpen.io/ue76f9767e794916fe

+1 I also like separating the login from nav items

**Comment by kristinashu** [comment]
Thanks, I've opened a ticket for implementation https://github.com/mozilla/teach.mozilla.org/issues/1616
