### ISSUE TITLE
[header] - ensure language is consistent across all products

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1366]
**Problem:**
Products (ie Thimble, Webmaker, MLN, Goggles, and 'Webmaker' login screen) are currently using a mix of Sign in, Log in, Sign out, Log out, Sign up, Create an account... Also using a mix of Sentence case and Title Case.

**Solutions:**
We should unify! Everyone can give their preference and then we'll implement the most popular version.
* "Sign in" vs "Log in"
* "Sign up" vs "Create an account" 
* "Log out" vs "Sign out"
* Sentence case vs Title Case

If any has any research regarding sign in verbiage please share.

**Seen on:**
Thimble, Webmaker, MLN, Goggles, and 'Webmaker' login screen

**Related Issue:** #1260
**/CC:** @sabrinang @vazquez @flukeout @kristinashu

**Comment by kristinashu** [comment]
I prefer:
* Sign in
* Create an account
* Log out
* Sentence case

**Comment by vazquez** [comment]
I prefer:

- Sign in
- Create an account
- Log out
- Title Case (I think I'm the only MoFo designer that prefers this)

**Comment by kristinashu** [comment]
@flukeout @sabrinang any opinion?

**Comment by flukeout** [comment]
Ha, judging by my choices for Thimble...

![image](https://cloud.githubusercontent.com/assets/25212/10682388/0339ed4a-78ea-11e5-9c20-8a395e28bb0a.png)

...I prefer "Log in" (gross) and mixing sentence and title case.

**Actual preferences**
* Sign in & Sign out
* Create an account

**Comment by sabrinang** [comment]
Preferences:
- Sign in 
- Sign out
- Create an account
- Sentence case

**Comment by Pomax** [comment]
- Sign in
- Sign out
- Create an account
- Sentence case

With the booknote that "create an account" feels like the lesser of two evils, because there's no explanation of what it's an account for. If you go through thimble, you probably expect to get a Thimble account, not a "webmaker account". Similarly, "Sign up" isn't very clear about *what* you're signing up for, but feels less clear about what's going to happen than "create an account".

**Comment by kristinashu** [comment]
Thanks everyone! The winners are:
- Sign in
- Sign out
- Create an account
- Sentence case

I'll create implementation to update the working on:
- Goggles
- Teach site
- Thimble
- Webmaker

Anywhere else?
