### ISSUE TITLE
[grid] - create layout for tablet view 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1367]
**Problems:** 
Many visual elements or text are spaced poorly or too large on the viewport. Currently, it is an enlarged mobile view version.

**Solutions:** 
* Create a layout specifically for tablet view and introduce another break point
* Fix various column, alignment and button size issues

**Seen on:** all pages of [MLN] (teach.mozilla.org)
Here are some examples of elements to fix:
<img width="749" alt="screen shot 2015-10-21 at 3 49 01 pm" src="https://cloud.githubusercontent.com/assets/2492510/10652846/b1f19d88-780e-11e5-8510-bd9f68c3decc.png">
<img width="733" alt="screen shot 2015-10-21 at 4 14 05 pm" src="https://cloud.githubusercontent.com/assets/2492510/10652856/c72a9718-780e-11e5-9ed2-062c34bc532a.png">
<img width="732" alt="screen shot 2015-10-21 at 4 14 41 pm" src="https://cloud.githubusercontent.com/assets/2492510/10652924/41a5a154-780f-11e5-9144-0f70bbedac2b.png">
<img width="734" alt="screen shot 2015-10-21 at 4 15 03 pm" src="https://cloud.githubusercontent.com/assets/2492510/10652925/441fe0e8-780f-11e5-808f-dd021248772c.png">
<img width="731" alt="screen shot 2015-10-21 at 4 18 09 pm" src="https://cloud.githubusercontent.com/assets/2492510/10652936/616ac19a-780f-11e5-82ee-f93997842d30.png">

**Related Issues:** #1260 
**/CC:** @kristinashu @sabrinang

**Comment by thiagotomasi** [comment]
Hey @sabrinang, could I help with this one?

**Comment by sabrinang** [comment]
Yes @thiagotomasi you certainly can help! You can continue mocking them up as .sketch files (or if you want to try a different method let us know how we can help you).

**Comment by kristinashu** [comment]
Closing this ticket. These issues will be covered by the MoFo Unified Design ticket https://github.com/MozillaFoundation/Design/issues/174
