### ISSUE TITLE
[footer] - group and simplify footer

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1368]
**Problem:**
* broken into two sections: at the bottom of the side bar and Hive at the bottom of page content
* Hive doesn't have a proper home - needs to have it's own page
* Webmaker is now in Tools so is redundant to repeat it as a footer link

**Solutions:**
* restrict footer to the bottom of the side bar
* short-term solution is to have a Hive link in the footer while long-term solution is to add a Hive page (Wireframes for Initiatives Page #1311)
* removed Webmaker link
* make this side nav footer sticky so it is always present in viewport on desktop (see #1333)

**Seen on:**
all pages of [MLN] (teach.mozilla.org)
<img width="1220" alt="screen shot 2015-10-21 at 4 26 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/10653042/8d552696-7810-11e5-951f-01238700e6ec.png">

**Related Issue:** #1260 #1333 #1311
**/CC:** @sabrinang @kristinashu

**Comment by kristinashu** [comment]
This could be a quick fix. @hannahkane are you ok with @mmmavis removing the Hive footer section and just having Hive as a link in the side bar footer? Longer term plan is to have a dedicated Hive page #1311 

We could also remove Webmaker from the side bar footer since it is now featured on the Tools page.

Mock up of the footer side bar can be seen in the header design ticket #1370 https://redpen.io/p/jh0a4bc04ea2daf52b

cc/ @cassiemc

**Comment by hannahkane** [comment]
+1 to removing Webmaker. Want to get @chrislarry33's OK before moving Hive to footer sidebar.

**Comment by kristinashu** [comment]
@hannahkane I've opened Implement updated footer #1437 for @mmmavis to do this heartbeat? So I think we can close this one. Sound good?
