### ISSUE TITLE
[grid] - standardize layout spacing

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1369]
**Problems:** 
Margin and padding on all pages are inconsistent.

**Solutions:** 
* streamline container / page wrapper margin and padding
* streamline column spacing

**Seen on:** all pages of [MLN] (teach.mozilla.org)

<img width="455" alt="screen shot 2015-10-21 at 4 29 19 pm" src="https://cloud.githubusercontent.com/assets/2492510/10653081/eb3bf802-7810-11e5-82b0-644bc70371ac.png">

**Related Issues:** #1260 
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
@mmmavis at some point we should talk about this and figure out the easier/best way to clean this up.

**Comment by kristinashu** [comment]
The main thing for me is getting all the main content container to have the same space on the left and right side. And making sure that everything lines up. It doesn't really matter how much padding is on the left and right side, just as long as it is the same on every page.

Example:
![mozilla-learning-2016-01-25-17-03-19](https://cloud.githubusercontent.com/assets/1068783/12569714/2bc55506-c386-11e5-886c-7c73b6adf040.jpg)
- Ignore the tabzilla
- 3 buttons shouldn't be so close to the edges
- blog post list needs to move to the right

**Comment by sabrinang** [comment]
I'm iterating from the bootstrap3 grid system (referencing: http://getbootstrap.com/css/#grid) on a sketch file (while starting the web lit wireframes). I will update this ticket when I have container/columns/gutters in good shape for large to extra small devices.

**Comment by kristinashu** [comment]
Closing this ticket. These issues will be covered by the MoFo Unified Design ticket https://github.com/MozillaFoundation/Design/issues/174
