### ISSUE TITLE
[illustration] - replace all filled icons with line art

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1371]
**Problems:** 
* placeholder icons *(fontawesome)* and the pledge icon are the only illustrations that are filled and it doesn't align with the illustration aesthetic

**Solutions:** 
* replace all fontawesome placeholders with a line art icon set
* update pledge icon so it doesn't have a fill

**Seen on:** 
[Clubs page] (https://teach.mozilla.org/clubs/)
<img width="1052" alt="screen shot 2015-10-21 at 4 41 44 pm" src="https://cloud.githubusercontent.com/assets/2492510/10653259/a56262a6-7812-11e5-8db1-faadf432a020.png">
[Home page] (https://teach.mozilla.org)
<img width="349" alt="screen shot 2015-10-21 at 4 45 25 pm" src="https://cloud.githubusercontent.com/assets/2492510/10653305/26f63068-7813-11e5-882a-1e02c1f3d698.png">

**Related Issues:** #1260
**/CC:** @kristinashu  @sabrinang

**Comment by thiagotomasi** [comment]
Hi @sabrinang and @kristinashu!
Can I help with this one?

**Comment by kristinashu** [comment]
@thiagotomasi that would be great, thanks! Let us know if you have any questions.

**Comment by kristinashu** [comment]
@thiagotomasi the current clubs (https://teach.mozilla.org/clubs/) icons are from fontawesome https://fortawesome.github.io/Font-Awesome/cheatsheet/

We're trying to move away for the filled in icons and move towards a simple line icon style. For example, we're starting to use some of these http://linea.io/

Looking forward to seeing what you come up with!

**Comment by kristinashu** [comment]
Here are the updated Club icons:
![teach-club-icons-01 2x](https://cloud.githubusercontent.com/assets/1068783/11945518/91704074-a805-11e5-8dbb-6c319e35e52f.jpg)

Updated Pledge icon:
<img width="353" alt="screen shot 2015-12-21 at 5 06 50 pm" src="https://cloud.githubusercontent.com/assets/1068783/11945529/a33907dc-a805-11e5-8363-e6d34a31cdae.png">

Opened implementation ticket here https://github.com/mozilla/teach.mozilla.org/issues/1508
