### ISSUE TITLE
[pre-footer] - unify all icon links above the footer

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1372]
**Problems:** 
Icons have different strokes widths and all the different colours are difficult to manage/maintain.

**Solutions:**
* Make sure they all have the same stroke width
* Pick a colour or a limited colour palette - could use site CTA colour (yellow or blue)

**Seen on:**
all pages of [MLN] (teach.mozilla.org)
<img width="366" alt="screen shot 2015-10-21 at 4 42 43 pm" src="https://cloud.githubusercontent.com/assets/1068783/10653331/6984d07e-7813-11e5-8271-3f51e5dd691e.png">

**Related Issue:** #1260
**/CC:** @sabrinang @kristinashu

**Comment by kristinashu** [comment]
Create icons based on design in #1414 and build #1434

Comp is here: https://redpen.io/p/cnca8a0265383acc93

Need to:
- make these icons yellow on every page
- reduce the size of the icons
- use 1px stroke

**Comment by kristinashu** [comment]
Here's a JPG showing all the current 3-up bottom icons and then the proposed icons below each set:
https://redpen.io/p/brdabe854cc619f9b9

Update:
* all icons are yellow (so they are consistent with CTA button colour)
* reduced the size of the icons
* use 1px stroke
* added blue link text to reinforce that it is a link

@sabrinang @hannahkane @cassiemc Let me know if any of you think we should change any of the copy or icons.

**Comment by cassiemc** [comment]
Looks good @kristinashu. Suggested a couple tweaks, nothing blocking.

**Comment by hannahkane** [comment]
Icons are lovely. Added copy suggestions.

**Comment by kristinashu** [comment]
Thanks! I've updated redpen https://redpen.io/p/brdabe854cc619f9b9

I still need to export all the SVGs for dev.

**Comment by kristinashu** [comment]
@cassiemc @sabrinang I think we could make the link icons the same blue as the text links (solves the issues of yellow not being visible enough and also ties the icon and the text together). I added a screen showing an example of this and also a possible hover state - icon zooms and all the text turns blue.

https://redpen.io/p/brdabe854cc619f9b9

**Comment by cassiemc** [comment]
good thinking! not sold on the hover states but would be easier to assess in a demo.

**Comment by kristinashu** [comment]
@cassiemc I've mocked up another option "Teach Icons - Multi Colored" https://redpen.io/p/brdabe854cc619f9b9

In this version, the icons are the color of the section (same as on the live site) which I like because it's nice and playful. The down side is it is less streamlined for updates. But Then we treat the link just like regular links on the site - icons aren't links and only the text link are links (like any other text link on the site). This way, we can have multiple links like for "We're @mozteach on Twitter and our community uses #teachtheweb". We just need to make sure the copy has a link, which so far they all do.

Thoughts?

**Comment by cassiemc** [comment]
@kristinashu Colour is good, streamlining link colour is also good. I'm less sold on just the text being clickable. The whole image+text area is really referring to the same CTA, and I think it'd help usability if the image was clickable as well as the text (particularly for mobile). That said, we don't necessarily have to implement a hover state for the images at this point, just ensure that they're clickable. (However, we *could* suggest css animations, maybe a single one as opposed to something that was specific to the shape, so that it was reusable across sections)

**Comment by kristinashu** [comment]
Thanks! Created implementation ticket and closing this one!
