### ISSUE TITLE
[illustration] - create a cohesive line art aesthetic

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1373]
**Problems:** 
* various inconsistencies in the line art aesthetic
* some small fills are present
* various line ends *(rounded, straight, tapered etc.)*
* various corner styles *(rounded, sharp etc.)*

**Solutions:** 
* update line art with unified stroke widths 
* remove any fills *(decide if small fills should be present)*
* unify corner styles *(rounded, sharp etc.)*
* document how to create unified line art

**Seen on:** all pages of [MLN] (teach.mozilla.org)

<img width="683" alt="screen shot 2015-10-21 at 5 04 07 pm" src="https://cloud.githubusercontent.com/assets/2492510/10653648/5c7fa590-7816-11e5-9b79-b1d761b8942f.png">
<img width="621" alt="screen shot 2015-10-21 at 5 03 49 pm" src="https://cloud.githubusercontent.com/assets/2492510/10653649/5dc76f8c-7816-11e5-85de-3737487e0687.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Footer icons are in https://github.com/mozilla/teach.mozilla.org/issues/1372

Circle icons svgs are here: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLYkJRSUhfVEg1c1E&usp=sharing

<img width="670" alt="screen shot 2015-12-15 at 9 15 41 am" src="https://cloud.githubusercontent.com/assets/1068783/11818015/bbc1dfde-a30c-11e5-94b6-2e46779ca34f.png">

- circle icons have 2px stroke and are 200px wide
- no fills
- corners are square
