### ISSUE TITLE
[illustration] - line art for clubs page

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1374]
**Problems:** 
* clubs page is the only page that doesn't have a line art illustration (for the description section)
* it has a photo as a placeholder

**Solutions:** 
* create line art for the clubs page
* another option is to consider switching the line art near the middle of the page to be featured on the description section instead and use a photo for that section

**Seen on:** [Clubs page] (https://teach.mozilla.org/clubs/)
<img width="1062" alt="screen shot 2015-10-21 at 5 35 03 pm" src="https://cloud.githubusercontent.com/assets/2492510/10654030/1830025a-781a-11e5-90e4-1cce24862242.png">
<img width="1048" alt="screen shot 2015-10-21 at 5 35 22 pm" src="https://cloud.githubusercontent.com/assets/2492510/10654035/2726183a-781a-11e5-8798-7a0f4d97db1f.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Will be fixed in https://github.com/mozilla/teach.mozilla.org/issues/1489
