### ISSUE TITLE
[illustration] - line art colour

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1375]
**Problems:** 
Currently, we have unique colour icons for every page and isn't the most efficient to produce or scale. 

**Solutions:** 
* streamline colours to 1 colour or multicolour
* consider colour to be adjusted in CSS

**Seen on:** all pages of [MLN] (teach.mozilla.org)
<img width="1187" alt="screen shot 2015-10-22 at 9 27 55 am" src="https://cloud.githubusercontent.com/assets/2492510/10671411/4250ae06-789f-11e5-8089-028555561ee0.png">
multi-colour fill example
<img width="938" alt="screen shot 2015-10-22 at 9 31 56 am" src="https://cloud.githubusercontent.com/assets/2492510/10671512/c7eba340-789f-11e5-883a-ed450c0add9e.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Fixing in https://github.com/mozilla/teach.mozilla.org/issues/1372
