### ISSUE TITLE
[visual element] - unify dividers and lines style

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1377]
**Problems:** 
* lines and dividers have inconsistent styles

**Solutions:** 
* streamline opacity, colour, weight
* decide on line details *(ball ends, diamond centres etc.)*
* consistent line ends *(straight, rounded, tapered etc.)*

**Seen on:** all pages of [MLN] (teach.mozilla.org)
<img width="639" alt="screen shot 2015-10-22 at 9 42 02 am" src="https://cloud.githubusercontent.com/assets/2492510/10671738/2dab4de2-78a1-11e5-9e74-a6e6b8a470c1.png">

[Homepage](https://teach.mozilla.org/)
<img width="1426" alt="screen shot 2015-10-22 at 9 45 37 am" src="https://cloud.githubusercontent.com/assets/2492510/10671846/bbee7ad4-78a1-11e5-94db-6d5eabe20bbc.png">

[Clubs Page](https://teach.mozilla.org/clubs/)
<img width="1425" alt="screen shot 2015-10-22 at 9 45 19 am" src="https://cloud.githubusercontent.com/assets/2492510/10671850/c00e0954-78a1-11e5-81af-0159420d962b.png">
[Clubs List](https://teach.mozilla.org/clubs/list/)
<img width="1427" alt="screen shot 2015-10-22 at 9 44 16 am" src="https://cloud.githubusercontent.com/assets/2492510/10671856/c4e8f8b2-78a1-11e5-9e94-eb168dba12b6.png">

[Tools Page](https://teach.mozilla.org/tools/)
<img width="1425" alt="screen shot 2015-10-22 at 9 44 47 am" src="https://cloud.githubusercontent.com/assets/2492510/10671863/ca9e2df4-78a1-11e5-9070-1793e98fb4ec.png">

[Teach like Mozilla Page](https://teach.mozilla.org/teach-like-mozilla/)
<img width="1426" alt="screen shot 2015-10-22 at 9 45 07 am" src="https://cloud.githubusercontent.com/assets/2492510/10671865/cbf39a7c-78a1-11e5-8a08-9be54aede6e0.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
@sabrinang mavis just fixed all of these in https://github.com/mozilla/teach.mozilla.org/issues/1447#issuecomment-164591560 So I think we can close this one!

**Comment by sabrinang** [comment]
checked it out on staging and dividers and lines are looking good - closing!
