### ISSUE TITLE
[visual element] - create dividers and lines in CSS

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1379]
**Problems:** 
* inconsistent implementation method *(some lines are .pngs or made in CSS)*

**Solutions:** 
* make all lines in CSS

**Seen on:** see issue #1377
**Related Issues:** #1377 #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
@sabrinang mavis just did this in https://github.com/mozilla/teach.mozilla.org/issues/1447
