### ISSUE TITLE
[brand] - remove all instances of the old webmaker brand

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1383]
**Problems:** 
Outdated and obsolete usage of Webmaker logo.

**Solutions:** 
Remove or replace logo.

**Seen on:** 
[Sign in] (https://id.webmaker.org/login?client_id=wm_id_YX9X9DqK4d4fB9LuFbZy&response_type=code&state=iocNCJo0xpPubmdETvqKYj0HwTVuhRfD&scopes=user%20email)
<img width="1424" alt="screen shot 2015-10-22 at 10 33 42 am" src="https://cloud.githubusercontent.com/assets/1068783/10673099/da501f44-78a8-11e5-88f6-36db94e3b850.png">

[Activities] (http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-kraken.html) - will be covered by #1319
<img width="1407" alt="screen shot 2015-10-22 at 10 33 51 am" src="https://cloud.githubusercontent.com/assets/1068783/10673125/00000420-78a9-11e5-9af5-3393b7471e7d.png">

[Blog] (https://blog.webmaker.org/reflecting-on-recent-accomplishments)
<img width="1432" alt="screen shot 2015-10-22 at 10 34 26 am" src="https://cloud.githubusercontent.com/assets/1068783/10673115/ede3adb4-78a8-11e5-918e-7f3ab6c37476.png">

**Related Issues:** #1260 #1319
**/CC:** @kristinashu @sabrinang

**Comment by sabrinang** [comment]
We can remove the webmaker branding from these pages:
![remove-webmaker-branding](https://cloud.githubusercontent.com/assets/2492510/11909586/6564fb1a-a59d-11e5-979c-93d6c70dbd12.png)

These are mainly teaching kits.

**Comment by mmmavis** [comment]
@hannahkane can we move this to the next heartbeat? This will involve changes to many websites and I'm hesitant to update multiple sites 2 days before the holiday break.

**Comment by hannahkane** [comment]
Sure. Done.

**Comment by mmmavis** [comment]
- [ ] http://blog.webmaker.org/
- [ ] https://id.webmaker.org
- [ ] http://mozilla.github.io/webmaker-curriculum pages

**Comment by mmmavis** [comment]
@sabrinang 

should I remove Webmaker logo from ALL pages on http://mozilla.github.io/webmaker-curriculum (there are around 32 pages in total)? Or just the ones that are linked from https://teach.mozilla.org/activities/ (kits captured in your screencap)?

**Comment by sabrinang** [comment]
@mmmavis Please remove all old webmaker logo branding from the upcoming curriculum queue as well - I forgot about those!

**Comment by mmmavis** [comment]
@sabrinang no worries. will do!

One more question - 

Do we want to remove the Webmaker logo off of 
- https://id.webmaker.org/ entirely  
- Or just the "page" that is used as Teach site login?

**Comment by hannahkane** [comment]
Might need @simonwex, @HPaulJohnson, @xmatthewx or @cassiemc to weigh in on whether to remove or replace on id.webmaker.org.

**Comment by cassiemc** [comment]
I would replace it on id.webmaker.org with the new webmaker logo, and remove it from the teach site login.

**Comment by mmmavis** [comment]
- Ticket for updating Webmaker logo on id.webmaker.org has already been filed here: https://github.com/mozilla/id.webmaker.org/issues/405
- I'll file a separate issue on id.webmaker.org for removing it from Teach site login.

**Comment by mmmavis** [comment]
- [x] http://blog.webmaker.org/
- [ ] teach site login pages on id.webmaker.org (ticket filed: mozilla/id.webmaker.org#407)
- [x] http://mozilla.github.io/webmaker-curriculum pages

**Comment by hannahkane** [comment]
I'm going to close this ticket since everything within it is accounted for in other tickets.
