### ISSUE TITLE
[interface element] - arrows icons

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1385]
**Problems:** 
There are various style of arrows present throughout the site and it isn't consistent visually.

**Solutions:** 
* use a consistent style of arrows and variations of use
* decide on colour and icon *(fontawesome)*
* consider any animations for arrows

**Seen on:** 
[Homepage] (teach.mozilla.org)
<img width="1425" alt="screen shot 2015-10-22 at 10 52 20 am" src="https://cloud.githubusercontent.com/assets/2492510/10673543/474e5f6e-78ab-11e5-84ed-1ae32a8ad3de.png">
<img width="1425" alt="screen shot 2015-10-22 at 10 51 46 am" src="https://cloud.githubusercontent.com/assets/2492510/10673539/40c884e4-78ab-11e5-819f-ffde091cb43e.png">
<img width="1425" alt="screen shot 2015-10-22 at 10 52 06 am" src="https://cloud.githubusercontent.com/assets/2492510/10673541/4512915c-78ab-11e5-8c83-c7c3cb9207a0.png">
[Event Resources] (https://teach.mozilla.org/events/resources/)
<img width="1425" alt="screen shot 2015-10-22 at 10 52 56 am" src="https://cloud.githubusercontent.com/assets/2492510/10673545/496612a6-78ab-11e5-8e39-ce31b6957bd9.png">
[Web Literacy] (https://teach.mozilla.org/teach-like-mozilla/web-literacy/)
<img width="1425" alt="screen shot 2015-10-22 at 10 53 47 am" src="https://cloud.githubusercontent.com/assets/2492510/10673548/4b23be5e-78ab-11e5-9eb2-651073b7f28d.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Most of the arrows no longer apply so we can close this ticket. 
- Arrows are no longer in the nav
- home page link arrows are being removed in https://github.com/mozilla/teach.mozilla.org/issues/1391
- Web Lit map is currently being updated
