### ISSUE TITLE
[colours] - colour palette

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1386]
**Problems:** 
Unsure of what our current colour palette aligns with and how to go about creating new colours when needed.

**Solutions:** 
Evaluate shades to be more cohesive and create a palette. 

**Seen on:** 
all pages of [MLN] (teach.mozilla.org)
<img width="472" alt="screen shot 2015-10-22 at 10 57 12 am" src="https://cloud.githubusercontent.com/assets/1068783/10673626/ae723c7e-78ab-11e5-998f-27114972699e.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by Pomax** [comment]
If we can defined these in terms of the base colours we want to use, and their permitted variants in terms of lightness/saturation adjustments, we can update the LESS to use only those, with a lighter() and lightest() mixin to ensure we only ever use the "right" colours.

**Comment by cassiemc** [comment]
Excellent thanks for that insight @Pomax

**Comment by sabrinang** [comment]
An iteration to compare @kristinashu 's colour recommendations / teach existing colours with the mozilla unified palette colours that matched it the closest to consider on redpen: https://redpen.io/fq9f2be8480a18d520

**Comment by cassiemc** [comment]
@sabrinang My head might just be filled with mucus but it's hard to know what I'm looking at here. Could you do a side-by-side two column comparison of each site? The approach is really helpful!

**Comment by kristinashu** [comment]
I think we should stick with the colours we have but update the shade so they are used more consistently (if Mozilla udpates it's colour palette and we have to align, then we can update):

<img width="852" alt="screen shot 2016-02-02 at 1 19 27 pm" src="https://cloud.githubusercontent.com/assets/1068783/12764618/b1b0795a-c9af-11e5-8e10-029fb60c73e9.png">

**Comment by sabrinang** [comment]
note: add 70% shade to in the palette (it is another opacity commonly used)

**Comment by cassiemc** [comment]
@kristinashu @sabrinang I'd like to see the closest equivalent shades still, to know what kind of difference this would make should we choose to align the teach palette with the moz palette. I agree that it's been nice having the flexibility to work with our own palettes, but in light of better/faster we may want to align more closely with the moz palette. I am speaking with Tim Murray on Friday and can update you guys then.

**Comment by kristinashu** [comment]
@cassiemc I think this is what @sabrinang is showing in the redpen link https://redpen.io/p/rx1ad484efc903dc60 - the bottom two palettes are moz colour options.

Good to hear you'll be speaking with Tim.

**Comment by cassiemc** [comment]
Let's go through it today then @sabrinang as I didn't understand the diagram. :)

**Comment by sabrinang** [comment]
I updated the https://redpen.io/fq9f2be8480a18d520 diagram to be more clear - let's chat over crit

**Comment by kristinashu** [comment]
Our plan is to simplify the palette in http://blog.seanmartell.com/2014/09/17/mozilla-id-project-palette-explorations/ and then update teach colors to that simplified palette. 

We don't necessarily need to align with the current teach sections colors (ie if the new pink isn't working then we could use a different color from the new palette - for example orange). 

However, with the latest mofo design audit there is talk of streamlining properties which would mean remove the side nav and go with a top horizontal nav - which would solve the side nav section color issues.

@cassiemc I think we're blocked on this one by the need for a mofo wide color palette?

**Comment by cassiemc** [comment]
I don't see the side nav issue being resolved for some time (thinking a couple months, maybe, if we decide to prioritize it at all). Re. colour – yes, that's the plan! I just filed https://github.com/MozillaFoundation/Design/issues/139 which we can tackle in the next heartbeat.

**Comment by kristinashu** [comment]
This is no longer blocked. We have v1 of a unified color palette https://redpen.io/aq798f74c9a3ad7266

**Comment by kristinashu** [comment]
Closing this ticket since colors will be covered by the Unified MoFo Design ticket https://github.com/MozillaFoundation/Design/issues/173
