### ISSUE TITLE
[colours] - use colours consistently

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1387]
**Problems:** 
Too many colours are being used and does not look consistent. 

**Solutions:** 
Document inconsistent usage (ensure only the three shades of a colour are used).

**Seen on:** 
all pages of [MLN] (teach.mozilla.org)
<img width="472" alt="screen shot 2015-10-22 at 10 57 12 am" src="https://cloud.githubusercontent.com/assets/1068783/10673626/ae723c7e-78ab-11e5-998f-27114972699e.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by Pomax** [comment]
If we can defined these in terms of the base colours we want to use, and their permitted variants in terms of lightness/saturation adjustments, we can update the LESS to use only those, with a `lighter()` and `lightest()` mixin to ensure we only ever use the "right" colours.

**Comment by kristinashu** [comment]
Colours we are going to use will be decided in https://github.com/mozilla/teach.mozilla.org/issues/1386 and https://redpen.io/p/rx1ad484efc903dc60

This ticket focuses on how we should use the colours consistently. Here are the changes I think we should make (when I say "#pagecolour" I mean the main colour for that section).

![teach-colours-01 2x](https://cloud.githubusercontent.com/assets/1068783/12764280/a4be2b72-c9ad-11e5-8a08-9b2f8cb6a46f.jpg)

@sabrinang any thoughts?

**Comment by sabrinang** [comment]
It is looking good! We can add 70% shade to in the palette (seen in ticket #1386) if we're using it in a few places just to document popular opacities used.

One thing to consider may be to keep the status messages/notices yellow but aligning it better - I feel the grey might feel a bit dark in comparison but I guess it depends on what context it will be used in.
<img width="1409" alt="screen shot 2016-02-02 at 1 41 45 pm" src="https://cloud.githubusercontent.com/assets/2492510/12765334/15347848-c9b3-11e5-970b-d53ac54f5d53.png">

**Comment by kristinashu** [comment]
Nice, I like the yellow background with the grey text. 

I think 70% will be useful (it's the colour behind the Mozilla logo side nav on production site). I think I mixed up my percentages in the illustrator file, wrote 30% but the colour was actually 70%).

**Comment by kristinashu** [comment]
Updated warning note and made the date circles (blog date circle on home page and the maker party resource circle) more consistent with each other:
![teach-colours-02 2x](https://cloud.githubusercontent.com/assets/1068783/12996609/325d2e26-d0e6-11e5-9b94-50d4c001bbad.jpg)

**Comment by kristinashu** [comment]
Closing this ticket since colors and their applications will be covered by the Unified MoFo Design ticket https://github.com/MozillaFoundation/Design/issues/173
