### ISSUE TITLE
[interface element] - labels

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1389]
**Problems:** 
Labels have inconsistent spacing, corners and typography.

**Solutions:** 
* unify corner radius
* use cohesive space margin and padding
* use cohesive typography *(all caps)* 
* colour

**Seen on:** 
[Teaching Activities](https://teach.mozilla.org/activities/)
<img width="1426" alt="screen shot 2015-10-22 at 11 10 45 am" src="https://cloud.githubusercontent.com/assets/2492510/10674016/a37ffe6c-78ad-11e5-8db3-cb2ef157804f.png">
[Maker Party](https://teach.mozilla.org/events/)
<img width="1425" alt="screen shot 2015-10-22 at 11 10 59 am" src="https://cloud.githubusercontent.com/assets/2492510/10674019/a4e0dd62-78ad-11e5-941a-4f29a8352873.png">
[Tools](https://teach.mozilla.org/tools/)
<img width="1426" alt="screen shot 2015-10-22 at 11 11 09 am" src="https://cloud.githubusercontent.com/assets/2492510/10674021/a64fe0f8-78ad-11e5-9eac-9068bd3f7a28.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Lets just update Tools to have uppercase so it matches the others.

**Comment by mmmavis** [comment]
updates:
@sabrinang @kristinashu and I decided to not use all caps for these label text. e.g., "Sample Activity" will stay as what it is and "HOSTED BY" would be "Hosted by" instead.
