### ISSUE TITLE
[typography] - consistent font sizing

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1390]
**Problems:** 
There are a lot of different font sizes, leading, and weights. This makes the site look messy.

**Solutions:** 
Streamline number of font styles. Create a sketch file with all the necessary font sizes (body, h1, h2, h3...). Ex if we have body text that is 11px, 12px, 14px lets just chose one size. Also address when to when to bold, when to italics... 

**Seen on:** 
all pages of [MLN] (teach.mozilla.org)

<img width="1068" alt="screen shot 2015-10-22 at 11 07 15 am" src="https://cloud.githubusercontent.com/assets/1068783/10673970/591ac456-78ad-11e5-9409-c53ddf1e955d.png">
<img width="1070" alt="screen shot 2015-10-22 at 11 07 41 am" src="https://cloud.githubusercontent.com/assets/1068783/10673967/59138bfa-78ad-11e5-9cf4-0c74bcb83f92.png">
<img width="1066" alt="screen shot 2015-10-22 at 11 07 53 am" src="https://cloud.githubusercontent.com/assets/1068783/10673969/59177b48-78ad-11e5-989a-a764240a178a.png">
<img width="1075" alt="screen shot 2015-10-22 at 11 08 05 am" src="https://cloud.githubusercontent.com/assets/1068783/10673968/5916ea98-78ad-11e5-8ed9-8d8a47e43c53.png">
<img width="1070" alt="screen shot 2015-10-22 at 11 08 22 am" src="https://cloud.githubusercontent.com/assets/1068783/10673966/5912645a-78ad-11e5-937a-8cf72672007f.png">
<img width="474" alt="screen shot 2015-10-22 at 11 52 55 am" src="https://cloud.githubusercontent.com/assets/1068783/10675160/7b75b4b0-78b3-11e5-9017-aadce86d3884.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
This will also include updating the site to Fira instead of open sans to align with the rest of Mozilla's sites.

**Comment by thiagotomasi** [comment]
Hey @kristinashu, could I help with this one?

**Comment by kristinashu** [comment]
Thank you @thiagotomasi! It would be great if you could help out with this. Any ideas on how you want to go about it? You could test out different font styles in sketch or if you're comfortable using developer tools you could test them out right in the browser. Whatever works for you.

**Comment by kristinashu** [comment]
Closing this since it will be covered by the MoFo Unified Design ticket https://github.com/MozillaFoundation/Design/issues/172
