### ISSUE TITLE
[interface element] - modals

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1392]
**Problems:** 
Inconsistent pop-up modals styles.

**Solutions:** 
* streamline modal sizes (padding, margin)
* streamline typography *(heading, form field text, notifications, error, confirm etc.)*
* streamline form field UI *(fields, labels, drop downs, check boxes,)*
* streamline closing button corner, button for social
* streamline and style error messages 

**Seen on:** 
[Homepage] (teach.mozilla.org) & [Clubs Page](https://teach.mozilla.org/clubs/)
<img width="1119" alt="screen shot 2015-10-22 at 11 46 28 am" src="https://cloud.githubusercontent.com/assets/2492510/10674970/951859e6-78b2-11e5-8d90-50c1e80f368f.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by thiagotomasi** [comment]
Hi @sabrinang,
I really want to help, can I do this one?

**Comment by sabrinang** [comment]
Hey @thiagotomasi - Yes, that would be great! 

On the site, https://teach.mozilla.org/, this is the latest style of modal we have to reference:
<img width="1423" alt="screen shot 2016-01-19 at 4 57 51 pm" src="https://cloud.githubusercontent.com/assets/2492510/12436888/df48c1fc-becd-11e5-84ec-fe60b76eeedf.png">

**Comment by thiagotomasi** [comment]
Hey @sabrinang,
Please take a look in this examples, and if everything are ok I can upload the Sketch file :smile:

One question, do you guys have icons to all of those modals?

![pledge to teach - mockup](https://cloud.githubusercontent.com/assets/4387026/12598413/5c26bb54-c471-11e5-929e-0642ac46163a.png)
![thanks for your pledge - mockup](https://cloud.githubusercontent.com/assets/4387026/12598414/5c2c1c52-c471-11e5-826f-d3deecb76837.png)
![get matched with a regional coordinator - cr eate - mockup](https://cloud.githubusercontent.com/assets/4387026/12598415/5c2c8a48-c471-11e5-9e99-5e9ace08ec84.png)
![get matched with a regional coordinator - login - mockup](https://cloud.githubusercontent.com/assets/4387026/12598416/5c31e556-c471-11e5-9350-d4708ef78e41.png)

**Comment by sabrinang** [comment]
Hi @thiagotomasi

Your revisions are looking great! The type styles, buttons and form layout are looking unified. Also, nice job on the last modal with the “don’t have an account yet?” bar treatment to the bottom which allows the form layout to maintain its hierarchy to match its other states. 

The only thing I’d consider to adjust is aligning the “apply” and “log-in” buttons to the centre since the previous modals have them there.

Other than the main line art .svg (which you included in your mockups), the other icons used are downloaded from the icon font [Font Awesome](http://fontawesome.io/) which it looks liked you used. Let me know if you meant something else.

Thanks for moving this issue along! After making the adjustment, feel free to upload the .sketch file and we will pass it on to development so the updates can be made :+1:

**Comment by thiagotomasi** [comment]
@sabrinang, thanks very much!

About the icons, I'm really sorry I believe I haven't been clear, I was talking about the icon title! :smile:
But I think it's is ok, since it's just a style guide for all modals!

About the alignment, I totally agree with you, but what do you think if we align every button at the left?

![pledge to teach - mockup](https://cloud.githubusercontent.com/assets/4387026/12611168/879d8752-c4d2-11e5-9a5f-d74be0992a1c.png)

BTW here is my file with the 2 options: [.sketch](https://github.com/mozilla/teach.mozilla.org/files/106432/Mozilla.-.interface.element.-.modals.zip)

**Comment by sabrinang** [comment]
Thanks @thiagotomasi for both mockups on the .sketch file! 

Seeing them next to each other, the centered buttons feel more balanced in the small modal space and the "forgot your password?" line could go beneath the button extending the modal taller a bit for space. At this moment we do not have icons to all the modals (just the pledge to teach icon). The text may change for "get matched with a regional coordinator" to just "apply to be a club captain" in the near future. It looks really balanced with an icon consistently there so what you have in your mockups can be a placeholder for now and can file another ticket when we're ready for an icon.

Great work Thiago :ok_hand: I'm going to assign @mmmavis as she will be implementing these design updates to the teach.mozilla.org site.

**Comment by sabrinang** [comment]
Will figure out resourcing for design updates next heartbeat (which starts next week) - unassigned for now

**Comment by kristinashu** [comment]
Closing this ticket. These issues will be covered by the MoFo Unified Design ticket https://github.com/MozillaFoundation/Design/issues/175
