### ISSUE TITLE
[interface element] - promotional banner on homepage

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1394]
**Problems:** 
Standardize visuals and content for promotional banner on the homepage so it doesn't interfere with main MLN content.

**Solutions:** 
* document how logos are used *(colour, size)*
* document the layout of promotional banners *(image, text length, CTA, responsive)*
* document button style
* document background options *(colours, patterns, transparency)*

**Seen on:** [Homepage] (teach.mozilla.org)
Thimble example
<img width="1425" alt="screen shot 2015-10-22 at 11 52 44 am" src="https://cloud.githubusercontent.com/assets/2492510/10675155/7480b664-78b3-11e5-94f0-b484680d52e3.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Moved to next heartbeat. Lets work on this at the same time as https://github.com/mozilla/teach.mozilla.org/issues/1535

**Comment by kristinashu** [comment]
Banner should not be too overpowering or distracting from the rest of the home page content and CTAs. To do this the banner should:
- have a neutral background colour 
- text should use teach font styles 
- links should be text (buttons should not be used but if a button must be used then it should be teach style button and colours)
- graphic for the campaign can use the campaign colors (full color logo or vector artwork)
- banner height should be minimal (less than 300px high).

Example: Encryption campaign 
![2x-02](https://cloud.githubusercontent.com/assets/1068783/12829652/1f3626c8-cb40-11e5-83cc-960ccd8a3c54.jpg)

**Comment by cassiemc** [comment]
@kristinashu This is good stuff. Are these guidelines documented on the google drive somewhere?

**Comment by kristinashu** [comment]
There's a folder in the Teach drive called "Teach-HomePromoBanner" which has the illustrator file: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLNnlXQmdFSjI1UmM/view?usp=sharing
I've added the guidelines next to the artboard within that illustrator file.

**Comment by cassiemc** [comment]
Perfect. Thanks @kristinashu
