### ISSUE TITLE
[interactive element] - transitions, states and animations

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1395]
**Problems:** 
Standardize transitions between pages and content or introduce some so it is less jarring experience.

**Solutions:** 
* streamline transitions
* streamline hover, click and visited states
* introduce some playful animations on the site that may improve how we communicate information

**Seen on:** all pages of [MLN] (teach.mozilla.org)

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Closing this ticket. This is a general need on most MoFo sites and will be covered in the MoFo Unified Design tickets.
