### ISSUE TITLE
[photography] - layout alternative for large banner images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1396]
**Problems:** 
Banner images take up a lot of real estate and Tools page is the only page without a banner image which is inconsistent (credentials will be different as well). 

**Solutions:** 
We could reduce the height of the banner or find another alternative.

**Seen on:** all pages of [MLN] (teach.mozilla.org)
<img width="811" alt="screen shot 2015-10-22 at 9 48 47 am" src="https://cloud.githubusercontent.com/assets/1068783/10672020/75f971fe-78a2-11e5-8cfd-cca14f6b6e59.png">
<img width="1417" alt="screen shot 2015-10-22 at 4 55 24 pm" src="https://cloud.githubusercontent.com/assets/1068783/10681458/4a20cf78-78de-11e5-8122-6b91a51d4d78.png">

**Related Issues:** #1260
**/CC:** @kristinashu @sabrinang

**Comment by kristinashu** [comment]
Need to prep images based on design in https://github.com/mozilla/teach.mozilla.org/issues/1414 and build https://github.com/mozilla/teach.mozilla.org/issues/1434

Comp is here: https://redpen.io/p/cnca8a0265383acc93

Need to:
- crop images to reduced the vertical height
- update dark overlay to be consistent on all images
- add image to tools page
- update home image - possibly to one mentioned in research report (https://www.flickr.com/photos/laura_nk/16249739479/in/album-72157650633495175/)

**Comment by kristinashu** [comment]
@sabrinang @cassiemc @hannahkane I've cropped a bunch of images for the shorter banners. Some are existing image and some are suggestions so let me know which ones you think will work best https://redpen.io/p/jna5c03b0eabf90217

**Comment by hannahkane** [comment]
Thanks, @kristinashu. Added my comments.

**Comment by kristinashu** [comment]
Ok thanks! I've updated redpen https://redpen.io/p/jna5c03b0eabf90217
and exported all the images for dev https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLeWUzN2FGZjU5Nms&usp=sharing

**Comment by hannahkane** [comment]
w00t. We don't already have a ticket for implementation, right? If not, I'll create one so we can close this.

**Comment by kristinashu** [comment]
Nope, don't think we have one yet. Thanks!
