### ISSUE TITLE
Add "Help us translate" CTA on Web Lit Basics I 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1411]
We just kicked off our mini-campaign to try to localize the Web Literacy Basics I module into 5+ languages by mid-Dec. 

Can we add a "Help us translate" CTA at https://teach.mozilla.org/activities/web-lit-basics/ that links to the blog post here: https://blog.webmaker.org/help-us-get-local-with-web-literacy

**Comment by hannahkane** [comment]
@kristinashu or @sabrinang - do either of you have time to mock-up what this CTA might look like? I don't think we have a style yet for this kind of thing.

**Comment by kristinashu** [comment]
I'll check in with @sabrinang but yes, I can mock it up.

**Comment by kristinashu** [comment]
Here are a couple options: https://redpen.io/p/dg7c71782aa6c22167

I don't want to create any new styles so I've pulled elements from https://teach.mozilla.org/clubs/

Option 1: CTA is at the top and uses a yellow feature box.
Option 2: CTA is at the bottom and uses vertical line element and yellow CTA button.

Let me know which one any of you prefer and what the copy should say, I think we should give some context before linking out.

**Comment by hannahkane** [comment]
Nice! Thanks, @kristinashu.

I'd say we should A/B test, but I think it might take awhile to get a statistically significant sample, and IIRC, this is a relatively short campaign. If I were going to pick, I'd guess Option 1 would get more eyes on it.

I actually think the copy you have is perfect. 

@ldecoursy - your thoughts?

**Comment by ldecoursy** [comment]
+1 looks great to me - thank you!

**Comment by kristinashu** [comment]
Great, I'll close this ticket and open the implementation ticket #1416
