### ISSUE TITLE
Summarize key points from analytics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1412]
Now that I have access to our analytics I'll choose a few key points to highlight and we can discuss recommendations based on that info.

**Comment by kristinashu** [comment]
<img width="267" alt="screen shot 2015-11-16 at 9 18 28 am" src="https://cloud.githubusercontent.com/assets/1068783/11191489/61ae37cc-8c50-11e5-934b-78d6f9fd6477.png">
<img width="809" alt="screen shot 2015-11-16 at 9 22 16 am" src="https://cloud.githubusercontent.com/assets/1068783/11191491/61b03c3e-8c50-11e5-8c1c-a2e6ab1aa84d.png">
<img width="813" alt="screen shot 2015-11-16 at 9 22 45 am" src="https://cloud.githubusercontent.com/assets/1068783/11191490/61aff094-8c50-11e5-85f9-833587e0245c.png">
<img width="810" alt="screen shot 2015-11-16 at 9 22 51 am" src="https://cloud.githubusercontent.com/assets/1068783/11191493/61b17086-8c50-11e5-829b-9582b739e5dd.png">
<img width="809" alt="screen shot 2015-11-16 at 9 23 05 am" src="https://cloud.githubusercontent.com/assets/1068783/11191492/61b11dde-8c50-11e5-827f-5118e39f437e.png">
<img width="816" alt="screen shot 2015-11-16 at 9 23 18 am" src="https://cloud.githubusercontent.com/assets/1068783/11191488/61adfda2-8c50-11e5-8ebf-49f6dcf76778.png">
<img width="783" alt="screen shot 2015-11-16 at 9 24 32 am" src="https://cloud.githubusercontent.com/assets/1068783/11191494/61c032ba-8c50-11e5-9c92-4bc4ace9c057.png">
<img width="789" alt="screen shot 2015-11-16 at 9 24 51 am" src="https://cloud.githubusercontent.com/assets/1068783/11191496/61c3cc9a-8c50-11e5-9557-1522f66b1862.png">
<img width="364" alt="screen shot 2015-11-16 at 9 25 31 am" src="https://cloud.githubusercontent.com/assets/1068783/11191495/61c25ac2-8c50-11e5-8301-74152c9b67f9.png">
<img width="365" alt="screen shot 2015-11-16 at 9 34 17 am" src="https://cloud.githubusercontent.com/assets/1068783/11191497/61c3d32a-8c50-11e5-9b4f-d85001358ab6.png">
<img width="763" alt="screen shot 2015-11-16 at 9 35 45 am" src="https://cloud.githubusercontent.com/assets/1068783/11191498/61c4fbba-8c50-11e5-8900-cb56f3395607.png">
<img width="1070" alt="screen shot 2015-11-16 at 9 37 02 am" src="https://cloud.githubusercontent.com/assets/1068783/11191499/61c5bfd2-8c50-11e5-9c25-fa5a4ab10cd9.png">
![screencapture-teach-mozilla-org-1447696045025](https://cloud.githubusercontent.com/assets/1068783/11191501/61d5b838-8c50-11e5-8730-7a680511bf23.png)
![screencapture-teach-mozilla-org-activities-1447696623271](https://cloud.githubusercontent.com/assets/1068783/11191500/61d4a254-8c50-11e5-99bd-19eb31a602ac.png)
![screencapture-teach-mozilla-org-activities-web-lit-basics-1447696581817](https://cloud.githubusercontent.com/assets/1068783/11191502/61d6f40a-8c50-11e5-9bde-4540fbfe9ad3.png)
![screencapture-teach-mozilla-org-clubs-1447696804356](https://cloud.githubusercontent.com/assets/1068783/11191503/61d7922a-8c50-11e5-9953-9fa3f6488a8b.png)
![screencapture-teach-mozilla-org-events-1447696960441](https://cloud.githubusercontent.com/assets/1068783/11191504/61d8eef4-8c50-11e5-9570-99c31c9ce0db.png)
![screencapture-teach-mozilla-org-teach-like-mozilla-1447697504509](https://cloud.githubusercontent.com/assets/1068783/11191505/61d9cb58-8c50-11e5-9474-0dad8b28a143.png)
![screencapture-teach-mozilla-org-teach-like-mozilla-web-literacy-1447697566993](https://cloud.githubusercontent.com/assets/1068783/11191506/61e772ee-8c50-11e5-9b4e-41a7dcc95c7c.png)
![screencapture-teach-mozilla-org-tools-1447697075772](https://cloud.githubusercontent.com/assets/1068783/11191507/61e829dc-8c50-11e5-9824-31fcc6931b9a.png)

**Comment by kristinashu** [comment]
@adamlofting @mmmavis is it possible to set up analytics in a way that tracks when users click on an external? The site has so many external links, it would be great to see which ones users are clicking on.

**Comment by adamlofting** [comment]
> @adamlofting @mmmavis is it possible to set up analytics in a way that tracks when users click on an external? 

We do have a way to track outbound links, but they need marking up individually like this:
https://github.com/mozilla/teach.mozilla.org/blob/develop/pages/home.jsx#L335

**Comment by hannahkane** [comment]
Will file a separate ticket for adding tracking code to individual links.
