### ISSUE TITLE
Activate in-page google analytics 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1413]
@mmmavis @adamlofting looks like all the analytics are working except when I go to Behavior / In-Page Analytics. I get this error message:
<img width="1413" alt="screen shot 2015-11-02 at 9 54 09 am" src="https://cloud.githubusercontent.com/assets/1068783/10895211/d66e1ca6-8167-11e5-9e15-3aec33ebba12.png">

Is everything up to date?

**Comment by adamlofting** [comment]
That's interesting - I don't use that feature much so hadn't noticed this.

I haven't looked into this closely yet, but I suspect this is related to how the site is built with React. 

It does work if you install the Chrome Extension linked in that message though:

<img width="1426" alt="screenshot 2015-11-04 11 31 01" src="https://cloud.githubusercontent.com/assets/1901816/10936925/953eda50-82e7-11e5-9163-6cfad41ed6d7.png">

**Comment by kristinashu** [comment]
Ok, it's working for me in Chrome. Thanks @adamlofting
