### ISSUE TITLE
Move Mozilla Clubs logo remix to new Thimble

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1415]
Hi - 

We've received two notes from folks who are trying to remix the Mozilla Clubs logo here: https://sabby.makes.org/thimble/NzYxNzkwOTc2/mozilla-clubs-wordmark however it's in old Thimble and not remixable. 

@sabrinang Are you able to access it from webmaker.org/me and copy/paste the code from this old Thimble make into new Thimble, then share the updated link?

Thanks!

cc @kgorr

**Comment by ldecoursy** [comment]
Any update on this?

**Comment by jgmac1106** [comment]
I have already migrated it for my club. I can share the project.

**Comment by jgmac1106** [comment]
Here is the project. I remixed mine and made it into a blank template. You may want someone who actually knows what they are doing to double check my mark up.

https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/16746/

**Comment by hannahkane** [comment]
@ldecoursy - is what @jgmac1106 has what you need? Can we close this ticket?

**Comment by ldecoursy** [comment]
I think it probably still needs the wrapper with the short instructions and font licensing/usage details that appear on @sabrinang's version.

**Comment by hannahkane** [comment]
@ldecoursy - how's this?

**Comment by ldecoursy** [comment]
Eggscellent! :egg:

**Comment by ldecoursy** [comment]
@amirad @kgorr We should update this link in the welcome kit or wherever else it may live.
