### ISSUE TITLE
Implement Add "Help us translate" CTA on Web Lit Basics I

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1416]
Based on design in #1411

Add a "Help us translate" CTA at https://teach.mozilla.org/activities/web-lit-basics/ that links to the blog post here: https://blog.webmaker.org/help-us-get-local-with-web-literacy

Here's the comp with a yellow feature box added. Styling pulled from https://teach.mozilla.org/clubs/

![red-pen-275b833e-a78f-477d-a384-9d0acd695309](https://cloud.githubusercontent.com/assets/1068783/10915671/997c268a-820c-11e5-99bb-291d4024aac3.png)

CC @hannahkane @mmmavis

**Comment by hannahkane** [comment]
Thanks for filing, @kristinashu!
