### ISSUE TITLE
Update Maker Party Certificate link on teach.mozilla.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1419]
Unless anyone was planning to update the Maker Party Certificate project, we had a community member send us this: https://d157rqmxrxj6ey.cloudfront.net/mhasan/13029/ (it's a remix of the old thimble project in the new thimble). 

On this Maker Party event resources page: https://teach.mozilla.org/events/resources/ the current link for the certificate goes to an old webmaker link that can no longer be remixed. 

cc @amirad @kgorr @chadsansing

**Comment by chadsansing** [comment]
+1.

**Comment by amirad** [comment]
Works for me! Let's get the link switched! 

Can we add a thank you or some recognition in our first newsletter @kgorr ??

**Comment by KGorr** [comment]
Excellent idea, @amirad! I'll make a note of it.
