### ISSUE TITLE
Create a Made with Code activities landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1425]
We currently host three Made With Code activities:
 * [Meme](https://teach.mozilla.org/activities/madewithcode-meme/)
 * [Movie Poster](https://teach.mozilla.org/activities/madewithcode-poster/)
 * [First Web Page](https://teach.mozilla.org/activities/madewithcode-firstwebpage/)

We need to give them a landing page, with links to all three.

Can use styles from https://teach.mozilla.org/activities/web-lit-basics/

url: /activities/madewithcode

Title: Made with Code

Image: use Made with Code logo and Google logo - see #1423 

Intro copy: Welcome! Mozilla is happy to partner with Google's Made with Code initiative to inspire girls to get creative with code. Below are three fun activities to help you create your own webpages by writing and remixing HTML.

[No "Learning Objectives" section"]

[No section headings - e.g. "Reading the Web"]

**Let's Make a Meme**
*Understanding remixing*
A “meme” is something that’s shared on the internet, and it usually has three parts: a picture, a caption, and a dash of humor. In this activity, you’ll make your own meme using a bit of HTML and your own creativity. 

**Make a Movie Poster**
*Understanding remixing*
Seen a movie or read any good books lately? Make a web page with your glowing (or vicious) review. Learn a little code along the way.

**Make Your First Webpage**
*Understanding remixing*
You’ve probably seen hundreds (if not thousands) of web pages. All of them are written in a language called HTML. It’s easy to start messing around with HTML. In this activity, you’ll make a basic web page in about 60 seconds or less.

Looking for more fun projects to make and remix using Mozilla's Thimble code editor? Check out [Mozilla's Thimble](https://thimble.mozilla.org)!

**Comment by hannahkane** [comment]
@ldecoursy - does the above work for you?

**Comment by ldecoursy** [comment]
This sounds great. I have two suggestions. 

1) I think we should have the intro match the voice of the project descriptions. For instance: Welcome! Mozilla is happy to partner with Google's Made with Code initiative to inspire girls like you to get creative with code. Below are three fun activities to help you create your own webpages by writing and remixing HTML.

2) Can we add something below the three activities along the lines of: Looking for more fun projects to make and remix using Mozilla's Thimble code editor? Click here! [link to thimble.mozilla.org]

Also, I found out they're making the switch from CodeAcademy to Mozilla on this page: https://www.madewithcode.com/resources/ on Dec. 7. 

Thanks!

**Comment by hannahkane** [comment]
Thanks, @ldecoursy! Updated first comment with your edits.

**Comment by jgmac1106** [comment]
These activities also need to be moved over (and updated) to new Thimble.
They link to old Thimble.

 I think I took @openmatt's meme maker (that made with code linked to) and
redid that one on new Thimble but I don't think the other two have been
ported over.

**Comment by hannahkane** [comment]
Thanks, @jgmac1106. See #1426.

**Comment by mmmavis** [comment]
@hannahkane thanks for much for putting everything in this beautiful format!!!

**Comment by mmmavis** [comment]
@hannahkane do we want to add a link to this landing page to the list of activities on https://teach.mozilla.org/activities/ ?

**Comment by hannahkane** [comment]
@ldecoursy - I'll defer to you on @mmmavis's question above.

**Comment by ldecoursy** [comment]
Sure - I'd say it can be at the bottom of the list on that page. Thanks!

**Comment by mmmavis** [comment]
@hannahkane @ldecoursy 

Would you say this is a **Beginner** package? And is developed by **Mozilla and Google's Made with Code**?  If you can provide a short description as well it'll be extra fantastic!

**Comment by ldecoursy** [comment]
Def beginner. Developed by Mozilla for Google's Made with Code initiative. 

Do you need something separate from the intro copy at the top of this ticket?

**Comment by mmmavis** [comment]
@ldecoursy 
nah I can use the same copy 
```
Mozilla is happy to partner with Google's Made with Code initiative to inspire girls like you to get creative with code. Below are three fun activities to help you create your own webpages by writing and remixing HTML.
```
(note that I removed "Welcome!")

**Comment by ldecoursy** [comment]
Sounds good @mmmavis!

**Comment by mmmavis** [comment]
oh wait sorry, I wonder if we should change "...inspire girls like you" to just "inspire girls" in case the reader is not female?

**Comment by ldecoursy** [comment]
:+1:

**Comment by Pomax** [comment]
Can we move those activities over from the old thimble to the new thimble, and then link to those instead? It seems counter productive to try to move people to new thimble, but introduce a new activities page that then doesn't use it.

**Comment by hannahkane** [comment]
There's a ticket to republish on new Thimble. I can do that this afternoon, unless someone else has time to do it earlier. https://github.com/mozilla/teach.mozilla.org/issues/1426

**Comment by Pomax** [comment]
aha! missed that ticket.
