### ISSUE TITLE
Republish Made with Code activities on new Thimble

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1426]
And then correct the links on these pages:

https://teach.mozilla.org/activities/madewithcode-poster/
https://teach.mozilla.org/activities/madewithcode-meme/
https://teach.mozilla.org/activities/madewithcode-firstwebpage/

**Comment by hannahkane** [comment]
Make a Movie: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/17071/

**Comment by hannahkane** [comment]
Meme: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/17083/

**Comment by hannahkane** [comment]
First web page: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/17084/

**Comment by hannahkane** [comment]
@mmmavis - I created the Made With Code projects in new Thimble. Links above. Can you please add them to the three Made With Code pages on Teach (will need to be added in two places per page), plus the new parent page (#1425)?

I don't know how to link directly to a remix in new Thimble. Do you?

**Comment by mmmavis** [comment]
@hannahkane 

> I don't know how to link directly to a remix in new Thimble. Do you?

I'm not 100% sure either.  

@Pomax is it Remix link https://thimble.mozilla.org/projects/PROJECT_ID/remix? eg., https://thimble.mozilla.org/projects/17084/remix ???

**Comment by flukeout** [comment]
Unfortunately, the remix URL is not based on the published URL you see in the address bar. To get the remix URL, you have to right-click the Remix button and copy the link.

This isn't ideal obviously - I'll file it in the Thimble repo, but that's how it works.

**Comment by mmmavis** [comment]
thanks @flukeout , yea I grabbed that https://thimble.mozilla.org/projects/PROJECT_ID/remix link from the Remix button so i think we are good.

@hannahkane I'll update the links in my PR https://github.com/mozilla/teach.mozilla.org/pull/1450
