### ISSUE TITLE
Design MLN Community newsletter template

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1428]
Starting in December (we hope), we'll be sending a monthly newsletter to the MLN community via Exact Target. This ticket is to design a template that we'll use every month. 

Some information from @kgorr, who's leading this effort:

3 words to describe how we want people to feel when reading the newsletter: connected, excited, motivated to #teachtheweb

### Main Content ###

 * Featured Activity (latest activities and lesson plans to teach the web) - FOCUS of template/main content with image, 250 words
 * Upcoming Mozilla Learning or Community Events - I'm thinking a sidebar, no images. Could this be a mini calendar with hyperlinks?
 * Mozilla Learning Announcements - bottom of newsletter, no image needed, bullets with room for a sentence or two explanation under each bullet
 * Community Spotlight (article featuring leaders doing inspiring work to spread web literacy) - I'm thinking this can be a sidebar too, just enough space for a paragraph and image, then linking to a blog article for more details. 

### Footer Content ###

 * Have questions, comments, or just want to join in the discussion? We're easy to contact:
 * Twitter: https://twitter.com/MozTeach
 * Discourse (Community Forum): https://discourse.webmaker.org/
 * Website: teach.mozilla.org
 * Email: teachtheweb@mozillafoundation.org

### Branding ###

This may change, but let's assume the main brand associated with this will be Mozilla Learning Network

**Comment by hannahkane** [comment]
@kristinashu - could you please take a look at this ticket and let @kgorr and @ldecoursy know if you have any questions about it. Don't need to start it until the next heartbeat, but I want to make sure we have the info we need. Thanks!

**Comment by kristinashu** [comment]
A newsletter will be great to have! 

@kgorr @ldecoursy just wondering many events you think would be featured in Upcoming Mozilla Learning and Community Events? Calendars can be tricky because content never seems to fit but I think a nicely styled list would work. Just wonder how many and what info is needed for each event (date, time, location, short description, url link for more info...)?

In general we should stay away from side bars - they won't work well on smaller screen sizes. So the email might get a little long but we'll see once it's mocked up. Do you think every email will have content for Featured Activity, Events, Announcements and Community Spotlight or would it depend on the month?

Also, here's a good resources for benchmarking http://reallygoodemails.com/

**Comment by KGorr** [comment]
Thanks for that link - really cool! Makes sense about the sidebar.

@ldecoursy can you speak to the amount of community events? I'm not sure... Date, time, location, short description & URL link would be great.

We can count on every month having a Featured activity, events, and community spotlight. The announcements section may be come and go depending on the season, but am hoping we can easily turn it into a "tips & tricks" section that was requested from the survey we did, found here: https://docs.google.com/document/d/12YqskxpFMbLdWeS12NzwfsAWrH25UtvXdEWwQ0qA-m8/edit#

**Comment by ldecoursy** [comment]
I think we can make a decision to highlight no more than 3 events in the newsletter - for starters they'll likely be our events or related events that we curate, and perhaps into next year we can decide if we want more of a public calendar that people can add events to (that we could then link to from the newsletter).

**Comment by kristinashu** [comment]
Great, thanks for the info! Everything sounds good to me.

**Comment by KGorr** [comment]
The latest news from Paul/Adam is that Exact Target will NOT be available for use before the new year. We were hoping to send out out first edition in December, which means we'll need the template to be BSD-friendly.

@ldecoursy, do you want to move forward with sending in Dec (and thus the designers will need to accomodate BSD), or should we wait until we get into Exact Target (and thus the designers only need to worry about that platform)?

**Comment by ldecoursy** [comment]
No, I don't think we need to rush it  - let's plan towards Jan.

**Comment by kristinashu** [comment]
Here's where I'm at with the comp: https://redpen.io/p/au9c53b3ae1141ebbc
I think we can adjust things once we have really content but let me know if you have any feedback!

![teach-email-01 2x](https://cloud.githubusercontent.com/assets/1068783/11354436/4e1731f4-9200-11e5-8db2-7f78f074b5c9.jpg)

**Comment by ldecoursy** [comment]
Sweet! Just left a few minor comments. :dancers:

**Comment by KGorr** [comment]
Love this! I agree with comments already made (minor things). Very nice job!

**Comment by kristinashu** [comment]
Thanks for the feedback, I've updated the comp: https://redpen.io/p/au9c53b3ae1141ebbc

I've also added an alternative version for comparison. The original one is inline with our other emails (pattern background framing the content) and the new version is breaking away from that. Let me know if you prefer one over the other.

@cassiemc any design feedback?
@simonwex let me know if you have any dev concerns.

**Comment by hannahkane** [comment]
Ooh...I quite like the second one. It gives all the focus to the content.

**Comment by simonwex** [comment]
What is the source for the list we want to send this newsletter to? Have they opted in to emails?

**Comment by hannahkane** [comment]
We're adding a sign-up to the /Community page (see #1434), and we'll eventually replace the Pledge to Teach on the homepage with this sign-up as well.

**Comment by simonwex** [comment]
Ah, so this is a new list? – Not one that already exists in BSD? I think that makes it easier.

**Comment by cassiemc** [comment]
@kristinashu A few visual tweaks / suggestions, nothing critical. Nice work.

**Comment by hannahkane** [comment]
@simonwex - I think we'll add to the existing list we've been building via the Pledge to Teach. Does that seem problematic to you?

**Comment by kristinashu** [comment]
Most people seem to prefer the version without the border so I've updated that version with all the feedback. 

https://redpen.io/p/au9c53b3ae1141ebbc

**Comment by hannahkane** [comment]
The final version is Alt v2, right? I think it looks fantastic. Let's close this ticket. 

@kgorr and @ldecoursy  - let us know when we should open an implementation ticket. That is, when we're ready to actually populate with real content and send.

**Comment by kristinashu** [comment]
Yup, that's the one!

**Comment by cassiemc** [comment]
@kristinashu It's good practice to link to the specific final file, rather than the set of redpen files. Nice work on this!

**Comment by kristinashu** [comment]
Good call, thanks @cassiemc 

Illustrator file is here: https://drive.google.com/open?id=0B2irLVDJivhLVHhXbGp6VjBtV28

![teach-email-05 2x](https://cloud.githubusercontent.com/assets/1068783/11510386/5a7ab830-9818-11e5-9bdd-36ecdb97c2f7.jpg)

**Comment by KGorr** [comment]
@hannahkane Would it be possible to upload the template into Exact Target before the content is ready? My Exact Target training is going to be in the next couple of weeks, and it would be great to have it uploaded before that so that I can see it/use it as I get trained.

**Comment by hannahkane** [comment]
@mmmavis - see @kgorr's question above, and let me know if I should file a ticket.

**Comment by mmmavis** [comment]
> @hannahkane Would it be possible to upload the template into Exact Target before the content is ready? My Exact Target training is going to be in the next couple of weeks, and it would be great to have it uploaded before that so that I can see it/use it as I get trained.

@hannahkane @KGorr I'm worried the timeframe will too be tight for this. I haven't got any ET training myself either so it will probably take me awhile to figure the template building process myself.

@KGorr Do you know roughly when we plan to send out the first email in this template?

**Comment by KGorr** [comment]
@mmmavis, no worries if it can't happen. It's a nice to have for my training, but not essential. We are hoping to have the first email go out in January sometime. Since Exact Target training isn't completed yet, no exact date has been set.
