### ISSUE TITLE
Run some test on usertesting.com

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1432]
We should determine the main goals of teach.mozilla.org then set up some tests on usertesting.org to determine if users can easily find the information they need.

cc @secretrobotron @hannahkane @sabrinang @cassiemc

**Comment by hannahkane** [comment]
Good idea. Would like to wait until we've finished our 2016 planning process, which should help clarify the goals.

**Comment by hannahkane** [comment]
Closing until we have specific testing needs.
