### ISSUE TITLE
Create Web Lit Basics II teaching kit

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1433]
### Part 1: Create Page ###

url: /activities/web-lit-basics-two

Page content is [here](https://docs.google.com/document/d/1TK2AAc5Bhe0sO1plj_ZtfI7LIMoc7rHnzmHoTt_URMI/edit#)

Note: This Teaching Kit does note follow the "Reading the Web," "Writing the Web," "Participating on the Web" structure of our other kits, so those header styles won't be needed. Instead, we can just list the activities directly under the Learning Objectives.

### Part 2: Add to /activities ###

@chadsansing - can you please fill in the below?

Web Literacy Basics II (Teaching Kit)
level: 
developed by: 
description:
image: https://c2.staticflickr.com/6/5760/22431506387_43e85e71bd.jpg

**Comment by chadsansing** [comment]
Level: Beginner
Developed by: Mozilla Learning Networks
Description: Explore making, media production, reverse-image search, and design on the web.

**Comment by mmmavis** [comment]
Hey @chadsansing 

I've noted it in the google doc but thought I should flag you here as well: link to "The Web is a Tool for Learning" seems to be a 404 :cry:

**Comment by hannahkane** [comment]
New link in doc: http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session02-web-is-a-tool-for-learning.html
