### ISSUE TITLE
Make Vision and Roadmap decks pretty and on-brand!

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1435]
cc @sabrinang @kristinashu

**Comment by hannahkane** [comment]
I'm killing this, because I can tell this deck won't be useful at this point. Will repurpose content for series of blog posts instead.

**Comment by kristinashu** [comment]
Whaaat! So sad.

**Comment by hannahkane** [comment]
It's still useful! Will find ways for it to live on; and may be revived in the future. But need to wait until after Orlando. :)
