### ISSUE TITLE
Benchmark curriculum database

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1443]
What other models can we look at for architecture and design inspiration?

**Comment by sabrinang** [comment]
WIP benchmarking various curriculum databases (learning platforms) on this google slide deck here: https://docs.google.com/a/mozilla.com/presentation/d/15OYzQ9-TkkWYJUb_Yh1p-viN8K_jnCGuF7Ih4ABQmm0/edit?usp=sharing

I'll be document points on the presenter's notes section of the deck

**Comment by jgmac1106** [comment]
It is a paysite but maybe poking around teachers paying teachers could give
some architecture insight.

In terms of taxonomies and web resources I will ask around in the #OER
community to see if anyone there built or uses something.

**Comment by jgmac1106** [comment]
Now that I think about it the ds106 assignment bank is a huge resource of
user created content: http://assignments.ds106.us/

**Comment by hannahkane** [comment]
@sabrinang - is there more to do here, or can we close this one?

**Comment by hannahkane** [comment]
Per conversation with @sabrinang - let's consider this a rolling ticket, and do some add'l benchmarking in January, perhaps with an emphasis on tools that index external content.

**Comment by hannahkane** [comment]
Also see http://howto.p2pu.org/modules/start/about-this-course/

**Comment by hannahkane** [comment]
@sabrinang - do you want to keep this ticket open as ongoing work, or do you think its usefulness has run out?

**Comment by sabrinang** [comment]
@hannahkane I think we noted to consider this a rolling ticket so we remember to benchmark (I haven't benchmarked as of late however as we're doing the research interviews)

**Comment by hannahkane** [comment]
@chadsansing shared http://recipe.soi.asia/, which seems very aligned.

**Comment by hannahkane** [comment]
from @xmatthewx: [TeachersPayTeachers](https://medium.com/bright/millions-of-teachers-minting-millionaire-teachers-decc4fe41604#.i3w8442op)

**Comment by hannahkane** [comment]
From @anmechung:

    Curriki is a website that curates content in a variety of disciplines, highlighting noteworthy teachers and content. With more than 8 million users from nearly 200 different countries, this site has been a vibrant place to create, share, and find open educational resources (OERs) since 2006. They offer free tools for build-your-own curricula and private virtual collaboration spaces.

    MIT OpenCourseWare site offers educators and students access to full courses designed and taught by MIT professors. Users can access the entire course library and the entire course packet. Course packets include video interviews with professors, syllabus, outlines, readings, assignments, projects and related resources. 

    OER Commons offers a vast database of teacher-created curriculum. The site offers educators a place where they can connect and share globally with other educators, and work with the curriculum those educators have shared. The content is vetted for credibility and provides citations for reference. Users can sign up for a free account, share their own work, and access and curate their own content.  This video helps you search smarter How to Search OER Commons.        

    WatchKnowLearn  is a wiki that allows teachers to edit/remix lessons by finding videos to use in lessons and allows educators to connect with other educators.

    ReadWriteThink, managed in part by the National Council of Teachers of English (NCTE) and offers subject-specific curriculum sites. They offer specific how-to videos on their YouTube channel to help you navigate better while hunting for language arts materials.

**Comment by chadsansing** [comment]
Just shared as part of a conversation with the USDOE #GoOpen team: [Learning Registry](http://learningregistry.org/).

**Comment by hannahkane** [comment]
Closing this as out-of-scope for current roadmap. Will likely revive in the future.
