### ISSUE TITLE
Review existing curriculum; propose architecture for shared tooling

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1444]
Existing content from MLN, MDN, Participation, and MSL is gathered in this pad: https://public.etherpad-mozilla.org/p/teach.mozilla-curriculum-plan

 - [x] Review all content to develop understanding of formats, audiences, and relevant meta-data
 - [x] Propose architecture for shared tooling (work with HK on this)

**Comment by sabrinang** [comment]
I will be reviewing the etherpad and propose ideas on this issue

**Comment by sabrinang** [comment]
WIP spreadsheet to document what content I looked at: https://docs.google.com/spreadsheets/d/1cP9TOdqFNbP1qu_5aEiai1emYgcRa5IaCOfUUll0_Oo/edit#gid=1414253108&vpid=A1

**Comment by hannahkane** [comment]
@sabrinang - I feel like you've done this, and we can close this ticket. I think the next steps are to design a research plan (outlined in the [project brief](https://docs.google.com/document/d/1f5AYLbenXmzTCg2mkvABjeUHAFXyhC2l1evC0wEpybg/edit#heading=h.khn1rpy8xnf6)) which may include building a prototype for testing.

Does that make sense to you?

**Comment by sabrinang** [comment]
@hannahkane - Yes, the project brief proposes the plan on how to approach the architecture.
The review of content was captured in the [spreadsheet](https://docs.google.com/spreadsheets/d/1cP9TOdqFNbP1qu_5aEiai1emYgcRa5IaCOfUUll0_Oo/edit#gid=1414253108&vpid=A1) and some ideas in the [slide deck](https://docs.google.com/presentation/d/1ybSPqdH9alm8E863_fj4lBiZnshhX8a5gYQWQaRkfVw/edit?usp=sharing) to capture initial understanding. We can open another ticket if these documents need to be cleaned up for future reference.
