### ISSUE TITLE
[visual element] - Unify all strokes 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1447]
Based on design in #1414 and build #1434 

Update all line breaks and form field outlines to be 1px width and light grey #c1c1c0 (so they will no longer be the section colour). So it will look like:

![screen shot 2015-11-24 at 11 18 01 am](https://cloud.githubusercontent.com/assets/1068783/11378810/ec0073c0-92a1-11e5-9e61-0c78047d04d5.png)
![screen shot 2015-11-24 at 11 18 08 am](https://cloud.githubusercontent.com/assets/1068783/11378811/ec056448-92a1-11e5-9ef2-61d0eee89817.png)
![screen shot 2015-11-24 at 11 18 14 am](https://cloud.githubusercontent.com/assets/1068783/11378812/ec078e08-92a1-11e5-8361-308bcfb2d392.png)

Comp is here: https://redpen.io/p/cnca8a0265383acc93

Issues found here (and probably other places):
- https://teach.mozilla.org/

<img width="437" alt="screen shot 2015-11-24 at 12 00 25 pm" src="https://cloud.githubusercontent.com/assets/1068783/11379021/fc3c33c2-92a2-11e5-8056-21fe931c77e5.png">

- https://teach.mozilla.org/clubs/ 

<img width="998" alt="screen shot 2015-11-24 at 11 55 16 am" src="https://cloud.githubusercontent.com/assets/1068783/11378915/76437582-92a2-11e5-8dc8-b860fe4a8619.png">

- https://teach.mozilla.org/clubs/list/

<img width="526" alt="screen shot 2015-11-24 at 11 57 27 am" src="https://cloud.githubusercontent.com/assets/1068783/11378937/99541432-92a2-11e5-8394-655cfdd1ec43.png">

- https://teach.mozilla.org/tools/

<img width="1012" alt="screen shot 2015-11-24 at 11 58 15 am" src="https://cloud.githubusercontent.com/assets/1068783/11378952/af8cf098-92a2-11e5-8287-4218805ea1f7.png">

- https://teach.mozilla.org/teach-like-mozilla/

<img width="734" alt="screen shot 2015-11-24 at 11 58 37 am" src="https://cloud.githubusercontent.com/assets/1068783/11378978/dd55345e-92a2-11e5-8490-9f19a787460a.png">

This will solve some of the issues in https://github.com/mozilla/teach.mozilla.org/issues/1377 and https://github.com/mozilla/teach.mozilla.org/issues/1379

**Comment by mmmavis** [comment]
@kristinashu I will need some help from you for updating the following files so that they are in `#c1c1c0` and the `1px` stroke. Thanks!

https://teach.mozilla.org/img/pages/about/svg/icon-horizontal-divider.svg
https://teach.mozilla.org/img/pages/clubs/svg/icon-line.svg

**Comment by kristinashu** [comment]
@mmmavis is there any way to do it through CSS?

**Comment by mmmavis** [comment]
@kristinashu good call! :+1:

**Comment by mmmavis** [comment]
@kristinashu the changes should be live on http://teach.mofostaging.net/ soon.  Please create a separate ticket for anything that I might have missed.

**Comment by kristinashu** [comment]
@mmmavis amazing! thanks!
