### ISSUE TITLE
Create chart style for Gigabit site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1452]
"Types of Support" Chart content near the bottom of [this doc](https://docs.google.com/document/d/1qfy0RsEzGRr9HLGDL1qah5iqwRSQY4T1ywWDHI9Y0io/edit).

**Comment by hannahkane** [comment]
@sabrinang - did you mention this during stand-up today? Can't remember. Want to make sure we don't drop this. Who's more likely to get to this - @sabrinang or @kristinashu ?

**Comment by sabrinang** [comment]
@hannahkane - I touched base with mavis, i'm working on it now

**Comment by sabrinang** [comment]
I created mockups for the content in the text doc: https://redpen.io/p/vj24b1b75c486dac28
The table / chart style is similar to what is seen on https://www.mozilla.org/en-US/contribute/events/

**Comment by hannahkane** [comment]
beautiful work, @sabrinang. Above and beyond.

cc @LindseyFrost  - check out what the gigibit page will look like in Sabrina's redpen above.

**Comment by LindseyFrost** [comment]
This is amazing! So excited about the changes!

**Comment by hannahkane** [comment]
Closing this design ticket.
