### ISSUE TITLE
Write final copy for Initiatives page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1456]
This is a new page we're creating on the Teach site. 

 Design is here: https://redpen.io/p/uvc0135f6b8d5b5f31

Draft copy is here: https://public.etherpad-mozilla.org/p/mlninitiatives

Looking for reviews from @KevZawacki, @ldecoursy, and @HPaulJohnson, if possible.

**Comment by ldecoursy** [comment]
I made some edits on the copy earlier today.

Thanks!

**Comment by hannahkane** [comment]
Ah, didn't see. Great edits. Thanks!

Will wait for final approval from @KevZawacki or @HPaulJohnson.

**Comment by hannahkane** [comment]
moving to next heartbeat to get final approval post-Orlando

**Comment by KevZawacki** [comment]
@hannahkane Just gave an edit -- looking good!

**Comment by hannahkane** [comment]
Thanks for feedback @ldecoursy and @KevZawacki!
