### ISSUE TITLE
Due December 17: New Web Lit Map design concept

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1457]
Task is to incorporate feedback from MozFest session and present a new concept that @anmechung and @chadsansing can share with stakeholders in January.

**Comment by hannahkane** [comment]
Adding as a p2 for the December 4th milestone. If it doesn't get completed this heartbeat, it will be a p1 for the first week after Orlando.

**Comment by hannahkane** [comment]
@sabrinang - should I move this to the next heartbeat?

**Comment by sabrinang** [comment]
@hannahkane yes - I'll work on it first week after Orlando

**Comment by sabrinang** [comment]
Initial Web Literacy design concepts on redpen: https://redpen.io/p/pz54052f2e19300634

Ideas use colour to highlight 21c skills on the web lit map and are toggleable from the key

feedback? @hannahkane @anmechung

**Comment by sabrinang** [comment]
I am also trying to think of an iteration that doesn't heavily depend on colour *(in consideration of accessibility, colour-blind users)*

**Comment by jgmac1106** [comment]
You could use what ever icons are being used in the 21c badge templates.
Toggle those.

The number of 21c skills is small you can choose from a broad enough range
to minimize color blindness.

Its when the colors are close in shade or complex in patterns that drive us
batty.

**Comment by sabrinang** [comment]
Next steps - annotate the designs various states to prepare for collecting feedback (on the 8th January from focus groups)

**Comment by sabrinang** [comment]
Updating the existing [Web Literacy] (https://teach.mozilla.org/teach-like-mozilla/web-literacy/) to Web Literacy v2.0 with a new visual. It is a entry-level web literacy & 21 century skill framework for knowing how to read, write and participate online. This corresponds with the evolving research in the [whitepaper](https://docs.google.com/document/d/1sP_nrYtkoZEyAOzfIxAFIgxBRq6T2ZGoBB_iuWYNyQI/edit).

v2.0 incorporates the 21 century skill categories which are represented as colours that overlay onto the literacies and competencies in both of these visual approaches:

![mln_web-literacy-_wireframes-v2](https://cloud.githubusercontent.com/assets/2492510/11946982/b6f6a67a-a815-11e5-8e19-deac94c237cd.png)


The honeycomb visual explores the competencies relationship to literacy by proximity and allows flexibility for the "open practices" competency to be highlighted separately to be incorporated into other competencies. The wheel has distinct competency relationships to a literacy.

I can continue iterating on a certain direction for example adding connections to make the honeycomb to make relationships more distinct and could potentially have the flexibility to connect across literacies if the research evolves in that direction:
![mln_web-literacy-_wireframes-v3](https://cloud.githubusercontent.com/assets/2492510/11946998/f1f2d7d0-a815-11e5-8260-d2b6876a3320.png)


Design Feedback? @cassiemc @kristinashu

What do you think of 21 century skills being represented as a colour overlay?

Do you have feedback on which visual concept is more effective at conveying these relationships?

**Comment by sabrinang** [comment]
Clickable prototypes are here:

Design 1 - https://marvelapp.com/106ifc6
Design 2 - https://marvelapp.com/bcbd6e

**Comment by chadsansing** [comment]
So happy to watch all of this progress. The Civ V grognard in me likes the hexagons, especially, as a pathway-mappable field.

**Comment by anmechung** [comment]
@chadsansing - :) 

We're sending this out to all the folks who participated in the focus groups to get their feedback by end of next week.

**Comment by sabrinang** [comment]
The email is sent out to present 2 concepts for feedback today. 
Form:  http://goo.gl/forms/5kRmzW7200

We also collect design feedback directly on Marvel:
Design 1: https://marvelapp.com/106ifc6
Design 2: https://marvelapp.com/bcbd6e

Feel free to give design feedback on google form or marvel - closing this ticket!
