### ISSUE TITLE
update the teach.wmo dependencies

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1460]
Some have become really out of date (being officially obsolete), so it's time to do a version bump. And hopefully not too much fixing.

- [x] update React to 14
- [x] update remaining dependencies with deprecation warnings
- [ ] update React-Router separately (https://github.com/mozilla/teach.mozilla.org/issues/1501)

**Comment by hannahkane** [comment]
@Pomax - did this get done, or should we move to next heartbeat?

**Comment by Pomax** [comment]
mostly, https://github.com/mozilla/teach.mozilla.org/pull/1480 is the React lift (it needs a review though), the other dependencies are less important and can be done incrementally on top.

**Comment by Pomax** [comment]
resolved.
