### ISSUE TITLE
[pre-footer] - remove 3-up links from bottom of Web Lit page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1461]
Related to: [pre-footer] - unify all icon links above the footer #1372 

**Problems:** 
Web literacy is the only secondary page that has the 3-up links.

**Solutions:**
* remove 3-up links
* add whitepaper link somewhere on the page 

**Seen on:**
https://teach.mozilla.org/teach-like-mozilla/web-literacy/
<img width="1422" alt="screen shot 2015-12-01 at 4 27 28 pm" src="https://cloud.githubusercontent.com/assets/1068783/11518695/8af9e33e-9848-11e5-876e-5ab3bb1455ee.png">

**Related Issue:** #1260
**/CC:** @sabrinang @kristinashu

**Comment by mmmavis** [comment]
@kristinashu just wanna double check - are we removing 3-up links from ALL pages on the MLN site?

**Comment by kristinashu** [comment]
@mmmavis the primary level pages (ex. home, teaching activities, mozilla clubs, maker party...) should all have the 3-up links but secondary pages (event resources and web lit map) and third level pages should not have the links.

**Comment by kristinashu** [comment]
@mmmavis you removed the 3-up links on this page in https://github.com/mozilla/teach.mozilla.org/issues/1506 so now we just need to add a link to the white paper (https://mozilla.github.io/webmaker-whitepaper/)

I've mocked up an example of how the bottom section could look:
![web-literacy---mozilla-learning-2016-01-04-13-56-58](https://cloud.githubusercontent.com/assets/1068783/12103443/1681ba76-b2f7-11e5-8799-062225751b82.jpg)

Assigning to you for implementation.

**Comment by mmmavis** [comment]
@kristinashu gotach! thanks for the clarification!
