### ISSUE TITLE
Draft blog post for Goggles FTU design

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1462]

**Comment by kristinashu** [comment]
@hannahkane if you want to see how the post is coming along you can check it out here: https://docs.google.com/a/mozilla.com/document/d/1MQ2z_MZZFbYU67M-7BUPpD-n6DdbXz2ZMEJ6-Fwco54/edit?usp=sharing

@cassiemc just gave some excellent feedback so I'll be working on those edits. Feel free to add your comments in now or tomorrow once I've made the changes Cassie suggested.

**Comment by hannahkane** [comment]
@kristinashu - great job with this! I like @cassiemc's suggestions a lot, and only had a few additional suggestions. Thanks for whipping this up so quickly!

**Comment by hannahkane** [comment]
Moving to next heartbeat to wrap up!

**Comment by kristinashu** [comment]
Hey @hannahkane and @cassiemc, I've updated the blog post https://docs.google.com/a/mozilla.com/document/d/1MQ2z_MZZFbYU67M-7BUPpD-n6DdbXz2ZMEJ6-Fwco54/edit?usp=sharing

I think the first draft was too long and boring so I've cut out a bunch. Any feedback you have would be much appreciated!

**Comment by hannahkane** [comment]
@kristinashu - I think this is terrific. I added a few comments, but they are small. I think the overall flow is great, and I love how it gives a little insight into the behind-the-scenes action.

**Comment by kristinashu** [comment]
Sounds like goggles will launch any day now so I'm wrapping this up. 
Doc: https://docs.google.com/a/mozilla.com/document/d/1MQ2z_MZZFbYU67M-7BUPpD-n6DdbXz2ZMEJ6-Fwco54/edit?usp=sharing
Image links: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLMGNVb2V6RzZJbUE&usp=sharing

@Pomax maybe you can fact check or let me know if I left anything major out?

**Comment by Pomax** [comment]
I don't think you did, it's a good post! (I did tweak the mention of my name, though, as I'm pretty much just Pomax online, even professionally)

**Comment by cassiemc** [comment]
Yes it's awesome @kristinashu! Excited to see this and all the goggles work ship. :)

**Comment by kristinashu** [comment]
Thanks everyone, closing!
