### ISSUE TITLE
Add tracking to external links

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1463]
Specifically:
 * links to external pages on /activities page (all the kits starting with Lo-Fi)
 * links to tools and activities on /tools
 * ~~Community link in sidebar (though that's changing soon, so maybe quickly obsolete)~~
 * sign in / sign up

**Comment by hannahkane** [comment]
@kristinashu  - ^ those are the ones I think we care about. Do you have any you'd want to add?

**Comment by kristinashu** [comment]
@hannahkane maybe sign in and sign up?

**Comment by hannahkane** [comment]
good call. adding.

**Comment by hannahkane** [comment]
@mmmavis - can you tell me how I can see the analytics for this? For example, how can I see how many people have clicked on https://epik.makes.org/thimble/NjU2MTQ2OTQ0/minecraft-a-flavor-of-java-epik from /activities?

**Comment by hannahkane** [comment]
or maybe that's a question for @adamlofting since I'm really just asking how to use GA. :)

**Comment by mmmavis** [comment]
I *think* this is how we check

1. Go to `teach.mozilla.org` from GA's dashboard
2. Go to Behaviour -> Events -> Overview -> Event Label
(Event Label = the url of link)

**Comment by mmmavis** [comment]
^ @hannahkane

**Comment by hannahkane** [comment]
Got it. Thanks, @mmmavis.
