### ISSUE TITLE
Trouble loading blog posts 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1465]
Seems to be a Google API problem

from https://developers.google.com/feed/ 
```
"This API is officially deprecated."
```
:sob: 

/cc @Pomax this is related to the "post undefined" error you mentioned to me today.

**Comment by mmmavis** [comment]
Posts are loaded again :octopus:

**Comment by hannahkane** [comment]
win!

**Comment by hannahkane** [comment]
Closing. @mmmavis - please reopen if there are any follow-up tasks.
