### ISSUE TITLE
Badges Search Issue

### ISSUE THREAD

**Issue by Ihab-Asafrah** [mozilla/teach.mozilla.org#1466]
I noticed that the badges function in Credly API matches the query string/keyword with the badge title only. So there is no direct way to match a query word with the badge description or creation date or any other criteria. Can we perform the search process and the matching on the Teach API itself and return the matched badges to any application that requests them?

**Comment by hannahkane** [comment]
cc @pomax

**Comment by aqarbook** [comment]
any updates on this ticket ?

**Comment by Pomax** [comment]
as far as I remember, the idea was to extend the teach-api so that the information that credly could not supply could be fetched that way. I believe there is a PR open for this already on https://github.com/mozilla/teach-api/pull/25 - am I incorrect in this?

**Comment by hannahkane** [comment]
@Pomax - is this ticket still useful?
