### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by Ihab-Asafrah** [mozilla/teach.mozilla.org#1467]
The authentication process flow: If a Mozilla app will request this API, then we will have like 3 logins in the way: one for the app, one for this API, and one for Credly API. I guess Mozilla manages this by giving one login for both the app and the Teach API using @webmaker account. Even though, we will still need two logins: one for Mozilla and the other for Credly API. The question is: How do you expect the flow of the authentication process? Does the user have to provide two logins? Is that OK?

**Comment by hannahkane** [comment]
cc @pomax

**Comment by AbuAlKarmi** [comment]
@simonwex any updates?

**Comment by simonwex** [comment]
There's work that Credly is going to do to support us getting an auth token for the user and logging them in to credly. Let's connect on Tuesday to sort this out.

**Comment by aqarbook** [comment]
i started working on this flow , i created a new table reference the user table to store user access and refresh token 
still i need to trigger loading credly token to session on login and handle save to be after authenticate request

**Comment by hannahkane** [comment]
@Pomax - is this ticket still useful?

**Comment by Pomax** [comment]
I don't believe so, @simonwex the interfacing with credly, as far as I understand it from the code we got from Souktel and heroku instance, this auth issue was solved?
