### ISSUE TITLE
Update banner images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1469]
From design in [photography] - layout alternative for large banner images #1396 

Comp with all the images: https://redpen.io/p/jna5c03b0eabf90217
JPGs of all the images are here: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLeWUzN2FGZjU5Nms&usp=sharing

All images have reduced height (except for home page).
Add image to tools page.

**Comment by kristinashu** [comment]
@mmmavis just noticed the clubs images on staging is the same as on the tools page - it should be the same as the current home page.

![tools](https://cloud.githubusercontent.com/assets/1068783/11944101/2733eb32-a7f8-11e5-8b48-a4acbe8a1202.jpg)
![tools 2x](https://cloud.githubusercontent.com/assets/1068783/11944100/2731b6b4-a7f8-11e5-89fd-3758cb191f05.jpg)

**Comment by mmmavis** [comment]
Nice catch @kristinashu ! It was some copy and paste mistake, heh, I just fixed this in https://github.com/mozilla/teach.mozilla.org/commit/9d3cf00f8804bb23db1d67afaa8393b930a3e9fc
