### ISSUE TITLE
Update value props in banners

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1472]
Based on #1414 and build #1434 we need to add a value prop intro to every primary page.

Here is the copy for the pages that need value props:

 * https://teach.mozilla.org/activities/: Activities and lesson plans to get you started
 * https://teach.mozilla.org/events/: Host a one-time event or workshop
 * https://teach.mozilla.org/tools/ (will be adding a banner image): Open source software to teach and learn the Web

**Comment by mmmavis** [comment]
PR has been merged.
