### ISSUE TITLE
Mozilla Gigabit Community Fund - Update Website Design

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1473]
The existing Gigabit website could be refreshed from the old sandstone to match some of the newer properties when they open for 2016 applications in January.

Current site: https://www.mozilla.org/en-US/gigabit/
![fireshot capture 31 - gigabit mozilla - https___www mozilla org_en-us_gigabit_](https://cloud.githubusercontent.com/assets/2492510/11579012/2bbb630a-99df-11e5-9b0d-909fd1fb8d22.png)

The website is hosted from mozilla.org so we can connect with the bedrock team if they have design guidelines for pages or have anything specific they require from their review. 

We can first discuss visual alignment with Hive CHA and KC and the relationship of these sites.

/cc @mmmavis @hannahkane

**Comment by sabrinang** [comment]
Initial ideas for Gigabit refresh: https://redpen.io/p/vj24b1b75c486dac28
*note: the text isn't finalized but there is a lot*

@cassiemc @hannahkane I'm uncertain what to visually align this with. For the mockups in the redpen, I'm following the design styles of other mozilla.org properties (like their flat buttons and beige instead of our MLN buttons) ![screenshot](https://cloud.githubusercontent.com/assets/2492510/11579917/0b8c7238-99e7-11e5-8fb4-766423f874a3.png) It was previously sandstoney but I am uncertain if I need to follow any style guidelines if it lives on mozilla.org - do you know who I should ask? It also aligns with Hive KC/CHA so I used the orange seen from the hive brand. Any feedback or ideas on this?

**Comment by hannahkane** [comment]
@sabrinang - thanks for doing this. Was more than was expected. I'll start a thread with the moz.org folks with a link to your redpen, so we can see what they think.

**Comment by hannahkane** [comment]
This is a P2. Top priority changes for the Gigabit pages are just to change the copy for now.

Design priorities for this heartbeat are the Web Lit Map design iteration and advancing the curriculum dbase work.

**Comment by hannahkane** [comment]
Closing this ticket in light of CMS and new bootstrap theme.
