### ISSUE TITLE
Update links to Discourse

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.mozilla.org#1474]
Links to Discourse have changed:
 * The link on the homepage should go here: https://discourse.webmaker.org/t/if-youre-new-to-the-community-please-introduce-yourself
 * The link on /clubs should go here: https://discourse.webmaker.org/c/mozilla-clubs
 * Link on /events should go here: https://discourse.webmaker.org/c/events
 * Link on /events/resources/ should go here: https://discourse.webmaker.org/c/events
 * Link on /tools should go here: https://discourse.webmaker.org/t/if-youre-new-to-the-community-please-introduce-yourself
 * Link on /teach-like-mozilla should go here: https://discourse.webmaker.org/t/if-youre-new-to-the-community-please-introduce-yourself

**Comment by Saallen** [comment]
Just noticed the link is broken here too 
https://teach.mozilla.org/teach-like-mozilla/ if you click on the Say Hello icon at the end of the page

**Comment by ldecoursy** [comment]
Good catch! 

I think the link on the Clubs page should point here: https://discourse.webmaker.org/c/mozilla-clubs

Teach like Mozilla page link can point here: https://discourse.webmaker.org/t/if-youre-new-to-the-community-please-introduce-yourself/15

Or, @hannahkane would you prefer they both link to the Discourse main page: https://discourse.webmaker.org/

**Comment by hannahkane** [comment]
@Saallen - thanks for the catch!

@ldecoursy - I think it's okay to link to separate, specific pages. Will update original comment.

**Comment by mmmavis** [comment]
There are 4 other Discourse links we should update

- About page: https://teach.mozilla.org/about/
- Maker Party 2015 page: https://teach.mozilla.org/activities/maker-party-2015/
- Protect Your Data page: https://teach.mozilla.org/activities/protect-your-data/
- Web Literacy Basics page: https://teach.mozilla.org/activities/web-lit-basics/

Suggestions on where we should link those to? @hannahkane @Saallen @ldecoursy ?

**Comment by hannahkane** [comment]
Thanks, @mmmavis 

My suggestion: 

About: https://discourse.webmaker.org/t/if-youre-new-to-the-community-please-introduce-yourself/15
Maker Party 2015: https://discourse.webmaker.org/c/events
Protect Your Data and Web Lit Basic: https://discourse.webmaker.org/c/curriculum

**Comment by mmmavis** [comment]
Lovely! Will have these updated!
