### ISSUE TITLE
Approve Thimble screenshots for Danish translation of Learn to Code 2

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1476]
We received an email yesterday from a Danish publishing house that publishes educational books for kids and young adults. They recently purchased the rights to translate *Learn to Code 2* from RisingStars publishing in the UK into Danish, and were inquiring about permissions for using Thimble screenshots (featured in the original book) that serve as a walk-through/tutorial. 

First, how cool that Thimble is featured in this book? http://www.risingstars-uk.com/series/switched-computing-learn-code-practice-books (scroll down to Content and you'll see we're in a book alongside Scratch and Lightbot)

Second, I've asked if they can provide the screenshots for us to review so,
1) We can be sure images are from new Thimble instead of old Thimble
2) As per legal, we need to be sure no 3rd party content is featured that might be problematic

Will share here when I receive them. 

cc @hannahkane @humphd @davidascher @flukeout @cassiemc @Pomax @HPaulJohnson @chrislarry33

**Comment by humphd** [comment]
Very cool!

**Comment by flukeout** [comment]
Awesome, let us know if we can help in any way!

**Comment by ldecoursy** [comment]
Turned out they were using screenshots from thimble.webmaker.org. I shared the new URL and they're going to update the screenshots, which likely won't happen until February. Will update here when I know more.

**Comment by hannahkane** [comment]
Putting this in a Feb milestone so we don't forget about it.

**Comment by ldecoursy** [comment]
Update: I checked in on this this week, and learned the person I was corresponding with is no longer the primary contact on this project. She said she'd connect me with the person who has taken over.

**Comment by hannahkane** [comment]
@ldecoursy - is this ticket still needed?

**Comment by ldecoursy** [comment]
I just emailed them again since I never received new contact info. I'll close this for now and re-open if/when I hear back.

**Comment by ldecoursy** [comment]
Just a note to follow-up, I heard back from the new contact - they just published the book! They never followed-through with sending the screenshots unfortunately. They are sending me a hard copy so we'll have for our files.

**Comment by ldecoursy** [comment]
Received the book - all clear. They also link to the new Thimble, and you can even watch a Danish video tutorial here: http://lærkode.alinea.dk/content.php?book=book_2#resource_2
