### ISSUE TITLE
Final design for Leadership Opportunities page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1481]
This is a new page we're creating on the Teach site.

Wireframe is here: https://redpen.io/p/uvc0135f6b8d5b5f31

Final copy is here: https://public.etherpad-mozilla.org/p/mlninitiatives

Next step is to finalize all design elements on the page.

**Comment by kristinashu** [comment]
Here's where I'm at with the comp: https://redpen.io/p/mw6aac463c1c49b796

@hannahkane @sabrinang @cassiemc please let me know if you have any feedback!

**Comment by hannahkane** [comment]
Lovely! Made two small comments.

**Comment by sabrinang** [comment]
I left some comments too and excited to see this page coming together :+1:

**Comment by kristinashu** [comment]
Thanks! I've made those updates https://redpen.io/p/mw6aac463c1c49b796

The only remaining issue is the wording of "There are a variety of ways to be a leader in the movement for a free and open Web."

@cassiemc do you have any feedback to add?

**Comment by hannahkane** [comment]
cc @ldecoursy and @KevZawacki on the copy issue. I'm finding "There are a variety of ways to be a leader in the movement for a free and open Web" awkward, but am having trouble coming up with an alternative.

**Comment by ldecoursy** [comment]
Explore ways to become a leader in the movement for a free and open Internet. 

Explore leadership opportunities in the movement towards a free and open Web.

**Comment by hannahkane** [comment]
Love the second one. Thanks, @ldecoursy!

**Comment by kristinashu** [comment]
Excellent, updated!

**Comment by cassiemc** [comment]
@kristinashu I added some comments about photo choices and ways I think we could use design to make the purpose of the programs/initiatives a bit clearer. Also think we can improve the copy on the buttons / ctas. @hannahkane you might also be interested in some of the comments around the page hierarchy which seemed ever so slightly off to me. https://redpen.io/mpd1a17be2766e666c

**Comment by hannahkane** [comment]
Thanks, @cassiemc. Agree that Fellowships ought to be promoted, in particular. Left a few other responses on the redpen.

**Comment by kristinashu** [comment]
I've updated the hierarchy so initiatives are now separated into three buckets: minimal commitment (1-3 days), larger commitment (over the course of a year), and location dependent (only available in some cities). 

Titles are focuses on leadership opportunities and CTA links go to the general event page (so users can learn more about the events before committing to them).

@cassiemc @hannahkane @sabrinang let me know if you think this direction is working then we can add updated copy.

**Comment by hannahkane** [comment]
@kristinashu - I think this is a great solution. The commitment and constraints are very clear now.

Tagging @ldecoursy for copy support. I added some suggestions to the redpen, but Lainie, perhaps you'll have edits.

**Comment by cassiemc** [comment]
I agree, this is great @kristinashu! The page hierarchy feels much much clearer to me, and more user-centred. Thanks for tackling it.

**Comment by kristinashu** [comment]
Thanks for the help! Closing and opened an implementation ticket - Implement Leadership Opportunities page #1510
