### ISSUE TITLE
[Design Audit] - Master Style Guide

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1483]
As we progress with the design audit we can document all the design decisions and progress in one place for designers and developers to refer to. Also, we can have one folder in google drive with all the assets.

cc/ @kristinashu @mmmavis @cassiemc

**Comment by cassiemc** [comment]
We're aiming to have the ```design audit``` tasks (35 open so far) by Feb 12, so in 4 heartbeats' time. Then let's take another two heartbeats to wrap up this ticket and document all the changes and design decisions, so deadline of March 11. If we can finish sooner than that, great!

**Comment by hannahkane** [comment]
@cassiemc @sabrinang - Can we clarify what the work is here for the December 25th milestone? Or should this ticket be moved to a later milestone? Thanks!

**Comment by cassiemc** [comment]
@hannahkane This was put into this milestone just for Sabrina to get started on it this week. Realistically it cannot actually be finished until the other audit work is complete (scoped tentatively for Mar 11). 

This week I'd love for @sabrinang to pick a format – ie. I am leaning toward the Github wiki and readme format, a la what @vazquez did for Webmaker (see https://github.com/mozilla/webmaker-core/blob/develop/README.md and https://github.com/mozilla/webmaker-core/wiki/Design ) as it's nice and open, easy to update, easy to link to. But definitely open to other ideas.

**Comment by sabrinang** [comment]
I'm referencing a prototype for firefox style guide (I can't share out their guide yet as it is still changing but it is schedule to be live at the end of the month). It has also adapted some [atomic design principles](http://bradfrost.com/blog/post/atomic-web-design/).  
![screenshot-ffguide](https://cloud.githubusercontent.com/assets/2492510/12399870/6d5c403e-bdd1-11e5-93af-eeed563f2c15.png)
I'm going to go through complete audit tickets and sort them in categories that work for the teach site.

**Comment by amirad** [comment]
hey all! Would love to share the style guide with an org that we have contracted to build out a pilot mobile site for Mozilla Clubs. Any estimates on when it might be done? Or in the interim, since they are going to start building in next couple weeks, is there any tips or hints I should give them when thinking of design? I pointed them to teach.moz and told them that we want it to be united with the theme of the site. cc: @cassiemc @hannahkane @sabrinang

**Comment by cassiemc** [comment]
Hmm, thanks for connecting the dots @amirad, good thinking. I'd also love an update on the styleguide, @sabrinang any word? I know the [design audit](https://github.com/mozilla/teach.mozilla.org/labels/design%20audit) work is still ongoing.

@amirad The style guide won't totally account for consistency, though. Would it be possible to have a design review between the contractor and our team before it goes into development? I definitely don't want to slow down the process but putting aside a couple hours for us to do some QA would probably save a lot of headache down the road.

**Comment by amirad** [comment]
I'm happy to share it with you @cassiemc (or whoever else you identify would be good) when we are reviewing it. I will loop you in when it's at that stage an we can come up with a plan from there.

**Comment by cassiemc** [comment]
That sounds like a plan @amirad, thanks. Also, @sabrinang is going to start pulling a guide together over the next couple days – it might be bare bones to start with but better than nothing. Feel free to connect them with me if there are any Qs in the meantime!

**Comment by amirad** [comment]
That is wonderful! Thank you both.

**Comment by sabrinang** [comment]
Got a start on this - WIP on redpen: https://redpen.io/p/rx1ad484efc903dc60

**Comment by cassiemc** [comment]
This is so awesome to see, thanks @sabrinang!

**Comment by cassiemc** [comment]
@amirad Do you know when the contractor intends to get started on this? Ideally we have a rough style guide for you before then. :)

**Comment by cassiemc** [comment]
@sabrinang Let's design this so that we don't need any dev help to implement. ie. Having it live in the teach wiki was a stellar idea! That way it's easily updatable and we can actually hack on it together to get it done. To that end I've left some comments on the redpen that should help us wrap this up. https://redpen.io/ywb006488f91162838 And we can actually just start building it here: https://github.com/mozilla/teach.mozilla.org/wiki/Style-Guide

**Comment by cassiemc** [comment]
@sabrinang FYI, I added a table of contents and accompanying pages that match the IA of your redpen. So now we just need to edit – add text and images – for each of those pages under 'Style Guide'. https://github.com/mozilla/teach.mozilla.org/wiki

**Comment by sabrinang** [comment]
@cassiemc - thanks for starting to organize it in the wiki! I'll continue documenting the style guide there

**Comment by amirad** [comment]
I have a call with them on Tuesday so can find exact dates/times then @cassiemc 
Looks like it's coming along though!

**Comment by cassiemc** [comment]
Sounds great, thanks @amirad! We are planning to have this wrapped up by end of the heartbeat, Feb 12, so this timing will probably work perfectly.

**Comment by cassiemc** [comment]
@sabrinang Can you link to your source file and I can put the images into the wiki?

**Comment by sabrinang** [comment]
@cassiemc .sketch file is located in this folder: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eNS02QktEUUZ3Zzg&usp=drive_web&ddrp=1#

**Comment by amirad** [comment]
@cassiemc this was the response from our contractor "Amira, I'd say really, we'd love the guide as soon as possible, but we're happy to have items drip fed to us, or to have your team feed back on our mock ups if they aren't ready to share the style guide! I'd love to get our dev team working on the build in the next few weeks." 
LMK if you have a finished date or anything I can send them in the interim.

**Comment by cassiemc** [comment]
@amirad It's all coming together in the wiki here: https://github.com/mozilla/teach.mozilla.org/wiki/Introduction (explore the links in the sidebar) We'll likely be editing it over the next few days but I agree something is better than nothing! We are also very open to them reaching out if they have specific questions or would like a design review/feedback, since it's all a bit of a work in progress.

**Comment by amirad** [comment]
Yes, yes! So good. Thank you! 

(and it looks lovely)

**Comment by hannahkane** [comment]
Wondering if there's a status update on this ticket? Is it likely to close this heartbeat?

**Comment by cassiemc** [comment]
@sabrinang did a great job updating this and adding examples per our last review. I just need to go through and add some text. So, @hannahkane, yes, likely to close.

**Comment by hannahkane** [comment]
hurray! thanks, @cassiemc and @sabrinang.

**Comment by cassiemc** [comment]
@hannahkane Just reviewed this now and I think we can close, woohoo! @sabrinang did a stellar job of putting this all together in the first place. We may want to file followups after further Foxlight work but for @amirad's current purposes this should totally suffice. :boom:

**Comment by hannahkane** [comment]
woohoo!

**Comment by amirad** [comment]
Yes! Looks great and serves all my partner needs :)
