### ISSUE TITLE
Create curriculum database prototype

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1490]
As we discussed, a prototype of the curriculum database could be a useful artifact to...
* Help us define what we want
* Try out our zany ideas
* Use for research

**Proposal**
Let's create a prototype that simulates the experience of an educator looking for content about web literacy. We'll use our internal content for now.

**To-do**
* Write a few user stories from the educator's point of view
  * This will help us figure out the prototype's feature set
* Figure out what curriculum we want to use
  * Use stuff from https://mozilla.github.io/webmaker-curriculum/
  * We can invent some not-yet-existing curriculum to fill gaps

**Current design work**
* Redpen https://redpen.io/p/cgf221df5b11a7be4a
* Presentation - [Curriculum Database Deck](https://docs.google.com/presentation/d/1ybSPqdH9alm8E863_fj4lBiZnshhX8a5gYQWQaRkfVw/edit#slide=id.ga39cad493_0_10)

**Comment by flukeout** [comment]
From the deck, some ideas on what we can keep track of per activity
* name
* description
* time to complete
* URL
* category (user perceived, internal)
* skill level - how is this measured
* author
  * person
  * organization
* technology 
* time 
* type
* language 
* ...
* others?

**Comment by hannahkane** [comment]
Potential user stories:
 * As an educator, I can easily find teaching content that's appropriate for my learners (e.g. age, skill-level)
 * As an educator, I can easily find teaching content that's appropriate for my context (e.g. duration, devices needed, language)
 * As an educator, I can easily discern the quality of a particular piece of curriculum
 * As an educator, I can offer feedback once I've made use of a piece of curriculum
 * As an educator without a desktop device, I can access curriculum on a mobile device

And some more advanced stuff:
 * As an educator, I can return to the database at a later time and easily find curriculum I'd thought was interesting
 * As an educator, I can submit curricular content to be considered for inclusion in the database
 * As a staff member or volunteer with admin privileges, I can review submitted curricula
 * As a frequent user of the tool, I can organize curricula into sequences useful for my learners

**Comment by flukeout** [comment]
**Discussion Question**
How much and what meta-data do we store? What about things like "learning outcomes" or "required materials"? It would be very useful to search with those in mind, but it puts extra work on the person adding it to the database to fill that stuff out accurately.

We could have optional fields maybe?

**Comment by sabrinang** [comment]
more meta-data to consider from spreadsheet: https://docs.google.com/spreadsheets/d/1cP9TOdqFNbP1qu_5aEiai1emYgcRa5IaCOfUUll0_Oo/edit#gid=1414253108

**Comment by hannahkane** [comment]
Great fodder for research questions. Would love to better understand what information is useful to people when they're searching. Let's set up some observations of people searching existing tools to understand their mental models.

**Comment by hannahkane** [comment]
Closing this, as per recent discussions to focus on creation workflows rather than search and discovery. May reopen in the future.
