### ISSUE TITLE
Few fixes on Hive site

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1492]
Can we please make the following changes at hivelearningnetworks.org?

* Remove the "Start a Hive" page from the site and main nav
* Remove Bay Area from home page (under list of Communities), Locations page (under list of Communities and contact details)
* Remove list of cities under "Coming Soon" on home page and Locations page
* On Connect page, please update link under Online Discussion Forum to https://discourse.webmaker.org/c/hive-learning-networks. Also remove Newsletter archives (never had a good system for updating that list unfort) and Hive Global Contacts

**Comment by hannahkane** [comment]
@ldecoursy - is it ok to put this in the first heartbeat of the new year?

**Comment by ldecoursy** [comment]
Yep!

**Comment by mmmavis** [comment]
:turtle: sorry for the wait.  changes are now live. :tada:

**Comment by ldecoursy** [comment]
Thank you!
