### ISSUE TITLE
Consider removing TLM page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1498]
We originally intended to build out https://teach.mozilla.org/teach-like-mozilla/, but so far we haven't been able to prioritize adding richer content.

This section got less-than-positive reviews in Laura and Bobby's [research](https://docs.google.com/document/d/1GJt1NqbBBvZGqPWIj8YUT-qXjCPfC30tfYEVfvqFwqs/edit#heading=h.7ukdb2pbvm96), and most of the content could easily fit elsewhere on the site.

I'm wondering if we can remove it from the site for now, and consider reviving it later (perhaps under a different name, since "Teach Like Mozilla" does not seem to resonate with our audience. Again, see the research report above).

Here's a proposal for how we could re-locate the content:
 * Add the values to our About page
 * Add the Web Lit Map as a sub-section under "Curriculum" (which is what we're thinking we might re-name Activities) - the whitepaper could live there, too
 * The Podcast could be moved to the soon-to-be-created Community page, or perhaps removed entirely if we have no plans to continue it

Thoughts? @chadsansing @ldecoursy @anmechung @chrislarry33 

cc @sabrinang

**Comment by ldecoursy** [comment]
+1 
We aren't continuing the podcast right away - Bobby has some ideas about that moving forward. Maybe existing archives can go on Community page?

**Comment by chadsansing** [comment]
I concur, but remain curious about where leadership materials land in the near-ish future.

**Comment by hannahkane** [comment]
@chadsansing - I think we can revive a PD page when we have that content ready to go. Not saying it doesn't belong on the site at all; just saying it's perhaps a net loss to have a not-so-great page up in the meantime.

**Comment by chadsansing** [comment]
@hannahkane, totes.

**Comment by hannahkane** [comment]
K. Thanks for helping make the decision. Filed #1506 to temporarily kill TLM page.
