### ISSUE TITLE
 [pre-footer] - implement unify all icon links above the footer

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1500]
Based on design in [pre-footer] - unify all icon links above the footer #1372 

Comp: https://redpen.io/p/brdabe854cc619f9b9
Illustrator File: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLaTN4bHo0eWNld1U/view?usp=sharing
SVGs: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLenZLWHdKTHJQMkk&usp=sharing

- Same hover area and icon zoom as on production
- Add blue link color to some text and underline blue text on hover
- Icons are smaller and have a thinner stroke than on production

**Comment by kristinashu** [comment]
cc @mmmavis

**Comment by mmmavis** [comment]
@kristinashu I'm gonna change colour of the Clubs pages icons to `#3379AC` so that it matches the Leadership Opportunities page icon colour

**Comment by kristinashu** [comment]
@mmmavis prefect thanks!

**Comment by mmmavis** [comment]
@kristinashu 
> Add blue link color to some text and underline blue text on hover

Are the icons hyperlinked as well?

**Comment by kristinashu** [comment]
Yes, it should be one big hover area - same as now. Just adding the some blue text as an extra visual cue. But doesn't matter if someone hovers over the icon or the text, it has the same effect and link.

**Comment by mmmavis** [comment]
okie dokie
