### ISSUE TITLE
Remove TLM page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1506]
- [x] Remove TLM page from main navigation
 - [x] Add Web Literacy Map as sub-menu item under Activities

(See discussion of other items [here](https://github.com/mozilla/teach.mozilla.org/issues/1498), but I think the above are the only two we need to take action on now.)

**Comment by mmmavis** [comment]
We have footer icon on https://teach.mozilla.org/activities/ and https://teach.mozilla.org/events/ linking to the TLM page. Should we just remove the icon from these two pages?

**Comment by mmmavis** [comment]
@hannahkane 

/cc @kristinashu

**Comment by kristinashu** [comment]
Lets replace the icon/link with a different one - maybe Follow on Twitter or Get Help? @hannahkane?

We can reference this JPG for all the link options https://redpen.io/p/brdabe854cc619f9b9

**Comment by mmmavis** [comment]
![fireshot capture 32 - web literacy - mozilla learn_ - http___localhost_8008_activities_web-literacy_](https://cloud.githubusercontent.com/assets/2896608/12101111/d75b281e-b2e7-11e5-964d-bf1ff77e764d.png)



@kristinashu we probably should update the line art again so that they are in pink :confounded:

**Comment by mmmavis** [comment]
@hannahkane are we okay with the url https://teach.mozilla.org/teach-like-mozilla/web-literacy/ still? I'm thinking maybe we can redirect it to `/activities/web-literacy/` instead so that it matches the sidebar hierarchy?

**Comment by kristinashu** [comment]
Just remembered the 3-up links should be removed https://github.com/mozilla/teach.mozilla.org/issues/1461 - so please go ahead and remove them.

I'll updated the top line icon to pink now.

**Comment by kristinashu** [comment]
@mmmavis here's the top icon in pink https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLSkF6QzBwaTZwUUE/view?usp=sharing

**Comment by hannahkane** [comment]
@mmmavis - good question about the url. We should change it. Is it possible to have the old link redirect to it, since it may be published in some places?

**Comment by mmmavis** [comment]
@hannahkane 

> @mmmavis - good question about the url. We should change it. Is it possible to have the old link redirect to it, since it may be published in some places?

yup, will do.
