### ISSUE TITLE
[illustration] - implement replace all filled icons with line art 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1508]
Based on design in https://github.com/mozilla/teach.mozilla.org/issues/1371

Replace solid Club icons with outline versions: (SVGs here https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLY0VNWXZLZ1ZtWFU&usp=sharing)

![teach-club-icons-01 2x](https://cloud.githubusercontent.com/assets/1068783/11945462/e02436d6-a804-11e5-9f93-2344dbceab2e.jpg)

Replace pledge icon on home page with outline version: (SVGs here https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLY0VNWXZLZ1ZtWFU&usp=sharing)

<img width="241" alt="screen shot 2015-12-21 at 5 05 08 pm" src="https://cloud.githubusercontent.com/assets/1068783/11945491/43f9ce1e-a805-11e5-8447-564e66a7f46d.png">
<img width="565" alt="screen shot 2015-12-21 at 5 05 21 pm" src="https://cloud.githubusercontent.com/assets/1068783/11945492/440a3d6c-a805-11e5-9d1c-798ac4b4c8cc.png">

with:
<img width="353" alt="screen shot 2015-12-21 at 5 06 50 pm" src="https://cloud.githubusercontent.com/assets/1068783/11945497/4a344a98-a805-11e5-89b4-f4e829c85103.png">

**Comment by cassiemc** [comment]
@kristinashu Similar to the comment made when you were looking to replace footer icons with yellow versions, I think the orange outlines get lost a little in the page (not enough contrast, esp. for people with vision issues). Maybe make them all blue?

**Comment by kristinashu** [comment]
@cassiemc I've updated all the orange icons to a darker orange (these icons and also the 3-up footer ones):
![teach-club-icons-02 2x](https://cloud.githubusercontent.com/assets/1068783/11964204/e005a904-a8a0-11e5-9b01-41bf136761b4.jpg)

**Comment by cassiemc** [comment]
Great @kristinashu

**Comment by mmmavis** [comment]
@kristinashu can you help update `icon-classroom.svg` so it's in blue! :+1:

**Comment by mmmavis** [comment]
@kristinashu can you also provide a version of `icon-classroom.svg` in blue (for the modal on homepage)! :+1:

**Comment by kristinashu** [comment]
Here you go https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLeXV0WGtrZmJxQmc/view?usp=sharing

Is there a way to change the colour of an SVG through code?

**Comment by mmmavis** [comment]
If the SVGs are always in one color I can do find/replace to update the color code used in `fill` attribute in the SVG's raw code. Not sure if we want to keep the design asset folder up to date with the files I manipulated though.
