### ISSUE TITLE
Implement Leadership Opportunities page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1510]
Based on design in #1481

Illustrator file:https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLX3dUbndDR21EUGs/view?usp=sharing
Assets: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLaG9ITWhNa3pPTGM&usp=sharing (all the logos are SVG except for the group of fellows which is PNG because there are some weird gradients and multiply effects)

Redpen: https://redpen.io/p/mw6aac463c1c49b796
![mln-leadership-comps-08 2x](https://cloud.githubusercontent.com/assets/1068783/11962410/807f3182-a894-11e5-806e-8fe9ffebf4c9.jpg)

**Comment by mmmavis** [comment]
@hannahkane 
apologies if this was stated somewhere already - what url should we give to this Leadership Opportunities page?

**Comment by hannahkane** [comment]
It wasn't. (I should really make that ticket template you suggested awhile back.)

I think /opportunities will work.

**Comment by jgmac1106** [comment]
Should there be another section pointing to MoCo resources.
Something like:

 As a Developer:
-Pretty image-Points to MDN
-Pretty image-Points to wherever contributors are onboarded or something
-Pretty image-Points to somewhere

Just an idea that we think about Leadership opportunities across Mozilla
and not just in MoFo

**Comment by hannahkane** [comment]
Interesting point, @jgmac1106. We link to the MDN Fellowship, but we could think more broadly about other opportunities to include (Reps?) Will file as a separate ticket though, since the design for this ticket is already completed.

**Comment by mmmavis** [comment]
@hannahkane @kristinashu any idea where in the sidebar we want to put "Event Resources"?

**Comment by hannahkane** [comment]
@mmmavis - ah, good question. If we don't want to do a third level in the nav (@kristinashu?), maybe we just leave it out of the nav. Users can get to it from the Maker Party page itself.

**Comment by kristinashu** [comment]
Yeah that's what I was thinking.

**Comment by mmmavis** [comment]
cool, thanks
