### ISSUE TITLE
image size on community page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1511]
Follow up to Build Community page #1434 

@mmmavis would it be possible to make the two images the same width as their text column? Can you increase the size of the image or I can make the assets bigger. Let me know what's easier. 

Staging:
<img width="1024" alt="screen shot 2015-12-21 at 4 45 09 pm" src="https://cloud.githubusercontent.com/assets/1068783/11963863/86b1a404-a89e-11e5-80a1-864fd95a18f5.png">

Comp:
<img width="878" alt="screen shot 2015-12-22 at 11 21 49 am" src="https://cloud.githubusercontent.com/assets/1068783/11963866/8aee2b64-a89e-11e5-8559-6d30178cbbce.png">

**Comment by mmmavis** [comment]
@kristinashu if you could make the assets 460px wide (and so 920px for retina) I can make sure they appear as wide as the section width. :+1:

**Comment by kristinashu** [comment]
@mmmavis here you go https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLbDJPem5qNXVIVjg&usp=sharing
Thanks!
