### ISSUE TITLE
DUE JAN 17: Promotional assets for Gigabit RFP announcement

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1514]
Background: In early 2016, we'll open up an application process for projects in Chattanooga and Kansas City to receive funding. We'll need to promote this opportunity on social media.

Questions for @LindseyFrost:
 * Where exactly will we be sharing—Twitter and Facebook? (This affects the size of the assets we create.)
 * Will the promotion include email?
 * What is the final deadline for getting you these assets?
 * For how long will you be promoting this? (Affects the number of assets we create)
 * Is your promotion local? e.g. Should we do separate versions for Chattanooga and Kansas City? Or is it something we promote globally?
 * What is the critical logistical information to include? Deadline? URL? "Projects must be piloted in Chattanooga, TN or Kansas City, MO"?
 * Can you share some ideas for messaging or taglines?
 * Do you have any preferences or requirements regarding visuals? Are there photographs you'd like to use? Illustrations you'd like to see?

@sabrinang or @kristinashu - please add any other questions you'd have if this were assigned to you

**Comment by LindseyFrost** [comment]
* Where exactly will we be sharing—Twitter and Facebook? (This affects the size of the assets we create.)

Both. 

* What is the final deadline for getting you these assets?

    January 17, 2016 for my sign off before 2 weeks of PTO

* For how long will you be promoting this? (The longer we do this, the more assets we should create. If we're going to be promoting for longer than a couple weeks, I'd suggest we do more than one or two.)

Promotional timeline:
 
January 26, 2016 - official launch with White House event (blog post, twitter/facebook messages, press outreach, etc) 
February 22, 2016 - deadline for optional Intent to Apply Form
March 18, 2016 - Deadline for Proposals 

We will be doing online and community based promotional outreach between January 26, 2016 and March 18, 2016. 

* Is your promotion local? e.g. Should we do separate versions for Chattanooga and Kansas City? Or is it something we promote globally?

Global and local. In order for projects to be eligible for funding, they need to take place in Kansas City or Chattanooga (or both). However, any company/organization is eligible to apply and receive funding, regardless of organization location as long as the pilot takes place in CHA or KC. The deadlines and URLs for submitting proposals are the same for both cities. 

* What is the critical logistical information to include? Deadline? URL? "Projects must be piloted in Chattanooga, TN or Kansas City, MO"?

Critical info: 
Mozilla Gigabit Community Fund
Projects must take place in Chattanooga, TN or Kansas City  (no designation for Missouri as projects can take place in either state in the KC metro region)
Deadline for applications is March 18, 2016
mozilla.org/gigabit

We should include the NSF logo, as they are our funder.

* Can you share some ideas for messaging or taglines?

The taglines on the website are: 
‘Learn on Tomorrow’s Networks’
‘Activating a National Gigabit Innovation Ecosystem’ (could we add ‘for Learning’ to the end to make it more educationally relevant?)

Other suggestions (taking from existing content): 
‘Moving next-generation technology out of labs and into classrooms’ 
‘Erasing boundaries between educators and technologists’
‘Making learning immediate, equitable, and immersive’

* Do you have any preferences or requirements regarding visuals? Are there photographs you'd like to use? Illustrations you'd like to see?

- Should include NSF logos for sure
- Some cute/appealing illustrations that make the content area (gigabit/high speed networks/etc) seem more approachable might be more impactful than pictures, but I leave that to you guys to decide!
- Gigabit Fund Photo Library: https://drive.google.com/folderview?id=0ByEwfEUJ9QP0fm93UHJlaFRnaXV1MmJIMjNMQjdZN0xkRU1mNm9raXJJeHlfNXNPZU9lTEU&usp=drive_web

Many thanks!  Let me know how I can help.

**Comment by sabrinang** [comment]
@LindseyFrost Can you relink the Gigabit Fund Photo Library URL? It doesn't work for me :(

**Comment by LindseyFrost** [comment]
@sabrinag I would be it seems to have disappeared entirely! AHHH!  Panic searching and will let you know tomorrow.

**Comment by LindseyFrost** [comment]
Well, @sabrinang, after about six hours of trying to find the mysterious missing folder, no luck!  So I'm trying to rebuild from scratch.  This will grow over the week:  https://drive.google.com/folderview?id=0B4nL9nCthgXlN1NFWDhtT0wwMDA&usp=sharing  There are also photos on the Hive CHA facebook page: https://www.facebook.com/hivecha/photos_stream?tab=photos_albums

In Google Drive folder, folder name is photographer credit.

**Comment by sabrinang** [comment]
@LindseyFrost Can you provide the copy for these posts so we have appropriate CTAs on the graphics to accompany them? If the post is different on Facebook than on twitter please indicate and write both. So far it looks like there are 3 posts with graphic content, for example:

**Post 1 - January 26, 2016**
Copy for FB and/or Twitter post: *TBD*
possible CTA copy for graphic: *we’re open for applications? apply now? we’re launching at white house?*

**Post 2 - February 22, 2016**
Copy for FB and/or Twitter post: *TBD*
possible CTA copy for graphic: *intent to apply deadline is today?*

**Post 3 - March 18, 2016 - Deadline for Proposals**
Copy for FB and/or Twitter post: *TBD*
possible CTA copy for graphic: *deadline for proposals is today?*

I'll export the design in various dimensions for the platform they will posted in. Also, please note that the social graphics will appear small on feeds so there shouldn't be too much text on the graphic itself but can highlight words from the post etc.
_______________

Here are two examples for post 1 could be like if the CTA is for applications opening:
<img width="1153" alt="screen shot 2016-01-06 at 4 33 32 pm" src="https://cloud.githubusercontent.com/assets/2492510/12159052/22df2d78-b494-11e5-9416-e933883ee5bf.png">

Before I get ahead of the content, is this along the lines of what you had in mind?

**Comment by LindseyFrost** [comment]
I love the one on the left, @sabrinang! This is exactly what we had in mind.  I've tried to do draft twitter posts for each of these, so we can get the appropriate CTAs.  Facebook copy will be very similar.  I think you're right that three graphics are probably exactly what we need.

Post 1 - January 26, 2016
Copy for FB and/or Twitter post: Today, we're launching our 2016 application window at the White House #eventhashtag.  Grants are available for gigabit ed tech pilots in #cha and #kc.  Apply by 3/18!
possible CTA copy for graphic: Now Accepting Applications

Post 2 - February 22, 2016
Copy for FB and/or Twitter post:  The final application deadline is 3/18, but submit an intent to apply form today to receive great proposal feedback from our Mozilla Gigabit team!
possible CTA copy for graphic: Apply by March 18

Post 3 - March 18, 2016 - Deadline for Proposals
Copy for FB and/or Twitter post:  Submit a proposal today to bring your #CHA or #KC gigabit-fueled ed tech dreams to life! 
possible CTA copy for graphic: Today is the last day to apply!

**Comment by sabrinang** [comment]
@LindseyFrost Thanks for drafting those posts and CTAs up! Take a look at these 3 post graphics on redpen and let me know what you think: https://redpen.io/p/fjaf4a6f7c15b89142

**Comment by sabrinang** [comment]
Hey @LindseyFrost can you give me feedback on what you think of the posts on redpen? https://redpen.io/p/fjaf4a6f7c15b89142 

If possible can you give me feedback by tomorrow to ensure we leave enough time for any adjustments, exporting sizes and design review before Friday since you'll be away for PTO next week.

**Comment by LindseyFrost** [comment]
Hey @sabrinang - I love them!  Apologies for delayed response.  Absolutely perfect!

**Comment by sabrinang** [comment]
@cassiemc  Design R? https://redpen.io/p/fjaf4a6f7c15b89142
- logos have been centered
- exported at 4 different dimensions for twitter and facebook usage

**Comment by cassiemc** [comment]
@sabrinang Only comment is that the more horizontal layouts would benefit from a more horizontal layout, but it's not a breaker for these, just if you have time. R+!

**Comment by sabrinang** [comment]
Thanks for the feedback @cassiemc 

https://redpen.io/p/fjaf4a6f7c15b89142
- I made layout adjustments for the horizontal layout for post 2 & 3
- For post 3, I added text "Submit a proposal" to balance out the space

**Comment by cassiemc** [comment]
Nice, @sabrinang!

**Comment by sabrinang** [comment]
@LindseyFrost The final social assets are complete and can be downloaded from this gdrive folder: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_ebGRFOTN1ci1GdTg&usp=sharing

All 3 posts are exported in 4 dimensions for facebook and/or twitter: 
<img width="1272" alt="screen shot overview" src="https://cloud.githubusercontent.com/assets/2492510/12341755/c9087566-bad8-11e5-83e0-3bf351dae8cc.png">

:sparkles: Closing this ticket! :sparkles:
