### ISSUE TITLE
Add Privacy Basics: Online Tracking module to /activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1520]
Note: We don't need to build a static page for the teaching kit. We only need to add the meta data to the /activities page.

Position: Immediately above "Privacy Basics: Passwords, Tracking, and Data Retention"
Image: https://mozorg.cdn.mozilla.net/media/img/teach/smarton/tracking/topic-think-deeper.2d1fbc329611.png
Title: Privacy Basics: Online Tracking
url: https://d157rqmxrxj6ey.cloudfront.net/mozstacy/21938/
Level: Beginner
Developed by: [Stacy Martin](https://mozillians.org/en-US/u/stacy) - Senior Data Privacy Manager at Mozilla and the Mozilla Learning Network team
Learners will complete a set of hands-on activities to better understand types of online tracking through the use of cookies and other technologies.

**Comment by chadsansing** [comment]
@hannahkane - lots of content, but meant to open folks' eyes to everything going on around them online. Let's try 'Beginner' and change it later of we get feedback re: difficulty.

**Comment by hannahkane** [comment]
Thanks @chadsansing! Updating first comment.

**Comment by hannahkane** [comment]
Needed for Internat'l Privacy Day Jan 28
