### ISSUE TITLE
Curriculum Database Research

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1522]
We've decided to kick off the new year with a little bit of research. We're going to talk to **5 educators** to find out how they currently search for and evaluate teaching materials and resources and how they would do that in a perfect world. We'll also do a little bit of observation to see how they do that today.

**Here's the outline** - [Curriculum Database Research](https://docs.google.com/document/d/1IYUVuaFy5JLFoC-EcO-YOhDeoI5dHRcYZCGM-XNx9ao/edit) - please edit!

**To do**
* [x] Finalize research questions
* [x] Finalize observation tasks
* [ ] Finalize testing setup for remote and in-person interviews
  * [Participant Sign-up Details]
(https://docs.google.com/document/d/1aIrr2fvy1_01azyhH1pmId9VBHE0wNoycFOh5ya74Lo/edit)
* [x] Create template doc for taking notes during research interviews & observations
* [x] Recruit 5 participants - #1528 
* [ ] Summarize research results - #1546

**All the docs** 
:file_folder: **[Reseach stuff folder](https://drive.google.com/open?id=0B_CPRh4f3yyqNWI1OEpxQVhmSTQ)**
* Research outline
* Participant signup
* Observation notes template

**Comment by hannahkane** [comment]
awesome. added my two cents.

**Comment by cassiemc** [comment]
Would add to the checklist, figure out your testing setup. Would be useful to record the screens / and or faces for observation and note-taking or later reflection. During the interviews it's helpful to have two people present, one observing and one taking notes.

**Comment by cassiemc** [comment]
@flukeout @hannahkane I want to commend you both for taking this on. As I was reading through the questions, it's clear that this type of user observation and testing will lead to some extremely valid insights! I'm so glad we're doing this.

I linked to this in the doc but if it's helpful, feel free to riff on this webmaker testing script from 2013 – https://docs.google.com/document/d/1PzyffnkznSukUNXD0GkAVlEMo5sEGeWp6KEFBPSRNl4/edit

**Comment by anmechung** [comment]
Great idea.  Added my 2 cents.

**Comment by flukeout** [comment]
**Benchmarking other databases**
* http://assignments.ds106.us/

**Comment by hannahkane** [comment]
@flukeout - also see #1443

**Comment by anmechung** [comment]
I did some editing of the questions including adding multiple choice responses so that one can collect background info more quickly, and grouping questions for flow.  If this is for both young people and adults, I'd recommend interviewing 5-10 educators to get the range and different perspectives.  Sending recommendations via email to @flukeout and @hannahkane with cc @chadsansing

**Comment by flukeout** [comment]
Thanks so much for your help @anmechung!

**Comment by hannahkane** [comment]
This is looking really good. Re: age of learners—I'd thought we were targeting our web lit curriculum to the14-24 age group, though of course it can be adapted for different audiences. Am I way off base, @chadsansing?

**Comment by flukeout** [comment]
But, the database itself might have curriculum that's suitable for a wider age range, yeah?

**Comment by hannahkane** [comment]
Good point.

**Comment by chadsansing** [comment]
@hannahkane, the default audience is 13+ because of ToS; however, ideally, we're always thinking about how to support leaders working with audiences of all ages.

**Comment by hannahkane** [comment]
thanks for details. broad age range it is!

**Comment by hannahkane** [comment]
Moving this parent ticket to the next milestone, since it's ongoing.

**Comment by hannahkane** [comment]
@flukeout - ok to close this ticket, since all remaining work is captured in other tickets?

**Comment by flukeout** [comment]
Sounds good!

**Comment by flukeout** [comment]
Summarized in https://github.com/mozilla/teach.mozilla.org/wiki/Curriculum-Database-Research-Findings

**Comment by hannahkane** [comment]
Looks great. Thanks, @flukeout!
