### ISSUE TITLE
Create a Curriculum Database deck to assist with research

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1523]
We already have a nice deck for [Thimble in the Classroom](https://docs.google.com/presentation/d/1CEC3YcpPIR4IRvBOaTF9b--NXLOmXFUCgpeCgcI6Dn0/edit#slide=id.p), and it would be useful to have something similar for our ideas about the Curriculum Database.

We can weave the two of them together or keep them separate.

**Questions**
* One deck for each or should we incorporate into one?
  * If we combine, might have to redo the wireframes so they are in the exact same style.
* Which screens should we include?

@sabrinang Can you post a link to the existing wireframes?

**Comment by hannahkane** [comment]
Just a note that the Thimble in the Classroom deck and wireframes could be modified to be less Thimble-specific, too.

**Comment by sabrinang** [comment]
existing wireframes in this redpen: https://redpen.io/p/cgf221df5b11a7be4a

**Comment by flukeout** [comment]
@sabrinang I reworked these three screens from your wireframes to match with the Thimble in the classroom stuff...

![image](https://cloud.githubusercontent.com/assets/25212/12280022/de7c641a-b93f-11e5-8377-f487d0ee97f4.png)

Do you think these three screens represent the bulk of the features from your wireframes?

**Comment by flukeout** [comment]
Moving to next milestone, after discussing with @hannahkane - we'll revisit these once we have more data from the research and can build wireframes that reflect what we've learned. 

cc @sabrinang

**Comment by hannahkane** [comment]
@flukeout @sabrinang @vazquez - based on our conversation today, I think we can kill this ticket for now. @flukeout will be opening new tickets that align with our content authoring/localizing/editing first approach.
