### ISSUE TITLE
Centre tools logos with headlines

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.mozilla.org#1527]
On https://teach.mozilla.org/tools/, the tools logos should be horizontally centred with the headlines. Looks like they are slightly to the left.

Here's what I see in chrome mac Version 47.0.2526.106
<img width="1014" alt="screen shot 2016-01-05 at 11 19 13 am" src="https://cloud.githubusercontent.com/assets/1186326/12120314/598fe674-b39e-11e5-8524-3a36c8860db5.png">

**Comment by thiagotomasi** [comment]
Hey @cassiemc!
I think this one it was already done! :smile: 
<img width="1235" alt="screen shot 2016-01-17 at 1 44 11 am" src="https://cloud.githubusercontent.com/assets/4387026/12375822/e3916c32-bcbb-11e5-8382-307ef493e355.png">

**Comment by cassiemc** [comment]
Yep looks good to me too @thiagotomasi!
