### ISSUE TITLE
Recruit and schedule 5 research participants

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1528]
Check #1522 for more background.

We need 5 educators who are teaching or planning to teach web literacy concepts. Ideally, we want a mix of the following attributes among our participants...

* Classroom and out of classroom teaching experience
* Age of students
* Length of time teaching

Remote or in-person meetings will work for this.

**Details**
Each session will take approximately 30 minutes will be divided into two phases: an interview & and a search task observation.

**[Participant List & Schedule](https://docs.google.com/document/d/1aIrr2fvy1_01azyhH1pmId9VBHE0wNoycFOh5ya74Lo/edit)**

**To-do**
* [x] Draft an email to send out to potential participants
  * Email text available in [Participant List & Schedule](https://docs.google.com/document/d/1aIrr2fvy1_01azyhH1pmId9VBHE0wNoycFOh5ya74Lo/edit)
* [x] Send it out
* [x] Schedule participants

**Comment by cassiemc** [comment]
@flukeout Not sure if you were planning to actually put stuff down here, but do note there are privacy issues around sharing personal details of research participants. Let me dig out those terms from Moco for you before you add anything publicly.

**Comment by hannahkane** [comment]
@anmechung @chadsansing - any recommendations for educators we might contact to participate in a 30-minute research study? As per Cassie's comments, please email @flukeout and me, rather than share contact details here.

**Comment by flukeout** [comment]
@cassiemc Yeah good point - I'll set up a separate doc for keeping track.

**Comment by anmechung** [comment]
Yes - will send via email

**Comment by anmechung** [comment]
Also - is this just a survey focused on teaching youth? Or adults too?

**Comment by flukeout** [comment]
@anmechung Ideally a mix of both, as it might change where and what types of materials they look for and use.

**Comment by jgmac1106** [comment]
I would also look to select one or two people involved in OER as they
probably have the most experience with curriculum databases.

**Comment by anmechung** [comment]
@jgmac1106 - good idea.  Can you email me with some suggestions and I'll forward?

**Comment by flukeout** [comment]
@hannahkane Could you look over the participant email draft in [Participant List & Schedule](https://docs.google.com/document/d/1aIrr2fvy1_01azyhH1pmId9VBHE0wNoycFOh5ya74Lo/edit) - if you're good with it, we can start sending it out.

Thanks for the rewrite & edits @anmechung!

**Comment by hannahkane** [comment]
R+ Looks good.

**Comment by flukeout** [comment]
Closing as this phase is finished.
