### ISSUE TITLE
Design for replacing Pledge to Teach with Newsletter Sign up

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1530]
The Pledge to Teach CTA has pretty low homepage performance compared to the other two CTAs. Additionally, participants in Laura and Bobby's research study found the language non-intuitive.

Let's replace the Pledge with a simple Newsletter sign-up

TODO:
 - [ ] Design CTA button (Icon, plus short CTA - e.g. "GET EMAIL UPDATES")
 - [ ] Design lightbox (could use copy from newsletter signup on /community)
 - [ ] File implementation ticket

**Comment by hannahkane** [comment]
@ldecoursy - would you be up for drafting new copy for the auto-email? This is an opportunity to update the existing copy which, as you mentioned, is out of date anyway (references "back to school").

/cc @chrislarry33 @kgorr @kristinashu @mmmavis @sabrinang @Pomax @adamlofting

**Comment by ldecoursy** [comment]
Happy to - can you give me a deadline?

**Comment by hannahkane** [comment]
How about final copy by end of next week, so we can implement the following heartbeat?

**Comment by ldecoursy** [comment]
ok!

**Comment by ldecoursy** [comment]
@hannahkane Draft copy is here: https://docs.google.com/document/d/1ooUGuo-i3GF1XssvgsBpYYB7FfKK2QumkRbMHW3ftgo/edit  Always open to edits :)

**Comment by hannahkane** [comment]
Thanks, @ldecoursy. Looks really good. I added a couple comments.

**Comment by ldecoursy** [comment]
Edits made!

**Comment by hannahkane** [comment]
Hi @my-le - there was a planning meeting today where we discussed assigning this ticket to you! It may not be immediately clear to you since you haven't worked on Teach.mozilla.org before, but @kristinashu, @vazquez, and I can brief you on this next week.

**Comment by vazquez** [comment]
I have briefed @my-le a little bit about this, but let's set up a meeting between @hannahkane @kristinashu @my-le and I to get specific requirements :)

**Comment by my-le** [comment]
@hannahkane, @kristinashu, @vazquez: “Pledge to Teach” button and lightbox are on Red Pen > https://redpen.io/p/kw3181d1724543c4f2

**Comment by hannahkane** [comment]
nice! I don't have a strong preference on the lightbox options. @kristinashu @vazquez - do you?

**Comment by adamlofting** [comment]
Flagging this ticket for @alicoding as he's working on switching the corresponding forms to ExactTarget this week.

**Comment by kristinashu** [comment]
Looks great @my-le! I just made a few little comments in the ticket.

**Comment by hannahkane** [comment]
Do we have a final version for this? Wondering if we should send this along to implementation?

**Comment by my-le** [comment]
@hannahkane If CTA's title is correct for you, I will send the icon file.
For the lightbox:
1) Text: I will make text changes (“Subscribe” + “privacy policy" in blue as currently on teach.mozilla.org)
2) Design: I would like to have @vazquez 's opinion about the version we keep.

**Comment by hannahkane** [comment]
Thanks, @my-le. 

Yes, I think "Get Email Updates" works.

**Comment by my-le** [comment]
@hannahkane Where could I upload the icon?
“Newsletter Subscribe” icon is based on “Teach an activity” icon (size and color).

**Comment by kristinashu** [comment]
@my-le I've just created a folder in our Teach drive where you can upload your files: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLb0Z2ZmlJNEhKSFE&usp=sharing

Could you please add your working file (for our future reference) and an SVG of the letter/envelope icon (for developer)? 

The little mail icon and the check mark should be from Font Awesome so you don't need to export those. Thanks!

**Comment by my-le** [comment]
@kristinashu You will find in the folder: AI working file, AI icon and SVG icon.

**Comment by vazquez** [comment]
I agree with @kristinashu that based on the brand the first option works best. Between us, I do like the coloured background better though :yum: 

![screenshot 2016-02-24 09 38 52](https://cloud.githubusercontent.com/assets/1119821/13288556/70f8cd0e-dada-11e5-93e3-3b27335957de.png)

**Comment by kristinashu** [comment]
Thanks @my-le! Could you also please add the illustrator file with the button and modal (just in case we need to edit it in the future)? And then update redpen to show only the final version (so that it will be totally clear to dev which one we're doing). Then I think we're good to close this ticket!

**Comment by my-le** [comment]
Please find in Teach drive folder:
– Icon: AI, SVG, working file
– CTA: AI, AI outline, PDF
– Lightbox: AI, PDF
+ Lightbox Final preview on Red Pen: https://redpen.io/vyb434e9f95b33a898

**Comment by kristinashu** [comment]
Excellent! Thanks @my-le
