### ISSUE TITLE
Copy audit

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1532]
Revisit all site copy with the following goals in mind:
 * Use inclusive language - no jargon or buzzwords
 * Frame everything in the context of the community, rather than "us"
 * Provide great onboarding (offer explanations of original concepts and ideas; offer first steps for first time visitors)
 * Make stronger case for Mozilla's role in education (e.g. showcase history, credibility in this area; remember that for many people Mozilla is not immediately associated with this kind of work)

To reference: many relevant comments in Laura and Bobby's [research](https://docs.google.com/document/d/1GJt1NqbBBvZGqPWIj8YUT-qXjCPfC30tfYEVfvqFwqs/edit#heading=h.ypdd3nrom6c6)

Outcomes:
 * revised copy on site
 * perhaps add'l content, e.g. a history of our education work on the About page
 * copy styleguide for future use

**Comment by hannahkane** [comment]
Wondering if @ldecoursy and @KevZawacki would like to be involved in this work? Timeframe is probably flexible.

**Comment by hannahkane** [comment]
Also, perhaps styleguide should be more of an org-wide venture? @chrislarry33?

**Comment by ldecoursy** [comment]
Delayed reaction, but I'd be willing to work on this copy audit for the site. MoFo styleguide might be up @KevZawacki's alley though? ;)

**Comment by KevZawacki** [comment]
@hannahkane I'm split between encryption and Open Web Fellows at the moment, but am happy to review/revise specific sections, if you flag them.

@ldecoursy It's on my list :-)

**Comment by cassiemc** [comment]
Related... https://github.com/MozillaFoundation/plan/issues/694

**Comment by hannahkane** [comment]
I'm probably not going to prioritize this for awhile, since there are many more urgent projects going on. Will keep it in the backlog.

**Comment by hannahkane** [comment]
Closing as out-of-scope for now.
