### ISSUE TITLE
Set up Community newsletter template & content into Exact Target 

### ISSUE THREAD

**Issue by KGorr** [mozilla/teach.mozilla.org#1534]
Starting in January, we'll be sending a monthly newsletter to the MLN community via Exact Target. This ticket is to input the design template, and the January content, into Exact Target.

**Design Template Ticket here**: https://github.com/mozilla/teach.mozilla.org/issues/1428

**January content here**: http://mzl.la/1OdyVA5

**Comment by KGorr** [comment]
@stephaniemcv @ldecoursy @mmmavis

**Comment by hannahkane** [comment]
@kgorr - Do you have a target date for sending?

**Comment by KGorr** [comment]
Pending approval on communication plan from @ldecoursy...

**Comment by ldecoursy** [comment]
Ideally we can get this out no later than Jan. 28. Preferably the week of the 18th.

**Comment by hannahkane** [comment]
If possible, I'd rather not add to the current heartbeat, which ends Jan 15th, and is very full. We can put it at the top of the list for the heartbeat that *starts* on the 18th. Does that work for you?

**Comment by ldecoursy** [comment]
That would work. Adding @stephaniemcv too as I know she and @KGorr had an initial convo about this.

**Comment by hannahkane** [comment]
Apologies—didn't realize @stephaniemcv had already been consulted. @stephaniemcv - feel free to assign this ticket to yourself if you're able to implement the January mailing.

**Comment by ldecoursy** [comment]
@stephaniemcv Anything else you need from us to prep this?

**Comment by stephaniemcv** [comment]
No, jsut as FYI, we will need to adjust the template slightly to minimize rendering issues. @lovegushwa is sharing some wire-framing with @kristinashu who will tweak.

**Comment by hannahkane** [comment]
just confirming - @stephaniemcv - you're available to implement after @kristinashu makes design tweaks?

**Comment by stephaniemcv** [comment]
Yup!

**Comment by hannahkane** [comment]
Awesome. Thank you! 

cc @simonwex

**Comment by KGorr** [comment]
@stephaniemcv, there is a short 3 question survey that we'd like to include in this newsletter to ask for feedback. Can this be done in the newsletter itself, or do we need to create a google form? The intro copy is already in the content draft...just need to add a link or the Qs directly. 

If it is a link, I'll create it ASAP. If it can be done directly in the newsletter copy, I'll add the 3Qs to the content draft. Thank you!

**Comment by KGorr** [comment]
@stephaniemcv, I should also add that the survey is currently housed in the announcements section of the template.

**Comment by stephaniemcv** [comment]
We will need to create form that you can link to. 
Unfortunately email clients consider forms in emails to be a security risk. While some email clients simply warn you of potential danger, others outright disable the forms or dump the email in SPAM folders.

**Comment by ldecoursy** [comment]
Good to know, and thanks again for your help with this @stephaniemcv 

If we were to remove the survey from this newsletter (and add it to a future one), what would the ETA be for sending it out? Asking because some of the content is timely (Hive Chicago Buzz is this weekend, and Privacy Month ends next week).

Thanks!

**Comment by stephaniemcv** [comment]
I'm going to try and get you a reviewable version by tomorrow afternoon. ETA depends on if we've got the audience correct and some coding issues with the template. 

I've been doing some more digging and I think someone may have already got your audience associated with the data extensions in ExactTarget. Does approx 125,000 sound about right for your previous email sends?

**Comment by davidascher** [comment]
I'll suggest that @adamlofting be involved in the survey topic if he isn't
already, as we need to build capacity to sample our audiences on a bunch of
levels.  For example, we might want to do a separate survey-specific
mailing to a subset of the group if it's really 125k people (which is
larger than I expected, but awesome if true).

--da

**Comment by adamlofting** [comment]
125k sounds right to me based on historic high profile CTAs like the snippet promoted pledge to teach. But, most of these people won't have heard from us after that action - so expect an initially cold response from most of them, and high unsubscribes for email 1. That will smooth out over time.

I'm happy to help with surveys. I have a login for the moco surveygizmo.com account which has been vendor reviewed etc. And we've been using it for End of Yeat and upcoming Encryption Campaign.

**Comment by KGorr** [comment]
Thanks for the support! 

With @HPaulJohnson's help, we sent a survey to that a sample of that list in November, I believe. The summary report can be found here: https://docs.google.com/a/mozilla.com/document/d/12YqskxpFMbLdWeS12NzwfsAWrH25UtvXdEWwQ0qA-m8/edit?usp=sharing.

The survey we are looking to do for this round (which can be pushed to next month if it will hold up sending) is a simple "what do you think of this newsletter" type feedback.

**Comment by stephaniemcv** [comment]
Here is the email loaded into Exact Target. Things to address:
-I did not code in the background image (partly due to time, partly because it's not always supported by email clients), but I'm not happy losing that design element. I propose making the intro text and background one image. This will mean the intro text will always need to be short so we can keep the font size large enough to scale well on mobile.
-Do we have a style guide for Teach? I used websafe fonts but I'd like to stay consistent with the brand.
-2 columns content area, leveling should be finished by end of day.
![2016-1-mln](https://cloud.githubusercontent.com/assets/11812272/12557400/c808d58a-c347-11e5-9a7b-30f86fa9b3db.jpg)

**Comment by hannahkane** [comment]
cc @kristinashu and @sabrinang for style support

**Comment by KGorr** [comment]
Thanks @stephaniemcv! I am planning to keep the intro paragraph to one sentence, so that shouldn't be a problem.

**Comment by stephaniemcv** [comment]
Great! Then we'll just need to decide in the process if that text is handed off to a designer to create the image or if I'll have access to the background file and create it as the email is built.

**Comment by kristinashu** [comment]
@stephaniemcv have you seen the work @lovegushwa is doing on this? He's trying to align both this email and the advocacy emails with FF+You https://redpen.io/p/vfdf531416d978c198 and https://redpen.io/p/xkd67d3afe0c3c922f 
I think FF+You is already built in Exact Target so we know what is/isn't possible. Would you be able to align it more with those examples? This way we can move towards a similar template for all our emails.

**Comment by stephaniemcv** [comment]
Yep, @lovegushwa and I have chatted. And the code in this newsletter is based off of the FF+You code in Exact Target. I am confirming now, but from my examination of the code in previous FF+You emails, they don't use background images and float text over the top of it.

**Comment by stephaniemcv** [comment]
Have confirmed with @bniolet1 that background images are not used in FF+Y since they don't render in Gmail and 25% of their audience would see black instead of the background image.

Should we set up a meeting to discuss how we can best align these templates?

**Comment by kristinashu** [comment]
@stephaniemcv here's the updated comp: https://redpen.io/p/au9c53b3ae1141ebbc
All the styles should be from the FF+You template except for the bottom where I've adjusted the links so they are now 4 buttons. Redpen comments have the color values. Hope that makes it easier for you but let me know if you have any questions! 
cc@lovegushwa

**Comment by hannahkane** [comment]
Just received the newsletter! Looks awesome. Can we close this ticket?

**Comment by KGorr** [comment]
Woo! Yes, this can be closed.
