### ISSUE TITLE
Design Encryption Campaign promo banner for teach site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1535]
The Encryption Campaign kicks off on January 28th. There will be a landing page for it that we can point to from the Teach.m.o promo space (this will replace the Thimble banner).

cc @HPaulJohnson @brettgaylor @valianttry to advise on copy and design

**Comment by hannahkane** [comment]
cc @ldecoursy

**Comment by cassiemc** [comment]
Better include @lovegushwa for design perspective

**Comment by hannahkane** [comment]
@lovegushwa - do we have some design assets we can use to make a promotional banner for the Teach site?

**Comment by kristinashu** [comment]
Linking this to audit ticket about standardizing these promo banners https://github.com/mozilla/teach.mozilla.org/issues/1394

**Comment by lovegushwa** [comment]
@hannahkane we should have something for you next week.

**Comment by hannahkane** [comment]
cool. Thanks, @lovegushwa. Moving to next heartbeat.

**Comment by hannahkane** [comment]
@lovegushwa - any update on this?

**Comment by kristinashu** [comment]
@lovegushwa @sabrinang can you please take a look at the banner below?

I'm trying to keep it fairly neutral so it doesn't compete with the main teach banner with the 3 CTAs. 

![teach-homepromobanner-01 2x-01](https://cloud.githubusercontent.com/assets/1068783/12762745/885843e4-c9a5-11e5-94f7-338d3fc311db.jpg)

**Comment by sabrinang** [comment]
+1 to grey banner so that we can use coloured logos instead of colouring the background incase those colours clash with the teach palette. Removing the promo button here looks a lot cleaner since it makes it less visually distracting from the button heavy hero banner we have right above it.

**Comment by cassiemc** [comment]
@kristinashu Can we strengthen the CTA somehow?

**Comment by kristinashu** [comment]
@cassiemc here are two more options:

![2x-02](https://cloud.githubusercontent.com/assets/1068783/12789639/787cb294-ca53-11e5-8649-1fa443ec323f.jpg)

![2x-03](https://cloud.githubusercontent.com/assets/1068783/12789638/787c5f56-ca53-11e5-98a3-aa35ad90ef9d.jpg)

**Comment by lovegushwa** [comment]
These are great @kristinashu I like the second option. Also yesterday @natalieworth designed and shipped a mozilla.org tile that you could steal from (designed to play well with other Mozilla assets). https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0dDRFRElzVlVDMTQ/view?usp=sharing

**Comment by cassiemc** [comment]
Let's discuss at crit today?

**Comment by kristinashu** [comment]
Going with this version:
![2x-02](https://cloud.githubusercontent.com/assets/1068783/12797226/b7818e28-ca77-11e5-8c1c-b38d22990c1f.jpg)

I've opened an implementation ticket here https://github.com/mozilla/teach.mozilla.org/issues/1619
