### ISSUE TITLE
Change links to Web Lit Basics activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1537]
Currently, on https://teach.mozilla.org/activities/web-lit-basics/, we link to six activities that live in http://mozilla.github.io/webmaker-curriculum/

@soapdog has been overseeing a project to get those activities localized into several languages (yay!). The translations are accessible via a dropdown menu on a different version of each of the six activities. Here are the EN versions of each activity. Note the dropdown menu in the top right corner of each.

http://mozilla.github.io/mozilla-club-activity-kraken-the-code/#en
http://mozilla.github.io/mozilla-club-activity-ping-kong/#en
http://mozilla.github.io/mozilla-club-activity-hack-the-news/#en
http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#en
http://mozilla.github.io/mozilla-club-activity-web-chef/#en
http://mozilla.github.io/mozilla-club-activity-story-of-us/#en

I propose that we change the links on /activities/web-lit-basics to point to the above links. This allows users to access the translated versions as well.

This isn't a great long-term solution (users will have to know where to go to access the translations), but in light of the curriculum database project, this feels like a decent stop-gap.

cc @chadsansing @soapdog @ldecoursy - does this plan sound alright to you?

**Comment by hannahkane** [comment]
We also have a bit of a versioning problem now, since we have two EN versions of each activity. Should we consider the newer ones canon now?

**Comment by ldecoursy** [comment]
I like it - we can describe in the blog post how to access the translated content. Other solution to link to the translations from each of the individual activities would take more time/resources, including adding new translations, where the solution Hannah outlines will take new translations into account more automatically.

**Comment by soapdog** [comment]
CC @soapdog

**Comment by ldecoursy** [comment]
@hannahkane Keep me posted on timing for this so we can publish blog post once the links are live.

**Comment by hannahkane** [comment]
@mmmavis - this is a P1 that's not blocked on anything. Possible to finish this heartbeat?

**Comment by hannahkane** [comment]
ping @mmmavis  - possible to do this today or tomorrow?

**Comment by mmmavis** [comment]
Sorry to miss the ping. I'll get a PR in today and push a new release next Monday.

/cc @Pomax

**Comment by hannahkane** [comment]
@mmmavis - were you able to push a PR for this? If not, I'd suggest re-assigning to @Pomax.

**Comment by mmmavis** [comment]
@hannahkane not yet. I wanted to finish reviewing the existing build system PRs that Pomax submitted first. I should be able to get this live today. (will update you if I fail to do so)

**Comment by mmmavis** [comment]
Reassigned to @Pomax :dancer: Thanks Pomax!

**Comment by Pomax** [comment]
I've updated them to the above links, although with an eye on our encryption/security campaign (and best practices really =), I'm using the https:// links, rather than the http:// version

**Comment by ldecoursy** [comment]
@Pomax @hannahkane I'm not actually seeing these versions live on the site yet. I tried refreshing - let me know if we're still waiting to push them live or if I'm missing something. Thanks!

**Comment by hannahkane** [comment]
I don't think we've done a push to production recently. @Pomax - do you have a time in mind to roll production?

**Comment by hannahkane** [comment]
@Pomax - should I be seeing this change on the production site, since we rolled it yesterday?
