### ISSUE TITLE
Create remixable curriculum template in Thimble

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1538]
We've done a bunch of work on the template so far in #1360 - it's time to take that work and create a useable template in Thimble.

**To do**
* [x] Remove the Kraken the Code content and make things generic
* [ ] Create a markup guide similar to the one for tutorials within Thimble ([This one!](https://thimble.mozilla.org/tutorial/tutorial-style-guide.html))
* [x] Test by trying to convert existing content into this format, or by creating a new activity (@chadsansing)
  * [ ] Make notes about what's working and what's not
  * [ ] Potentially observe, record this process
* [ ] Come up with a default image for the sidebar
* [ ] Come up with a placeholder image for the content (to illustrate how to use them)
* [ ] Design a favicon
* [x] Test template & make defensive CSS when long strings in...
  * [x] Activity title
  * [x] Activity step name
  * [x] Photo attribution in aside
  * ... others?
* [ ] Test template & make defensive CSS for giant images in...
  * [ ] Aside thumbnail
  * [ ] Aside without a thumbnail at all
  * [ ] Images in the agenda steps

For making & testing the CSS changes listed above, I'm using the [Curriculum Template - Updates](https://d157rqmxrxj6ey.cloudfront.net/flukeout/24615/#overview) project.

**Bugs**
* [x] Aside gets too wide in [Chad's project](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24387/#overview)
* [x] Title overlapped by Remix button in [Chad's project](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24387/#overview)

**Questions**
* [ ] Should we keep the base CSS & JS as separately so we can update them independently of the curriculum? For example - there are no ways for me to fix Chad's project without him editing it.
  * One solution would be to maintain the Curriculum Template as a home for the CSS file that the rest of the templates link to. This has the downside of locking it into one persons's account - so maybe a github hosted stylesheet is a better approach.
* [ ] Is this approach useful and scalable? Will get some insight based on discussions with @chadsansing on Tuesday.

**Notes from Chattin' with Chad**
* Add a guidelines.html maybe for some tips and tricks for using the template
* Host the CSS externally from the template so that fixes can be made globally
  * Comes with some risks - but seems like a good option
* Make a markup guide like we do for Thimble
  * Include a video embed example
* Explore feasibility of version with separate .html pages for each step

**Comment by chadsansing** [comment]
Ready, steady, go! Can test beginning late next week (post travel).

**Comment by jgmac1106** [comment]
Let me know if you need any help testing it. We are getting ready for
#walkmyworld. It will be Thimble heavy.

**Comment by chadsansing** [comment]
I say, 'Jump in!', @jgmac1106!

**Comment by hannahkane** [comment]
Just a note for @chadsansing and @jgmac1106  - given #1537, we might want to start testing with a module other than Web Lit Basics, because the l10n aspect adds an extra wrinkle.

@flukeout - We do need to consider l10n as one of the requirements for curriculum formats moving forward, though.

**Comment by jgmac1106** [comment]
Is there a link to the Thimble project? I will play with Bridge to Infinity.

**Comment by chadsansing** [comment]
@jgmac1106: try https://d157rqmxrxj6ey.cloudfront.net/chadsansing/22265/.

**Comment by jgmac1106** [comment]
not the bridge project but the curriculum template project.

**Comment by chadsansing** [comment]
D'oh.

**Comment by flukeout** [comment]
I'm working on it now, and will add it to this ticket when it's ready, probably later today!

**Comment by flukeout** [comment]
@chadsansing Hey so I've published the curriculum template here:
https://d157rqmxrxj6ey.cloudfront.net/flukeout/17698/#overview

When you have a chance, could you please attempt to transfer an existing piece of curriculum (or a new one you're working on) to this template? When doing so, please make notes of what's working well and what isn't so that we can evaluate this approach.

Please ping me if you have any questions. If you're up for it, I'd also be interested in watching you do this over a screenshare.

Cheers!

**Comment by flukeout** [comment]
I'm already noticing some weird scrolling problem with the navigation, I'll resolve that.

**Comment by jgmac1106** [comment]
typo line 46 in the javascript file has hash*

**Comment by flukeout** [comment]
@jgmac1106 Thanks, fixed!

**Comment by hannahkane** [comment]
Gonna roll this into the next heartbeat, because I don't think we'll finish testing by tomorrow. :)

**Comment by chadsansing** [comment]
Here is a test activity - image/sidebar skews way big. User error?

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24387/#overview

**Comment by jgmac1106** [comment]
In line 131 of CSS you can play with the image size and reduce it from 100%.

You also chose a rectangular image. When I choose a square image for the
aside it works fine.

**Comment by chadsansing** [comment]
Image resize in CSS results in changing the image width without chancing the aside width.

**Comment by flukeout** [comment]
@chadsansing @jgmac1106 Thanks for looking into this. Looks like the longer step titles in Chad's activity caused the aside expand, and it didn't have a ``max-width`` rule, which I'll add.

**Comment by flukeout** [comment]
@chadsansing I made an updated stylesheet for the curriculum template, it's hosted here...

https://d157rqmxrxj6ey.cloudfront.net/flukeout/24615/css/style.css

Can you make your project reference this new one instead of the embedded one? Once you do, let me know if it's solved the problems you were having with the layout issues in the aside. Thanks!

**Comment by chadsansing** [comment]
@flukeout, success!

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24387/#overview

**Comment by hannahkane** [comment]
Is the checklist at the top of this ticket up-to-date? Wondering if we'll need to roll this ticket into the next heartbeat.

**Comment by flukeout** [comment]
@hannahkane Let's roll it into next. I'm reviewing @chadsansing's latest notes from his experience using it now, so there will be some updates for sure.

**Comment by flukeout** [comment]
**Chad's latest feedback**
* [ ] On the last step of a lesson, have a next button or link.
* [ ] Link from the header on each step back to the module index and the lesson overview.
* [ ] Increase font-weight of bold/strong.
* [] How does <figure> work? CSS? Why not <img>?
* [ ] Default to 'Made by Mozilla' w/ teach dot link? To 13+ for age?
* [ ] Just curious: when do we use <b> rather than <strong> these days?
* [ ] Anxious for new competency & button bootstrap color/naming conventions for Web Lit Map 2.0. Competencies link to Web Lit Map 2.0?
* [ ] If I am at the end of step 3 (for example) and then click on step 4, step 4 displays at the same relative position, not at the top of the step.
* [ ] Line-spacing after </ol> or </ul> is too short before a new paragraph.
* [ ] Standardize image width & height? Or provide best practice ratio/size in comments?
* [ ] Code tag - needs more contrasting color and/or background.
* [ ] Back buttons/links to other activities in the same module would be great - maybe solveable by linking the header/module name/lesson name?

**Comment by flukeout** [comment]
Feedback from Educator using an activity
* Easy to read, easy to navigate, and sleek design!
* There is a lot of white space to the right of the page - is that something that can be fixed? The sleek layout would look that much better if the content took up the entire page.
* When I click through the navigation buttons to the left of the page, it takes me to the next page, but is set to the bottom of the page and I have to scroll up to the top to start reading.
* After going through several pages, I realized it is going to the next page set to wherever you are on the previous page. For example, since I read through page A and am now at the bottom, it takes me to the bottom of Page B. But if I were to be reading the top of Page A and click to Page B, it will take me to the top of Page B. Does that make sense? It really should always be taking you to the top of the next page.
* The italics paragraphs that are meant to be facilitator notes are a little hard to decipher from the rest of the text. It's not a huge deal, but you may consider bolding it or putting a gray box around it. Just something to distinguish a bit.
* Is there going to be a way to navigate from activity to activity without having to click through all the others?

**Comment by flukeout** [comment]
@chadsansing Can you link an activity that has Facilitator Notes, as referenced in the feedback above?

**Comment by chadsansing** [comment]
Last paragraph of step 2 [here](file:///Users/csansing/GitHub/curriculum-testing/curriculum-migration/web-lit-basics-two-migrated/session01-why-do-we-use-the-web.html#step-2). Just em tagged for now.

**Comment by chadsansing** [comment]
Could also consider building in a Read, Write, or Participate line above the web competency buttons and a 21st century skills line below it so we can reflect Web Lit Map 2.0 things on the template.

**Comment by flukeout** [comment]
Closing since it's probably not going to be Thimble template anymore - but will move to a new ticket as we continue to iterate.

**Comment by hannahkane** [comment]
@flukeout - did you intend to leave this open?

**Comment by flukeout** [comment]
@hannahkane Did not, thanks!
