### ISSUE TITLE
Update distro list for new Club submissions

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1541]
Can we update the list of folks who receive individual notifications when Clubs are submitted?

@amirad Can you share your preferred list?

**Comment by amirad** [comment]
Hmm,

Myself
Kristina
Lainie (?)

I really don't see the point of having too many people on it so minimizing the list is probably a good idea!

**Comment by ldecoursy** [comment]
I don't need to be on it ;)

**Comment by amirad** [comment]
lolz

Then just Kristina and I are probably needed for now.

**Comment by hannahkane** [comment]
@mmmavis - can I assign this one to you?

**Comment by mmmavis** [comment]
just self-assigned

so just keep Kristina Gorr and Amira on the list?

**Comment by hannahkane** [comment]
yep.

**Comment by mmmavis** [comment]
Updated! Amira/Kristina Gorr/Hannah/myself are on the distribution list now.

**Comment by amirad** [comment]
Thank you!
