### ISSUE TITLE
Add "Regional Coordinator" field to Clubs application form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1544]
Some Club Captains are recruited by RCs, and therefore don't need to be matched up with one after their application is approved. However, we can't know this based on the information provided in the application form.

Let's add an optional field, after the Website field, with the label: "If you already have a Regional Coordinator, please include their name (optional)" with the field helper text "Leave this blank if you'd like to be matched with a Regional Coordinator"

This field should also be added to the Clubs admin interface.

**Comment by hannahkane** [comment]
cc @amirad and @kgorr to approve copy and placement

**Comment by KGorr** [comment]
We have this RC question in the interview form (last Q): https://docs.google.com/a/mozillafoundation.org/forms/d/1J-S6nKTHd-yLzcWaE6Wu3pFesSYYdr3yfPlGECOPp44/viewform
I don't manage the RC process at all, though, so @amirad will have to speak to the usefulness of adding to the initial application.

**Comment by hannahkane** [comment]
Oh, maybe I misunderstood. Thought it was desirable to have this question in the initial form, but if not, we can close this ticket. @amirad - can you please advise?

**Comment by amirad** [comment]
I'm curious as to whether clubs who have RCs don't submit the survey (so many reasons this could occur, they don't think they need too, language barrier etc.). I think we should move it to the website.

"If you already have a Regional Coordinator, please include their name (optional)" with the field helper text "Leave this blank otherwise" (we aren't matching new clubs that sign up at the moment so don't want to imply they will be matched!).

**Comment by KGorr** [comment]
So, to confirm @amirad, I should remove this question from the interview form?

**Comment by hannahkane** [comment]
I know this was probably mentioned as an idea before and maybe I objected at the time, but wondering if we should just add the survey questions to the initial form on the site.

Is there value in having this be a two-step process?

If we want to combine, I have a few suggestions about how to modify the questions in the survey for inclusion in the form.

@amirad @KGorr ?

**Comment by KGorr** [comment]
I am totally fine for making it all one step. The more streamlined, the better!

**Comment by hannahkane** [comment]
If Amira agrees, I'd suggest we edit the form to go like this:

Title of form: Apply to be a Club Captain

[Remove text about waiting list]

Section 1: About You
**What is your full name?**
**What is your Twitter handle, if applicable?** optional
**How did you hear about Mozilla Clubs?** 
[helper text: Event, Friend, Regional Coordinator, Twitter, teach.mozilla.org, etc.]

Section 2: About Your Club
**What is the name of your Mozilla Club?**
[helper text: "Mozilla Club Rio," for example]
**Where is your Club located?**
[helper text: Type in a city or country]
**What is your Club‘s website?** optional
[helper text: www.myclubwebsite.com]
**Can you tell us more about how you'll organize your Club?**
[helper text: Please include where your club will meet, topics you'll cover, how frequently, and the audience you want to serve.]
**Why do you want to host a Mozilla Club?**
[helper text: Include what you will be able achieve with your club that you could not do before.]
**Are you currently working with a Regional Coordinator?**
If yes, please type their name below. 

Note: I'm suggesting we remove a few fields, because they don't seem necessary to the approval process, but please correct me if I'm wrong—
 * Who is your Mozilla Club affiliated with? (currently on the web form)
 * How do you teach the web? (currently on the web form)
 * I have read the Mozilla Clubs Fact Sheet. (currently on the web form)
 * Email address (currently on google form, but we'll have this from their login info)
 * Do you have access to devices and resources to teach? (on google form)

**Comment by KGorr** [comment]
@hannahkane, if @amirad is OK with these changes, can we change the helper text for the both "Can you tell us more about how you'll organize your Club?" and "Why do you want to host a Mozilla Club" to include "Please be as detailed as possible." Some folks are writing 1 sentence responses (with 5-8 words in said sentence), so I'm following up with an email to try to get more details.

**Comment by hannahkane** [comment]
@Kgorr - good idea. Could we be even more specific? What length of content is desirable—4-5 sentences? 2-3 paragraphs? We can indicate that with copy and with the size of the box we show.

@amirad - what do you think about all of the above?

**Comment by hannahkane** [comment]
Adding the "blocked" label, because we can't start working on this until we finalize the content.

**Comment by KGorr** [comment]
Suggestion:

Can you tell us more about how you'll organize your Club?
[helper text: Please include a short paragraph about where your club will meet, topics you'll cover, how frequently, and the audience you want to serve.]

Why do you want to host a Mozilla Club?
[helper text: Please include a short paragraph about what you will be able achieve with your club that you could not do before.]

I think saying "short paragraph" makes it seem less daunting but expresses that we are looking for details. Open to feedback though!

**Comment by amirad** [comment]
Sorry for blocking. I'm torn because we have a lot of people who sign up but then don't engage and follow-up with the questions which let's us weed out those that are not going to engage in that second step. 

I do like those questions for the initial sign-up though.

**Comment by hannahkane** [comment]
@amirad - can you clarify whether you want this to be a one-step or two-step process? If the above questions become the initial sign-up form, what would be the second step?

(Note: If we do make this a one-step process, we'll need to change the auto-email so that it *doesn't* link to the google form, but instead describes a different expectation about what's coming next.)

**Comment by hannahkane** [comment]
pinging @amirad so we can unblock this for the next heartbeat

**Comment by amirad** [comment]
I'M SUCH A BLOCKER! 
So yes, one step for now and when we have training up and running that will be the second step before the club gets approved. Will figure out process once it's ready to implement.

**Comment by hannahkane** [comment]
OK, I'm going to suggest we hold off on these changes until we have the training up and running. Does that work?

**Comment by amirad** [comment]
Sure!

**Comment by hannahkane** [comment]
Closing this ticket in lieu of a new one I'm going to file, based on [this](https://docs.google.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit)
