### ISSUE TITLE
Summarize research results

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1546]
Format TBD

**Comment by hannahkane** [comment]
Assigning to @flukeout, but also @sabrinang

**Comment by hannahkane** [comment]
@flukeout - can you provide an update before you leave today? If it's just wikifying a doc - you can delegate that to me, if you need to.

**Comment by flukeout** [comment]
@hannahkane The summary is here https://docs.google.com/document/d/1QQAPepC9gWSzMUCx-IrSiWUwCRDCVktYiL1EBEupXZQ/edit - it's about 95% done and will be converted into a WIKI on Tuesday morning.

**Comment by hannahkane** [comment]
@flukeout - great summary. I added a few questions.

**Comment by hannahkane** [comment]
Closing because work is summarized here: https://github.com/mozilla/teach.mozilla.org/wiki/Curriculum-Database-Research-Findings
