### ISSUE TITLE
Add "Reason for Denial" field to Clubs admin

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1549]
When we mark a Club as Denied, we should be able to choose a reason from a picklist. The possible reasons are:
* no longer interested
* not qualified
* no response after initial application
* email bounces

**Comment by hannahkane** [comment]
@kgorr and @amirad - does this look good to you? I consolidated the reasons, but let me know if they should be expanded.

**Comment by KGorr** [comment]
This looks greats to me @hannahkane!

**Comment by amirad** [comment]
yes looks good @hannahkane

**Comment by hannahkane** [comment]
@Pomax - assigning to you as part of Teach site work. Let me know if I can help clarify the task here.

**Comment by hannahkane** [comment]
blocked bc we don't have anyone currently available to work on teach-api stuff

**Comment by hannahkane** [comment]
@pomax - were you able to get to this? If not, I'm going to take it out of the milestone.

**Comment by Pomax** [comment]
moving to the next milestone - @simonwex and I will look at this on monday, as getting the Teach-API to run properly for testing/extending, without someone familiar with doing that, is proving to be rather tricky
