### ISSUE TITLE
Is the "private-eye" activity actually used?

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1589]
There is a "private eye" activity, active on https://teach.mozilla.org/activities/private-eye/, but it doesn't look like there is a way to get to this activity from the activities list. Is this still a real activity?

**Comment by hannahkane** [comment]
I believe we used this link in a promotional campaign last year. Is that right, @HPaulJohnson? 

@chadsansing - any use for it these days?

**Comment by chadsansing** [comment]
Not to my knowledge. Mebbe check with Stacy Martin re: useses.

On Fri, Feb 5, 2016 at 12:59 PM, hannahkane <notifications@github.com>
wrote:

> I believe we used this link in a promotional campaign last year. Is that
> right, @HPaulJohnson <https://github.com/HPaulJohnson>?
>
> @chadsansing <https://github.com/chadsansing> - any use for it these days?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/teach.mozilla.org/issues/1589#issuecomment-180470815>
> .
>



-- 
Chad Sansing
Curriculum Developer, Web Literacy
Mozilla Foundation
chad@mozillafoundation.org
@chadsansing

**Comment by hannahkane** [comment]
I think we can kill this page. Looks like we link to other very similar content within the other privacy-themed activities.

**Comment by Pomax** [comment]
kk, killing
