### ISSUE TITLE
Update sign in wording

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1598]
Based on https://github.com/mozilla/teach.mozilla.org/issues/1366

We're updating copy across all mofo products to have consistent wording for signing in. Please update copy on teach.mozilla.org to (in sentence case):
- Sign in
- Sign out
- Create an account

**Comment by cassiemc** [comment]
@kristinashu Are there any other places these updates need to be made other than teach.mozilla.org?

**Comment by cassiemc** [comment]
@kristinashu n/m, just saw you filed a bunch of different bugs.

**Comment by kristinashu** [comment]
Closing this ticket. These issues will be covered by the MoFo Unified Design ticket https://github.com/MozillaFoundation/Design/issues/163
