### ISSUE TITLE
Update whitepaper for upcoming Web Literacy 2.0

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1600]
On the bottom of https://teach.mozilla.org/activities/web-literacy/, where it says "read our whitepaper on why Mozilla cares about Web Literacy.” It currently links to http://mozilla.github.io/webmaker-whitepaper/

This is dated and needs to be updated to the current concept paper:
- [ ] Access to mozilla.github.io. I think the paper can live here again but we need to figure out how to get access for @anmechung and Iris to be able to update this content themselves
- [ ] Fork the old whitepaper template and remove old webmaker branding/footer on it
- [ ] Update link on web literacy page

**Comment by hannahkane** [comment]
@sabrinang - can you fork the whitepaper template or do you need dev assistance?

**Comment by mmmavis** [comment]
I'm curious about why we want to **fork** the repo. Can updating content on that existing page/repo (http://mozilla.github.io/webmaker-whitepaper/) be an option too?

**Comment by jgmac1106** [comment]
For history purposes I think both versions of the paper should live
somewhere and be accessible.

**Comment by hannahkane** [comment]
@anmechung - do you have an opinion on the above?

**Comment by anmechung** [comment]
Its a good idea make sure that people can access the different versions.  There is already a link in the Web Lit 2.0 paper to the first paper.   In addition, we could make a link to it at the bottom of the latest paper.

**Comment by hannahkane** [comment]
OK, it sounds like we want to fork this repo: https://github.com/mozilla/webmaker-whitepaper. 

I would say we should just add new content to that repo, but I don't think "webmaker-whitepaper" is the right name. It could be weblit-whitepaper instead. 

@anmechung - can you provide a link to the whitepaper content, so we can get a sense of how many different elements there will be between the older version and the new one?

**Comment by anmechung** [comment]
Here is a link to new concept paper:  http://bit.ly/1TOegsj

**Comment by hannahkane** [comment]
With some help with the Webmaker logo, I can probably do this one myself. @mmmavis - is that true, or am I likely to run into trouble?

**Comment by cassiemc** [comment]
Webmaker logos are here: https://drive.google.com/folderview?id=0B2qu3ExKWIlvZTB2UWFGQ18xVjA&usp=sharing

@hannahkane if you need an export or anything, I'm happy to help.

**Comment by smithisgeneric** [comment]
It looks like the decision to keep the existing white paper alive was reached. I'd like to chime in to support this. I've distributed the URL to the original white paper as part of grant deliverable. It could cause problems for me if the white paper disappears or if the (current) page contents are replaced with other materials.  

Creating a v 2.0 of the white paper with a distinct weblink works well!

**Comment by sabrinang** [comment]
/cc @flukeout 

Luke and I are going to look into this tomorrow and see how we can style the templates being developed currently (the ones that will be used for clubs) to accommodate this whitepaper. It can potentially live http://mozilla.github.io/learning-networks/__newnamehere__

**Comment by hannahkane** [comment]
I heartily approve of this idea. Thanks!

**Comment by flukeout** [comment]
The work-in-progress version lives here right now...
http://flukeout.github.io/master-template/weblit/whitepaper.html

**Comment by hannahkane** [comment]
Wow, this looks lovely.

**Comment by flukeout** [comment]
**Questions**
* Do we add a footer?
* Do we link back to the Teach site somewhere and how?
* Do we add a mozilla & teach logos?
* Do we want to indicate the format for this article (and others using similar templates)?
  * White Paper
  * Guide
  * etc...

**Comment by hannahkane** [comment]
I'd say: 
 * yes, we should link back to Teach. Many people will be arriving here *from* the Teach site, but since people will also share the paper directly, we should definitely provide a way back to Teach, as well as...
 * ...provide some overarching brand context. I'd say we want to associate  this with both Mozilla and Teach. Since there isn't a Teach logo, perhaps we do something similar to what we do in the footer of the Thimble and Goggles homepages - use the mozilla wordmark and include a sentence explaining the connection to the Mozilla Learning Network and linking to Teach.
 * Re: format of the article—I don't think that's important to readers
 * Since this won't need to be edited very often, if at all, maybe we could just host this on the Teach site, at teach.m.o/web-literacy/whitepaper. On the other hand, since it doesn't follow the Teach design rules, perhaps it's better to host it as a github page, much like the [current one](http://mozilla.github.io/webmaker-whitepaper/). The url could be mozilla.github.io/weblit-whitepaper. 
 * Should be linked from the Teach site, yes. It's referenced in @sabrinang's [designs](https://redpen.io/pacfea7a617e7587c3) for the Web Lit Map

**Comment by anmechung** [comment]
+1 to all of @hannahkane comments including the lovely part! 

- Personas that @sabrinang  generated for MozFest will need to be added somewhere - @sabring - let me know when you unearth them, and I'll write some others that can also be added to page for the Web Lit map visual.
- Realized that I need to get from @wiobyrne references to be included in the footnotes for studies referenced in the footnotes
- Should also be linked to web lit map visual when its available
- To avoid confusion, can you move references to Digital-Age Skills in the title, sub-title, and change Digital-Age Skills in the left bar to Web Literacy Skills? 
- Can you remove the word "concept" from the first sentence?  we'll just call it a paper
- Can you add a link to the original white paper after the conclusion section?

**Comment by jgmac1106** [comment]
Is it a link to Mozilla Leadership Network or Learning Network?

Its Leadership Network in all the curriculum. We should match in the white
paper.

.....or explain the naming conventions du jour.

But excited to see it going live. Looks good @flukeout

**Comment by wiobyrne** [comment]
@anmechung no problem. 

Just tell me where and when.

**Comment by anmechung** [comment]
@wiobyrne Can add to  http://bit.ly/1TOegsj as footnotes as soon as you are able?  Thx!

**Comment by hannahkane** [comment]
@jgmac1106 - Teach site will continue to be known as "Learning" for the time being. "Leadership" represents overarching programmatic work, beyond the educational hub (also includes, as an example, Mozilla Science).

**Comment by sabrinang** [comment]
@anmechung I have the 5 personas we used for MozFest in madlib form:

**Teacher**
My name is Mr. G and I am a high school music teacher. I’m interested in teaching my students to be responsible citizens of the web given how active they are in making and remixing digital music. With all the issues about copyrights and licenses, I need resources that will help educate me and them about these issues as well how to be a good collaborator and leader. 

**Afterschool Educator**
My name is Maya, and I work at an afterschool program where middle school students participate in a variety of activities from homework help to creating their own online movies. Kids love this program, but we have parents who are concerned about security and privacy. We need a workshop or set of activities to help participants and their parents understand how to protect their privacy and be able to develop and share movies in the open.  

**Researcher**
My name is Jane and I am a professor at a research university. I’m want to learn how to effectively data mine and publish my research online.  I need basic digital literacy skills to understand how best to search and aggregate data online, and how to post my research in the open for feedback and comment. I need a MOOC to learn these skills and a way to and collaborate with other colleagues to develop common practices.

**Activist**
My name is Roshni and am a self-proclaimed programmer who started coding on my own as a teen.  I now own my own start-up technology company, and the more time I spend collaborating online, and understanding the most critical innovation of my generation, I’m realizing how vital it is for me to teach and educate others about how to protect the web as a vital public resource.  I need resources to teach others about basic web literacy skills, and campaigns to invigorate them about why they should care about the web.

**Welder**
My name is Adeo and I am learning to be a welder in a job training program.  I want to start my own business, and need to learn how to use the internet to build a website, find partners, and create jobs for others in my community.  I need low-cost tools and an online community to learn these skills and promote his new business.

**Comment by anmechung** [comment]
@sabrinang - do you think these personas should be on the web literacy map page? or should we add them to the white paper?  Or both?

**Comment by anmechung** [comment]
@wiobyrne can you add the references by mid-week?  http://bit.ly/1TOegsj

**Comment by wiobyrne** [comment]
I'm adding them in right now.

-Ian

_________________________

W. Ian O'Byrne, Ph.D.

College of Charleston

wiobyrne.com

Be sure to subscribe to my newsletter.

**Comment by sabrinang** [comment]
@anmechung It'll be quite text heavy on the web literacy map page so I'd keep the map page focused on the graphic + corresponding definitions only and suggest keeping personas separate living in the whitepaper or have it as a subsection under web literacy map. (If it lives on site as a subsection, we'd need text to give context to frame these personas.)

**Comment by anmechung** [comment]
@sabrinang - good idea.  Let's keep the personas separate living in the white paper.

**Comment by anmechung** [comment]
@wiobyrne thanks!

**Comment by hannahkane** [comment]
@flukeout - how are you doing on this one? Do you have all the info you need to finalize?

**Comment by flukeout** [comment]
@hannahkane @sabrinang @anmechung 

I've added a References section to the white paper based on what was in the Google Doc and created a new 'content' repo to host the whitepaper.

http://mozilla.github.io/content/web-lit-whitepaper/

Please have a look & read and file any issues you find here...
https://github.com/mozilla/content/issues

**Note**
We can't host the whitepaper in the original repo (http://mozilla.github.io/webmaker-whitepaper/) because it includes the word ``webmaker`` in it, which is old-school. We also can't rename it because that would break the link to that content.

**Comment by hannahkane** [comment]
Looks awesome, @flukeout.

@anmechung - please let us know if this looks good to you and if we can close this issue.

**Comment by flukeout** [comment]
I'm going to close now and we can file issues in https://github.com/mozilla/content/issues OK?
