### ISSUE TITLE
Finalize Web Lit 2.0 design (from feedback summary)

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1601]
We have received responses for our "Mozilla Web Literacy Map 2.0 (Feedback on Design)” survey from 30 respondents and the choice is ... [Design 2](https://marvelapp.com/bcbd6e)!

### Feedback Summary
Overall, Design 2 has resonated with the majority (~83%) for its round colour coding, framing open practices as a competency, how it represents the r/w/p framework, intuitive/clear/easy defined hierarchy to understand the concept. However, people notice it is less fluid in terms of overlap between competencies to the three main categories. It loses the multiple interconnection between the skills, it doesn't leave space for anything else (rigid representation) and that there are different sizes of the "slices" (skills) makes it seem that some are more important than others (due to an uneven division 4r/5w/5p).

Design 1 felt chaotic and was not immediately intuitive but people liked to visualize the overlapped connections, interconnectedness and organic representation that is coherent with what the web is. With unclear relationships some felt more expansive flexibility and support for more custom journeys and combinations. This created lack of direct correlation, distinction, hierarchy to r/w/p and the colour coding was less impactful.

#### Design Updates:

- Finalize Colours
    - improve on colours to match other MoFo/teach colour schemes
    - improve on colours to be more neutral if possible
        - associations with progress indicators (stop, wait, go etc.)
    - improve legibility; do not use white text on colour
        - white text on a pale, pastel background is difficult to read
    - ensure colours are colour-blind friendly
    - grey used makes it seem disabled or inactive somehow
        - “more color to tint each section, instead of leaving it gray"
    - ensure framework works as static image and print friendly version - greyscale + all colour

- Finalize UI of 21c skills legend

- Other things to note outside of design that is content driven
    - Content - “I think there are arguments to be made that all of these skills can be used in all of these literacies, but the color coding works in this interactive context."
    - Format - "I like moving from the center to 3 principles -to further deconstructing the three principals into more specific skills and competencies - it creates a flow for orientation and training"
    - Localization - request for a way where it is easily localizable for other languages
    - Interactive - people are excited to see this as an interactive tool linking to content activities
        - improve showing progression of learning
        - link out to badges and online digital product
    - "Open Practices” - people find the placement of "Open Practices" is a bit awkward in both designs and the term itself - they may want to incorporate it into the definition of web literacy, rather than it being a sub skill (many divided responses on this topic)
    - Name suggestion - "wheel of web literacy"

**Comment by sabrinang** [comment]
cc/ @anmechung

**Comment by anmechung** [comment]
@sabrinang can we name it  Web LIteracy 2.0 as a placeholder for now?

**Comment by sabrinang** [comment]
Yeah @anmechung let's use Web Literacy 2.0

**Comment by cassiemc** [comment]
@sabrinang What do you mean by "Finalize UI of 21c skills legend" in the issue's description? Was there other feedback there? (Looks pretty good to me)

Looking at your list, the main things that seem actionable are maybe turning 'open web practices' so that it's on its side (on either side, similar to the other sections to its right and left), and then finalizing colors. Maybe not too much left when you pare it down to those two tasks?

@hannahkane Please correct me if I'm wrong, but I think it's fine for MVP to be a static graphic, given we can link to curriculum in other ways. And that would support postponing localization. It also seems devs are pretty tied up this heartbeat so might be worth phasing in interactivity later.

**Comment by hannahkane** [comment]
@cassiemc - the implementation including localization will happen in upcoming heartbeats, though I'd like for it to be interactive when we launch it. for this heartbeat the goal is to ship final copy and all design assets. agreed that it looks like there are only a few tasks remaining.

**Comment by jgmac1106** [comment]
Something also to remember. We will need canonical links to atleast each
competency (skills as well would be nice) for badging purposes. On the
current iteration you will see that little s thing for the link.

Even if we aren't using the Mozilla badges that we are piloting it will
help out the community erit large if they can link back to map.

**Comment by cassiemc** [comment]
@hannahkane Sounds good. Don't want to over-rotate on it but would be good for @sabrinang to consult with a dev this heartbeat before finalizing the design, if it is to be interactive. Do you know who's building this page? @mmmavis @Pomax ?

**Comment by jgmac1106** [comment]
@sabrinang and @anmechung I really like the design 2 and the color coding interactivity will be awesome. 

Are we no longer going to display the skills under each competency? Will I get a list of the skills when I click on a competency?

**Comment by anmechung** [comment]
@jgmac1106 Glad you like design 2 and the color coding interactivity - @sabrinang brilliance :) 
yes, the plan is to display skills and competencies

**Comment by hannahkane** [comment]
@cassiemc - I don't know who will be building the page yet. @sabrinang - let's check in with @mmmavis and @Pomax about this during stand.

**Comment by sabrinang** [comment]
**Updates:**
- Colours is TBD but I have tested variations of the mozilla palette that work better together for colour-blindness and greyscale
- grey is still present as it is doesn’t interfere with the colour coding and is part of the accent palette
- improved contrast of labels and checkboxes
- balanced out orientation the labels to be all horizontal so the “open practices” label is horizontal with the rest so it isn’t as awkwardly positioned (this also maybe more legible and easier localization purposes as well)
- improved balance of colour division for 21c skills so they have equal area (divided horizontal instead of vertical)
- 21c Skills legend checkboxes are balanced to be right (large devices) or below (med-small devices) the visual 
- the graph is interactive and when a literacy or competency is selected the graph will highlight that section and display the corresponding description and activities beneath (selecting the centre will highlight the entire graph again)
- the Web Literacy page can serve as static graphic (by default when you first visit the page, all 21c skills are selected and the r/w/p descriptions are below)
- 21c skill descriptions are found on separate page (subsection under Web Literacy in the navigation)

![web literacy 2 0 graph design](https://cloud.githubusercontent.com/assets/2492510/13006958/71876f7a-d141-11e5-8baa-c2a5f032849d.png)

See redpen for the design in context and in various selected states: https://redpen.io/p/to351d853022563354

**Comment by sabrinang** [comment]
Closing (I'll file separate issue for final colours)
