### ISSUE TITLE
Finalize Web Lit 2.0 copy 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1602]
We will need to finalize the copy that is displayed with Web Lit 2.0 on the site for the wireframes.

- [ ] short descriptive introduction about web lit 2.0 that goes above graphic
- [ ] Definitions, learning outcome etc. for the 3 literacy, the 14 competency and 4 21c skill
- [ ] optional: copy for select personas if they are not displayd in whitepaper

**Comment by anmechung** [comment]
@IBGMozilla and @anmechung will finalize copy for wireframe

**Comment by hannahkane** [comment]
@anmechung and @IBGMozilla - when do you think you'll have final copy for this?

**Comment by anmechung** [comment]
End of this week for sure!

**Comment by hannahkane** [comment]
Cool. This is @sabrinang's top issue this heartbeat, so the sooner she has final copy, the better.

**Comment by anmechung** [comment]
I've completed revisions, and asking @KGorr to a copy edit.

**Comment by hannahkane** [comment]
@kgorr - do you have an estimate for when we'll have final copy? Thanks!

**Comment by KGorr** [comment]
I made edits/suggestions and @anmechung and team were tackling them Friday. Should be finished soon!

**Comment by anmechung** [comment]
@kgorr - thanks for the edits/suggestions.  All incorporated and ready for @sabrinang

**Comment by hannahkane** [comment]
does @sabrinang have access to the doc? if so, let's close this ticket!

**Comment by anmechung** [comment]
yes! Closing.
