### ISSUE TITLE
[Feb 17] Check Digital Learning Day traffic

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1606]
Digital Learning Day is Feb 17 and as of Jan 27th they added a link on their resources page to teach.mozilla.org. 

Can we check traffic numbers on Feb 17 - I'm interested in seeing if/how this drives folks to our site. 

cc @chadsansing

**Comment by hannahkane** [comment]
@ldecoursy and I did this.
