### ISSUE TITLE
Create landing page for Curriculum Workshop series

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1608]
@chadsansing and @amirad are going to start co-hosting a monthly Curriculum Development Workshop for the community. (@chadsansing - what's the most relevant ticket for background?)

The series needs a landing page that will include:
 * some explanatory information about the goals of the series (to be provided by @chadsansing)
 * information about the upcoming workshops: topic + date/time
 * during the actual workshops themselves, the landing page should serve as the entry point to the event - including a way to view the workshop (likely a Google Hangout on Air) and a way to access the event etherpad
 * access to an archive of previous workshops

As an example, we could use this page as a model: http://edtechtalk.com/ttt

Let's discuss the best way to build this page. Ideally, it can be updated dynamically, or easily updated by @chadsansing.

**Comment by hannahkane** [comment]
@chadsansing - can you please remind me of the date of the first workshop?

**Comment by ldecoursy** [comment]
March 8

**Comment by chadsansing** [comment]
@hannahkane, see [#330 in the learning-networks repo](https://github.com/mozilla/learning-networks/issues/330).

**Comment by anmechung** [comment]
Will there eventually be some way to link this to existing/emerging curriculum/activities etc.?  There might be some examples of through lines that may be helpful for people to navigate all Mozilla's resources?

**Comment by hannahkane** [comment]
@anmechung - I think this page will likely live on teach.mozilla.org, so it will be in the context of the activities and everything else.

**Comment by hannahkane** [comment]
Closing this because we've moved this work over to the curriculum repo: https://github.com/mozilla/mofo-cms-experiment/issues/17
