### ISSUE TITLE
Create landing page for MLN Community Calls

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1609]
We will be hosting monthly community calls, starting March 23 (tentatively).

We'll need a landing page that includes:

* some explanatory information about the goals of the calls (to be provided by @ldcoursy)
* information about the upcoming calls: topic + date/time
* during the actual calls themselves, the landing page should serve as the entry point to the event - including a way to hear/see the call (not sure what tech we're using for these yet) and a way to access the event etherpad
* access to an archive of previous calls

Let's discuss the best way to build this page. Ideally, it can be updated dynamically, or easily updated by staff.

**Comment by ldecoursy** [comment]
cc @KGorr

**Comment by ldecoursy** [comment]
Tentatively March 23rd

**Comment by hannahkane** [comment]
Closing this here, because we've moved this work over to the CMS repo: https://github.com/mozilla/mofo-cms-experiment/issues/16
