### ISSUE TITLE
Update links to Mouse activities on /activities

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1611]
The following two activities are currently featured on teach.mozilla.org/activities. Mouse recently updated the content into new Thimble and a template that does not have the Webmaker logo in the header. 

Can we update the links for the following?

* Creative Commons GIF Exchange - https://d157rqmxrxj6ey.cloudfront.net/mouseorg/18015/
* CSS Story Cards - https://d157rqmxrxj6ey.cloudfront.net/mouseorg/19913/

cc @chadsansing

**Comment by hannahkane** [comment]
@Pomax - assigning this to you as one of the small front-end tasks needed this heartbeat
