### ISSUE TITLE
track logouts using an OutboundLink component rather than <a>

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1613]
We track login events via GA at the moment, but not logout events; it'll be good to add an event signal to the LogoutLink component so that we can see the number of logouts per timeunit in addition to logins.

**Comment by hannahkane** [comment]
@Pomax - do we need to roll this to the next heartbeat?

**Comment by hannahkane** [comment]
@pomax - do you want to assign this to yourself?

**Comment by mmmavis** [comment]
I have a PR in for this. Assigning this ticket to myself now.
