### ISSUE TITLE
(Push Live on Feb 16) Implement Encryption Campaign promo banner for teach site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1619]
Based on - Design Encryption Campaign promo banner for teach site #1535 

Comp: https://redpen.io/p/ya4ae604c136854f8e

Assets (both SVG and PNG version): https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLU0FwS1I5N2hKdEU&usp=sharing

ai: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLNnlXQmdFSjI1UmM/view?usp=sharing

Links to mzl.la/encrypt (which I think is https://advocacy.mozilla.org/encryption but will need to confirm). Also need to confirm launch date, which I think is either the 8th or 10th?

**Comment by kristinashu** [comment]
@lovegushwa can you please confirm launch date and url when you can?

**Comment by mmmavis** [comment]
Reassigned to me. I should be able to have a PR up for this today.

**Comment by mmmavis** [comment]
PR submitted. Note that https://mzl.la/encrypt links https://advocacy.mozilla.org/ (not https://advocacy.mozilla.org/encryption)

**Comment by kristinashu** [comment]
Thanks @mmmavis launch date has been confirmed as Feb 10th. Looking into URL...

**Comment by kristinashu** [comment]
Confirmed by @HPaulJohnson, URL will be advocacy.mozilla.org/encrypt

**Comment by mmmavis** [comment]
@hannahkane @kristinashu when should we push this live? PR has been reviewed and is okay to go!

**Comment by hannahkane** [comment]
asking @HPaulJohnson to provide a time window. there may be a late-breaking change of plans, so let's wait until we hear from him.

**Comment by HPaulJohnson** [comment]
Hi all- late breaking update: we've recently decided to do some additional testing on the initial content to a smaller audience before we promote more widely across all our channels and properties. 

So please hold off on going live with this promo until further notice (expect an update in the next few days).

**Comment by HPaulJohnson** [comment]
We are ready to turn this on Tuesday a.m (2/16). Let me know if that works and if there's anything else that's needed from us.

**Comment by hannahkane** [comment]
Discussed at planning meeting today - @mmmavis will push this on Tuesday.
