### ISSUE TITLE
Evaluate current content creation platform ideas with respect to collaboration and localization

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1621]
We're currently experimenting with quite a few ways for our internal teams to create content...

* Thimble curriculum template
* Gavin's CMS "Mage"
* Mavis' Wordpress Instance
* Science & Clubs github hosted templates

We also know that localization and collaboration are important aspects in content creation. With this in mind, let's create a matrix that compares and evaluates the four approaches along those attributes.

We can use this matrix to identify gaps in our approaches, and also to better match approaches to future needs within the org.

We're starting work in #1620 to discover what kinds of collaboration are important.

cc @hannahkane Can you do a sanity check on this issue please?

**Comment by hannahkane** [comment]
Looks good, @flukeout. Would add that "remixing" and "editing" are important parts of some content creation, too.

**Comment by hannahkane** [comment]
@flukeout - do you have any updates on this ticket? Do you expect we'll need to roll it into the next heartbeat?

**Comment by hannahkane** [comment]
@flukeout - not feeling the need for this ticket so much. what do you think - should we close?

**Comment by flukeout** [comment]
Yeah, makes sense. Closing.
