### ISSUE TITLE
Teach Chad and Hannah how to update /activities page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1626]
@simonwex points out that it would be relatively simple for @chadsansing (and me!) to learn how to update the /activities page with new modules when we have them.

@mmmavis - would you be able to help Chad and I get set up to do this?

**Comment by mmmavis** [comment]
Yup yup no problem! But I'd suggest to wait till the build rewrite work is in a good place first. /cc @Pomax

**Comment by hannahkane** [comment]
Let's use this as a teaching case: https://docs.google.com/document/d/1j6kTdhfTION7_N63Ws-qv1NC-V2a0Iuh-4PDkGfQRIE/edit?ts=56b9cdab#heading=h.nir6usoqepnq

**Comment by hannahkane** [comment]
@mmmavis / @chadsansing  - should we pick a time to walk through this? Is 30 minutes enough time, or should we schedule an hour?

**Comment by chadsansing** [comment]
An hour, @hannahkane? My calendar is up-to-date. Want to find a time? I can, also.

**Comment by mmmavis** [comment]
Hey @hannahkane & @chadsansing ,

Question - wondering if you are expecting submitting code changes via Github's interface or through a proper dev environment setup (e.g., Terminal+Github+code editor etc)?

To add new teaching modules/kits we will need to edit multiple files in the codebase, including uploading images files to a specific directory - this is hard and cumbersome to achieve if we rely solely on Github's Interface.

I'll create a Github `branch` before the call tomorrow to show you the code changes involved for [the teaching case](https://github.com/mozilla/teach.mozilla.org/issues/1626#issuecomment-184835391) @hannahkane mentioned above. I'd like to get your thoughts first before we get into the could-be-super-confusing coding world. I think having both of you set up with proper dev environment and learn to use React is way tooooooooooooooo much :cold_sweat:

**Comment by hannahkane** [comment]
I'm good with terminal+github+editor if @chadsansing is!

**Comment by chadsansing** [comment]
Let's try it.

**Comment by mmmavis** [comment]
`branch` created here: [example code](https://github.com/mozilla/teach.mozilla.org/pull/1653)
Code changes in 3 files + 10ish image files - shouldn't be too bad!

**Comment by mmmavis** [comment]
### Install `node`

1. Install Xcode Command Line Tools: https://developer.xamarin.com/guides/testcloud/calabash/configuring/osx/install-xcode-command-line-tools/
2. Install Homebrew: http://brew.sh/
3. Install `node` via Terminal: `brew install node`

### Fork Teach Repo

1. Go to https://github.com/mozilla/teach.mozilla.org
2. Click on the "Fork" button <img width="80" alt="screen shot 2016-02-18 at 8 59 01 pm" src="https://cloud.githubusercontent.com/assets/2896608/13166951/b7813baa-d682-11e5-8c29-455c949a303b.png"> at top right of the page and select you account
3. You should now have a fork of Teach at https://github.com/hannahkane/teach.mozilla.org :tada: https://github.com/chadsansing/teach.mozilla.org

### Clone Repo to Your Machine
1. In Terminal, navigate to the directory where you want the repo to be cloned to.
2. Clone the repo: https://help.github.com/articles/cloning-a-repository/ 
3. Configure a remote for the fork: https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by mmmavis** [comment]
### Sync a Fork

1. `git fetch upstream`
2. `git checkout develop`
3. `git merge upstream/develop`
(more explanation here: https://help.github.com/articles/syncing-a-fork/, except we are working off of the `develop` branch, instead of `master`)

### Create a Branch

1. `git checkout -b issue-number-add-new-activity develop`

### Get Teach Site Running Locally

1. Install all the required node packages: `npm install`
2. Run the site: `npm start`
3. Check out `http://localhost:8000`

**Comment by hannahkane** [comment]
Thanks for the awsm training today, @mmmavis!

my dev environment issue was resolved by uninstalling and then reinstalling homebrew, so I'll play around with this on Monday.

**Comment by hannahkane** [comment]
@mmmavis - should we close this/ @chadsansing - has your dev environment issue been resolved?

**Comment by chadsansing** [comment]
Let's close. I'll come back to my dev environment after the NYC/IPPD training and file another issue for help if need be.

**Comment by mmmavis** [comment]
:grin:
