### ISSUE TITLE
Update Gigabit Pilot Periods

### ISSUE THREAD

**Issue by LindseyFrost** [mozilla/teach.mozilla.org#1628]
The Gigabit Pilot Period windows need to be updated at https://www.mozilla.org/en-US/gigabit/apply/

The new dates are:

May 16, 2016 - September 4, 2016: Round 1 Pilot Period
    
January 2, 2017 - April 24, 2017: Round 2 Pilot Period

Thank you!

**Comment by mmmavis** [comment]
I can have a PR in this Friday/Next Monday.  Is there a deadline that's tie to this? It would be great to inform the mozilla.org team about that. :smiley:

**Comment by LindseyFrost** [comment]
Thank you, Mavis! It would be idea to have it updated by 3/18.

**Comment by mmmavis** [comment]
@LindseyFrost Cool, any time before 3/18 is also fine as well right?

**Comment by LindseyFrost** [comment]
Correct!

**Comment by LindseyFrost** [comment]
(The sooner the better really)

**Comment by mmmavis** [comment]
PR submitted to mozilla.org repo: https://github.com/mozilla/bedrock/pull/3881

**Comment by mmmavis** [comment]
Live on https://www.mozilla.org/gigabit/apply/ :dancers:
