### ISSUE TITLE
Email sign up check box

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1632]
@hannahkane I'm wondering if you have any legal insights about email sign ups? On teach we have a check mark agreeing to our policy (users can't uncheck):

<img width="667" alt="screen shot 2016-02-11 at 1 38 33 pm" src="https://cloud.githubusercontent.com/assets/1068783/12991670/0739dde6-d0c5-11e5-90c1-77b0b4ac529c.png">

Whereas on the new encryption site (http://advocacy.mozilla.org/encrypt), there's a check box users have to click to accept the policy (it has to be checked in order for people to sign up):

<img width="584" alt="screen shot 2016-02-11 at 9 43 02 am" src="https://cloud.githubusercontent.com/assets/1068783/12991674/09c75552-d0c5-11e5-96f1-1fa1a936b751.png">

@lovegushwa was this a conscious decision? 

Usability wise, I think it's easier/better to just have the check mark like on teach because people don't really have an option - it has to be checked in order for people to sign up. But I'm wondering if we have to have the actual check box for legal?

Side note: Sign up on https://www.mozilla.org/en-US/ doesn't have any sort of checkbox. 

cc @cassiemc

**Comment by cassiemc** [comment]
@kristinashu In the past on login/ID work we decided as you did that it was better to pre-select the check. Like you say they don't really have an option.

**Comment by hannahkane** [comment]
+1 - was intentional to pre-check, and, iirc, that was preferred by our legal dept

**Comment by kristinashu** [comment]
Ok thanks!
