### ISSUE TITLE
Review/update content on /activities

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1633]
@chadsansing and I were talking about reviewing current content on the /activities page - several links go to old Webmaker, and we have some new content coming down the pike to add.

Can we review any traffic analytics to see which links get the most clickthroughs so we can make more informed decisions?

Related to #1626

**Comment by ldecoursy** [comment]
New content coming would be Letters to the Next President page, MOUSE web lit activities https://d157rqmxrxj6ey.cloudfront.net/mouseorg/23946/, what else?

**Comment by hannahkane** [comment]
Good idea. Happy to walk through analytics with you both whenever you'd like.

**Comment by hannahkane** [comment]
@ldecoursy - should we set up a time to talk?

**Comment by ldecoursy** [comment]
Closing this - duped by #1669
