### ISSUE TITLE
Access to Google Analytics

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.mozilla.org#1634]
As part of some audit work in the plan repo, can I have access to analytics for the teach site? @hannahkane @adamlofting Thanks in advance!

**Comment by hannahkane** [comment]
I don't have permissions to grant permissions, so this will have to be @adamlofting.

**Comment by adamlofting** [comment]
Done :+1: 

Let me know if you'd like access to any of the other sites. I'm admin on some of them, and some of them are administered by MoCo, but I can file the necessary bugs to get you setup.
