### ISSUE TITLE
HTML Document Title doesn't update as you navigate between pages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1635]
We should file a follow-up PR for https://github.com/mozilla/teach.mozilla.org/pull/1627

Issue:
`document.title` doesn't update as you navigate between pages. @Pomax can fill in more details in here but he mentioned it was something to do in `page.jsx`

**Comment by Pomax** [comment]
This is because page.jsx in the PR changes the title in `componentWillMount`, but react-router recycles the element, so it'll only ever mount once. Instead, we need to hook into `componentDidUpdate` to catch subsequent page loads.
