### ISSUE TITLE
Web Literacy - Line Art

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1650]
We have 3 placeholders (for Read, Write, Participate) and icons used for 21 Century badge skills that we can make into line art to match the rest of the illustration styles present on the site. The line art colour will adopt the section colour.

![icons to line art](https://cloud.githubusercontent.com/assets/2492510/13121764/9950375a-d568-11e5-96dd-3e87e9bb3626.png)

Related to issue: #1603 (web literacy wireframes)

**Comment by chadsansing** [comment]
These would be cool to consider as the new "buttons" for web literacy competencies on curriculum pages/lesson plans. Do they or can they share a fixed width?

**Comment by sabrinang** [comment]
The line art version of these icons can be found here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eMTJTYlZHNWpuaGs&usp=drive_web
<img width="1377" alt="screen shot 2016-03-14 at 4 52 50 pm" src="https://cloud.githubusercontent.com/assets/2492510/13763671/3bf27c06-ea05-11e5-8b73-8e7f74c79daa.png">

@chadsansing the widths vary slightly in these but they can rescaled for your lesson plan needs

**Comment by chadsansing** [comment]
Thank you, @sabrinang -

**Comment by sabrinang** [comment]
Create 4 more line art (seen in badges):
<img width="370" alt="screen shot 2016-03-21 at 12 47 51 pm" src="https://cloud.githubusercontent.com/assets/2492510/13931978/27f3f0fa-ef63-11e5-8b98-eafb0aacce6c.png">

**Comment by hannahkane** [comment]
@sabrinang - can we close this ticket?

**Comment by sabrinang** [comment]
Since we have streamlined the badges into 4 for 21C Skills (5 collaboration badges merged as 1) the other badge illustrations are unnecessary to create now. The navigation icon for web literacy has also been completed: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_ed0VIMXlfQUhWcEU/view?usp=sharing
