### ISSUE TITLE
Web Literacy - Colour Coding

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1651]
Finalize with aligned colours from update palette issue: https://github.com/MozillaFoundation/Design/issues/139 and ensure colour tests are conducted for accessibility (colour blindness and greyscale printing)

![web literacy 2 0 graph design](https://cloud.githubusercontent.com/assets/2492510/13006958/71876f7a-d141-11e5-8baa-c2a5f032849d.png)

![colour tests](https://s3.amazonaws.com/redpen-prod/red-pen-a24f817a-0694-4c5b-de5e-acb0bfdfa137.png)

**Comment by sabrinang** [comment]
mofo wide colours being tested on https://github.com/MozillaFoundation/Design/issues/152

**Comment by sabrinang** [comment]
Using this palette 

![web-literacy_colours](https://cloud.githubusercontent.com/assets/2492510/13757278/efbc0f42-e9e0-11e5-8ce6-c78d7815bc1c.png)

Tested from: https://github.com/MozillaFoundation/Design/issues/152#issuecomment-196460839

**Comment by sabrinang** [comment]
The mofo palette has been updated with adjustments so I will revise and test again using palette from this issue: https://github.com/MozillaFoundation/Design/issues/139#issuecomment-196534991 and also address feedback from https://github.com/mozilla/teach.mozilla.org/issues/1659#issuecomment-196496801

**Comment by hannahkane** [comment]
@sabrinang - can we close this ticket now?

**Comment by sabrinang** [comment]
Current palette we are using:
![web-literacy_colour-test-unified-11](https://cloud.githubusercontent.com/assets/2492510/14083110/cbf20182-f4c8-11e5-8a89-e4c954aef28c.png)
