### ISSUE TITLE
Filing a Mozilla Leadership Curriculum Design Brief

### ISSUE THREAD

**Issue by chadsansing** [mozilla/teach.mozilla.org#1652]
Thinking ahead to April/May production for draft 1.0 of the Mozilla Leadership Curriculum (due H1), I'm drafting and sharing a design brief and sharing to @cassiemc and @hannahkane. GDoc incoming.

[Back to issues.](https://github.com/mozilla/teach.mozilla.org/issues)

**Comment by chadsansing** [comment]
Here it is: https://docs.google.com/document/d/1U6ujOTYD2Bb4b-AvLMzDkX87T6NfIPIdyDxcEonpb5s/edit#

**Comment by chadsansing** [comment]
Sketching [here](http://chadsansing.github.io/leadership-curriculum/1-1-becoming-a-mozillian.html#overview).

**Comment by hannahkane** [comment]
Sweet. Thanks, @chadsansing. Should we three meet about this briefly and then file design and implementation tickets that would necessitate further conversations with designers and devs?

**Comment by chadsansing** [comment]
Yeah; I'll send an invite on the morrow.

**Comment by cassiemc** [comment]
I'm up for it. Next week should be much more open por moi

**Comment by hannahkane** [comment]
We had the meeting, and a ticket is filed in [/plan](https://github.com/MozillaFoundation/plan/issues/757), so I'm going to close this.
