### ISSUE TITLE
Review style guide copy re. the MLN name

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.mozilla.org#1658]
@hannahkane @HPaulJohnson @KevZawacki – Would love for you guys to review some copy that @sabrinang and I would like to include in this repo's style guide. Eventually it'd be great if you could review all of it (but we're not quite there yet), so just looking at the ['Our Name' section](https://github.com/mozilla/teach.mozilla.org/wiki/Resources#our-name) would be helpful! Here's the text copy & pasted.

> When talking about the Mozilla Learning Network, you should refer to it in its entirety. Avoid using abbreviations such as MLN due to confusion within the wider Leadership Network. Although the URL is teach.mozilla.org, please refrain from referring to the project as Mozilla Teach for consistency purposes. We have also been loosely referred to as Mozilla's education hub but officially we are known as the Mozilla Learning Network.

Does anyone else need to review this? We may decide to do something differently with it later down the road but good to have a section like this documented.

**Comment by KevZawacki** [comment]
@cassiemc Looks good! Great that we're clarifying this stuff.

**Comment by hannahkane** [comment]
@chrislarry33 and @ldecoursy to review. I believe there was talk of removing "Network" from the Mozilla Learning branding, to reduce confusion further.

Could edit last sentence to be something along the lines of, "We are sometimes referred to internally as Mozilla's education hub (compare to Mozilla Science Lab as the science hub, Open News as the journalism hub, etc.), but officially we are known as..."

**Comment by ldecoursy** [comment]
@chrislarry33 look ok?

Formally Mozilla Learning Hub, or Mozilla Learning for short. Mozilla Learning is the education hub within the Mozilla Leadership Network (MLN) - as Mozilla Science Lab is the science hub and OpenNews is the journalism hub. Although the URL is teach.mozilla.org, please refrain from referring to the project as Mozilla Teach for consistency purposes.

**Comment by jgmac1106** [comment]
"MLN"character count=3 (129 left after #teachtheweb)
"Mozilla Learning Network character count"=(104 characters left after
adding #teachtheweb)"
Twitter handle most associated with MLN and #teachtheweb @MozTeach

Yet told to no say Mozilla Teach even though the site as noted is labeled
teach.mozilla.org and social media as noted runs through @MozTeach?

Curriculum in Thimble, "created by Mozilla Leadership Network" activities
and guides created by "Mozilla Learning Network"

Not suggesting a silo like Twitter should dictate naming protocol but I
doubt a style guide is going to clean up any of this confusion.

**Comment by cassiemc** [comment]
Thanks @jgmac1106 for pointing out the discrepancies, that's really quite helpful! Our aim with the style guide is to all get on the same page first about the ideal language, then we'll go about cleaning house. URLs and social media channels are all going to be addressed in a more extensive brand cleanup later.

**Comment by hannahkane** [comment]
I'm going to close this ticket, since I think it's well-covered in https://github.com/MozillaFoundation/plan/issues/741
