### ISSUE TITLE
Implementation: Replace Pledge to Teach CTA with newsletter sign-up

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1665]
Design is being finalized in #1530

**Comment by hannahkane** [comment]
@Pomax - wondering if you can take this one? I don't think the design is quite finalized, but it's close.

**Comment by hannahkane** [comment]
Marking as a P1 because I'd rather dedicate time to this than things in this milestone marked as P2.

**Comment by kristinashu** [comment]
@Pomax 
My will be updated the redpen (https://redpen.io/p/kw3181d1724543c4f2) but essentially it's:
- on the home page, replace the text "Pledge to teach" with "Get email updates"
- replace the icon of a person/chalkboard with the letter/envelope (SVG https://drive.google.com/a/mozilla.com/file/d/0B_itHmpwHBFvRFA0TUpLak52MUE/view?usp=sharing)

<img width="597" alt="screen shot 2016-02-24 at 10 11 00 am" src="https://cloud.githubusercontent.com/assets/1068783/13295777/4602f908-dadf-11e5-9b1b-b4587805df48.png">

- update the modal to this (but without the circle around the icon - same icon as above)
<img width="613" alt="screen shot 2016-02-24 at 10 13 05 am" src="https://cloud.githubusercontent.com/assets/1068783/13295800/5be359a2-dadf-11e5-9a57-54447b220156.png">

**Comment by kristinashu** [comment]
Redpen is updated https://redpen.io/p/kw3181d1724543c4f2

**Comment by Pomax** [comment]
@kristinashu UX wise, this means we don't automatically pop up the "pledge to teach" modal anymore on first visit, I take it?  Are we still going to say "thank you for signing up" based on a redirect after clicking "sign up" (previously "pledge") or is that no longer necessary since no one's making personal commitments?

**Comment by kristinashu** [comment]
We should keep the thank you message but I'm not too sure about the automatic pop up? @hannahkane do you think we can get rid of that for a little while and see how the newsletter sign up performs just as one of the three banner CTAs?

**Comment by hannahkane** [comment]
Ah, yes, meant to say that originally. We can remove the pop-up.

**Comment by Pomax** [comment]
just to verify: remove auto-popup on first visit, keep "thank you, share this with your friends!" notice after filling in email and clicking "sign up"?

**Comment by hannahkane** [comment]
Correct.

**Comment by Pomax** [comment]
PR is up on https://github.com/mozilla/teach.mozilla.org/pull/1667, there's some questions concerning the correct SVG sizing, although it looks like it fits the other CTAs now - would be good to get @kristinashu's opinion on that, thought, before we decide to merge

**Comment by kristinashu** [comment]
@Pomax looks good to me!

**Comment by Pomax** [comment]
PR landed, follows-ups were filed by @mmmavis
