### ISSUE TITLE
add web literacy training module to teaching activities

### ISSUE THREAD

**Issue by anmechung** [mozilla/teach.mozilla.org#1666]
@hannahkane @sabrinang  We've been delivering professional development via 1/2 day (in March), full day (see below), and 2 day (available in May) training modules.  

These may eventually be included in the curriculum database, but in the meantime, can we add to the teaching activities page (along with single activities, kit,) and call it Training Module?
Here is a link to a full-day training module: 
https://d157rqmxrxj6ey.cloudfront.net/chadsansing/14616/
In the next 2 weeks, we will have a link for a 1/2 day training module, and by 2 day training moduled ready to share in May

Haven't done yet, but also need to link each activity in the the training module to each web literacy skill as has been done for Web Basics I already (which Chad is updating).

adding @ldecoursy @chadsansing @jvallera

**Comment by hannahkane** [comment]
@anmechung - I believe I can add this myself now, thanks to my newfound knowledge from @mmmavis.

For the full-day training module, we'll need to have the following information to include on teach.mozilla.org/activities. Can you please fill in the blanks?

Title: Teaching How to Read, Write, and Participate on the Web: Web Literacy for Educators (Full Day Training Module)
Level: 
Developed by: 
Description: 
Image: [can use the one from the module itself)

**Comment by anmechung** [comment]
@hannahkane Great!  I need to modify it a bit to make it more generic - take out slides in intro for NWP for instance, and update with a few things we learned today from the IPPD training.  @KGorr would you willing to proof after I do this including checking links?

**Comment by KGorr** [comment]
@anmechung , sure thing! Just let me know once it's ready.

**Comment by hannahkane** [comment]
Just confirming - this content is not quite ready to go?

**Comment by anmechung** [comment]
@hannahkane Correct - I need to make a few updates and have @kgorr copy-edit before posting!  Will let you know when its ready!

**Comment by anmechung** [comment]
@chadsansing I remixed IPPD and NWP workshops to create a more generic 1-day training module.  https://d157rqmxrxj6ey.cloudfront.net/anmechung/39298.  Ready for you to update the cookies for the internet part of the agenda.

**Comment by chrislarry33** [comment]
Loving this. Can make attribution just Mozilla not Mozilla learning networks

**Comment by anmechung** [comment]
@chrislarry33 done - attribute to just Mozilla.

**Comment by anmechung** [comment]
@chadsansing text for welcome: https://docs.google.com/document/d/1XZjgWtfEvzLCErwIwJjXTbD7BtrBzLLMHF0Pj8eK_i8/edit#

**Comment by anmechung** [comment]
@KGorr ready for you to copy and link edit  https://d157rqmxrxj6ey.cloudfront.net/anmechung/39298.  Thank you!

**Comment by KGorr** [comment]
@anmechung, here are a few things on the main page:

Left side bar:
- Under Materials section: 2nd bullet: “Inter-connecter” typo. should be “connected”
- Under Learning Objectives: 
     - 1st bullet typo - remove “now”
     - Last bullet uses "MLN" - calling this out to make sure it is the appropriate time/way to use it

Under Agenda:
- Welcome link not working
- Choose your own Thimble adventure link not working
 
It seems not all of the activity pages need my review (like Hack the News) - can you call out which pages linked from the agenda you'd like for me to review, so I can focus on those you need? Thanks!

**Comment by anmechung** [comment]
@kgorr - thanks for the edits!  @chadsansing @jvallera https://d157rqmxrxj6ey.cloudfront.net/anmechung/40860/  can you take a look?  The piece that I need someone to help with are the colors for the web literacy skills at the top of each page.  When I edited the skills to match updated Web Lit 2.0 and lost different colors as a result.  @chadsansing - something you can fix?

**Comment by chadsansing** [comment]
@anmechung, I don't believe there's a new CSS style guide for the Web Lit Map 2.0 map/buttons (right, @hannahkane?), so apart from referencing the old makerstrap colors or adding something like this...

style="background-color:[color code];"

...to each opening <button> tag, I'm not sure there's much to be done.

Other ideas, @hannahkane, @flukeout, et al?

**Comment by hannahkane** [comment]
I think the colour coding work is still [in progress](https://github.com/mozilla/teach.mozilla.org/issues/1651). Is that right, @sabrinang?

**Comment by sabrinang** [comment]
Yes @hannahkane I am testing out the colours to align with the mofo wide palette on the design repo here: https://github.com/MozillaFoundation/Design/issues/152

**Comment by anmechung** [comment]
@hannahkane I made a few modifications using the old colors, and I think it will work for now.  It's ready to go if you are okay with it.  https://d157rqmxrxj6ey.cloudfront.net/anmechung/40860/ 

Title: Mozilla Web Literacy Leaders 1-Day Training Module
Level: Beginner
Developed by: Mozilla
Description:  An interactive, learner-centered 1-day training module designed to learn and teach others how to read, write, and participate on the Web. 
Image: [can use the one from the module itself)
