### ISSUE TITLE
Update Learning blog url and styles

### ISSUE THREAD

**Issue by cassiemc** [mozilla/teach.mozilla.org#1668]
Eek. The Learning blog has a couple big design problems. The url isn't reflective of the current brand – shouldn't be webmaker – and the styles are based on the now very old Makerstrap. http://blog.webmaker.org/

Not sure if this is the right repo, and will leave to @hannahkane to prioritize, but this makes me cringe! Waiting on stats to understand larger impact but there seem to be between 4-10 posts a month. 

Styles should reflect the work from the teach audit so I will add that label.

**Comment by hannahkane** [comment]
I feel the cringiness, but probably won't prioritize into the next couple of heartbeats, given other priorities. I'm guessing we can do the restyling fairly soon, but the url issue is dependent on the Ed Hub name ticket.

**Comment by cassiemc** [comment]
Sounds good!

**Comment by hannahkane** [comment]
See https://github.com/MozillaFoundation/plan/issues/687

**Comment by kristinashu** [comment]
Closing this ticket. 

Blog design work is represented in MozillaFoundation/plan#687

Cringy URL is covered in https://github.com/mozilla/teach.mozilla.org/issues/1855
