### ISSUE TITLE
Loading a new page does not show the top of the page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/teach.mozilla.org#1672]
For example, if I scroll to the bottom of the home page and then click on Teaching Activities, I'm in the same scroll position as the previous page (the bottom of the page) but I should see the top of the page. 

I think this came up while working with Scott on the advocacy site, he said it was a react router default setting but he was able to fix it. 

cc/ @Pomax @mmmavis

**Comment by Pomax** [comment]
Yeah I think this is because React swaps in DOM rather than "really" loading a page so the scroll position doesn't reset. We could probably issue a scrollTo(0,0) when a navigation's about to occur.

**Comment by hannahkane** [comment]
Taking this out of the heartbeat, which is already quite full

**Comment by kristinashu** [comment]
I think this is the same as https://github.com/mozilla/teach.mozilla.org/issues/1812 so closing this one
