### ISSUE TITLE
Build Curriculum Workshop Page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1673]
**Url**: http://teach.mozilla.org/community/curriculum-workshop
**Mockup**: https://github.com/mozilla/mofo-cms-experiment/issues/17#issuecomment-191001306 (correct me if this is not the right link, @flukeout )
**Sidebar**: Add "Curriculum Workshop" as the secondary nav link under "Community"

@mmmavis tasks:
- [x] help @flukeout setup dev environment
- [x] add a new page and some basic setup to the codebase for @flukeout to drop in content and styling
- [x] add a nav link in the Community section to the new page

@flukeout's tasks: 
- [ ] add content and styling to the page (thanks Luke!)

/cc @hannahkane @flukeout

**Comment by flukeout** [comment]
@mmmavis awesome, thanks! I added a bullet item to your to-do list to add the nav item as well.

**Comment by mmmavis** [comment]
@flukeout https://github.com/mozilla/teach.mozilla.org/pull/1674 ! Maybe you can just work off of my branch? Both @Pomax and I will be in the office today so ask us if anything doesn't make sense to you.
