### ISSUE TITLE
Add attribution on Web Lit Basics I landing page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1675]
Checking to see if there's a way to add attribution to the Web Lit Basics I landing page https://teach.mozilla.org/activities/web-lit-basics/

This kit in particular features several community contributions that I think would be fair to call out, otherwise it may be perceived as Mozilla-created content.

Can we add to the description with links?
* Kraken the Code - made by Mouse
* Ping Kong - made by Mouse
* HTML Puzzle Boxes - made by Yofie Setiawan and Mozilla Indonesia
* Web Chef - Inspired by Creative Commons and P2PU School of Open
* Story of Us - Based on a project by WNYC Radio Rookies

**Comment by hannahkane** [comment]
@sabrinang @kristinashu - do we have an existing style we can use for adding attribution?

@mmmavis - is it a problem to have attribution on this page, but not the other pages that use the same template?

**Comment by ldecoursy** [comment]
Another option would be just to add the copy above to the activity descriptions on that page?

**Comment by mmmavis** [comment]
@hannahkane 
> @mmmavis - is it a problem to have attribution on this page, but not the other pages that use the same template?
Should be fine :dancer:

**Comment by hannahkane** [comment]
I think I can do this. Assigning to myself.

**Comment by hannahkane** [comment]
@ldecoursy - do you have links to go along with the attributions?

**Comment by ldecoursy** [comment]
* Kraken the Code - made by Mouse  http://mouse.org/
* Ping Kong - made by Mouse    http://mouse.org/
* HTML Puzzle Boxes - made by Yofie Setiawan and Mozilla Indonesia   http://www.mozilla.or.id/
* Web Chef - Inspired by Creative Commons and P2PU School of Open  https://creativecommons.org/ and https://courses.p2pu.org/en/groups/teach-someone-something-with-open-content/
* Story of Us - Based on a project by WNYC Radio Rookies https://radiorookies.makes.org/thimble/diy-toolkit-how-to-report-your-own-story

**Comment by hannahkane** [comment]
actually, I'm not going to be able to do this myself. @mmmavis - I was just going to add a line to each description, but I don't know how to apply a style to links from within the description value. that is, I can link it properly, but it won't look like a link (different color or underlined). can you advise?

**Comment by mmmavis** [comment]
@hannahkane can you post a screencap or commit the code somewhere? and I'm also happy to take over this ticket :wink:

**Comment by hannahkane** [comment]
@mmmavis - just put code [here](https://github.com/mozilla/teach.mozilla.org/pull/1737) so you can see what I tried.

You're welcome to just do this if it's faster, but I'm happy to learn how to do it to maybe save you time in the future. :)
