### ISSUE TITLE
Replace activity link on Goggles landing page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1677]
Can we replace the third activity currently listed on the Goggles landing page? 

Title: #allthestickerz
Link: https://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session04-all-the-stickerz.html
Description: Create and publish pixel art stickers, then use them to annotate and remix the Web.

cc @chadsansing

**Comment by hannahkane** [comment]
Putting this in the current milestone because it is #notgreat that the current activity link is broken.

**Comment by chadsansing** [comment]
Updated all the links I could find to https://goggles.mozilla.org.

**Comment by Pomax** [comment]
to confirm, we want to replace the "Remix Science for Girls" activity with this new activity? What should the title be? Literally `#allthestickerz`?

**Comment by chadsansing** [comment]
#allthestickerz is it, @Pomax. You can see thimage we've been using [here](https://chadsansing.github.io/curriculum-testing/curriculum-migration/web-lit-basics-two-migrated/session04-allthestickerz.html#overview).

**Comment by Pomax** [comment]
I assume you mean https://d157rqmxrxj6ey.cloudfront.net/chadsansing/7048/stickerz-love.png, is there a larger version available of this?

**Comment by chadsansing** [comment]
Not presently. Maybe the web-lit-two module header pic is better? https://teach.mozilla.org/activities/web-lit-basics-two/

**Comment by Pomax** [comment]
we can probably scale up the sticker image with smoothing turned off, I'll try that first.

**Comment by Pomax** [comment]
![stickerz-love](https://cloud.githubusercontent.com/assets/177243/13820178/681a801c-eb59-11e5-83d1-e9cf2ecf3fbc.png)

**Comment by chadsansing** [comment]
+1 here.

**Comment by Pomax** [comment]
landed, will push to prod once staging rolls over to the new version

**Comment by Pomax** [comment]
pushed.
