### ISSUE TITLE
Few changes to Hive site

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1690]
@mmmavis  - we have a few small changes to the Hive site.

* Locations page - remove Leah and Elsa
* Resources page - can we make this page private/not visible?
* Connect page - remove "Claim Hive Community Badge" section

**Comment by hannahkane** [comment]
Putting this in the upcoming milestone since the current milestone is quite full. Also, noting that this doesn't necessarily have to be @mmmavis. :)

**Comment by mmmavis** [comment]
I'll need to double check with @jbuck and see where our existing WP lives first.

**Comment by jbuck** [comment]
Which domain is this?

@mmmavis It probably has been migrated, but everything works exactly the same as before. Logins and all

**Comment by ldecoursy** [comment]
hivelearningnetworks.org

**Comment by mmmavis** [comment]
@jbuck is it still a WP instance or now a set of .html files? I've been ssh'ing to the WP server and `git pull` from the theme repo to update the site. If it's the former I can ask @cade to grant me access to the new server. If it's the latter... could you let me know how I can make changes to those files?

/cc @cadecairos in case jbuck is available to answer this question. :wink:

**Comment by jbuck** [comment]
Still a WP site. I haven't migrated it yet, so I'd suggest working with @cadecairos  to see if you want to keep it as WP, or just convert it to a static site with wget

**Comment by hannahkane** [comment]
just want to revive this issue. @mmmavis - is there a clear next step?

**Comment by mmmavis** [comment]
@cadecairos could you grant me SSH access? ping me on Mattermost when u get a chance so I can share my SSH key and ip with you. :grin:

**Comment by hannahkane** [comment]
pinging @cadecairos and @mmmavis to make sure this ticket doesn't get lost

**Comment by cadecairos** [comment]
I've added @mmmavis's public key to the instance running the blog. I believe she's going to be taking care of this in the next couple days.

**Comment by mmmavis** [comment]
Hey @ldecoursy ,
> Resources page - can we make this page private/not visible?

Are we hiding https://hivelearningnetworks.org/resources and its 3 subpages?

- https://hivelearningnetworks.org/resources/at-a-glance/
- https://hivelearningnetworks.org/resources/events/
- https://hivelearningnetworks.org/resources/community/

OR just https://hivelearningnetworks.org/resources ?

**Comment by ldecoursy** [comment]
@mmmavis Resources and its 3 subpages please :)

**Comment by mmmavis** [comment]
Done! sorry for the wait.
