### ISSUE TITLE
Update Mouse projects on /activity page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1691]
On teach.mozilla.org/activities

Remove (these are both included in the link to include below):
* Creative Commons GIF Exchange
* CSS Story Cards

Add: 
* Mouse Activity Kit

Thumbnail image - Mouse logo, see attached
Link - https://d157rqmxrxj6ey.cloudfront.net/mouseorg/34864/
Level - Beginner
Title - Mouse Activity Kit
Description - Mouse's online and offline activities like Kraken the Code, Tag Tag Revolution and CSS Story Cards explore topics ranging from HTML/CSS to search engine optimization and online identities.

![mozilla-square](https://cloud.githubusercontent.com/assets/4885898/13643525/5ab7ce80-e5ef-11e5-85f9-cdb143adb4ce.png)

**Comment by hannahkane** [comment]
I can do this one!

@ldecoursy - wondering if we might want to reconsider the title. "Mouse Activity Kit" might be a little confusing to people not yet familiar with the organization. Totally your call (or theirs).

**Comment by ldecoursy** [comment]
Yes, ok, will check with them and be back soon!

**Comment by ldecoursy** [comment]
OK let's go with "code/explore/connect with Mouse"

**Comment by ldecoursy** [comment]
Is it too late to change the logo to this? 
![mozilla-square-2](https://cloud.githubusercontent.com/assets/4885898/13677303/5555caa0-e6b7-11e5-98c8-98c4d9afe253.png)

**Comment by ldecoursy** [comment]
Sorry, last one! @hannahkane 
![mozilla-rectangle](https://cloud.githubusercontent.com/assets/4885898/13704482/340825f6-e76a-11e5-9890-6a417e46a1b6.png)

**Comment by hannahkane** [comment]
Filed a new ticket to update the logo.  See #1700
