### ISSUE TITLE
Create archive page for Mozilla Curriculum Workshop

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1694]
From @chadsansing:

Thank you, landing page team! We have an episode in the can on https://teach.mozilla.org/community/curriculum-workshop/.

That means we're ready to talk archiving. I *think* each entry should have

- An info header or box (like a grayed-out 'upcoming workshop' box?).
- An embedded video.
- The embedded etherpad - OR - transcripts of the etherpad and its chat.

I have transcripts in .md files [here](https://github.com/MozillaFoundation/curriculum-workshop/tree/master/march-8-2016) and will capture them for each subsequent episode, as well.

I imagine we need an archive page, as well as a page per archived episode. Does that sound right? Is there a way to automate this?

Thoughts on what to include and how to format, @hannahkane, @flukeout, @mmmavis, @ldecoursy, @amirad, @KGorr, @poh?

**Comment by hannahkane** [comment]
From @jgmac1106:

When archiving the talks is it also possible to post an mp3 for download?

When we were doing shows last year for MLN we found many folks downloading the audio for commute times.

A link to an mp3 would suffice but an rss feed for a “podcast" would be nicer...and then we get two shows from one event.

**Comment by chadsansing** [comment]
Do we have a preferred way to rip the audio from the video? That sounds like a great, light-touch suggestion to add value.

**Comment by hannahkane** [comment]
OK to close this?
