### ISSUE TITLE
March 23: Build MLN Community Call landing page and archive pages with CMS

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1697]
Per discussion with @simonwex, we'd like to build out a page for the MLN Community Calls (launches March 24th) **with the CMS** during the March 25 heartbeat.

The page layout will be based on the Curriculum Workshop landing page—likely including both a landing page and an individual page as described in https://github.com/mozilla/mozmaker/issues/48.

Ideal workflow would be something like what @flukeout described here: https://github.com/mozilla/wp-calypso/issues/19

Page copy, etherpad link, and video link to be provided by @ldecoursy and @kgorr.

**Comment by hannahkane** [comment]
@kgorr - we don't need it sooner. We'll likely use the Curriculum Workshop content as placeholder in the meantime. Thanks!

**Comment by KGorr** [comment]
@hannahkane, this should be what what you need:

**Page content:** https://docs.google.com/a/mozilla.com/document/d/12BkqcjSL1xTaetVWwRXvseEoaIoKMq0xGegqBckRusk/edit?usp=sharing @amirad, did you want to take a look at it before they upload? @ldecoursy, has edited.   

**Etherpad link:** https://public.etherpad-mozilla.org/p/MozTeachCC

**Video embed:** <iframe width="560" height="315" src="//www.youtube.com/embed/QfvrKvx4mUk" frameborder="0" allowfullscreen></iframe> (If you need different link, just let me know!)

**Comment by amirad** [comment]
Looks good to me!

**Comment by hannahkane** [comment]
@mmmavis @flukeout @gvn @simonwex - this is the ticket I mentioned at stand-up today. We need to ship this *in advance* of the end of the heartbeat, so wondering if we should built it the same way we built the Curriculum Workshop page.

@flukeout - would you want to take a crack at it?

**Comment by flukeout** [comment]
@hannahkane Yeah - I'll take this. We can just clone the current workshop page, and when the CMS is ready, we'll implement the "full design" which includes the Upcoming & Archived events in separate tabs.

**Comment by flukeout** [comment]
@mmmavis Can create this page with the same workflow as the last one? If so, could you please...

* Duplicate the current Curriculum Workshop Page
  * Can you duplicate the stylesheet as well in case I need to make special changes to this page?
* Set up the route so the page lives at ``https://teach.mozilla.org/community/community-call``
* Set up the ``Community Call`` menu item in the side-bar navigation under the Community header
  * Make it the first item of the two, so it's alphabetical

Once this is ready, let me know what branch it's in and I can add the content. Sounds good?

@hannahkane Does that URL and menu item label work for you?

**Comment by hannahkane** [comment]
url and menu item work for me, thanks

**Comment by flukeout** [comment]
@KGorr I'll need a link for the embedded video stream. Were you planning to use the same one as the Curriculum Workshop page? If so, the trouble with that is that it's showing the content from the workshop, which will be confusing...

![image](https://cloud.githubusercontent.com/assets/25212/13862036/e254fad4-ec4d-11e5-982b-e257c82a6694.png)

@mmmavis How can I change the page ``<title>``? Right now it just says "Mozilla Learning"

**Comment by KGorr** [comment]
Sorry @flukeout, looks like I had an adding link error earlier. It is a different video stream than the workshop.

Video embed: <iframe width="560" height="315" src="//www.youtube.com/embed/QfvrKvx4mUk" frameborder="0" allowfullscreen></iframe>

Event page link: https://plus.google.com/events/cj0tnkno6h0eod15toq7hgdddno

YouTube page: http://www.youtube.com/watch?v=QfvrKvx4mUk

Covering the bases, just in case.

**Comment by KGorr** [comment]
@flukeout, OK, it's just not showing the video embed code when I try to add it. I'll skype it to you and see if that works.

**Comment by flukeout** [comment]
There's a PR with the changes [here](https://github.com/mmmavis/teach.mozilla.org/pull/8), as soon as it's merged we'll put it on staging for review.
