### ISSUE TITLE
add details for "creativity" and "problem solving" badges

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1710]
these currently lack subtitles, unlike the other badges.

**Comment by hannahkane** [comment]
@Pomax - do you need content for this?

**Comment by Pomax** [comment]
if there is any, having that in this ticket will be useful

**Comment by hannahkane** [comment]
@anmechung - can you add copy for requirements here, too, please?

**Comment by anmechung** [comment]
Yes, and will include all in one google doc I'll share later today or tomorrow!  Thanks

**Comment by Pomax** [comment]
subsumed by https://github.com/mozilla/teach.mozilla.org/issues/1811
