### ISSUE TITLE
"collaboration" badge need requirements

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1715]
the individual badges page for "collaboration" does not list any requirements.

**Comment by hannahkane** [comment]
@Pomax - do you need content for this?

**Comment by Pomax** [comment]
if there is any, having that in this issue will be useful

**Comment by hannahkane** [comment]
@anmechung - do you have content for this section?

**Comment by hannahkane** [comment]
actually, @Pomax - clarifying question. I'd thought things like the Badge requirements would be something an admin would enter through the admin interface. Do they need to be entered by an engineer?

**Comment by Pomax** [comment]
they need initial data to work with for implementation purposes, and that needs to be "real" text so that the implementation choices make sense for what the live site will be doing. Having empty badge information does not let us work out the design implementation properly.

**Comment by hannahkane** [comment]
OK, thanks. In that case, @anmechung - can you please provide?

**Comment by anmechung** [comment]
Yes - will put something in google doc and send later today or tomorrow.

**Comment by anmechung** [comment]
@hannahkane @pomax see google doc for content - let me know if you have questions
https://docs.google.com/document/d/1u9j28HqV8QMsk-foS1r0N-tVtmcLTLsGz9m7eKcT_eU/edit

**Comment by anmechung** [comment]
@Pomax @hannahkane please note that per conversation with @sabrinang I've updated the content for badge requirements.  Collapsed from basically 8 badges to 4 badges. 5 sub-badges for collaboration  are now just 1 collaboration badge.

**Comment by Pomax** [comment]
subsumed by https://github.com/mozilla/teach.mozilla.org/issues/1811
