### ISSUE TITLE
"problem solving" badge need requirements

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1716]
The individual badges page for "problem solving" justs dummy criteria at the moment, rather than real criteria.

**Comment by hannahkane** [comment]
@Pomax - do you need content for this?

**Comment by Pomax** [comment]
if there is any, having that in this issue will be useful

**Comment by hannahkane** [comment]
@anmechung - can you add copy for requirements here, too, please?

**Comment by jgmac1106** [comment]
@annmechung is there one document that list all the badge pathways
(criteria and required evidence) for the badges being piloted?

**Comment by Pomax** [comment]
subsumed by https://github.com/mozilla/teach.mozilla.org/issues/1811
