### ISSUE TITLE
Images in the community page have a horizontal scrollbar

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.mozilla.org#1731]
Fixed in #1729 

The two images mid page in /community have scrollbars under their containers.

It also has some weird side effect where the images started to overlap if the width of the screen got smaller, my fix handles that too.

**Comment by ScottDowne** [comment]
@Pomax or @mmmavis thoughts?

**Comment by ScottDowne** [comment]
Oh, I also added an explicit width and height to these images as I'm told the browser can use it to display the images faster because it doesn't need to detect the size.  Not sure if it uses css for that.

If there are issues with the width and height on the img then I'm not super picky and we can remove it.

**Comment by Pomax** [comment]
setting the dimensions on the page for images that don't change very often is a good idea.
