### ISSUE TITLE
Update language and label in various Web Lit activites 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1738]
Update the [activities](https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#heading=h.hwiildxvzsx4) (left hand column on each of the activity pages) and change from Web Literacy Competencies to “Web Literacy Skills” with corresponding skills in the 3 column from left. Also add “21st Century Skills” header (similar to Web Literacy Skills) underneath with corresponding 21st Century Skills in far right column.

Mentioned in issue: https://github.com/mozilla/teach.mozilla.org/issues/1659#issuecomment-198633349

/cc @chadsansing @anmechung

**Comment by anmechung** [comment]
@chadsansing and I updated the the crosswalk - activities and corresponding web literacy skills, and @chadsansing updated the language in each Web Lit Basics II activity.  Needs to be updated for Web Lit Basic I.  If someone can do this or show me how to do it that would be great. 
https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#
closed

**Comment by anmechung** [comment]
@chadsansing can you show me how to update the Web LIt Basic I activities?  Its confusing otherwise.

**Comment by chadsansing** [comment]
@anmechung - @ldecoursy and I want to open a broader discussion about what to do with that unit. Let's talk after my PTO.

**Comment by hannahkane** [comment]
is this now duped by #1791?

**Comment by sabrinang** [comment]
@hannahkane Yes, that issue is addressing what is mentioned here.

**Comment by hannahkane** [comment]
K. Closing this then.
