### ISSUE TITLE
Update Web Literacy 2.0 whitepaper changes

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1739]
Update http://mozilla.github.io/content/web-lit-whitepaper/ as mentioned in this issue: https://github.com/mozilla/teach.mozilla.org/issues/1659#issuecomment-198633349

- making it more clear 21 Century skills are separate from competencies (not seen on the same bullet list)
- integrate specific 21C competencies into the white paper rather than as a link to chart
- add the text seen on bottom of page 10 (in red) to the white paper https://docs.google.com/document/d/1Cs0rAd7zZqV5pNovTbjqF-F0eM6Qw0etnG5SOWa4jVk/edit. Also add in 5 places to clarify skills and competencies (also in red): top of page 4, middle of page 5, top of page 8, foot on page 8, middle of page 10.

/cc @anmechung

**Comment by anmechung** [comment]
@sabrinang when you update the new web lit paper, can you do the follow:
- remove hyperlink to "21st Century Skill" on page 1, first paragraph
- Research Finding section: change hyperlink for "Web LIteracy Map" to original concept paper, remove hyperlink to strategies evolved and "existing basic web literacy grid" and change the wording of this to "first web literacy map"
- Under each web literacy skill, the 21C skill is a bullet - can you distinguish this from the competencies in some way (as we discussed)?  Also, can you make the 21C skill headings plural, i.e. 21C Skills? I updated this in the google doc version of the paper too. 
- currently the link to the original white paper is the the new white paper.

**Comment by anmechung** [comment]
@sabrinang revise on the second bullet above: the hyperlink for "web literacy map" is correct (its to wiki page which will also work), but if can make hyperlink to "first web literacy map" that would be great.

**Comment by anmechung** [comment]
@sabrinang This is probably the most appropriate link to the first web literacy paper: http://mozilla.github.io/webmaker-whitepaper/

**Comment by sabrinang** [comment]
Copy changes has been updated in https://github.com/mozilla/content/pull/5#event-613963483. I'll continue to update this paper with pictures of persona images https://github.com/mozilla/content/issues/1 and adjusting hierarchy in heading styles.

**Comment by sabrinang** [comment]
Updated this in https://github.com/mozilla/content/pull/6
