### ISSUE TITLE
Question about production site

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1746]
@Pomax @alicoding 

Are we still serving static files from S3 for production site? If so I'll need to amend the [CHANGELOG](https://github.com/mozilla/teach.mozilla.org/blob/develop/CHANGELOG.md#changed)

**Comment by alicoding** [comment]
Currently it still is serving the files from S3. I have a pull request and working on getting that off, but probably going to be sometime before end of this week.

**Comment by mmmavis** [comment]
@alicoding have we say goodbye to S3 yet? :smile:

**Comment by Pomax** [comment]
some more information over in https://github.com/MozillaFoundation/mofo-devops/issues/290 but I think S3 is still technically up?

**Comment by alicoding** [comment]
We're not using that s3 bucket now and will remove that after we are super sure that this is good without it :)

**Comment by Pomax** [comment]
\o/

this calls for an extra victory coffee checkbox.

**Comment by mmmavis** [comment]
WOOHOOO fantastic work team! :tada: :beers:

**Comment by mmmavis** [comment]
Let's [update README.md](https://github.com/mozilla/teach.mozilla.org/issues/1797) and close this ticket then!
