### ISSUE TITLE
Create archive page for Mozilla Learning Community Call

### ISSUE THREAD

**Issue by KGorr** [mozilla/teach.mozilla.org#1752]
Similar to the [open ticket](https://github.com/mozilla/teach.mozilla.org/issues/1694) for archiving the Mozilla Curriculum Workshop, we'll also need to archive the Community Call page.

I believe the format is already in progress via the CMS template work, so this serves as a reminder to please include the community call landing page: https://teach.mozilla.org/community/community-call/ Thanks!

CC @hannahkane

**Comment by hannahkane** [comment]
@KGorr - do you have info about the upcoming call we can include?

**Comment by KGorr** [comment]
I have a planning meeting tomorrow with @thornet , so I hope to know more then! For now, new etherpad is: https://public.etherpad-mozilla.org/p/mozcommunitycallApril16 and I can skype the embed code for the live stream to you/Luke. Just let me know who is working on it. Thanks @hannahkane!

**Comment by hannahkane** [comment]
please share details with @flukeout. Is it okay to wait until we have details about the upcoming call before archiving the last one?

**Comment by KGorr** [comment]
Yes! I'll get it @flukeout ASAP. Thanks!

**Comment by flukeout** [comment]
:+1:

**Comment by flukeout** [comment]
**Updated content**

Youtube link
``<iframe width="560" height="315" src="//www.youtube.com/embed/d3YJUZVoYws" frameborder="0" allowfullscreen></iframe>``

Content
https://docs.google.com/document/d/12BkqcjSL1xTaetVWwRXvseEoaIoKMq0xGegqBckRusk/edit

**Comment by KGorr** [comment]
@thornet, there are a couple of items highlighted in the page content that @flukeout added above that need your input/approval. Thanks!

**Comment by KGorr** [comment]
Content is good to go @flukeout. Thanks @thornet!

**Comment by flukeout** [comment]
PR filed for these changes https://github.com/mozilla/teach.mozilla.org/pull/1804

Will post a link to review content once it's on staging.

**Comment by KGorr** [comment]
Thank you!
