### ISSUE TITLE
Link to whitepaper on 21st Century Skills page is wrong

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1756]
Looks like we're linking to the older Whitepaper on the 21st Century Skills page: /web-literacy/skills

Correct link is: http://mozilla.github.io/content/web-lit-whitepaper/

**Comment by anmechung** [comment]
+1 and FYI @sabrinang is making some edits to the new web lit white paper.

**Comment by mmmavis** [comment]
fixed.
