### ISSUE TITLE
Update X-Ray Goggles Cheat sheet

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1775]
We're in the process of updating some of the activities featured at teach.mozilla.org/activities

The Hacking My Media activity (also a featured activity on the Goggles landing page), links to an HTML Cheatsheet Thimble project which I've updated here: https://thimbleprojects.org/mozillalearning/48435/

The first link to "download the cheatsheet" goes to an old PDF with Hackasaurus branding. I know this printable format has been useful for events in the past, and think it's worth updating. 

Should be simply swapping out Hackasaurus logo at top with new Goggles logo, and updated URL at the bottom.

**Comment by ldecoursy** [comment]
Here's the PDF of the cheatsheet https://wiki.mozilla.org/images/f/fa/Xray_goggles_cheatsheet.pdf

**Comment by Pomax** [comment]
@hannahkane do we know who can update these links?

**Comment by hannahkane** [comment]
@pomax - Lainie or I can update the Thimble project. Do you mean who can update the pdf? Since we don't have the original file, we might need to re-create it. @sabrinang - wondering if you'd have time for this?

**Comment by sabrinang** [comment]
@hannahkane Yeah, I can update the pdf

**Comment by hannahkane** [comment]
thank you, @sabrinang!

**Comment by sabrinang** [comment]
Work in progress on redpen here: https://redpen.io/p/dh0df011100a3ae33e

I have a question about one of the keys, does "backspace" still delete an element on the newest version of xray goggles? (I tried and it didn't work so I excluded it on the newer ideas). 

Also, we should consider calling it Keyboard Shortcuts instead of Cheat Sheet because it was immediately clear what cheat sheet meant. Some feedback I got from was if that heading is necessary at all and we can consider including a tagline instead.

**Comment by hannahkane** [comment]
pretty!

cc @Pomax for the answer to your question about the backspace shortcut. I don't know why that would have changed, but maybe?

**Comment by hannahkane** [comment]
ping @Pomax to answer the question re: backspace shortcut.

Otherwise, @sabrinang, are we good to go on this?

**Comment by Pomax** [comment]
I completely missed this issue - backspace as far as I'm aware does not do any element deletion, just text deletion in the edit box when you click on a part of the page.

**Comment by sabrinang** [comment]
Thanks Pomax, I have excluded the backspace as an element deletion shortcut on this sheet. 
@ldecoursy Please review on redpen here: https://redpen.io/owf9f6ab2a2cdf269b 

If there are any other changes let me know. If it is good to go the files are exported to google drive (.png .jpg .pdf) here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eYU94eFBja29sX3c&usp=sharing

**Comment by hannahkane** [comment]
@ldecoursy - does this work for you? Can we close?

**Comment by ldecoursy** [comment]
It does! Thanks all! Should we add a link to the SUMO page for Goggles?

**Comment by hannahkane** [comment]
@ldecoursy - can you clarify? Are you suggesting we add a question to the Goggles section of SUMO that includes a reference to the Cheat Sheet? I think that's a good idea, but just want to confirm that's what you meant.

**Comment by ldecoursy** [comment]
Yep, will close this and file separate ticket.
