### ISSUE TITLE
Update activity link on teach.mozilla.org/activities 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1776]
Here is the new link (in new Thimble) for the Hack My Media activity - featured on both teach.mozilla.org/activities and goggles.mozilla.org

https://thimbleprojects.org/stephguthrie/48361/

**Comment by ldecoursy** [comment]
On the teach site, it's listed as Girls in Tech: Hacking My Media

**Comment by hannahkane** [comment]
Making this ticket specifically about the Teach site, because I can fix that. Filed one for goggles here: https://github.com/mozilla/goggles.mozilla.org/issues/287

**Comment by Pomax** [comment]
cheers, removing the goggles label in that case

**Comment by hannahkane** [comment]
oh sorry, @Pomax - just saw your label updates. ha. sorry, probably being over process-oriented here. :) but I can do this one, so it'll save you a few minutes. :)

**Comment by Pomax** [comment]
\o/
