### ISSUE TITLE
Images on /activities don't have fixed width anymore

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1781]
https://teach.mofostaging.net/activities
<img width="670" alt="screen shot 2016-03-31 at 2 16 18 pm" src="https://cloud.githubusercontent.com/assets/2896608/14191136/2af3157a-f74b-11e5-9d0a-cb875d86c6e3.png">

It's probably related to the recent change made in https://github.com/mozilla/teach.mozilla.org/commit/99672d323b35f2caf3b22b0f205f5319abb03080#diff-9fb9a1085ade89fb217c95df87a638cf . 

@ScottDowne could you remind me what the reason was for the CSS change?

**Comment by ScottDowne** [comment]
max-width: 100% doesn't work in firefox stable.

**Comment by ScottDowne** [comment]
I should be more specific. This page https://teach.mofostaging.net/community had horizontal scrollbars on some of the images.

**Comment by ScottDowne** [comment]
you can still see it here: https://teach.mozilla.org/community

Firefox stable.

**Comment by ScottDowne** [comment]
If we move max-width: 100% onto image-container, it doesn't bug out in firefox stable, and doesn't seem to cause any other issues. I'm testing a bit more, but it makes sense.

**Comment by ScottDowne** [comment]
I think something like this https://github.com/mozilla/teach.mozilla.org/pull/1784/files
