### ISSUE TITLE
Better align SUMO with teach.mozilla.org content

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/teach.mozilla.org#1785]
Surfacing this issue for discussion.

Joni Savage, who maintains SUMO, reached out about https://support.mozilla.org/en-US/products/webmaker. There are dead links + dated copy that doesn't jibe with current teach.mozilla.org language and resources.

For example, "[What is a Webmaker mentor?](https://support.mozilla.org/en-US/kb/webmaker-mentor)"

Might be worthwhile to do an audit and delete confusing language that refers to the MLN community as the Webmaker community. 

@ldecoursy @KGorr

**Comment by ldecoursy** [comment]
Thanks @KevZawacki - good flag. 

Honestly that entire Events section is outdated and should probably be removed - https://support.mozilla.org/en-US/products/webmaker/events-and-help-for-mentors

Also, the Get the Most from Webmaker.org is also very old (also remove). 

The Webmaker for Android, Thimble and Goggles all seem up-to-date, but do they belong under the Webmaker banner or can they be separate?

**Comment by KevZawacki** [comment]
@ldecoursy That's an easy fix :-) I'll email Joni now. 

Agreed that housing all the tools under the Webmaker banner is strange:

![screen shot 2016-04-01 at 3 26 29 pm](https://cloud.githubusercontent.com/assets/11045250/14217788/1cb0dc6c-f81e-11e5-9c42-fed1f46eaac9.png)


 Would we want to give each tool it's own icon? Or rename the Webmaker icon to something more generic? I'm thinking the latter... but we'd need a generic MLN icon.

**Comment by ldecoursy** [comment]
We don't have that yet so maybe we leave it for now- or change to Thimble (which has more momentum) and say Thimble and other tools for teaching and learning the Web.
