### ISSUE TITLE
Update links to Web Lit Basics 1 activities in Web Lit Map

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1792]
The Web Lit Map 2.0 is linking to older versions of the Web Lit Basics I activities. 

Can we update the links to the versions that have the translations available as a pull-down on the top right-hand corner?

* Kraken the Code https://mozilla.github.io/mozilla-club-activity-kraken-the-code/#en
* Ping Kong https://mozilla.github.io/mozilla-club-activity-ping-kong/#en
* Hack the News https://mozilla.github.io/mozilla-club-activity-hack-the-news/#en
* HTML Puzzle Boxes https://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#en
* Web Chef https://mozilla.github.io/mozilla-club-activity-web-chef/#en
* Story of Us https://mozilla.github.io/mozilla-club-activity-story-of-us/#en

This should happen after the skills are updated in these activities, as per #1791 

cc @chadsansing @anmechung

**Comment by hannahkane** [comment]
@ScottDowne - I think this might be something I can do myself. Would I just update the links in pages/web-literacy/activitydata.js?

**Comment by ScottDowne** [comment]
@hannahkane  :star: :star: that's exactly it!

**Comment by hannahkane** [comment]
ok, cool. I'll submit this now, so it's ready to go, since the links won't change even after we do #1791.
