### ISSUE TITLE
Encryption banner is missing on homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1796]
Chrome and FF

Does appear on staging in FF

**Comment by hannahkane** [comment]
cc @mmmavis @ScottDowne

**Comment by ScottDowne** [comment]
staging has the fix, I suspect prod does not. There is something related to this that I fixed already, which is also not on prod, so once that's up, I think both issues are going to go away.

**Comment by kristinashu** [comment]
@hannahkane I see the banner now so I think this has been fixed.
