### ISSUE TITLE
Hive Waterloo logo needs to be changed to Hive Waterloo Region 

### ISSUE THREAD

**Issue by simonaramkisson** [mozilla/teach.mozilla.org#1805]
@sabrinang @mmmavis 

Hi all,
Hive Waterloo has asked that we change their current logo from "Hive Waterloo" to "Hive Waterloo Region" as that is the official name of their municipality. 

Let me know if you need anything from me, the vectorized files are here: https://drive.google.com/drive/u/0/folders/0B4Q8pzCpDS_eQi1sOXo3Rk83Vms 

Thanks so much,
Simona

**Comment by simonaramkisson** [comment]
@hannahkane

**Comment by sabrinang** [comment]
@simonaramkisson I have updated the logo to Waterloo Region. You can find the .eps file here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eMkJwVzU0TWVTNlU/view?usp=sharing
and .png file: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTGpXSGdIVFcxWU0/view?usp=sharing

**Comment by simonaramkisson** [comment]
Awesome! Thanks so much @sabrinang!
