### ISSUE TITLE
Broken Link on Teaching Activities Page

### ISSUE THREAD

**Issue by KGorr** [mozilla/teach.mozilla.org#1806]
The "Code/Explore/Connect with Mouse" activity featured on the [teaching activities](https://teach.mozilla.org/activities) page goes here https://d157rqmxrxj6ey.cloudfront.net/mouseorg/34864/ and is landing on an "Oh no! The page you're looking for is not available! " message.

**Comment by hannahkane** [comment]
Thanks for noticing and filing! Fixed in https://github.com/mozilla/teach.mozilla.org/issues/1793 (will be pushed live with next release)
