### ISSUE TITLE
Adjustments to 21C Skill labels on Web Lit Map

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.mozilla.org#1808]
I was looking through the map and noticed Synthesize, Share and Connect had the wrong 21C on the map. On the whitepaper it is identified as:

Synthesize - 21C Skills: Problem-solving, Communication  (Blue, Orange)
Share - 21C Skills: Creativity, Communication (Purple, Orange)
Connect - 21C Skills: Problem-solving, Communication, Collaboration (Blue, Orange, Yellow)

/cc @anmechung

**Comment by anmechung** [comment]
@sabrinang good catch  - it is correct in the whitepaper!

**Comment by hannahkane** [comment]
@Pomax @mmmavis @ScottDowne - do any of you have time to make this change?

**Comment by ScottDowne** [comment]
I can fix

**Comment by ScottDowne** [comment]
FIxed in https://github.com/mozilla/teach.mozilla.org/pull/1821

@Pomax or @mmmavis review?
