### ISSUE TITLE
When navigating to a new page, should be scrolled to top

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1812]
STR:

Scroll down to the bottom of a page - for example, the homepage.
Use the sidebar navigation to click on another page.
You'll be scrolled down to the bottom of the other page.

**Comment by Pomax** [comment]
this would be because of how React isn't actually "loading a new page" but just swaps in UI content. We might be able to fix this by having `<Sidebar>` links always trigger a `window.scrollTo(0,0)`.
