### ISSUE TITLE
Images on Teaching Activities page are way too wide.

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1817]
Check out https://teach.mozilla.org/activities

![image](https://cloud.githubusercontent.com/assets/25212/14570347/af6ec84a-02f8-11e6-9f78-1cb07c94736b.png)

**Comment by hannahkane** [comment]
Is this a dupe of https://github.com/mozilla/teach.mozilla.org/issues/1781?

**Comment by flukeout** [comment]
Oh yea, looks like.
