### ISSUE TITLE
Sign-up thank you page is 404'ing

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1818]
See https://twitter.com/dietrich/status/722153934341562368

**Comment by hannahkane** [comment]
Putting in the current milestone because it is embarrassing and because it will likely be confusing to users.

cc @Pomax and @mmmavis - do I need to alert anyone else?

**Comment by Pomax** [comment]
I think that covers it - it feels like this is react-router doing the wrong thing with the `https://teach.mozilla.org/?signup=thanks` location

**Comment by hannahkane** [comment]
cc @KGorr so she can follow along in case users ask about this

**Comment by Pomax** [comment]
@mavis pretty sure I found the problem, namely that the code that rewrites express `url` paths to react-router `path` properties did not strip #hash and ?query=value stuff. I've fixed that up and filed a PR, can you review?
