### ISSUE TITLE
Update Club Captain application

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1822]
See Items 2 and 3 on [this doc](https://docs.google.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit)

Needs a little bit of UX thought, but mostly just form field changes.

**Comment by xmatthewx** [comment]
Current form: 

<img width="650" alt="screenshot 2016-04-21 16 13 34" src="https://cloud.githubusercontent.com/assets/53411/14722887/0b6461fe-07dc-11e6-9e13-fa3993b7ad63.png">

**Comment by xmatthewx** [comment]
Find the happy medium to learn enough info to evaluate potential captain, without asking so much that it overwhelms.

**Comment by sabrinang** [comment]
I have taken a pass at adapting the copy in the form format (pages 8-10 of the New CC application flow doc): https://docs.google.com/a/mozilla.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit?usp=sharing

<img width="1085" alt="screen shot 2016-04-26 at 10 26 17 pm" src="https://cloud.githubusercontent.com/assets/2492510/14842625/ed7c19f4-0bfd-11e6-9628-cfb93c4e831f.png">

@amirad @hannahkane  Please take a look at the copy as I have shuffled and reduced some text. Feel free to edit directly or comment in the google doc as it is easier and more direct than redpen.

https://redpen.io/p/he4d93fc5a7a4e6b0b - redpen illustrates form states and format in context.
<img width="1035" alt="screen shot 2016-04-26 at 10 29 56 pm" src="https://cloud.githubusercontent.com/assets/2492510/14842670/804235d4-0bfe-11e6-8c3a-7769b165808a.png">

**Comment by xmatthewx** [comment]
Nicely done @sabrinang. The two-step process feels very approachable.

**Comment by amirad** [comment]
Agree! love the two step process.

**Comment by hannahkane** [comment]
Want to flag @carotejada to make sure this works for her as well.

**Comment by Carotejada** [comment]
Thanks @hannahkane!

@sabrinang LOVE it!!!!

**Comment by sabrinang** [comment]
I scheduled a review session with @amirad  @Carotejada @Pomax  to go over form content and structure.

Amira and Carolina - we can continue iterating copy and content on the same google doc: (pages 8-10 of the New CC application flow doc): https://docs.google.com/a/mozilla.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit?usp=sharing and inform Pomax of our plans so he can flag any structure limitations as he is familiar with how the form is implemented (some interactive states are shown on the [redpen](https://redpen.io/p/he4d93fc5a7a4e6b0b).

**Comment by sabrinang** [comment]
We reviewed content and tech requirements. The text has been revised on [google doc](https://docs.google.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit) and design revised on [redpen](https://redpen.io/p/he4d93fc5a7a4e6b0b).

Ready for design review on Mondays critique.

**Comment by sabrinang** [comment]
Revised repen https://redpen.io/p/he4d93fc5a7a4e6b0b with feedback and made form full width to provide more space, be directly linkable (if we give it its own URL), avoids issue of users losing form progress if they click outside modal accidentally and looking closer like a [unify form field design](https://github.com/MozillaFoundation/Design/issues/165)
<img width="1338" alt="screen shot 2016-05-03 at 5 50 17 pm" src="https://cloud.githubusercontent.com/assets/2492510/15002619/d2613c3a-1157-11e6-900d-2b829e6473a0.png">

**Comment by hannahkane** [comment]
+1 for unification!
@sabrinang - does this need to go through another design review, or is it ready for implementation?

**Comment by Carotejada** [comment]
@hannahkane @sabrinang This is great :)

**Comment by sabrinang** [comment]
@kristinashu R? on full page form redpens: https://redpen.io/cg7a422f47a656dd0e

**Comment by kristinashu** [comment]
Looks great @sabrinang! I much prefer the full page layout. Just made a couple notes about the progress bar and making required fields, but they're just things to consider.

**Comment by xmatthewx** [comment]
R+! Added a redpen comment or two, but nothing critical. Nicely done.

**Comment by sabrinang** [comment]
Thank you for reviewing! I have updated spacing for the subhead and streamlined the progress bar. I will file a new issue for implementation.
