### ISSUE TITLE
Update MLN Community Call page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1839]
@kgorr - when you have details about the next Community Call finalized for the site, please drop them here and we'll update the site. Thanks!

**Comment by KGorr** [comment]
@hannahkane - will do!

**Comment by KGorr** [comment]
Here is the video embed code

`<iframe width="560" height="315" src="//www.youtube.com/embed/LlEXY8NKxoY" frameborder="0" allowfullscreen></iframe>` (I figured it out @flukeout!!!!!!!!) Ha! 

Here is the etherpad: https://public.etherpad-mozilla.org/p/mozcommunitycallMay16

Should have the page copy sometime this week. Thanks!

**Comment by hannahkane** [comment]
Adding the blocked label just to note we're blocked on copy, but no rush on our end @KGorr.

**Comment by KGorr** [comment]
@hannahkane, here is the page content:

**"Upcoming Call" box content:**

May 25: 11am HADT/ 1pm PT/ 4pm ET/ 8pm GMT/ 10pm SAST
Gigabit
Featured speakers: Caleb Bagby, teacher at Red Bank High School in Chattanooga, Chad Sansing, Curriculum Developer and Web Literacy for Mozilla, and Rebecca Dove and Quest Taylor, who are working together on an artificial intelligence literacy application called Pennez.

Technology is continually advancing. Join us as we explore how high-speed, low-latency gigabit networks are allowing educational technology to advance rapidly. Thanks to these new connection speeds, education has the opportunity to evolve in ways that wouldn’t be possible on traditional networks, becoming more immersive and more engaging than ever before.

**Content for under the "upcoming call" box:**
On this month’s call, we’ll explore how gigabit technology is transforming today’s classroom. We’ll discuss how emerging technologies like virtual reality, artificial intelligence, and 4K video streaming are being deployed to engage students, address learning needs, and create new outcomes for education.

Viewers can ask questions and share ideas and feedback of their own through the embedded agenda and chat.

**Comment by hannahkane** [comment]
Thanks, @KGorr!

@mmmavis - I'm wondering if you think this is something I could do. My guess is that I would copy the content of /community-call-march-23.jsx into a new file and replace the relevant content with the most recent info. Then I would update /community-call.jsx with the newest info and add a link to the new page at the bottom.

If it's as straightforward as that, should I give it a try?

**Comment by flukeout** [comment]
GO HANNAH!!!!!

Yeah, that's pretty much it. You also have to update an entry in the ``routes`` file - that's what tells the server which page to show depending on the URL.

Here is the last PR related to the changes, there are a bunch of CSS changes you can ignore, but you'll see the ``routes.jsx`` pages there.
https://github.com/mozilla/teach.mozilla.org/pull/1804/files

Lastly, you'll need to change the class name on the info callout box and change the heading to say "Past Workshop" instead of upcoming one.

```
<section className="callout-box past-workshop">
  <h2>Archived Call</h2>
```

I'm happy to take this on though, let me know!

**Comment by hannahkane** [comment]
thanks for the additional info, @flukeout. I'll give this a try and let you know if I run into trouble. Thank you!!!
