### ISSUE TITLE
Change Gigabit twitter handle

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1840]
The Gigabit twitter handle has changed to https://twitter.com/MozGig

There are two places on the gigabit website that reference an older handle. We should change it.

Right hand info box on the [homepage](https://www.mozilla.org/en-US/gigabit/):

![screen shot 2016-04-25 at 8 31 45 am](https://cloud.githubusercontent.com/assets/8389648/14789174/2b38e86a-0ac0-11e6-85da-5b8ee6859519.png)

Bottom of the [Apply page](https://www.mozilla.org/en-US/gigabit/apply/):
![screen shot 2016-04-25 at 8 31 22 am](https://cloud.githubusercontent.com/assets/8389648/14789164/1bd3bab2-0ac0-11e6-8393-a8de67bcb7ff.png)

cc @jenntbeard

**Comment by hannahkane** [comment]
@mmmavis - possible for you to make this change?

**Comment by mmmavis** [comment]
yup yup i'll submit a PR to mozilla.org later today :bowtie:

**Comment by jenntbeard** [comment]
Thank you so much!!

**Comment by mmmavis** [comment]
No problem! :wink: 

Bugzilla ticket filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1267409
Will have a PR up for this soon.

**Comment by mmmavis** [comment]
PR up on https://github.com/mozilla/bedrock/pull/4092

**Comment by mmmavis** [comment]
changes are live! https://www.mozilla.org/gigabit and https://www.mozilla.org/gigabit/apply! :tada:
