### ISSUE TITLE
Adjust Curriculum Template design to make it easier to read.

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1841]
Received some feedback from  a Hive member:

> My feedback (before use with other humans) is a UI piece for teachers. That is a lot of dark gray text on white (necessary, of course!). Can we play with the format to make it more read-able? I suggest bullets or color blocks if possible.

@chadsansing Do you have any extra info on this?
* Do you know which specific curriculum they are referring to?
* What do you think they mean by a UI piece for teachers?

**Comment by chadsansing** [comment]
@flukeout, this is in response to JS activities under development that use the curriculum template.

E.g. http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session01-buttons-and-alerts.html#overview

I think the UI piece means using some indicator to chunk and break up text whenever possible, like between a paragraph and list. Let's ask. I'll ship the thread to the Hive member for more feedback.

**Comment by Animaltinez** [comment]
@flukeout @chadsansing I think Chad described what I was thinking pretty well. Teachers, like all people, don't read, they skim, especially if they are in a workshop and have to follow this like a guide. 

My comment could also have read: "Please increase overall read-ability" 


Does that help?

**Comment by flukeout** [comment]
Sure, thanks! I think there are two ways to do this...

* Changes to the design like making the base font darker and easier to read.
* Content changes that reduce the amount of text and introduce more bullets and lists

I'll focus on the first for now and let @chadsansing mull on the second.

I also noticed that the way we're structuring the headings is pretty hard to read...

![image](https://cloud.githubusercontent.com/assets/25212/14895629/713f815a-0d2e-11e6-815a-b2998dec617d.png)

It looks like there are three levels of heirarchy here, so we should have a way to make that more apparent.

Additionally, when the page is scrolled, the sidebar image goes away! Yikes...

![image](https://cloud.githubusercontent.com/assets/25212/14895671/a0e527f2-0d2e-11e6-9a97-20d164badc7f.png)

I'll get on that too.

**Comment by chadsansing** [comment]
Awesome, @flukeout. I agree that content is part of the issue here. Hopefully, as more curriculum gets used, we'll get more feedback and can better balance the amount of text against users' desire to have things broken down. 

In the meantime, @Animaltinez, I assure you the intent here is to provide detailed lesson plans for participatory activities - we would run these activities live at web literacy trainings, but never in a sit-and-read-the-plan way. What cues could we use to help hook educators and get them to go from skimming to reading while looking for classroom materials?

**Comment by Animaltinez** [comment]
@chadsansing , this: 

_What cues could we use to help hook educators and get them to go from skimming to reading while looking for classroom materials?_

...is a very interesting question that is a great example of a topic for an event Sprout is working on with MLN to discuss “Sustained Engagement/Engagement & Sustainability” . 

I don’t have much detail on that just now, but this is helpful to naw on in the meantime. –a

**Comment by flukeout** [comment]
First, some updates to the overview page...

* New styling for ``Activity 1 of 8``
* New styling for Description paragraph
* New styling for Web & 21C skills
  * This matches how we present them on the Web Lit map pages
* New treatment for module names above title

![image](https://cloud.githubusercontent.com/assets/25212/14922877/f1e90518-0dee-11e6-998a-e218618c42f7.png)

cc @chadsansing 

Coming next, changes to the step pages.

**Comment by flukeout** [comment]
Some fancy list treatments...

![image](https://cloud.githubusercontent.com/assets/25212/14925403/1b715c20-0dfc-11e6-98e1-f132897b488d.png)

**Comment by flukeout** [comment]
Title treatment once you're viewing the steps of an activity...

![image](https://cloud.githubusercontent.com/assets/25212/14925465/69596860-0dfc-11e6-9a30-ec32b1da6703.png)

@chadsansing Will these (like Intermediate Web Literacy II) link somewhere?

**Comment by chadsansing** [comment]
@flukeout - I love how this is coming along. Let's try to link the module title (e.g. "Intermediate Web Literacy II") back to the module index page of off /activities. This module is almost live, but not quite yet, so the link in this case is forthcoming.

**Comment by flukeout** [comment]
**Cover page**

![image](https://cloud.githubusercontent.com/assets/25212/14931027/27233662-0e1d-11e6-9a9a-5058cb146f2c.png)

**On Subsequent pages**

![image](https://cloud.githubusercontent.com/assets/25212/14931035/34c52532-0e1d-11e6-95af-8e3bb2b30c07.png)

**Next-up treatment**

![image](https://cloud.githubusercontent.com/assets/25212/14931037/406e13c6-0e1d-11e6-9e16-a4041334dc02.png)

**Comment by flukeout** [comment]
The big to do is to figure out the problem with the image not scrolling with the side-nav.

**Comment by chadsansing** [comment]
Keep it rollin', @flukeout.

**Comment by flukeout** [comment]
Closing and starting #1850 where we review the changes and continue the discussion.
