### ISSUE TITLE
[May 4] Design print ad for Gigabit City Summit program

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1845]
From @jenntbeard:

We just received a request for a 1/4-page ad for the printed agenda/program that comes with our Gigabit City Summit sponsorship. The ad should be 3.875" x 5" and full color. 

Lindsey suggested that we might be able to repurpose the art that was used for the RFP with a call to action to about our next two Mozilla Gigabit cities.

Potential copy (with logo attached):
Two new Mozilla Gigabit cities are coming in 2017.
It could be yours.
Learn more at mozilla.org/gigabit

**Comment by hannahkane** [comment]
@sabrinang - as discussed at stand, can we put this on your plate this heartbeat?

**Comment by sabrinang** [comment]
@hannahkane Yup, I'll take this on this heartbeat

**Comment by jenntbeard** [comment]
@sabrinang Do you need me to upload the Mozilla Gigabit logo or provide any other info? Thanks for taking this on!

**Comment by sabrinang** [comment]
@jenntbeard I made some iterations with the potential copy seen on this issue. Redpen here: https://redpen.io/p/um5d47a6424ad92c01 

Let me know if this copy is finalized and if there are any other visual preferences or considerations for this ad

**Comment by hannahkane** [comment]
This looks great, @sabrinang.

I'm finding the grammar slightly awkward, but I think it's a subjective thing. @jenntbeard - what do you think about "Two new Mozilla Gigabit cities are coming in 2017. One could be yours." ?

**Comment by jenntbeard** [comment]
@hannahkane I had a drafted comment to change that to exactly that wording, thank you. Our team is voting on design choice now and I should have that within the next 30 minutes. Thank you all!

**Comment by sabrinang** [comment]
We are design critiquing now and we like idea 1 best for its simplicity (so it doesn't overshadow the message) and most suitable for printing purposes

**Comment by jenntbeard** [comment]
Great, we all like #1 as well with the copy change to "One could be yours".

**Comment by sabrinang** [comment]
Thanks for all the feedback! The design has been revised:
- increased contrast of orange to white and font weight to help with legibility for print
- new copy for the last line "One could be yours"

The updated repen here: https://redpen.io/so78780de139673fbb
Exported (.jpg .png .pdf with and without 0.125" bleed) to google drive here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_eNkJMVVNtSFJtS0E&usp=sharing

**Comment by jenntbeard** [comment]
@sabrinang @hannahkane This is fabulous, thank you so much for pulling this together so quickly, it looks great!

**Comment by hannahkane** [comment]
Nice work, @sabrinang! Closing. :)
