### ISSUE TITLE
Sponsorship Ad for Allied Media Conference Brochure

### ISSUE THREAD

**Issue by mcdermott415** [mozilla/teach.mozilla.org#1852]
Dear MoFo Designers,

Mozilla is a sponsor for the 2016 Allied Media Conference. 
By this Friday, May 6th, we need:

    Full page ad: 7.5" x 7.5"
    300dpi, photoshop, illustrator, PDF or tiff preferred. No Word documents. 
    All ads are black and white.

With the Mozilla Logo, we want this text:
Mozilla is proud to sponsor the 2016 Allied Media Conference
Let's stand up for the open web together.

A photo or fox is welcome!  I know this is a tight timeline, so please re-purpose any existing design assets that would make this possible.

**Comment by hannahkane** [comment]
As discussed, given the tight timeline and already full heartbeat we're in the midst of, we're not going to be able to do this. Closing this ticket, but noting that we might add "ad template" to the list of templates we make available for staff use. cc @sabrinang @kristinashu 

Thanks, @mcdermott415, for filing the ticket, and for your understanding!

**Comment by mcdermott415** [comment]
Thanks Hannah, and all for helping me understand the process! Good luck
getting through the crunch.
