### ISSUE TITLE
Replace link to X-Ray Goggles Cheat Sheet in Hack the News activity

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1854]
We have an updated X-Ray Goggles cheat sheet (activity and printer-ready PDF): https://thimbleprojects.org/mozillalearning/48435/

Can someone help update the link on the nav in this Hack the News activity (it's linked from the web lit map and also part of Web Lit Basics I module): https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html

**Comment by hannahkane** [comment]
Donezo.
