### ISSUE TITLE
Add Goggles printable cheat sheet to SUMO

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.mozilla.org#1859]
Per #1775 

Can we add a question to the [X-Ray Goggles SUMO page ](https://support.mozilla.org/en-US/products/webmaker/x-ray-goggles) along the lines of: Do you offer a tip sheet with X-Ray Goggles shortcuts that I can print for an event?

**Comment by hannahkane** [comment]
Done: http://mzl.la/1VN2n87
