### ISSUE TITLE
Make npm start run app.js

### ISSUE THREAD

**Issue by davidascher** [mozilla/teach.mozilla.org#1861]
Instructions say to use `npm start` but that doesn't actually run the full server, including the wordpress magical bits.  `npm run app` does, but may as well make `npm start` 'do the right thing'.

**Comment by Pomax** [comment]
fixed as per https://github.com/mozilla/teach.mozilla.org/commit/c9c9200b82bd8b243c56d7c7bde3488faf1701fd
