### ISSUE TITLE
Add automated cross-browser testing

### ISSUE THREAD

**Issue by k88hudson** [mozilla/teach.mozilla.org#334]
Let's have a solution to automate cross-browser testing for chrome, firefox, ie, and some mobile browsers if possible. This will reduce the amount of manual testing and give more visibility to platforms and browsers most of us don't use on a daily basis.

IMO it's OK if these tests are super basic/just hit up most routes and check links or titles, the idea would be to generate screenshots that can be quickly checked.

Work started here for an implementation with saucelabs: https://github.com/mozilla/teach.webmaker.org/pull/314

**Comment by hannahkane** [comment]
I am super excited about this ticket.

**Comment by hannahkane** [comment]
Has this work been completed? Can the ticket be closed?

**Comment by hannahkane** [comment]
Closing this because it feels out of date
