### ISSUE TITLE
CSS sourcemaps are broken unless the autoprefixer is disabled

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#413]
Aki [noticed](https://github.com/mozilla/teach.webmaker.org/pull/386#issuecomment-85766775) recently that CSS sourcemaps are currently broken. I think this occurred in f7928476276ed68c11a325f2962cfd1cdfc71331 when we migrated from [lessprefixer](http://lessprefixer.com/) to `gulp-autoprefixer`. It seems to be due to https://github.com/sindresorhus/gulp-autoprefixer/issues/10, which is still unresolved.

In #386, Aki tried moving to `less-plugin-autoprefix` to resolve this problem, but that seems to be plagued by https://github.com/less/less-plugin-autoprefix/issues/7 (see also https://github.com/mozilla/teach.webmaker.org/pull/386#issuecomment-86010164).

Potential solutions:
* Move back to lessprefixer. Unfortunately, this will involve changing all our LESS back to lessprefixer's mixins, which may be a bit of a chore at this point.
* ~~Attempt to downgrade our version of LESS, which Aki reportedly had [some success](https://github.com/mozilla/teach.webmaker.org/pull/386#issuecomment-86091896) with (but may not have committed to her PR, since it's still not working on my end).~~ Can't do this due to https://github.com/plus3network/gulp-less/issues/140.
* Just live with it until either of the aforementioned bugs in `less-plugin-autoprefix` or `gulp-autoprefixer` are fixed. In the meantime, we could potentially offer some kind of environment variable that disables the autoprefixer in favor of having usable sourcemaps (this was done in https://github.com/mozilla/teach.webmaker.org/commit/38de9d276c362dcf8a0b05a9518bbcc2c0e86722).

The current workaround for this is to disable the autoprefixer by setting `LESS_AUTOPREFIXER` to `off`, which was added in https://github.com/mozilla/teach.webmaker.org/commit/38de9d276c362dcf8a0b05a9518bbcc2c0e86722.

**Comment by toolness** [comment]
Update: I tried minifying the CSS before autoprefixing, which was recommended in https://github.com/sindresorhus/gulp-autoprefixer/issues/10#issuecomment-86787366, and it *apprared* to work at first glance: CSS rules were no longer always mapped to `styles.css`. However, upon closer inspection, they were mapped to the wrong line number in the corresponding `.less` file, and sometimes they were even mapped to the wrong `.less` file.

**Comment by toolness** [comment]
I recently watched Andrey Sitnik's CSSConf 2015 talk on [PostCSS: the Future after Sass and LESS](https://www.youtube.com/watch?v=1yUFTrAxTzg) and it brought up two possible solutions:

1. Replace our `less-autoprefixer` with [postcss/autoprefixer](https://github.com/postcss/autoprefixer).
2. Replace our entire LESS toolchain with PostCSS.

Apparently option 1 is used by Google, and option 2 is used by Twitter, so it's not just some weird experimental new thing we'd be switching to. Based on the talk, I think it could potentially be a good idea... another strategy is to first do option 1 and then do option 2 if we really want.

@mmmavis, if you have time to watch that video (or alternatively read [A List Apart article on PostCSS](http://alistapart.com/column/what-will-save-us-from-the-dark-side-of-pre-processors)) I'd like to know what you think.

**Comment by mmmavis** [comment]
i'm horrible at monitoring GitHub mentions... just saw this now.  Yup I'll find time to watch that video sometime this week!

**Comment by Pomax** [comment]
this will be part of https://github.com/mozilla/teach.mozilla.org/issues/1509
