### ISSUE TITLE
Redesign Discourse header + footer to match teachDOT

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.mozilla.org#452]
Our discourse install is using a header from webmaker training. With the implementation of teachDOT, we should update the navigation & header to point to the teach site and specific teach pages. Additionally, a Mozilla footer should be implemented (e.g. see [Mozilla Science discourse install](http://forum.mozillascience.org/) for footer example).

Relies on #152

**Comment by hannahkane** [comment]
If this needs engineering and design resources, I don't think we can fit this into the current milestone, which is quite full. @LauraHilliger, would you be okay with putting it in the next one?

**Comment by LauraHilliger** [comment]
Header is just css + fixing links, so as soon as teach is live, I'll just fiddle around. Then next heartbeat we can put a little time into the design + footer. Will need to make decisions on brand here b/c [this exists](https://discourse.mozilla-community.org/) and it appears we don't have a "Mozilla Learning" brand yet.

**Comment by hannahkane** [comment]
Sounds good. Thanks, @LauraHilliger.
