### ISSUE TITLE
Automated tests fail on IE9

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#455]
Alas.

Upon brief investigation, these seem to be the major issues:

- [ ] Use of [`classList`](http://caniuse.com/#feat=classlist) in the `Page` component.
- [ ] To check array length, we do `array.length.should.equal(1)` but IE9 doesn't like this. A simple change to `should(array.length).equal(1)` fixes this.
- [ ] In a `TeachAPI` test we stub out `console.warn` but IE9 doesn't like this.
- [ ] I've noticed that the tests don't even run unless I've enabled the F12 developer tools, and I suspect this might be because [`console.log` doesn't exist unless developer tools are enabled](http://stackoverflow.com/a/5473193). It might be good to bust some kind of fake no-op for the `console` object if it's not already defined, just so that stray `console.log` calls don't crash older browsers.

Those seem to be the main ones.

**Comment by toolness** [comment]
Also, the map component doesn't seem to fetch map data, which is a bummer.

**Comment by toolness** [comment]
Just wanted to mention that we've removed this from v1 since we'll be implementing #572 to disable JS entirely on IE9 for launch. For v2 we should probably plan on having IE9 work with JS enabled, though.

**Comment by Pomax** [comment]
IE9 is finally EOL as of January 16! \o/

**Comment by mmmavis** [comment]
merry xams :tada:
