### ISSUE TITLE
MOBILE: Adjust spacing and copy on the Web Clubs page

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.mozilla.org#517]
- [ ]  reduce and fix spacing in between sections on this whole page
- [ ] list below map should probably take up 1-col as it is currently using 2-col (use div class="col-xs-12" instead of div class="col-xs-6")

**Comment by ScottDowne** [comment]
@iamjessklein 

I think this might be the next good bug for you.

Something to check, I am pretty sure that divs by default would do exactly what `col-xs-12` does. So try removing it completely. :+1:
