### ISSUE TITLE
MOBILE: Can't delete location from Clubs form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#541]
I can see the little "x" within the location field, once I've added a location, but clicking it doesn't seem to clear the field.

Safari, iPhone 5

**Comment by toolness** [comment]
Uhoh, hrm. That is a bit concerning because that is a third-party component we're using rather than our own code, so fixing it could be a bit tougher.

Are there any easy workarounds? For instance, is it possible to use the backspace key to erase the location field or anything?

**Comment by hannahkane** [comment]
Took me a minute to find a workaround. I couldn't put my cursor at the end of the location to backspace. But eventually I figured out that, with my cursor at the *beginning* of the location, I could just start typing a new location and it would overwrite the existing one.

I'll remove this as a blocker to launch, but I'll want to test this with users.

**Comment by toolness** [comment]
Ah yeah, that is definitely a weird and confusing workaround. Would be nice to figure out a better solution, will see what we can do!

**Comment by toolness** [comment]
Update: in #692 I upgraded `react-select` to 0.4.6 and hoped that it would fix this problem, but it didn't. :( Should probably just file a bug in that project.
