### ISSUE TITLE
Thin white line around body

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/teach.mozilla.org#619]
There's a thin white border around the entire body of the site. Intentional? Looks a bit 1998.

**Comment by hannahkane** [comment]
@secretrobotron - do you see a line around the rest of the site, or just the top?

Looks like the line on top is from the Mozilla.org header - there's also a white line at the top of mozilla.org.

**Comment by secretrobotron** [comment]
Oh yeah, I see that. But, there's a line on the left side of teach, which isn't on mozilla.org.

**Comment by hannahkane** [comment]
Oh, I see it now on Chrome, but not FF.

**Comment by secretrobotron** [comment]
Ah yeah, true. :+1:

**Comment by ScottDowne** [comment]
Top border is us: https://github.com/mozilla/teach.webmaker.org/blob/develop/less/common.less#L10

Left is added when you create a row via bootstrap.

No idea why these are the way they are...

**Comment by ScottDowne** [comment]
I'm not convinced this is a priority.

For more info on the chrome/bootstrap/left border, it has something to do with the psudo element bootstrap adds to row, it has `content: " "` which for some reason makes chrome go "I'm pretty sure you want a border here".

**Comment by ScottDowne** [comment]
You can also see the top border in FF, but not the left.
