### ISSUE TITLE
Event resource page has weird image placement when in a wider screen

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.mozilla.org#628]
![2015-04-08_16-14-47](https://cloud.githubusercontent.com/assets/124687/7054460/991a9eb6-de0a-11e4-99fa-25f3eaf4d16b.jpg)

I wasn't sure what to do here.

I didn't want to stretch the image, and I didn't want to center it or split them up, so I left it how it was in the mock ups. We should consider an alternative or better placement.

**Comment by ScottDowne** [comment]
Also in mobile, the images don't center.

![2015-04-08_16-15-10](https://cloud.githubusercontent.com/assets/124687/7054471/aed19598-de0a-11e4-9c97-4959f579bc61.jpg)

**Comment by ScottDowne** [comment]
Also also in mobile, The images should shrink if they get larger than the container. Right now they overflow hidden.

**Comment by mmmavis** [comment]
This looks fine to me @ScottDowne .  If we have an orphan that gets left out and goes to the 2nd row then I think that'll be an issue.
