### ISSUE TITLE
Make the site print-friendly

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#638]
Based on the conversation in https://github.com/mozilla/teach.webmaker.org/pull/582#discussion_r28011035 and https://github.com/mozilla/webmaker-curriculum/issues/99 I thought it might be useful to make the Teach site reasonably print-friendly. This shouldn't be too hard, I'm guessing, because we already support browsers that don't have JS, and many of our solutions for supporting those use cases can also apply to print.

That said, we might want to consult the teach team to see if it's even a priority, or if it's only a priority for certain pages, etc., so I'm filing this issue to deal with it at a later time. Perhaps during GROOMING.

<img src="http://media.giphy.com/media/4WO68upjIpDPO/giphy.gif">

**Comment by LauraHilliger** [comment]
relates to #94 (the clubs curriculum could use your hands, stylesheet is very rudimentary IMHO)

**Comment by hannahkane** [comment]
Grooming notes:
* P2: make it possible to print 
* P3: make it ideal
* Effort for P2: small to medium
