### ISSUE TITLE
Google Analytics for new oAuth2 Flow

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.mozilla.org#656]
WRT #626

Thanks for flagging this @toolness 

The GA events I'd like to see captured are:
* Clicked Create an Account
* Clicked Login
* Clicked Logout
* Logged In
* Logged Out

This will give us enough visibility about 'conversion rates' for the teach site. We'll also have more detailed login data within the id.w.o Google Analytics property where we can look at things like validation errors.

For the links to external URLs, there are implications for making sure this data is recorded in GA before redirecting the user. I'll will build this into `react-ga` today so that we have a standard way of doing this.

Q: Does the new flow have distinct Logged In and Logged Out events we could hook this up to, or does it check this repeatedly to get the current status?

**Comment by adamlofting** [comment]
I've just added outbound link tracking to `react-ga`, with notes on how to use this in the docs: https://github.com/adamlofting/react-ga#gaoutboundlinkargs-hitcallback

This uses the hitCallback on the GA event tracking so as soon as the data is logged we can redirect the user on to the target URL.

**Comment by adamlofting** [comment]
And we'll need to bump `react-ga` to version `1.0.10`

**Comment by toolness** [comment]
Ok, I think this is also blocked on https://github.com/adamlofting/react-ga/issues/14, since an `<OutboundLink>` component would be the easiest way to add this functionality to Teach.

**Comment by hannahkane** [comment]
@adamlofting - this ticket feel stale to me in light of our focus on the network strength KPI. Going to close, but feel free to re-open if you'd like.
