### ISSUE TITLE
Lazy-load tabzilla

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#658]
Tabzilla is a bit annoying to me because it loads jQuery, which the rest of our site doesn't need (React-based code often doesn't need it, since React takes care of DOM manipulation for us). This will slow down page load times for our users, and it's particularly annoying because lots of our users will never even click on the tabzilla tab!

There's a few potential things we can do to alleviate this:

* An easy, but not incredibly effective strategy is to add the `async` attribute to the `tabzilla.js` script, so that at least loading tabzilla doesn't slow down the page load time. However, this won't save much because the `tabzilla.js` script is actually not very big--it's its dynamic injection of jQuery that takes a long time.
* An easy, but not very user-friendly strategy is to simply not load `tabzilla.js` at all. The tabzilla link, when un-embellished by `tabzilla.js`, is actually just an `<a href="http://mozilla.org">`--so when a user clicks on the link, they'll simply be taken to mozilla org. This isn't as slick as the tabzilla widget sliding down, though.
* A harder, but more useful strategy is to lazy-load tabzilla JS only when the user hovers/clicks/taps on it. We'd have to also trigger the opening of tabzilla once it loaded, if the user indeed did click/tap on it. A potentially annoying side effect of this, though, is that the first time a user clicks/taps on tabzilla, there may be a perceptible delay. That said, we could wrap this up into a handy `<Tabzilla>` React component that our other properties could use, which might be useful.

Before actually investigating too far into this, though, we should profile the performance of the whole site. As [Amdahl's Law](http://en.wikipedia.org/wiki/Amdahl%27s_law) suggests, if Tabzilla's load time is minimal compared to other factors slowing down our site, spending lots of time to optimize Tabzilla's load time won't do us a lot of good.

**Comment by toolness** [comment]
Um, so I did do a tiny bit of performance profiling, but I also just kinda wanted to implement the last bullet point because it sounded cool, so I did that in #667.

**Comment by Pomax** [comment]
tabzilla changed a bit since then, closing as overtaken by the march of time
