### ISSUE TITLE
Use a form validation library

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#670]
As @mmmavis discovered in https://github.com/mozilla/teach.webmaker.org/issues/481#issuecomment-91397570, we are not currently using a form validation library, but instead doing validation in a somewhat ad hoc way by combining HTML5 form validation with kind of [janky fallbacks](https://github.com/mozilla/teach.webmaker.org/pull/593). There are also some things we have yet to validate, like #424.

It might be a good idea for us to revisit this during [GROOMING](https://camo.githubusercontent.com/d5233e909de33ade6f4f52e81f90c3e86ab6aa7c/687474703a2f2f6d656469612e67697068792e636f6d2f6d656469612f34574f363875706a497044504f2f67697068792e676966) and consider using a real form validation library that is compatible with React and offers a better user experience.

I also have some thoughts on making our forms work for folks who aren't on JS-enabled browsers, e.g. so they work using standard GET/POST, but this will mean having form validation code that works on both the server and client.

@mmmavis, if you have experience with any validation libraries that you find particularly awesome, feel free to mention them here!

**Comment by mmmavis** [comment]
@toolness 
I don't have much experience using validation libraries.  One library that we used for engagement team type of work (e.g. EOY campaigns etc) is [ParsleyJS](http://parsleyjs.org/).  It's jQuery dependent and I'm not sure if it's compatible with React.  Will have to do some research on it.

**Comment by hannahkane** [comment]
@toolness, you are obsessed with grooming. :)

**Comment by hannahkane** [comment]
Grooming notes: 
 * P3
 * effort includes researching libraries
 * this is related to browser support question since forms require js
 * may become higher priority if we have more complicated forms
