### ISSUE TITLE
Use react-router to manage modals

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#686]
As mentioned in #567 and alluded to in https://github.com/mozilla/teach.webmaker.org/pull/373#discussion_r26956659, we may want to consider giving modals their own routes, e.g. `/mozilla-web-clubs/add` for the "add a club" modal. This has a number of benefits:

* It allows react-router to do much of the work of showing/hiding modals.
* Links to modals can be shared between users. (For instance, we can share a direct link to the "add a club" modal, rather than sharing a link to the clubs page and telling users to click "add your club").
* It makes modals easier to develop and debug (devs can just go to the URL of the modal they want to change and reload it).
* Giving each modal its own URL could make it possible for non-JS and ["safe mode"](https://github.com/mozilla/teach.webmaker.org/pull/579) browsers to use modals.

**Comment by Pomax** [comment]
react-router has changed so much that we'll be looking at how to update the codebase afresh in 2016
