### ISSUE TITLE
CSS sourcemap doesn't work on FF

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#689]
I tried

1. create a .env file
2. put `export LESS_AUTOPREFIXER=off` in the .env file
3. run `source .env`
4. run `npm start`

AND

1. creating a .env file
2. run `LESS_AUTOPREFIXER=off npm start`

both approaches don't work

Note: 
1) sourcemap shows up fine on Chrome v41
2) I'm on FF v37

**Comment by hannahkane** [comment]
@mmmavis - Is this a blocker for launch? I can't tell.

**Comment by mmmavis** [comment]
It's def not a blocker.  Created this ticket so that we don't forget to tackle this when we have time.

**Comment by mmmavis** [comment]
obsolete.
