### ISSUE TITLE
Tabulator component doesn't have unit tests

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#699]
I noticed that `pages/event-resources.jsx` doesn't seem to have any unit tests, which is concerning because its `Tabulator` component has JS event handlers in it.

@ScottDowne would you be interested in writing tests for this? I think you could probably use the [sidebar tests](https://github.com/mozilla/teach.webmaker.org/blob/develop/test/browser/sidebar.test.jsx) as a jumping-off point.

**Comment by ScottDowne** [comment]
I'll do this after the expander tests.
