### ISSUE TITLE
Tab view on events resources page isn't accessible

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#724]
As discussed in https://github.com/mozilla/teach.webmaker.org/pull/582#discussion_r28010202, the tab view (`Tabulator` in the code) on the events resources page doesn't support keyboard usage, and may need additional WAI-ARIA markup for full accessibility.

**Comment by mmmavis** [comment]
I can take this on.  My immediate guess is if we make the header [`role=link`](
http://www.w3.org/TR/wai-aria/roles#link) we can fix this problem.  But I will use with VoiceOver to test my hypothesis.

**Comment by toolness** [comment]
It looks like all the tab content is in the DOM, so this is *theoretically* accessible for screen readers, but because we're not using any header tags or anything, it's just a massive blob of text that's hard to navigate. Using `<h4>` for `.event-detail-head` might help, as well as using `<h3>` for the `.tabulator-head` and/or `.tabulator-head-no-js` might be useful (though we should probably set one of those to aria hidden so they're not repeated twice on screen readers).

I'm also noticing that the Logos & Assets above the Tabulator on the Events Resources also isn't keyboard accessible--it's a problem somewhat similar to #927, where the keyboard focus appears to "disappear" while the focus is inside one of the resource download links. I guess this should probably be filed as a separate issue.
