### ISSUE TITLE
Scope local club community features for teach[dot]

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.mozilla.org#725]
This ticket is a place to discuss the Online Local Nodes requirements for teach.mozilla.org. Requirements were started in [this document](https://teach.etherpad.mozilla.org/requirements)(see lines 42, 134), but we need to get more specific on the functional features.

This came over the webmaker list, I like the way a user can commit to a role - maybe relevant for Q3/Q4 functional specs. Filing an issue b/c I'm not sure where the inspiration pile for teach[dot] is.

http://test.openki.net/

cc/ @hannahkane @chrislarry33 @thornet @ldecoursy

**Comment by thornet** [comment]
Thanks for the link! Could we reframe this ticket around what we could apply towards future site iterations? Is it "Scope how users can browse and select roles on teach.mozilla.org"?

**Comment by thornet** [comment]
Is this ticket still needed, @LauraHilliger?

**Comment by LauraHilliger** [comment]
yes, but maybe @hannahkane has this scoping work happening elsewhere?

**Comment by hannahkane** [comment]
I don't understand what this ticket is about! I don't understand the connection between "Scope local club community features for teach[dot]" and the openki project. Can someone explain? :)

**Comment by LauraHilliger** [comment]
@hannahkane I just updated the description a little, does that help? This is a place to collect inspiration for functional features needed on teachDOT. I wasn't sure if you had already started scoping features for horizontal communication, annotation, etc...

**Comment by hannahkane** [comment]
I'm still not sure I totally understand the connection to openki, but perhaps the teach.mozilla.org roadmap is what we're looking for? http://wiki.webmaker.org/Teach

**Comment by LauraHilliger** [comment]
The connection is in inspiration - openki has a specific feature that might be interesting for our community. The roadmap is generally scoping community functions (in Q3/4 UGC Add/Browse), but we've not specifically scoped user stories like "our users should be able to commit as an attendee, mentor or organizer for an event". Not sure that's a function we want, but I filed the issue because I don't know if/where there is a scoping doc that is that specific. We're not doing until Q3/4 but I wanted to save the inspiration somewhere...
