### ISSUE TITLE
Mozilla Webmaker logo, sidebar icons are sometimes squished in IE11

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#726]
This is what it looks like on my screen:

![2015-04-20_9-50-29](https://cloud.githubusercontent.com/assets/124687/7231351/c45df992-e742-11e4-91bf-ce7ae540a80c.jpg)

When I reload, some of these "squished" images may appear just fine, while others are still squished; sometimes they all look fine.

**Comment by toolness** [comment]
Er, nevermind, this actually appears to be a bug in the Web Accessibility Toolbar (WAT), which I'm using for #723. When refreshing the page, that logo and the icons on the sidebar sometimes randomly appear squished, and sometimes they appear fine... But when I disable WAT, they consistently look fine. False alarm, sorry!

**Comment by toolness** [comment]
Wait, no, it's not a false alarm--I just reloaded the page with the add-on disabled and the logo looks squishy again! What's going on... This is particularly hard to debug because of how inconsistently the problem appears.

**Comment by toolness** [comment]
Looks like this might have some info: https://gist.github.com/larrybotha/7881691

**Comment by Pomax** [comment]
After lots of page navigation and reloading using the most vanilla IE11 available, I cannot seem to recreate this, so let's close it until someone runs into it again and then we can hopefully get some more STR and details for debugging this.
