### ISSUE TITLE
Log errors and/or warnings

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#759]
We don't seem to have anything robust in place for logging/reporting errors that occur, neither on the server-side (in teach-api) nor the client-side (except via some things using GA--but we don't get detailed tracebacks or anything).

With @jdotpz's setup, we used New Relic and that graylog thing, right? Are we still using those?

For the Hive Directory I've set it up to email me whenever a request error (500) occurs, but that's so rare, and the Directory's traffic is so light, that it's not overwhelming. It's also emailed *only* to me, so if I went on vacation, nobody else would be notified of errors.

It would be nice to figure out a solution for this, and it may also help with #735.

@simonwex and @jbuck, any thoughts here?

**Comment by rossbruniges** [comment]
In my day I believe https://getsentry.com/welcome/ was used a lot for this
sort of things in the larger MoCo applications. Might we still have a site
license for this?

**Comment by toolness** [comment]
Thanks ross! I'm not sure if we still have a site license, but I'll look into it. For now I've just enabled Heroku's free newrelic add-on for teach-api, but obviously that's only going to be useful for the server-side stuff.
