### ISSUE TITLE
Improve cross-site performance by using a shared CDN

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#817]
Both Teach and id.webmaker.org use React, and it could speed up performance if they both requested it from the same CDN rather than separately including it in their app bundles (which is what's currently happening).

Granted, right now they're both using *different versions* of React, so it wouldn't help until the two used the exact same one, but it's still worth considering.

There may be other common libraries for which this is the case too.

**Comment by Pomax** [comment]
id.wmo is now considered an independent oauth2 authority, so despite us "owning" both, no sharing should happen.
