### ISSUE TITLE
Design announcement for users in Hive cities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#861]
We can detect when a user is near a city where we have a current Hive—we should let them know about the abundance of resources in their community!

For grooming: what might this look like? an ad? what might the CTA be? to visit the local Hive page? to sign up to receive info by email?

**Comment by iamjessklein** [comment]
Things to consider:  :thought_balloon: 
* who is the audience?
* long term vs. short term solution? (long term might = notification system, short term might be more ever-present) 
* messaging should be dismiss - able

**Comment by hannahkane** [comment]
Grooming notes:
 Effort estimate for geofencing and creating a dismissable notification: medium, but suspect that geofencing may have landmines (it's a snake!)
Also: do we need to go through privacy/security review?

**Comment by hannahkane** [comment]
Realistically, this isn't going to happen in the next heartbeat, so I'm moving it.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
As a main point for everyone(!) I propose to try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
