### ISSUE TITLE
Can't see Clubs text box on map if description is long

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#868]
@jgmac1106 reports in #391: "When a club writes a long narrative description it messes up the map navigation. At least for me when I try to read the text box the map pushes down and the text box fades away."

**Comment by hannahkane** [comment]
Can't reproduce this now. @jgmac1106 - are you still seeing this?

**Comment by mmmavis** [comment]
@jgmac1106 I think https://github.com/mozilla/teach.webmaker.org/pull/1001 might have fixed this bug. Mind testing it again?

**Comment by mmmavis** [comment]
I believe the bug was resolved. :smile: closinggg this ticket now.
