### ISSUE TITLE
Add BrowserStack or SauceLabs to diagnostic tools

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#915]
In addition to our [developer buttons](https://github.com/mozilla/teach.webmaker.org/issues/806#issuecomment-102375902) for loading pages in PageSpeed and Tenon, it might be useful for add another button for [BrowserStack integration](https://www.browserstack.com/integrations#integration-examples). (**Update:** SauceLabs integration would be a cool alternative.)

**Comment by simonwex** [comment]
@toolness, I don't think so, but I'm not 100% sure. @k88hudson or @gvn did either of you look into it?

**Comment by k88hudson** [comment]
@simonwex nope. i've used it a couple of times but don't have an account set up or anything

**Comment by gvn** [comment]
I looked at it a bit, but went with SauceLabs because of our relationship with them...

**Comment by toolness** [comment]
Oh cool, it looks like sauce has manual testing tools too. Can mofo devs get the account info so we can easily manually test the site?

**Comment by gvn** [comment]
Turns out you can use Sauce free for open source projects, so I just made my own acct!

**Comment by mmmavis** [comment]
Awesome!  I've only heard of BrowserStack but not SauceLabs.  Time to [sign up](https://saucelabs.com/opensauce/) an account :grin:

**Comment by toolness** [comment]
Whoaaaaaaa that is awesome, thanks gvn!!!!!!!

**Comment by gvn** [comment]
![thumbs](https://cloud.githubusercontent.com/assets/206379/7781094/07e7cd5a-009d-11e5-8cac-0237dea19e4b.gif)

No probs!

**Comment by Pomax** [comment]
adding this to our January 2016 milestone for consideration

**Comment by Pomax** [comment]
closing this for now, it's going to be too involving for anyone to work on.
