### ISSUE TITLE
"Web Literacy Basics" link on the Teaching Activities page causes full page refresh

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#986]
With JS enabled, any navigation from one part of the site to another is very quick because the page is changed in-place to present the user with new content. However, the link to the Web Literacy Basics kit on the activities page causes a full-page refresh.

This is basically because those teaching kits were assumed to always be links to external sites, so we always use a standard `<a>` tag instead of react-router's `<Link>` (which is what enables the performance boost). Fixing this issue will probably involve modifying our code to conditionally use `<Link>` if it's determined that the teaching kit isn't actually on an external site.

**Comment by toolness** [comment]
Also, once #980 lands, our new "Protect Your Data" activity will have the same issue.

**Comment by mmmavis** [comment]
this looks like something we can work on this heartbeat
