### ISSUE TITLE
Design badge iconography for "Club Captain" and "Regional Coordinator" badge

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#996]
We can make use of the badge design system already in place:

http://emilygoligoski.com/2014/05/07/introducing-mozilla-visual-templates-for-badge-issuers/

@chrislarry33 and @thornet - which category would you say the CC and RC badges fall under - Community or Team/Project?

**Comment by thornet** [comment]
Looks like "Team/Product" is most relevant. Thanks!

**Comment by cassiemc** [comment]
We've used font-awesome icons in the past, so this bug is really about finding the right symbol to represent these two categories and then putting it into the 'team/product' template referenced in the first comment. Here's the font-awesome cheatsheet: http://fortawesome.github.io/Font-Awesome/cheatsheet/ and here is the badge template system: https://drive.google.com/file/d/0BzfN9sXlOXt1UzNxaWpZc3N2ODg/view?usp=sharing

@hannahkane Can you link to anything that more fully explains what "Club Captain" and "Regional Coordinator" are about?

**Comment by cassiemc** [comment]
Worth saying that the final deliverables should at minimum be an .eps file. Do you know the size of the final svg or png assets you'll need, @hannahkane?

**Comment by hannahkane** [comment]
More info about Clubs in general here:http://mozilla.github.io/learning-networks/clubs/. The "Who is involved" section explains the roles of Club Captain and Regional Coordinator.

Hmm...I'm not sure about the sizes we'll need, so maybe the deliverable should be an original editable file?

**Comment by thornet** [comment]
For both of these roles, I see strong attributes being how they are facilitative leaders, empowering others, and networked. Might be something that communicates "service to others". 

I think we'll want to steer clear of things that over-elevate the person, like superhero or things like that. 

Rather, how could we show how they serve communities, are caring mentors, and are grounded in real relationships?

**Comment by cassiemc** [comment]
This is great info @hannahkane and @thornet, thanks!

**Comment by thornet** [comment]
Just catching up on a lot of tickets. Is this one still active? 

A heads-up: we're exploring have "tiers" of clubs at the moment. This might be a light spectrum / tier system to indicate how far on-boarded, active and experienced a club is. 

This may affect how we do the Club Captain badges, to accommodate for a visual showing how veteran / deep in the program a captain is.

**Comment by anmechung** [comment]
Tiers - Great idea

**Comment by hannahkane** [comment]
No one is working on this right now, and it's not assigned to any milestone. 

Adding the "Blocked" label to indicate that we're waiting on final decisions about tiers. Thanks, @thornet!
